### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by MarkNijhof** [ninenines/cowboy#1000]
Hi Loic,

We are running Elixir in production based on Cowboy and we see quite regularly one of the following errors (crashes) happening, the majority are the "insufficient security" one. I am guessing these are just bots or browsers with outdated SSL versions.

- SSL: :certify: ssl_alert.erl:93:Fatal error: bad certificate
- SSL: :hello: tls_handshake.erl:118:Fatal error: inappropriate fallback
- SSL: :hello: tls_handshake.erl:167:Fatal error: insufficient security
- SSL: :hello: tls_handshake.erl:174:Fatal error: protocol version

So currently this throws a 500, but I much rather want to return a 405 Not Allowed. Also because this is a crash we get notified via Rollbar which just clutters the log. So since these errors are kind of expected I was wondering if we can hook into the cowboy pipeline early enough to catch these scenarios and return a 405 instead? Is there a reason this is a 500 vs 405?

**Comment by essen** [comment]
I doubt this throws a 500, at least for the latter three. This is the SSL application error-ing out in the handshake, before Cowboy receives any request.

**Comment by ferd** [comment]
There can be a handshake mid-request or mid-response in the case of renegotiation. For the server-initiated ones this happens after 2^28 payloads have been encrypted (according to the source) and can happen at any time, and the client can trigger them whenever it feels like doing so. To reduce the probability of this kind of mid-stream issue, you should disable client-initiated renegotiation (it's a fairly well known DoS technique, even if Erlang has a cooldown on renegotiation). Little can or should be done for server-initiated renegotiation. 

In any case yeah, whatever code cowboy throws is not gonna make it to the client since the connection is interrupted anyway.

**Comment by essen** [comment]
Right Cowboy currently does not disable renegotiation so this could happen. Cowboy 2 will force disable renegotiation entirely (due to HTTP/2 requirements, and related aforementioned issues).

**Comment by MarkNijhof** [comment]
It is crashing which I guess would have resulted in a 500, but the explanation makes sense. I am actually seeing it quite regularly, mostly the "insufficient security" one, a few times a day, and this is for a pretty unknown service. Besides disabling client-initiated renegotiation should I be doing something else as well?

When do you expect Cowboy 2 to land?

**Comment by essen** [comment]
Can't say off-hand, would need to look at why the SSL application errors out exactly. Note that a lot of logs from that application are from expected errors (for example if an old client tries to connect and the older ssl versions are not enabled, you will get a message logged; probably the one about the version you got).

Cowboy 2.0.0-pre.4 will be tagged in a few weeks, with few breaking changes expected after that, but still a lot of work remaining. I don't plan to release 2.0 stable until the test suites cover all features and RFCs supported. I really want to do it right this time.

**Comment by MarkNijhof** [comment]
Ok so there is basically no way to configure cowboy to not log those expected errors, which is fine, I just wanted to make sure before I start filtering in the logging application.

Thanks for Cowboy ect btw, awesome products
