### ISSUE TITLE
getting an environment value for an already running listener

### ISSUE THREAD

**Issue by ludwikbukowski** [ninenines/cowboy#1005]
Due to the  [Cowboy documentation](http://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy/index.html#set_env) there is exported function `set_env` which updates or sets an environment value for an already running listener. Thats cool but how can I get the value of already running listener?
Shouldn't be there an exported function `get_env/2` ?

**Comment by essen** [comment]
You can use `ranch:get_protocol_options(Ref)` to get access to them.

It's unusual so I'm wondering what your use case is?

**Comment by ludwikbukowski** [comment]
I'd like to **add** a new path to `dispatch` proplist so I guess I need to get a list of existing paths

**Comment by essen** [comment]
OK. Typical case is having a function that returns the list of routes, and simply update that function and then use it when you update the routes, so there's not really any adding or removing going on. For special cases the function I mentioned should be fine, it's just a level deeper than the structure you get.
