### ISSUE TITLE
Is there a stable version for 2.0.X?

### ISSUE THREAD

**Issue by helloyan** [ninenines/cowboy#1009]
Is there a stable version for 2.0.X?

**Comment by essen** [comment]
No. I am doing the last few changes for 2.0.0-pre.4 which will be more stable than previous versions, and I will recommend, but might see some additional breaking changes.

**Comment by helloyan** [comment]
which version do you suggest to  use ? 1.0.4 ?

**Comment by essen** [comment]
Yep.
