### ISSUE TITLE
can cowboy work with some dynamic language?

### ISSUE THREAD

**Issue by helloyan** [ninenines/cowboy#1010]
If i want to make some dynamic pages,  i should write all the html code in erlang,  does cow boy has some solution?

**Comment by essen** [comment]
Not sure what you mean but if you're looking for a template engine there's erlydtl or mustache, probably more.

**Comment by crownedgrouse** [comment]
See also nitrogen or n2o.

**Comment by essen** [comment]
Closing due to question answered. Thanks!

**Comment by crownedgrouse** [comment]
Not to mention zotonic, on the road to move from webmachine to cowboy,  for information.

**Comment by crownedgrouse** [comment]
https://github.com/zotonic/zotonic/pull/1355 for reference
