### ISSUE TITLE
a suggestion for the manual 

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1012]
i am reading this: http://ninenines.eu/docs/en/cowboy/2.0/guide/req/
i am now lost in the "parse_qs" function
i am sure a formal definition of the return value type for the functions will be very helpful
also a return value example formatted as "~p" would help.

**Comment by essen** [comment]
Yeah the manual hasn't been updated yet. The cowboy_req interface is a work in progress.

**Comment by eugene-panferov** [comment]
please, don't make it big bloated "respectful" manual, it is now better than the majority of the mainstream manuals. incomplete yet succint.

**Comment by essen** [comment]
There's two documents, the guide that you linked to, and the function reference which is the one who has all the type information.

**Comment by eugene-panferov** [comment]
in this case, the guide seems to be a perfect place for an example output for the function "request:parse_qs". as far as i understand the attitude of the document it will be great to SEE the data structure example next to the function call example (the output of the function is not trivial to imagine)

**Comment by essen** [comment]
It's a list of key/value, it's pretty trivial for anyone doing Erlang. But chances are you'll be more interested in match_qs rather than parse_qs. :-)

**Comment by eugene-panferov** [comment]
yes :) i confused the names :)

**Comment by essen** [comment]
The manual for these functions is much improved and should leave no room for errors. The guide is not as specific, but the guide is meant to show what you can do only. I'll close this as fixed. Thanks!
