### ISSUE TITLE
WARN file missing when compiling

### ISSUE THREAD

**Issue by raarts** [ninenines/cowboy#1013]
After reading the guidelines for contributing I think this qualifies as a bug report (I treat warnings as bugs), but feel free to close if not.
```
WARN:  File missing. Remove from dep graph:
/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/kernel-5.0/include/file.hrl
WARN:  File missing. Remove from dep graph:
/Users/raarts/work/myproject/_build/prod/lib/cowlib/include/cow_inline.hrl
```

**Comment by essen** [comment]
I'm not sure what would make such a warning, can you tell me what command you run and how that is a problem?

**Comment by raarts** [comment]
This occured during compilation of cowboy, but after googling the `exact` error message, it seems to be generated by rebar.  Sorry for wasting your time.
