### ISSUE TITLE
rest_handlers page is truncated on ninenines.eu site

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#1014]
scroll to bottom on http://ninenines.eu/docs/en/cowboy/2.0/guide/rest_handlers/ and https://github.com/ninenines/cowboy/blob/master/doc/src/guide/rest_handlers.asciidoc

**Comment by essen** [comment]
I think you already opened a ticket on ninenines.github.io :-)

**Comment by marianoguerra** [comment]
maybe, I have bad memory :D, doesn't seem to be here: https://github.com/ninenines/ninenines.github.io/issues?q=is%3Aopen+is%3Aissue

feel free to close this if it's a duplicate

**Comment by marianoguerra** [comment]
maybe this one? https://github.com/ninenines/cowboy/issues/970

**Comment by marianoguerra** [comment]
or this one https://github.com/ninenines/cowboy/issues/969

**Comment by marianoguerra** [comment]
I see that the docs on the ninenine site aren't as updated as the docs folder on this repo, let me know if you prefer me to keep pointing docs problems.

now I will read the docs from the repo instead.

**Comment by essen** [comment]
Well the docs for master are outdated so don't read them. :-)

**Comment by essen** [comment]
Done, thanks!
