### ISSUE TITLE
What's the way to know the verson of cowboy?

### ISSUE THREAD

**Issue by basharov** [ninenines/cowboy#1015]
I find some examples on the web that seem to be broken with the version from `master` branch.

Also, seems like hex.pm version is different too.

How do I know exactly what version of cowboy I have by looking in its folder?

Also, I see inconsistencies in documentation, particularly on [hooks](http://ninenines.eu/docs/en/cowboy/2.0/guide/hooks/), where it shows an example as 

```
cowboy:start_http(my_http_listener, 100,
    [{port, 8080}],
    [
        {env, [{dispatch, Dispatch}]},
        {onresponse, fun ?MODULE:custom_404_hook/4}
    ]
).
```

but in the current code there is no `start_http` function and `env` and `onresponse` are records, not tuples.

**Comment by essen** [comment]
Master has seen numerous changes and is not stable. Documentation is in the process of being updated. What you find on hex, or the recommended versions are 1.0. Master will become 2.0.

The version can be found in the ebin/cowboy.app file once compiled for example.

**Comment by essen** [comment]
Closing, thanks!
