### ISSUE TITLE
timeout implementation incomplete

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#1018]
this only accepts infinity: https://github.com/ninenines/cowboy/blob/master/src/cowboy_rest.erl#L237

which doesn't match this type: https://github.com/ninenines/cowboy/blob/master/src/cowboy_rest.erl#L24

the cowboy_protocol:opts() type mentioned here: https://github.com/ninenines/cowboy/blob/master/src/cowboy.erl#L41 doesn't seem to be implemented anywhere.

also cowboy:start_clear seems to ignore the timeout option but does support a request_timeout option.

**Comment by essen** [comment]
Seems that's all long fixed.
