### ISSUE TITLE
how to options the https to  do not check crt file

### ISSUE THREAD

**Issue by lcwxz1989** [ninenines/cowboy#1023]
a just what to mock https service without crt check for  offline test

**Comment by essen** [comment]
Can you be more specific? Do you use a self signed certificate and Erlang rejects it? Something else? Typically clients have an option to connect even if the certificate is insecure.

**Comment by lcwxz1989** [comment]
@essen  I use a self signed certificate and the https service which use the certificate worked well.And I got it , I need to check out client model to get how to options the request without crt check, 3ks

**Comment by essen** [comment]
Right, there should be nothing to do as far as the server is concerned. Try `curl -ki URL` for example.

**Comment by essen** [comment]
Closing, thanks!
