### ISSUE TITLE
Cowboy can't process GET parameter with two %% in name

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowboy#1024]
`http://localhost:8080/?%%echo=123`
` #{'%%echo' := Echo} = cowboy_req:match_qs([{echo, [], undefined}], Req0),`

the error is
```
Ranch listener http, connection process <0.187.0>, stream 1 had its request process <0.188.0> exit with reason function_clause and stacktrace [{cow_qs,unhex,"%",[{file,"src/cow_qs.erl"},{line,341}]},{cow_qs,parse_qs_name,3,[{file,"src/cow_qs.erl"},{line,35}]},{cowboy_req,match_qs,2,[{file,"src/cowboy_req.erl"},{line,181}]},{toppage_handler,init,2,[{file,"src/toppage_handler.erl"},{line,10}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,39}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,172}]},{cowboy_stream_h,proc_lib_hack,3,[{file,"src/cowboy_stream_h.erl"},{line,157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
```

**Comment by essen** [comment]
Seems like it's working as intended. Correct me if I'm wrong but %% is not valid as the %s need to be url encoded as %25%25.

**Comment by brigadier** [comment]
Yes you are right, technically it's not valid. I just expected slightly more leniency in cowboy to such minor irregularities.

**Comment by essen** [comment]
Cowboy is strict, except for interoperability purposes, with these goals in mind:

- Handle badly formatted input from heavily used clients by default (browsers, curl, flash...)
- Provide options or workarounds for enabling other non-strict or invalid behaviors for less common clients

I should probably document this somewhere.

**Comment by brigadier** [comment]
Yeah I see. In my case customers can enter GET parameter names and match the queries against these parameters, so one of the customers decided to use the %%name in his urls.

**Comment by essen** [comment]
Some preprocessing should be easy to do, especially now that the Req is a map. Enjoy!
