### ISSUE TITLE
Can I get the steaming request DATAs frames in HTTP/2?

### ISSUE THREAD

**Issue by tony612** [ninenines/cowboy#1033]
In the situation that client sends multiple DATA frames in HTTP/2, my server should handle each DATA frame one by one. But it seems `cowboy_req:read_body` always tries to read the whole body by client.

Is there anyway to achieve this?

**Comment by essen** [comment]
Stream handlers get data frames directly. They are currently undocumented. See cowboy_stream_h.

**Comment by tony612** [comment]
@essen But in `cowboy_stream_h`, new `Data` is stored in `read_body_buffer` with old buffer which is still a whole body, right?

Or, do you mean I need to write stream handler by my self?

**Comment by essen** [comment]
Yes you need to write a stream handler by yourself. You can implement what you need and fallback to cowboy_stream_h for the rest if needed.

**Comment by tony612** [comment]
@essen Got it. Thanks!

**Comment by essen** [comment]
Feel free to provide feedback on it, I want to make the chaining of stream handlers easier in the future.
