### ISSUE TITLE
HTTP/2 Examples and documentation

### ISSUE THREAD

**Issue by jbrisbin** [ninenines/cowboy#1034]
I have been trying to intuit how the HTTP/2 support works in Cowboy and having a hard time putting the pieces together. In particular, I'd like to see some straightforward examples that show serving HTTP/1.1 requests for things, then having an upgrade somewhere to do the HTTP/2 streaming.

I wish there were Elixir examples as well, since that's how I would be setting this stuff up and experimenting. Some of the Elixir examples around are now out-of-date.

**Comment by essen** [comment]
There's no particular differences in the interface between HTTP/1.1 and HTTP/2. HTTP/2 has the push mechanism added, but that's about it. All examples that aren't marked as broken support both HTTP/1.1 and HTTP/2.

**Comment by jbrisbin** [comment]
@essen The push is precisely what I'm looking into. I'm looking to open an HTTP/2 connection between two parties based on header metadata and then do binary transfer. Does the event sourcing example use HTTP/2?

**Comment by essen** [comment]
This might be helpful: https://github.com/ninenines/cowboy/blob/master/test/handlers/resp_h.erl#L131

There's no need to do different behavior between HTTP/1.1 and HTTP/2, Cowboy takes care of that.

All you need to connect with HTTP/2 is a capable client. It's enabled by default on both clear and TLS listeners.

**Comment by essen** [comment]
We need to add an example for push.

**Comment by essen** [comment]
There is a PR with a push example so I'll close this in favor of the PR.
