### ISSUE TITLE
Fake protocol for testing

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1035]
Make a fake protocol-like module for issuing HTTP requests without going through TCP. Should probably run in its own process and have a gun-like interface for interacting with it, except no parsing/connection handling would need to be done.

**Comment by aerosol** [comment]
Awesome. The  rationale is that cowboy itself is tested elsewhere. Spawning HTTP clients just to test user-defined handlers semantics is a huge overkill (out of the domain scope and resource waste). To illustrate it with pseudocode:

```erlang
Req1 = reqmake:new(). %% -> #{method => get, url => <<"/">>, other_sane_defaults}.

Req2 = reqmake:new(#{method => post, url => <<"/create">>, headers = #{content_type => <<"application/lolson">>}}).

%% test

Resp = my_handler:init(Req1),
?cowboy_awesome_assertions_status(Resp, 200),
?cowboy_awesome_assertions_body_matches(Resp, #{<<"data">> := #{<<"valid">> := true}}).
```

**Comment by essen** [comment]
So right now I think this can be achieved via `cowboy_stream`: https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_stream/

One could easily just call `cowboy_stream` a few times and then take the response out of the returned commands and compare them with the expected result.

I'm not sure a wrapper process/module is needed since you can just call `cowboy_stream` directly. I won't have time to experiment with it though but if someone does and finds that some changes would be good to have in Cowboy to help with this I'm open to them. In that case please open a separate ticket per changes needed.

Thanks!
