### ISSUE TITLE
The "onresponse" hook doesn't work (v2)

### ISSUE THREAD

**Issue by manifest** [ninenines/cowboy#1036]
It looks like `onresponse` hook doesn't work in v2. Is there some workaround for logging responses?

``` erlang
cowboy:start_clear(
    httpd,
    100,
    [{port, 8080}],
    #{env => #{dispatch => dispatch()}, onresponse => fun log/4}).

log(_, _, _, Req) ->
    error_logger:info_report([{req, Req}]),
    Req.
```

**Comment by essen** [comment]
Hooks are out. Stream handlers are in. It's not been documented yet.

Stream handler coming with Cowboy: https://github.com/ninenines/cowboy/blob/master/src/cowboy_stream_h.erl
Configuration: https://github.com/ninenines/cowboy/blob/master/src/cowboy_clear.erl#L43

Basically define a module implementing the four callbacks, forward everything you don't care about to the caller or to cowboy_stream_h, and catch response or headers tuples in info callback for your purposes.

Design has not been finalized yet, feedback is welcome.

**Comment by manifest** [comment]
Thanks for the clarification. I will take a look.

**Comment by essen** [comment]
Closing because only pending documentation which is a work in progress. Thanks!

**Comment by jvdvleuten** [comment]
@essen I don't understand the example you gave earlier. How to implement this with the REST handler if a request ends prematurely? For example, due to an unforeseen `'exit'`? I would like to trap the 500 response and add some CORS headers to them.

**Comment by essen** [comment]
Look at the `cowboy_compress_h` module and replace what it does in the fold function with what you need, or catch the exit specifically.

**Comment by jvdvleuten** [comment]
Thanks for the very quick reply. I am a bit of a beginner to cowboy though.. Are you saying with "replace what it does" to fork the code and maintain an own version of what it does? Or add some kind of a hook?

I am now using the the `cowboy_rest` handlers, with a custom `my_cors_middleware`.
```
{ok, _Pid} = cowboy:start_clear(my_http_listener, 100,
				    [{port, 8081}],
				    #{env => #{dispatch => Dispatch},
				      middlewares => [my_cors_middleware, cowboy_router, cowboy_handler]}).
```

Are you saying, I should now use `stream_handlers => [cowboy_compress_h, cowboy_stream_h]` and add my own to handle premature errors? Will this work with the `cowboy_rest` handler?

Maybe it's easier for me to catch errors elsewhere for now. The problem I have is that my internal server errors don't have the CORS headers in the response..

**Comment by essen** [comment]
Stream handlers catch *everything* as far as HTTP is concerned. So you could easily catch the {response, 500...} tuples returned by cowboy_stream_h and add your headers there.

**Comment by jvdvleuten** [comment]
@essen Thanks! 

So I add `stream_handlers => [my_error_stream_h, cowboy_compress_h, cowboy_stream_h]` to the options map, and implement my own `my_error_stream_h` :) Will try this out! Thanks very much!

**Comment by essen** [comment]
Yep!

**Comment by manifest** [comment]
@jvdvleuten here is one more example of [stream](https://github.com/manifest/datastore/blob/master/src/datastore_streamh_log.erl?ts=2) for purpose of logging HTTP requests. It's initialized [here](https://github.com/manifest/datastore/blob/master/src/datastore_http.erl?ts=2#L62). You could also find interesting the [example](https://github.com/manifest/datastore/blob/master/src/datastore_httpm_cors.erl?ts=2) of CORS middleware.
