### ISSUE TITLE
Cowboy 1.0.4 escaping plus sign in path

### ISSUE THREAD

**Issue by aberman** [ninenines/cowboy#1037]
When I pass in a + into the path of a URL (e.g. somePath/my+var), it is being translated to a space once I receive it in the handler as well as in any path constraints (my+var is becoming "my var").  Debugging shows that it is being received properly by Cowboy, but I haven't been able to figure out where it is being escaped.  Plus signs are supposed to be escaped in the query string, but not in the path.  Any ideas where this might be happening?

Thanks!

**Comment by essen** [comment]
Here: https://github.com/ninenines/cowboy/blob/1.0.x/src/cowboy_router.erl#L325

This has been fixed in master: https://github.com/ninenines/cowboy/blob/master/src/cowboy_router.erl#L321

I'm mostly working on master now but let's leave the ticket open in case I do another point release. Thanks!

**Comment by aberman** [comment]
Awesome, thank you, Loïc!

**Comment by essen** [comment]
This will be fixed in 1.1 released later today. Thanks!
