### ISSUE TITLE
I guess there is a mismatch with timeout option.

### ISSUE THREAD

**Issue by mm-tfx** [ninenines/cowboy#1038]
In function cowboy:start_clear, one can provide some protocol options. The option I wanted to use was timeout. I have set this option using timeout => 10000 but still server worked as this timeout was 5000ms. 
In one of my handlers I added timer to delay response sending.  I started with 1000ms and gradually increased this to 5000ms and then it stopped working. So I tried to find how to force server to wait a little bit longer for the response. Like I wrote this timeout option seemed to be a solution but I couldn't make server to use value provided by me.
I checked cowboy_http and found out there that timer is called request_timeout. I used this one in start_clear function and now server waits 10000ms before closing down the connection.
Is this a fault or perhaps I did not checked something?

Thanks.

**Comment by essen** [comment]
Where did you find the timeout option? It was indeed renamed to request_timeout, but perhaps not everything was renamed. Note that the 2.0 docs are still a work in progress.

**Comment by mm-tfx** [comment]
The first place is the 2.0 doc or rather manual and cowboy_protocol function reference.
To be honest I am a bit confused right now about cowboy_protocol module. Is it still valid and should be present?

**Comment by essen** [comment]
No cowboy_protocol module is gone, replaced by cowboy_http. I'm currently updating cowboy_req, haven't made my way to these yet.

**Comment by mm-tfx** [comment]
In cowboy_http in the type section there is still timeout mentioned.

**Comment by essen** [comment]
Yep most likely. :-) Both documentation and typespecs are being updated.

**Comment by mm-tfx** [comment]
Thanks for help.

**Comment by mm-tfx** [comment]
One more question: On the request_timeout expiration would it be possible to send some decent response to the client like 408 or even 504?

**Comment by essen** [comment]
We can't send a response if the client didn't send a request beforehand. We need to receive at least the request-line before we do that. Cowboy does it in all permitted cases.

**Comment by mm-tfx** [comment]
I do agree but what if handling of the request takes too long? For some reason I have had such behaviour and then on the timer expiration server sent empty response to the client.

**Comment by essen** [comment]
OK so this is the normal operations:

* no request-line receive; no response sent back
* request-line received but without the complete headers; 408 sent back
* request-line and headers received, and a handler eventually times out; 204 or 500 sent back depending on the handler type (loop handler would 204 for example, while normal handler would 500) - note that HTTP/2 might send RST_STREAM instead
* request-line and headers received, handler started replying and eventually times out; just terminate the current response (HTTP/1.1) or send an RST_STREAM (HTTP/2)

I'm not sure all that is implemented and works properly. Can you tell me which cases exactly gets you an empty response, and what you mean exactly by empty response?

**Comment by mm-tfx** [comment]
I think my case would be last bullet in your list.
Perhaps not the best description for Empty Response but anyway I meant:
curl: (52) Empty reply from server
As I was using curl for testing.
I can check what gun_client said if you need this one.

I was thinking about 408 or 504 in this case but now I am checking those two codes again and I am not sure if those are the best here.

**Comment by essen** [comment]
Empty reply is definitely not the last one, and if it's curl then it's either the second or third one (probably third). Would be good to have a short demo showing the problem. Maybe reusing an existing example.

**Comment by mm-tfx** [comment]
I'll do that. Would it be ok to put this into simple repo her?

**Comment by essen** [comment]
Perfect, thanks. I'll try to fix it before I tag next and get back to you.

**Comment by mm-tfx** [comment]
Almost the same but using gun client:
```
2> {ok, ConnPid} = gun:open("localhost",8081).
{ok,<0.81.0>}
3> {ok, Protocol} = gun:await_up(ConnPid).
{ok,http}
4> 
4> 
4> StreamRef = gun:get(ConnPid, "/", [{<<"accept">>, "application/json"}]).
#Ref<0.0.1.234>
5> gun:await(ConnPid, StreamRef).
{error,{closed,"The connection was lost."}}
```

**Comment by essen** [comment]
This issue has been fixed a while ago. Thanks!
