### ISSUE TITLE
kick previous connection

### ISSUE THREAD

**Issue by jianjyan** [ninenines/cowboy#1041]
Hi, 
I want to kick a previous connection due to one account can only establish one connection.
my way to do so is:
1.  register the account to the pid of websocket handler within the init function(user sent account and password via query string)
2. test the account if is bound to a pid
3. send message to the bounded account, like account ! {ctrl, kick}
4. in the process of bounded account, websocket_info({ctrl, Msg},State)-> {stop, State}.

In this scenario, the account is registered successfully, but whereis(account) always return undefined; any suggestion?

**Comment by essen** [comment]
Why not just exit(Pid, kill) it instead of sending a message?

**Comment by jianjyan** [comment]
because I want to retrieve data from another process as well, for example:
A has a State which contains the  x info,  B wants to connect to A but at first he need A's x info;  I don't want  them to query the info from DB, due to performance problem.
The exit(Pid,kill) is good, but firstly, I can't get the Pid,  that's the problem:  whereis(account) returns undefined permanently.

**Comment by jianjyan** [comment]
Ok, I have to make a clarify,  in a simple sentence:
if it's possible to register the websocket_hanler process to identifier??

I have registered a identifier to the process, then run whereis function immediately, and it returns correctly;  but an undefined atom returned permanently in other process, even manually runt it in erlang shell. 
but

**Comment by essen** [comment]
You should not store state inside a Websocket connection process. You should store it in a separate session process.

As for how to find this process, a process registry like `syn` is probably what you want. I do not know what your issues with `register` are but honestly that's out of scope. The erlang-questions mailing list would be a better place for questions related to this. Note that `register` is only for the local node so that might be why you have issues.

**Comment by jianjyan** [comment]
So, what kind of data I can store in the state?  in my case, I just store the user info of  the people who hold the connection.

what the "syn" exactly means?   a gen_server process which reserve for the process' registration ?

the register() function is do called in the same node; I'll asking in erlang-questions mailing list.

**Comment by essen** [comment]
`syn` is a project. https://github.com/ostinelli/syn

You can store what you want in the state, but it won't survive a disconnect, so it's not useful for session state. You can have a separate process for that and make that separate process ensure there's only one connection, like you wish to have.

**Comment by jianjyan** [comment]
thanks bro!  I got your point.
