### ISSUE TITLE
How to make keepalive works?

### ISSUE THREAD

**Issue by dcy** [ninenines/cowboy#1042]
Hi!
I tried the [/examples/hello_world](https://github.com/ninenines/cowboy/tree/master/examples/hello_world):
```
dcy@dcy-dcy:~/app/cowboy/examples/hello_world$ curl -i http://localhost:8090
HTTP/1.1 200 OK
content-length: 12
content-type: text/plain
date: Wed, 26 Oct 2016 02:42:28 GMT
server: Cowboy

Hello world!
```
There is no ```connection: keep-alive```.

And i test [gun](https://github.com/ninenines/gun). I use a gen_server:
``` {ok, ConnPid} = gun:open("192.168.3.236", 8090``` and
``` {ok, ConnPid} = gun:open("192.168.3.236", 8090, #{http_opts => #{keepalive => 100000}})```
The gen_server always receive ```{gun_down,<0.765.0>,http,closed,[],[]}``` about 5 seconds.

How to make keepalive works?

**Comment by ferd** [comment]
In HTTP/1.1, if no `connection: close` header is passed, the connection is assumed to be keepalive by default.

**Comment by dcy** [comment]
But in my test, the keepalive does not work. curl's result have not the content about"connection: keep-alive".
And [gun](https://github.com/ninenines/gun) always receive ```{gun_down,<0.765.0>,http,closed,[],[]}``` about 5 seconds.
I use cowboy 1.0.4

**Comment by essen** [comment]
Connection: keep-alive doesn't need to be sent if the connection is using HTTP/1.1, it's the protocol default.

As for why Gun detects the connection being closed after 5s, well that's because the default keepalive configuration value in Cowboy is 5s; Cowboy will close idle connections after 5s. Make that value larger if required.

**Comment by dcy** [comment]
Thanks!
How to set the default value?

**Comment by essen** [comment]
https://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_protocol/
