### ISSUE TITLE
sensitive data protection

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/cowboy#1047]
Hi Loïc,
I maybe missed something in documentation, but is there a functionality in cowboy that protect cowboy processes to be traced/observed , on rules basis for example ?
I mean setting process_flag(sensitive, true) at process init , in order to prevent any data theft at runtime, by an hidden node sniffing ? (VISA card numbers in a commercial website, for examples ...).
This can be done at middleware side, but there is a security hole at cowboy level in order to have the whole transaction protected , from https side to final PSP provider.
Thanks for your thoughts.

**Comment by essen** [comment]
You can set the protocol module to your own which does any necessary initialization before calling cowboy_clear/cowboy_tls (Cowboy 2) or cowboy_protocol (Cowboy 1).

**Comment by crownedgrouse** [comment]
but i suppose it will apply to any requests, not on only the sensitive page ?

**Comment by essen** [comment]
Yes any requests.

Also note that in Cowboy 2, more than one process is involved, so you would need to do that for both the connection and the request process.

**Comment by crownedgrouse** [comment]
thanks !
