### ISSUE TITLE
Won't state passed to handlers change?

### ISSUE THREAD

**Issue by tony612** [ninenines/cowboy#1051]
I thought the state passed to handlers will be the new state returned by `handler/init/2` based on the API
```
init(Req, State) ->
    {ok, Req, State}.
```
and the description *The last value of the tuple is a state that will be used in every subsequent callbacks to this handler* in this doc https://ninenines.eu/docs/en/cowboy/2.0/guide/handlers/

But it doesn't work as I expected if it returns a new `State`. Do I misunderstand something?

**Comment by essen** [comment]
Maybe the phrasing is not very good? State returned is used on the next call, which returns a new State used for the next call, etc.

**Comment by tony612** [comment]
@essen But from this code(https://github.com/ninenines/cowboy/blob/master/src/cowboy_handler.erl#L38), I didn't see where `State` is used.

**Comment by essen** [comment]
I don't see a problem there. Just that in that function HandlerOpts is passed as second init/2 argument, State. Hasn't been renamed to InitialState yet is all.

**Comment by tony612** [comment]
But the returning result is `{ok, Req2, [{result, Result}|Env]}`, which doesn't change the new state. In the next call, `State` in `init/2` is still the beginning value(`HandlerOpts` or `InitialState`).

Well, I changed an example to describe what I thought: https://github.com/tony612/cowboy/commit/e924525347b366e4ee6fc50f72fa588a024cb0ba

**Comment by essen** [comment]
Yes because that's a different request. Handler processes and state are only per request.

**Comment by tony612** [comment]
Got it. But the code example and doc is still a little confusing to me. `Opts` will be a better word for me than `State`. Or maybe it's better to mention it's in one request.

**Comment by essen** [comment]
It's State because it's the same as the State in other callbacks. It's not options; these became unnecessary now that we have maps. So the router will say InitialState, and everywhere else will say State.
