### ISSUE TITLE
Crash detected while running REST Handler

### ISSUE THREAD

**Issue by shobhitsingh** [ninenines/cowboy#1055]
After running a simple rest app, I can see following crash in Cowboy, though my request completes successfully with 200 ok.
`14:33:08.564 [error] CRASH REPORT Process <0.315.0> with 0 neighbours exited with reason: no case clause matching {ok,#{bindings => [],body_length => 307,charset => undefined,has_body => true,has_sent_resp => true,headers => #{<<"accept">> => <<"*/*">>,<<"authorization">> => <<"Basic Removed for simplicity">>,<<"content-length">> => <<"307">>,<<"content-type">> => <<"application/xml">>,<<"host">> => <<"localhost:6000">>,<<"user-agent">> => <<"curl/7....">>},...},...} in cowboy_rest:process_content_type/3 line 933 in cowboy_stream_h:proc_lib_hack/3 line 162`

**Comment by essen** [comment]
`ok` is not a proper return type for the AcceptCallback type of functions.

**Comment by shobhitsingh** [comment]
This is my 

```
content_types_accepted(Req, State) ->
    {[
	    {<<"application/xml">>, handle_events},
		{<<"application/json">>, handle_events}
	], Req, State}.
handle_events() ->
cowboy_req:reply(Result, Req, State).

What should I change here?
```

**Comment by essen** [comment]
handle_events should not return what cowboy_req:reply returns.

Check https://ninenines.eu/docs/en/cowboy/2.0/manual/cowboy_rest/#_content_types_accepted for what is expected.

**Comment by shobhitsingh** [comment]
Thanks, so there is no way to reply other status than 200. Based on the link true will return 200 and I can only set the response body, but cannot return 400 for a bad request for example.

**Comment by essen** [comment]
Depending on the request method, presence of a response body etc, a 200, 201, 204, or even 30x may be returned on success. A 400 is returned if you return false. Probably more cases I forget.
