### ISSUE TITLE
Cowboy 1.0.4 uses Cowlib 1.0.2

### ISSUE THREAD

**Issue by jaynel** [ninenines/cowboy#1056]
Ran across the crypto:strong_rand_bytes/1 issue when compiling for 19.1. I see it is fixed in cowlib, but that fix is in a later build. Cowboy uses the default erlang.mk which looks like it is using Cowlib 1.0.2. Is that intentional? Does it require an upgrade to Cowboy 2.0 before Cowlib will invoke the new crypto call?

Looking at Cowboy 2.0.0-pre3 it invokes Cowlib 'master' rather than a tagged version.

**Comment by essen** [comment]
I will tag Cowboy master and use tags for cowlib/etc. when releasing 2.0.0-pre.4 (almost done with the docs! so shouldn't be much longer).

For Cowboy 1.0.4 I don't remember exactly what the versions were but I made a mistake in Cowlib at some point and Cowboy 1.0.4 isn't compatible with it. From 2.0 onward Cowlib will be proper semver and this shouldn't happen anymore, but I'm afraid 1.0.4 won't be updated (customers not interested). The crypto thing should also just be a warning when Cowlib is used as a dependency so I don't think there's much problem there, is there?

2.0.0-pre.4 will also be the recommended version moving forward (in fact the current master code is it, just missing some docs).

**Comment by jaynel** [comment]
It's now deprecated as a warning, but I was compiling with warnings as errors and that was the only error that tripped me. I can wait for 2.0. Still doing an initial deploy so I can make the first release with the latest, greatest code during December.

**Comment by essen** [comment]
Right. Wish I finished with the new version sooner, but customers have been very demanding recently. Hopefully can finish soon.

**Comment by raarts** [comment]
This still isn't fixed yet. Now getting: `Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1`

**Comment by essen** [comment]
There are no Cowboy 1.x versions planned. Update to 2.0!
