### ISSUE TITLE
‘cowboy_protocol:opts’  no longer exists.

### ISSUE THREAD

**Issue by 0xfei** [ninenines/cowboy#1057]
cowboy.erl 
-spec start_clear(ranch:ref(), non_neg_integer(), ranch_tcp:opts(),
	cowboy_protocol:opts()) -> {ok, pid()} | {error, any()}.

'cowboy_protocol:opts()' should change to 'opts()'？

**Comment by essen** [comment]
A lot of typespecs are outdated. They'll be updated after the docs are done. To see which spec is correct, check the docs (the cowboy module docs is up to date), then feel free to send PRs.

**Comment by 0xfei** [comment]
Ok, keep learning cowboy.
