### ISSUE TITLE
Return status 431 if the request header fields are too large (RFC6585)

### ISSUE THREAD

**Issue by josevalim** [ninenines/cowboy#1063]
RFC6585 says:

> 431 Request Header Fields Too Large (RFC6585 5, RFC6585 7.3)
> The request's header fields are too large.
> When rejecting a single header, the response should detail which header was at fault.
> When an attack is detected it is recommended to drop the connection directly instead of sending this response.

However, when a header name or value are too large, Cowboy simply returns 400. Returning a more appropriate status code should also help developers who ran into this limit by accident, for example because they end-up creating a large cookie by mistake.

I will be glad to send a PR if agreed this would be an improvement.

**Comment by essen** [comment]
That RFC is in my list of things to review/implement, so a PR is definitely welcome.

**Comment by essen** [comment]
Just make sure to include a test. :-)

**Comment by essen** [comment]
Done.
