### ISSUE TITLE
cow_cookie returns badarg for cookie with no value

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowboy#1065]
```erlang
{error, badarg} = {cow_cookie:parse_cookie(<<"test; a=b; c=d">>).
```
Such cookies are valid by RFC http://www.ietf.org/rfc/rfc2109.txt (4.1)

This makes ```cowboy_req:cookie()``` crash whenever a cookie without value presents in the cookie string.

**Comment by essen** [comment]
This https://tools.ietf.org/html/rfc6265 is the cookie RFC. The one you link was never actually implemented by clients and servers. If my quick look is correct, a name without an equal sign is invalid, but an empty value is OK.

If you see this problem with a popular client in the wild, please detail which one and how to reproduce.

**Comment by brigadier** [comment]
I just got an error log from one of my customers with such errors. Easy to reproduce in Firefox, and likely in other browsers too, with javascript ```document.cookie="test";```

**Comment by essen** [comment]
Yeah, the API problem is documented there: https://tools.ietf.org/html/rfc6265#section-6.2

I am not sure what should be done about this. Is it a blocker for you? Or can the client-side code be changed to have proper key/values?

**Comment by brigadier** [comment]
In my case I can't control what customers do with the software.
I'll have a look at the cow_cookie, going to try to patch it.

**Comment by essen** [comment]
Alright then we probably should allow this form with a good comment in the code saying why we differ from the RFC.

**Comment by brigadier** [comment]
what do you think about this?
https://github.com/brigadier/cowlib/commit/5cbe8a32a968f1b3a204bce67fceea7912170473

**Comment by essen** [comment]
Don't know. :-) I'll get back to you tomorrow.

**Comment by essen** [comment]
Also see #997.

**Comment by brigadier** [comment]
Got another interesting cookie today - "Blocked by http://www.hide-my-ip.com/upgrade-to-remove" (without quotes). Without value, and also contains spaces.

**Comment by essen** [comment]
I think it's pretty clear we should handle invalid cookies without crashing, not sure if they should be ignored or otherwise though.

**Comment by brigadier** [comment]
The easiest way with respect to the existing codebase would be assuming that valid cookies can be without value, with any symbol in name but '=' and ';' and even with empty name. 
```erlang
[{<<>>,<<>>},
 {<<97,32,98,0,10,10,34,99>>,<<>>},
 {<<"x   ">>,<<>>},
 {<<"\r">>,<<"123">>}]  = 
cow_cookie:parse_cookie(<<"=;a b\0\n\n\"c=;x   ;\r=123;">>). ```

The `cowboy_req:set_resp_cookie` should still allow rfc-compatible cookies only.

**Comment by essen** [comment]
I don't think we want to consider them valid when they are not. Also your example is wrong, as `\n` or `\r` would break HTTP/1.1 and we definitely don't need to support that.

I'd be most interested to see what other servers are doing.

**Comment by essen** [comment]
Thoughts for food: http://stackoverflow.com/questions/1969232/allowed-characters-in-cookies

**Comment by brigadier** [comment]
checked with nginx+php5-fpm, got quite a strange results.
If every cookie in the cookie string is malformed, for example "ab cd;ef" then $_COOKIE array is empty.
If the cookie string contains at least one valid cookie  $_COOKIE contains both valid and invalid cookies. 
The cookies with spaces in the name considered as valid, but the spaces are converted to underline.

```
curl -v --cookie "ab cd=123;e f;" http://localtest.com
```
$_COOKIE:
```
Array
(
    [ab_cd] => 123
    [e_f] => 
)
```
```
curl -v --cookie "e f;gh" http://localtest.com
```
$_COOKIE:
```
Array
(
)
```

**Comment by brigadier** [comment]
Django builtin webserver also returns empty dict when there are no valid cookies, but otherwise has quite different opinion:
```
curl -v --cookie "ab cd=123;e f;"  http://127.0.0.1:8000/polls/
```
request.COOKIES
```
{'': 'e f', 'ab cd': '123'}
```

```
curl -v --cookie "e f;gh"  http://127.0.0.1:8000/polls/
```
request.COOKIES
```
{}
```

**Comment by essen** [comment]
Yeah, I can't say I'm too surprised.

Looking into what Python itself does (https://hg.python.org/cpython/file/tip/Lib/http/cookies.py), I sigh. They implement the older cookie parsing routines, with quoting and so on. Cookies are a mess.

Anyway I don't think for this issue that we want to change the *parsing*. The parsing is pretty good and should work for all normal cases. The only thing that needs fixing is how we handle errors, and we definitely don't want to crash for that.

This is what can happen when cookies are invalid:

* crash
* ignore but log them
* just ignore
* try parsing them anyway

There's also the issue of what the server is supposed to do when it encounters bad cookies. If the cookies are left as-is (like when we crash) then they won't be deleted until they expire, and this can be pretty bad for user experience.

Even if we ignore them, they still won't be deleted and will just clutter the bandwidth until they expire.

One thing for sure: we should be able to parse cookies regardless of the presence of invalid segments inside the header. The only question is what to do with those invalid segments.

**Comment by brigadier** [comment]
My take on it:
- Server never should crash on invalid cookies, and should allow invalid segments. 
- We can allow spaces in cookies names. 
- Cookies with empty name  `(;=val;)` should be skipped. 
- Cookies with invalid characters such as `\n` or `,` should be silently skipped. 
- Cookies with no value (without '=') should be considered the same as having empty value. From the pow of purist it would be better to make them having `undefined` as value, but this would break backward compatibility and complicate consumer code which will have to have a case for atom.

This changes parsing, but not much, and changes towards simplification.

**Comment by essen** [comment]
See that's the thing, if we only skip the empty values then we can't ask the browser to delete them (not that we can ultimately ask it to delete all of them if they are path-specific anyway, but still).

**Comment by brigadier** [comment]
Well, something did set these cookies in the browser. So even if we tell the browser to delete them, there's very big chance that this 'something' would just set them again.

**Comment by essen** [comment]
Looking at the most recent draft of the cookie RFC revision: https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.2.2 - still not much to go on with.

> * Server never should crash on invalid cookies, and should allow invalid segments.

I don't think that should be the default, at the very least. Considering the number of vulnerabilities that result from bad or inconsistent parsing, strict must always be the default.

I'm thinking that perhaps Cowboy can do some filtering on cookie names before attempting to parse the cookies. So for example if you only care about a cookie named `session_id` then you could call `cowboy_req:parse_cookies([session_id], Req)` and Cowboy would remove all parts of the cookie header string that are definitely not it before attempting to parse what remains. Maybe something like split on `;` and then keeping only the relevant cookies. When using `cowboy_req:match_cookies/2` we already pass the fields so there doesn't need to be a new argument for the names, but we need a way to signal whether this should be strict or non-strict parsing. Maybe the filtering can be done through a separate function `Req = cowboy_req:filter_cookies([session_id], Req0)` and then you call the usual function on the new `Req`. That gives us the best of both world. Thoughts?

> * We can allow spaces in cookies names.

I don't think PHP is worth copying there. If there's spaces then it might just be a random sentence that was stored using the string cookie API from Javascript. I don't think we should try to handle things that are completely wrong. And the server definitely should not send cookies like this. Filtering them out if we receive them is almost always the right thing to do.

> * Cookies with empty name  `(;=val;)` should be skipped.
> * Cookies with invalid characters such as `\n` or `,` should be silently skipped.

Same goes, completely wrong.

> * Cookies with no value (without '=') should be considered the same as having empty value. From the pow of purist it would be better to make them having `undefined` as value, but this would break backward compatibility and complicate consumer code which will have to have a case clause for atom.

This is already the case and I don't remember why I merged it but at least the original issue is done.

I think I will add that `filter_cookies` function.

**Comment by essen** [comment]
Done in 03dac1486d72d9d84a3cb99d2040c78b25853257. Closing, thanks!

**Comment by brigadier** [comment]
Tbh I don't think this function is very good solution for this problem. For anyone but you and a few of those who knows about the issue #1065 it is not obvious that this function exists at all as there are no similar functions in other web stacks. Also it is not obvious that by default cowboy_req:cookie crashes with bad cookies as any (almost any?) other stack wont crash. So typical use case will be the following: one writes software without using this function, then it encounters bug on production box and then he has to fix this bug. In the worst case the bug will go unnoticed at all.

**Comment by brigadier** [comment]
I'd add option to the cowboy_req:cookie, something like `{malformed_cookies, ignore|crash}`, with `ignore` as default

**Comment by essen** [comment]
You're right, I forgot to make the `parse_cookies` and `match_cookies` documentation explicit about that. I will fix that tomorrow.

As for other software, well, it's not like there's much consistency around cookies. As long as the documentation is explicit I don't see the problem. And like i said Cowboy is very strict (for good reasons!) so ignoring errors is not something I'm willing to do unless there's a very good reason. Even then strict should remain the default. And it's consistent all across Cowboy so I don't think anyone would be too surprised about it.

**Comment by essen** [comment]
I have added the information to the documentation, including a snippet showing how to deal with parsing errors that may occur even after filtering, and will push it later today.
