### ISSUE TITLE
return 406 when accept-language: ru-RU and languages_provided  = [<<"ru">>,<<"en">>].

### ISSUE THREAD

**Issue by maxifly** [ninenines/cowboy#1069]
languages_provided(Req,State) ->
  {[<<"ru">>,<<"en">>],Req,State}.

and in header:
 accept-language: ru-RU

and cowboy return 406

Maybe in  cowboy_rest:match_language have error?

match_language(Req, State, Accept, [Provided|Tail],
		Language = {Tag, _Quality}) ->
	Length = byte_size(Tag),
	case Provided of
		<< Tag:Length/binary, $-, _Any/bits >> ->

Maybe correct code :

match_language(Req, State, Accept, [Provided|Tail],
		Language = {Tag, _Quality}) ->
	Length = byte_size(Provided),
	case Tag of
		<< Provided:Length/binary, $-, _Any/bits >> ->

**Comment by essen** [comment]
No this way is correct. The client requests `ru-RU` specifically, and not other kinds of Russian. The server doesn't provide `ru-RU`. See https://tools.ietf.org/html/rfc7231#section-5.3.5 and particularly the matching scheme Cowboy implements: https://tools.ietf.org/html/rfc4647#section-3.3.1

The example in the first link should be a good explanation of how a client is expected to behave.
