### ISSUE TITLE
cow_multipart:parse_content_disposition/1 gives different result

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#1073]
hello Essen,

I don't know the things I found is a bug or not, but at least I would report it.

I upload files from WEB clinet through HTML POST to the cowboy web server. In this side the handler process got the file successfully. 
Later, when I try parse the "Headers" of the given message by cow_multipart:parse_content_disposition/1, I realized, the result differs when I use different files size (??). 

Here is an example:

When the size of the file is small, few kb. In this case the Header variable looks like this -to get what Headers is, pls, check the bottom part, where I put the source-:

	[{<<"content-type">>,<<"application/octet-stream">>},{<<"content-disposition">>,<<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}]

When I parse this by cow_multipart:parse_content_disposition/1, like this

	{_HeaderPart_1, HeaderPart_2 } = cow_multipart:parse_content_disposition(erlang:term_to_binary(Headers))

I got this result:

	(igs@ethrbh-VirtualBox)14> {_HeaderPart_1, HeaderPart_2 } = cow_multipart:parse_content_disposition(erlang:term_to_binary(Headers)).
	{<<131,108,0,0,0,2,104,2,109,0,0,0,12,99,111,110,116,101,
	   110,116,45,116,121,112,101,109,0,0,...>>,
	 [{<<"name">>,<<"uploadUpgPkg">>},
	  {<<"filename">>,<<"relup">>},
	  {<<"j">>,<<>>}]}

When the size of the file is big, few Mb. In this case the Header variable looks like this -to get what Headers is, pls, check the bottom part, where I put the source-:

	[{<<"content-type">>,<<"application/x-gzip">>},{<<"content-disposition">>,<<"form-data; name=\"uploadUpgPkg\"; filename=\"igs-0.0.2.tar.gz\"">>}]

The result of cow_multipart:parse_content_disposition/1 looks like this

	(igs@ethrbh-VirtualBox)11> {_HeaderPart_1, HeaderPart_2 } = cow_multipart:parse_content_disposition(erlang:term_to_binary(Headers)).
	{<<131,108,0,0,0,2,104,2,109,0,0,0,12,99,111,110,116,101,
	   110,116,45,116,121,112,101,109,0,0,...>>,
	 [{<<"form-data; name">>,<<"uploadUpgPkg">>},
	  {<<"filename">>,<<"igs-0.0.2.tar.gz">>},
	  {<<"j">>,<<>>}]}
	(igs@ethrbh-VirtualBox)12> 

To me, the content-disposition is the same in both, except the name of the file. The problem comes, when I do search for "uploadUpgPkg" in the 2nd element in the result of the cow_multipart:parse_content_disposition/1 function call. In the case when the file size small, the "uploadUpgPkg" is there, but the 1st element its tuple is <<"name">>. In the case when the file size is big, the first element of the tuple is <<"form-data; name">>.

Now I don't understand, I did something wrong, or the cow_multipart:parse_content_disposition/1 does something wrong?

Could you please help to me?

This is the source

	init(Req, Opts) ->
		{Data, Req2} = do_init(Req),
		{ok, cowboy_req:reply(200, #{}, term_to_binary(Data), Req2), Opts}.

	%% ====================================================================
	%% Internal functions
	%% ====================================================================

	do_init(Req) ->
		{Data, Req2} = acc_multipart(Req, []),
		?DO_IGS_INFO("@@ 1",[
							 {data, Data},
							 {req, Req2}
							 ]),
		
		[{Headers, Body}] = Data,
		?DO_IGS_INFO("@@ 2",[
							 {headers, Headers}
							 ]),
		
		{_HeaderPart_1, HeaderPart_2 } = cow_multipart:parse_content_disposition(erlang:term_to_binary(Headers)),
		
		{<<"form-data; name">>, NameBin} = lists:keyfind(<<"form-data; name">>, 1, HeaderPart_2),
		FileUploadReqType = erlang:binary_to_list(NameBin),
		
		{<<"filename">>, FilenameBin} = lists:keyfind(<<"filename">>, 1, HeaderPart_2),
		FileName = erlang:binary_to_list(FilenameBin),
		
		%% Put the file into the current directory
		FileWriteRes = file:write_file(FileName, Body),
		[CurrentPath] = string:tokens(os:cmd("pwd"), "\n"),
		
		case FileUploadReqType of
			"uploadUpgPkg" ->
				FileNameWithPath = string:concat(string:concat(CurrentPath, "/"), FileName),
				
				?DO_IGS_INFO("Got SwM upgrade/downgrade package",
							 [{fileUploadReqType, FileUploadReqType},
							  {fileName, FileName},
							  {fileWriteResult, FileWriteRes},
							  {path, CurrentPath},
							  {fileNameWithPath, FileNameWithPath}
							 ]),
				
				?DO_IGS_INFO("Pass the filename with its full path to the igs_swm_lib:upgrade/1 function.",[]),
				
				UpgRes = igs_swm_lib:upgrade(FileNameWithPath),
				
				?DO_IGS_INFO("Pass the filename with its full path to the igs_swm_lib:upgrade/1 function - DONE",
							 [{result, UpgRes}]),
				
				ok;
			_->
				?DO_IGS_WAR("Unsupported file upload request type, but the received file is saved.",
							[{fileUploadReqType, FileUploadReqType},
							 {fileName, FileName},
							 {fileWriteResult, FileWriteRes},
							 {path, CurrentPath}
							 ]),
				ok
		end,
		
		{Data, Req2}.

	acc_multipart(Req0, Acc) ->
		case cowboy_req:read_part(Req0) of
			{ok, Headers, Req1} ->
				{ok, Body, Req} = stream_body(Req1, <<>>),
				acc_multipart(Req, [{Headers, Body}|Acc]);
			{done, Req} ->
				{lists:reverse(Acc), Req}
		end.

	stream_body(Req0, Acc) ->
		case cowboy_req:read_part_body(Req0) of
			{more, Data, Req} ->
				stream_body(Req, << Acc/binary, Data/binary >>);
			{ok, Data, Req} ->
				{ok, << Acc/binary, Data/binary >>, Req}
		end.

thanks for your help,
/Robi

**Comment by essen** [comment]
Can you show me the HTML form that sends this?

**Comment by ethrbh** [comment]
hello Essen,

This is the HTML form

		<form method="post" enctype="multipart/form-data" action="/upload" id="uploadLinkForm">
		  <input type="file" name="uploadUpgPkg"/>
		  <input type="submit"/>
		</form>

thanks for your help,
/Robi

**Comment by essen** [comment]
```
	{_HeaderPart_1, HeaderPart_2 } = cow_multipart:parse_content_disposition(erlang:term_to_binary(Headers)),
```

Why do you term_to_binary? This creates a binary in the Erlang term format. What you need to do is pass the value for the content-disposition header.

**Comment by ethrbh** [comment]
hello Essen,

I have removed the term_to_binary, but in this case the process crashes earlier. As I see, the Headers is not binary, but list, and it does not fit to the requirement of cow_multipart:parse_content_disposition/1. Please see below.

This is the result when I do not use term_to_binary/1 for Headers

	12:51:37.533 [info] "@@ 2", headers: [{<<"content-type">>,<<"application/octet-stream">>},{<<"content-disposition">>,<<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}], module: igs_web_upload_handler, line: 35
	12:51:37.534 [error] CRASH REPORT Process <0.1207.0> with 0 neighbours exited with reason: no function clause matching cow_multipart:parse_cd_type([{<<"content-type">>,<<"application/octet-stream">>},{<<"content-disposition">>,<<"form-data; name...">>}], <<>>) line 575 in cowboy_stream_h:proc_lib_hack/3 line 162
	12:51:37.535 [error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[webHttp,<0.1205.0>,1,<0.1207.0>,function_clause,[{cow_multipart,parse_cd_type,[[{<<"content-type">>,<<"application/octet-stream">>},{<<"content-disposition">>,<<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}],<<>>],[{file,"src/cow_multipart.erl"},{line,575}]},{igs_web_upload_handler,do_init,1,[{file,"src/igs_web_upload_handler.erl"},{line,37}]},{igs_web_upload_handler,init,2,[{file,"src/igs_web_upload_handler.erl"},{line,18}]},{cowboy_handler,execute,2,[{file,...},...]},...]]},...}}

I tried execute the comamnd in the Erlang shell too, but of cours chrases. I checked have doublechecked what kind of data needs for cow_multipart:parse_content_disposition/1 as input, and it needs binary. In my case the Headers not binary but pure list.

	(igs@ethrbh-VirtualBox)1> 
	(igs@ethrbh-VirtualBox)1> Headers = [{<<"content-type">>,<<"application/octet-stream">>},{<<"content-disposition">>,<<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}].
	[{<<"content-type">>,<<"application/octet-stream">>},
	 {<<"content-disposition">>,
	  <<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}]
	(igs@ethrbh-VirtualBox)2> 
	(igs@ethrbh-VirtualBox)2> cow_multipart:parse_content_disposition(Headers).
	** exception error: no function clause matching 
						cow_multipart:parse_cd_type([{<<"content-type">>,
													  <<"application/octet-stream">>},
													 {<<"content-disposition">>,
													  <<"form-data; name=\"uploadUpgPkg\"; filename=\"relup\"">>}],
													<<>>) (src/cow_multipart.erl, line 575)
	(igs@ethrbh-VirtualBox)3> 

thanks,
/Robi

**Comment by essen** [comment]
You need to pass the content-disposition header, not all headers. `lists:keyfind(<<"content-disposition">>, 1, Headers)`.

Anyway I am not sure why you want to call this function, the function you want is probably `cow_multipart:form_data(Headers)` which parses everything and return you a `file` or `data` tuple depending on what the field is.

**Comment by ethrbh** [comment]
hello Essen,

Maybe you remember, I made a PR for adding new example for upload large size files (PR: https://github.com/ninenines/cowboy/pull/1061). Here, I made the first draft of the handler, and I got the filename from the Header with like this https://github.com/ninenines/cowboy/pull/1061/files/6e1021f22a5432909d10a35946da2b8436daa284#diff-db9b94dd82f054dde193d687d940779e Later, you have suggested to

`Use cow_multipart:parse_content_disposition/1 for getting filename from the header of the request.`

And I did the changes, but I guess, I missunderstand you, because I passed the whole Header to the cow_multipart:parse_content_disposition/1, not just the part of the Header :-( But now I got what you say, and I will fix the fault.

thanks for your help,
/Robi

**Comment by essen** [comment]
I probably gave bad advice when trying to answer too quickly. Unless you have specific needs, the form_data function is the one you want. My bad.

**Comment by ethrbh** [comment]
hello Essen,

No problem at all, really. I am just happy that I can correct advice/answer from you at the "end".

I guess, you can close this ticket.

thanks again,
/Robi
