### ISSUE TITLE
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY error on Chrome (2.0.0-pre.4)

### ISSUE THREAD

**Issue by davidrutt1** [ninenines/cowboy#1075]
Error encountered when  loading a web page from Chrome with Cowboy 2.0.0-pre.4. 
Running server with cowboy with cowboy:start_tls(https, 100,...).
Likely an issue with blacklisted ciphers in HTTP/2

**Comment by essen** [comment]
Cheers. I am traveling next week so will not be able to do it until the week after, but do remind me at some point before that so I don't forget.

**Comment by essen** [comment]
I can't seem to reproduce, at least when trying against localhost. I of course get the warning about the self-signed certificate, but nothing else. Can you post a picture of the exact error you're getting?

**Comment by davidrutt1** [comment]
You know, I have upgrade to the pre-5 version of cowboy and now I cannot
get the error either. So perhaps it was a pre-4 issue or maybe something
else changed. I may have upgrade openssl on my development server in the
meantime as well. So maybe that was related to the issue. Thanks for
checking it out.

**Comment by essen** [comment]
OK then let's close it for now; please reopen if it happens again.

**Comment by turtleDeng** [comment]
I also encountered the same problem.
https://groups.google.com/forum/#!topic/erlang-programming/castDGxkH4U

**Comment by essen** [comment]
Worth noting that Cowboy 2 currently does NOT enforce the cipher/extension requirements of HTTP/2. Could be an issue if you don't do it yourself.
