### ISSUE TITLE
Race condition: requests spaced at exactly the keep-alive timeout apart can get discarded

### ISSUE THREAD

**Issue by SimonWoolf** [ninenines/cowboy#1077]
This is with cowboy 1.0/1.1.

If keepalive is on and a request arrives at exactly the keep-alive timeout (that is, [this value](https://github.com/ninenines/cowboy/blob/1.1.x/src/cowboy_protocol.erl#L90)) after the last request from the same client, it can get discarded.

If it arrives a few milliseconds before Timeout, it goes over the existing stream to the existing handler process and everything is fine. If it arrives a millisecond after Timeout, the stream has already been closed, the ranch acceptor opens a new stream, the request goes to a new handler process and everything is fine. But there's a couple of milliseconds in the middle when everything seems to go a bit pear-shaped.

From the TCP stream's point of view, immediately after the client sends the HTTP request, the server responds with a RST (TCP reset), closing the stream. This generally gets exposed to the client as a 'network error' or somesuch.

![wireshark](https://cloud.githubusercontent.com/assets/5908687/22033726/85aef714-dce1-11e6-9380-5b36b759a376.png)

Ran into this with a test that was (for some reason) waiting 5000ms between two requests, and the second one would intermittently fail. (the Timeout defaults to 5s).

**Comment by essen** [comment]
There is, but as far as I understand it's not possible to do anything about this with HTTP/1.1. HTTP/2 solves this by having a GOAWAY frame which contains the ID of the last successful stream, so the client can know what went through and didn't, but HTTP/1.1 does not have such a mechanism.

**Comment by mattheworiordan** [comment]
@essen what has HTTP/1.1 got to do with it.  As I understand it, it's the responsibility of the server to decide how to handle a request, and in this racey situation, should Cowboy not open a new stream as it would if the keep-alive timeout had passed?  What specifically in HTTP/1.1 effects Cowboy's ability to handle that?

**Comment by essen** [comment]
Correct me if I'm wrong, but you are sending a request at the exact same time Cowboy is closing the connection. Basically Cowboy closes the connection *before* it receives the data you sent on the socket. Not much it can do?

**Comment by mattheworiordan** [comment]
> Correct me if I'm wrong, but you are sending a request at the exact same time Cowboy is closing the connection

Ah, didn't realise that was happening.  If the client adheres to the keep-alive timeout, would extending the server timeout to allow for this racey situation help fix the problem.  @SimonWoolf are clients not responsible for reattempting that TCP connection before HTTP even gets involved?

**Comment by SimonWoolf** [comment]
> Basically Cowboy closes the connection before it receives the data you sent on the socket. Not much it can do?

After thinking some more about it, I guess you're right, I can't think of anything cowboy can do to avoid this. (The server doesn't ACK the TCP packet with the second HTTP request, indicating that the server dropped the TCP connection before receiving that packet, so something at Cowboy's level never has a chance to act on it).

I should have worked that out before opening this bug -- apologies.

>  If the client adheres to the keep-alive timeout, would extending the server timeout to allow for this racey situation help fix the problem

The client never knows about this timeout, it's just serverside. (I have extended the timeout a bit to make this less likely, and made it a non-round number so any clients that happen to wait 5s between requests don't hit it a bunch).

> are clients not responsible for reattempting that TCP connection before HTTP even gets involved?

I guess the client's http lib (here, node's built-in one) could detect that the packet with the HTTP request was never ACKd, establish a new TCP stream, and resend it on that. But it doesn't. I don't know enough about this to guess whether that's a bug in node, or whether that's standard for http client libs.

Never realised how hacky HTTP/1.1 keepalive was before. Bring on HTTP/2, I guess :smile:
