### ISSUE TITLE
cowboy:stop_listener/1 crashes when calling it from my app shell

### ISSUE THREAD

**Issue by miquecg** [ninenines/cowboy#1082]
I don't think this is expected behaviour but if I try to stop a listener from my application shell I get a crash dump.

The motivation to do this is because I cannot stop my service using the start script generated by rebar3 when releasing, and I think this could be related. Something is getting stucked while stopping the service and definitely is cowboy related (without this app no problems so far).

I've tried the workaround suggested in #1021 but the result is the same. My project is running on Erlang 18.3.

[This issue in ranch](https://github.com/ninenines/ranch/issues/90) could also be relevant.

```
> cowboy:stop_listener(http_server).
> 16:57:30.310 [info] Application my-service exited with reason: shutdown
Terminating: []
{"Kernel pid terminated",application_controller,"{application_terminated,my-service,shutdown}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_terminated,my-service,shutdown}
```

**Comment by essen** [comment]
It shouldn't happen with Cowboy master. Try it.

**Comment by miquecg** [comment]
I've just tried tag `2.0.0-pre.6` but it's not working for me. Same issue.

**Comment by essen** [comment]
But have you also updated Ranch or was it the same version as before? The fix is in Ranch.

**Comment by miquecg** [comment]
Well, I did `rebar3 upgrade` and then `rebar3 release ...`. I saw in the output that ranch 1.3.0 was fetched. In fact I tried this before upgrading manually ranch to that version and it didn't solve the issue.

I'll check again on Monday. Maybe I did something wrong.

**Comment by essen** [comment]
I can't reproduce on the `ssl_hello_world` example. I need more info if it's really an issue in Cowboy.

**Comment by miquecg** [comment]
I will try running the examples provided because the problem is still present. I've built the project again with tag `2.0.0-pre.6` and checked that ranch 1.3.0 was being used and happens the same.

**Comment by miquecg** [comment]
I've managed to understand what was going on. I was returning the cowboy PID in the start function, so when stopping the listener the whole application went down. I didn't pay attention to that return value, sorry!
