### ISSUE TITLE
[Proposal] Automatic Let's Encrypt configuration

### ISSUE THREAD

**Issue by imetallica** [ninenines/cowboy#1083]
Hi, I want to propose a feature which I believe would save time and money and, I've found in another webserver: [Caddy](https://caddyserver.com)

The idea is that we can make Cowboy automatically request certificates from Let's Encrypt, if in the configuration the url address is set to do so, and cowboy cannot find these certificates previously. Also, it should make Cowboy refresh these in a weekly (or monthly) manner (maybe make it configurable?). I believe since Let's Encrypt is now part of the Linux Foundation and has a ton on visibility it would be quite a handy feature for Cowboy to have.

So, things to consider:
- Integrate with the ACME protocol.
- Add a new option in the endpoint configuration (which is backwards compatible)
- Check expiration date & renewal. Probably as a configuration option (which again is backwards compatible)

I would love to discuss this and, being ok with everyone, I could give a shot implementing it on Cowboy.

**Comment by essen** [comment]
Doesn't ACME require JSON? I don't really want to double the size of Cowboy just for something like this. It should be done in a separate project.

I am open to adding capabilities of changing certificates without having to stop everything, if that's missing.

**Comment by imetallica** [comment]
@essen yes, ACME requires JSON. Well, yeah, it might turn Cowboy really big, maybe as a side project would be a better idea.

**Comment by essen** [comment]
Alright, closing this then. If and when someone starts this project and needs changes in Cowboy, they can open tickets with the specifics. Thanks!

**Comment by mmzeeman** [comment]
FYI, we have implemented this in https://github.com/zotonic/zotonic/tree/master/modules/mod_ssl_letsencrypt, which also uses cowboy.

**Comment by ShalokShalom** [comment]
@mmzeeman Your link is down, can you activate it again? 

Here is the Erlang API for Let`s encrypt: https://github.com/gbour/letsencrypt-erlang

I also appreciate such an implementation.

**Comment by mmzeeman** [comment]
Sure. We have moved to an OTP compliant directory structure.

https://github.com/zotonic/zotonic/tree/master/apps/zotonic_mod_ssl_letsencrypt

We use https://github.com/zotonic/letsencrypt-erlang.git as dep. Not sure what the difference is with the dep you mention. @mworrell you probably know?

**Comment by ShalokShalom** [comment]
No, I mean such an implementation as that one here, which is proposed. 
Some implementation, in general. Sorry, my English is in Beta. :hugs:

**Comment by mmzeeman** [comment]
What do you mean? Zotonic uses cowboy and letsencrypt to request new certificates for sites.

**Comment by mworrell** [comment]
@mmzeeman the zotonic version is modified to enable multiple LetsEncrypt processes (as we have multiple sites, and they can request a certificate in parallel). The changes aren't merged (yet) as we bumped into a test failure. After that test failure is resolved we can merge upstream.

**Comment by ShalokShalom** [comment]
I mean simply the integration that is meant in this issue in general. A theoretical one in Cowboy :hugs:
