### ISSUE TITLE
failing silently when still providing Req objects after upgrading

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/cowboy#1085]
[Example](https://github.com/ingwinlu/cowboy_pre_req_fail) showing silent fail of cowboy after upgrading to recent pre-6 version without updating the callback handler. The handler is still providing the old Req field in the callbacks. Cowboy is failing silently which is not expected behaviour

**Comment by essen** [comment]
I'm not sure much can be done about that considering websocket_init was made optional (so the wrong function arity will be seen as the function missing). On the other hand if a function is missing past that point it produces an error as expected.
