### ISSUE TITLE
"make run" fails when following Getting Started guide

### ISSUE THREAD

**Issue by stephenlam** [ninenines/cowboy#1086]
I tried to follow the instructions here: https://ninenines.eu/docs/en/cowboy/2.0/guide/getting_started/

"make run" succeeds at the end of the Bootstrap step. But once I modify the Makefile to add the cowboy dependency, I get the following error:

~/hello_erlang$ make run
make[1]: Entering directory '/home/stephenlam/hello_erlang/deps/cowboy'
make[2]: Entering directory '/home/stephenlam/hello_erlang/deps/cowlib'
make[2]: Leaving directory '/home/stephenlam/hello_erlang/deps/cowlib'
make[2]: Entering directory '/home/stephenlam/hello_erlang/deps/ranch'
make[2]: Leaving directory '/home/stephenlam/hello_erlang/deps/ranch'
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clear.erl cowboy_clock.erl cowboy_compress_h.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_static.erl cowboy_stream.erl cowboy_stream_h.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
src/cowboy_http.erl:505: illegal use of variable 'Name' in map
src/cowboy_http.erl:507: illegal use of variable 'Name' in map
src/cowboy_http.erl:508: illegal use of variable 'Name' in map
../../erlang.mk:5055: recipe for target 'ebin/cowboy.app' failed
make[2]: *** [ebin/cowboy.app] Error 1
../../erlang.mk:4859: recipe for target 'app' failed
make[1]: *** [app] Error 2
make[1]: Leaving directory '/home/stephenlam/hello_erlang/deps/cowboy'
erlang.mk:4180: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by essen** [comment]
You need Erlang 19+. See the chapter just before that one.
