### ISSUE TITLE
Regression in path segments parsing with some non-percent-encoded unallowed characters

### ISSUE THREAD

**Issue by dumbbell** [ninenines/cowboy#1087]
In the copy of `cow_uri` found in Cowboy 1.1.0, there is a regression compared to the previous Cowboy 1.0.x URL decoding around some unallowed characters in URI path segments.

For instance, `>` is supposed to be percent-encoded according to RFC 3986 because it's not part of the `unreserved` or `sub-delims` sets (see parapgrahs 2.2, 2.3 and 3.3).

However, Cowboy 1.0.x accepted and handled requests with a URI containing a plain `>`. Now, `cow_uri:urldecode()` found in Cowboy 1.1.x crashes with `function_clause` when it sees such a character.

**Comment by essen** [comment]
Shouldn't be a problem in 2+ and you don't care much about 1.x anymore so I'll be closing this. Thanks!
