### ISSUE TITLE
Release 1.1.0 has inconsistent dependency on ranch

### ISSUE THREAD

**Issue by nalundgaard** [ninenines/cowboy#1088]
The recent [1.1.0](https://github.com/ninenines/cowboy/tree/1.1.0) has an inconsistent version pin for ranch. the Makefile pins it at [1.3.1](https://github.com/ninenines/cowboy/blob/1.1.0/Makefile#L18), but it's still set at [1.2.0](https://github.com/ninenines/cowboy/blob/1.1.0/rebar.config#L1) in the rebar.config.

My company uses rebar to package our Erlang HTTP services, and we were just looking at updating from 1.0.4 to 1.1.0, but we've found that ranch is still pulled down from `1.2.0`. This seems like an oversight. Is it possible to get a 1.1.1 tag that corrects this inconsistency?

**Comment by essen** [comment]
Sure, send a patch. Looks like 1.1.x branch doesn't generate rebar.config automatically, which is why I didn't catch it.

**Comment by nalundgaard** [comment]
@essen Done! #1089 targets the 1.1.x branch.

**Comment by essen** [comment]
Thanks, a bit late for me right now so I'll see when I next have some time. Cheers.
