### ISSUE TITLE
Implement gzip and Brotli in Erlang? or as dirty NIF

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1092]
Even though Brotli is better for many or most cases, we still need gzip for some things, like Websocket compression. The zlib module coming with Erlang is implemented in C with zlib but seems to only ever use one core so that's not good.

**Comment by essen** [comment]
deflate: https://tools.ietf.org/html/rfc1951
gzip: https://tools.ietf.org/html/rfc1952
brotli: https://tools.ietf.org/html/rfc7932

**Comment by essen** [comment]
Implementing in Erlang is probably crazy talk. An alternative would be to wait for OTP 20 and implement as CPU? bound dirty NIFs.

**Comment by essen** [comment]
Sounds like gzip was made much faster in OTP 20.1. I'll close for now and take a look later on.

**Comment by Fudoshiki** [comment]
Hello, planning to add Brotli now?

**Comment by essen** [comment]
No plans unless a paid customer asks. There is https://github.com/yjh0502/erl-brotli if you want to try, but I don't know how it fares.

**Comment by Fudoshiki** [comment]
Thanks
