### ISSUE TITLE
Small changes to rebar.config

### ISSUE THREAD

**Issue by altishchenko** [ninenines/cowboy#1122]
Please, change the dependancies in rebar.config to state {branch, "master"} and {tag, "1.3.0"} instead of pure values here:
```erlang
{cowlib,".*",{git,"https://github.com/ninenines/cowlib",{branch, "master"}}},{ranch,".*",{git,"https://github.com/ninenines/ranch",{tag, "1.3.0"}}}
```

**Comment by essen** [comment]
No.

This file is generated, and Erlang.mk does not care about branch/tag/.. so it won't be added.

**Comment by altishchenko** [comment]
Very unfortunate. Produces useless rebar warnings. :(

**Comment by essen** [comment]
Rebar or rebar3? It's only rebar3 AFAIK.

**Comment by altishchenko** [comment]
Oh, sorry. rebar3 for sure - more nitpicking...
Alas, not a big deal.
