### ISSUE TITLE
cowboy_http.erl , the default type of 'set_cookie' is a list which causes match failed. 

### ISSUE THREAD

**Issue by ForLina** [ninenines/cowboy#1124]
In cowboy_http.erl, the default type of 'set_cookie' is  list ,

cowboy_http.erl
`headers_to_list(Headers0=#{<<"set-cookie">> := SetCookies}) ->

    Headers1 = maps:to_list(maps:remove(<<"set-cookie">>, Headers0)),
    Headers1 ++ [{<<"set-cookie">>, Value} || Value <- SetCookies];
headers_to_list(Headers) ->
	maps:to_list(Headers).`

But when you use httpc:request/N, the value of 'setcookie' is a string,  so you can't tranfer the headers to a map simply using
` maps:from_list([{list_to_binary(K), list_to_binary(V)} || {K, V} <- Headers])`

**Comment by essen** [comment]
You can't because maps can't have multiple identical keys. Not much I can do there.

Also note that cookies *should* be set using set_resp_cookie which handles this exception properly.

**Comment by ForLina** [comment]
Thanks. This happens when I try to use Cowboy as a proxy server, I receive request and transpond it to a http server in interal server.

**Comment by essen** [comment]
Yep. You'll have to do a little pre-processing unfortunately.
