### ISSUE TITLE
upload example (cowboy 1.1.2)

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1125]
I'm testing the upload example code.  If I use small files it works fine (under 100k).  I tried an 8 meg file, it has an error:

Error in process <0.994.0> on node '....' with exit value:
{[{reason,
      {badmatch,
          {more, 

 with << binary numbers output >>......

Is this a file size limit problem?  How can I upload large files?

Thanks.

**Comment by essen** [comment]
https://github.com/ninenines/cowboy/pull/1072

**Comment by comptekki** [comment]
It looks like this is for cowboy post 1.1.2.  I've been messing with it to
get it to work with cowboy 1.1.2, but the setup/return values have
changed....  keep getting errors on file submit.

Thanks.

**Comment by essen** [comment]
There's no plans for more 1.1 releases, and if there are they won't include providing better examples.

The user guide for 1.0 already had code for streaming the body, see https://ninenines.eu/docs/en/cowboy/1.0/guide/req_body/#streaming_the_body

**Comment by comptekki** [comment]
OK.  Thanks.  I also need to see what I need to change to change my current
app to current master compatibility.
