### ISSUE TITLE
Handle system messages

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1126]
And write a sys_SUITE.

**Comment by fishcakez** [comment]
Please feel free to use any code, particularly the tests, from the my
system message PRs targeting v1.1. Not sure any of it applies anymore but
be my guest all the same.

**Comment by essen** [comment]
Yes! I kept them open specifically for that reason. :-) Thanks!

They probably don't apply anymore since they pre-date the large internal rewrites in 2.0.0-pre.4. But they'll be a good checklist.

Note that this ticket is specifically about handling system messages, the processes already use proc_lib.

**Comment by essen** [comment]
While I'm here...

https://github.com/ninenines/cowboy/pull/750
https://github.com/ninenines/cowboy/pull/754

**Comment by essen** [comment]
Man these PRs were huge. I will only respond to system messages first, with no code_change/format_status and such (or rather, not change of state when code_change happens, etc.) and we can see later for bigger and better.

**Comment by essen** [comment]
This part is done on master.
