### ISSUE TITLE
cookie_example is not working 

### ISSUE THREAD

**Issue by perneh** [ninenines/cowboy#1128]
/git/cowboy/examples/cookie$ make run

/home/per/git/cowboy/examples/cookie/_rel/cookie_example
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

(cookie_example@Vivo1)1> 
=ERROR REPORT==== 19-Feb-2017::16:21:43 ===
Ranch listener http, connection process <0.521.0>, stream 1 had its request process <0.522.0> exit with reason function_clause and stacktrace [{cowboy_req,header,[<<"cookie">>,#{path => <<"/">>,resp_cookies => #{<<"server">> => [<<"server">>,<<"=">>,"503725",<<"; Version=1">>,<<>>,<<>>,[<<"; Path=">>,<<"/">>],<<>>,<<>>]}},undefined],[{file,"src/cowboy_req.erl"},{line,347}]},{cowboy_req,parse_header,4,[{file,"src/cowboy_req.erl"},{line,391}]},{cowboy_req,match_cookies,2,[{file,"src/cowboy_req.erl"},{line,402}]},{toppage_handler,init,2,[{file,"src/toppage_handler.erl"},{line,13}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,172}]},{cowboy_stream_h,proc_lib_hack,3,[{file,"src/cowboy_stream_h.erl"},{line,157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

=ERROR REPORT==== 19-Feb-2017::16:21:43 ===
Ranch listener http, connection process <0.521.0>, stream 2 had its request process <0.523.0> exit with reason function_clause and stacktrace [{cowboy_req,header,[<<"cookie">>,#{path => <<"/">>,resp_cookies => #{<<"server">> => [<<"server">>,<<"=">>,"730271",<<"; Version=1">>,<<>>,<<>>,[<<"; Path=">>,<<"/favicon.ico">>],<<>>,<<>>]}},undefined],[{file,"src/cowboy_req.erl"},{line,347}]},{cowboy_req,parse_header,4,[{file,"src/cowboy_req.erl"},{line,391}]},{cowboy_req,match_cookies,2,[{file,"src/cowboy_req.erl"},{line,402}]},{toppage_handler,init,2,[{file,"src/toppage_handler.erl"},{line,13}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,172}]},{cowboy_stream_h,proc_lib_hack,3,[{file,"src/cowboy_stream_h.erl"},{line,157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

**Comment by essen** [comment]
It is working, but you need the most recent version of Cowboy to have the correct example. Examples currently download master and don't use the top-level Cowboy.
