### ISSUE TITLE
Example cookie client returns test= and not the client cookie 

### ISSUE THREAD

**Issue by perneh** [ninenines/cowboy#1130]
sorry 4 being zealous, I like it when things work
cowboy$ git pull
Already up-to-date.
                           <<"cookie">> => <<"server=900690; client=test=">>,

**Comment by essen** [comment]
Returning `test=` is the correct behavior?

**Comment by perneh** [comment]
No it did return the client cookie before

**Comment by essen** [comment]
Please describe the problem with steps to reproduce. I have no idea what you are saying right now.

**Comment by perneh** [comment]
I did just git pull 
cd examples/cookie
make run
http://localhost:8080/

Cowboy Cookie Example
Refresh the page to see the next cookie.
Cookie Set Server-Side
524693
Cookie Set Client-Side
test=

**Comment by essen** [comment]
That's the intended behavior. Client cookie does not change (it's set to `test=` every time), only server one does.

**Comment by perneh** [comment]
OK it just don't make any sense to me.
