### ISSUE TITLE
Docs for websocket "Keeping the connection alive" are outdated

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#1132]
It says to return a number for idle_timeout as 4th tuple item, it seems it's a map now.

Did a quick search and couldn't find an issue for this, feel free to close if there's already one.

https://ninenines.eu/docs/en/cowboy/2.0/guide/ws_handlers/#_keeping_the_connection_alive

**Comment by essen** [comment]
Forgot to update the site! Will do now.

**Comment by essen** [comment]
Done! Thanks.
