### ISSUE TITLE
cowboy_req:qs/match_qs cannot handle 2 or more key/value query string

### ISSUE THREAD

**Issue by refactor** [ninenines/cowboy#1135]
for URL like
/path?id=135&lang=en

below dosen't work:
{id := ID, lang := Lang} = cowboy_req:match_qs([id, lang], Req)

**Comment by essen** [comment]
I have a test for this that is passing. You'll have to provide more info.

**Comment by refactor** [comment]
sorry, it looks like a cURL problem. it's OK when using Safari browser.

**Comment by refactor** [comment]
when using cURL command line, the URL should be quoted, just like a string:
curl "http://localhost:8080/path?id=135&lang=en"

otherwise, without quoted, only the first query parameter are submit

**Comment by essen** [comment]
Right, because `&` is a special character in the shell to run the command in the background. Closing!
