### ISSUE TITLE
crash after ping pong

### ISSUE THREAD

**Issue by jianjyan** [ninenines/cowboy#1139]
Hi,
I've called the net_adm:ping('xchat@192.168.0.100); response is pong.
then crash happened:
ing/1       ping_list/1  
(xchat_dev@192.168.0.100)1> net_adm:ping('xchat@192.168.0.100').
pong
(xchat_dev@192.168.0.100)2> 01:55:25.388 [error] Supervisor xchat_sup had child auth_process started with auth_process:start_link() at <0.814.0> exit with reason killed in context child_terminated
01:55:25.388 [error] Supervisor xchat_sup had child auth_process started with auth_process:start_link() at <0.814.0> exit with reason reached_max_restart_intensity in context shutdown
01:55:25.392 [info] Application xchat exited with reason: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,xchat,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,xchat,shutdown})
heart: Sun Mar  5 01:55:32 2017: Erlang is crashing .. (waiting for crash dump file)
heart: Sun Mar  5 01:55:32 2017: Would reboot. Terminating.

I can't find the crash dump file, where's the default folder for the cowboy's crash dump?
auth_process:init function has nothing functionality but these:
init([]) ->
	% init netease sms
	% init netease im token
	?DEBUG("auth_process init"),
	case cache:start_link({global, pswd_cache}, [{policy, lru}, {n, 10}, {ttl, 3600}]) of
		{ok, _} -> ok;
		{error, {already_started, _}} -> ok;
		_ -> ok
	end,
	case cache:start_link({global, sms_cache}, [{policy, lru}, {n, 10}, {ttl, 900}]) of
		{ok, _} -> ok;
		{error, {already_started, _}} -> ok;
		_ -> ok
	end,
	case cache:start_link({global, user_token_cache}, [{policy, lru}, {n, 10}]) of
		{ok, _} -> ok;
		{error, {already_started, _}} -> ok;
		_ -> ok
	end,
	{ok, #state{}}.

**Comment by jianjyan** [comment]
auth_process works fine without ping is called

**Comment by essen** [comment]
I don't know what this is, but this isn't Cowboy. Please use the correct channels for asking your question. If it's a general Erlang question, the erlang-questions mailing list is your best bet.

**Comment by jianjyan** [comment]
hi,
just cant find the crash dump when using cowboy

**Comment by essen** [comment]
OK but Cowboy doesn't do anything about that so please ask on the Erlang channels.
