### ISSUE TITLE
web socket handle cannot get current request infomation

### ISSUE THREAD

**Issue by RazgrizHsu** [ninenines/cowboy#1145]
the current websocket_handle is 
```
websocket_handle(Frame = {text, _}, State) ->
    {reply, Frame, State};
websocket_handle(_Frame, State) ->
    {ok, State}.
```
i'm using JavaScript webSocket to test,
when i send message to server,
i just can received the frame without the client infomation

please help me, thanks

**Comment by essen** [comment]
What do you mean by client information? The frame? Is the client sending text or binary frames? Please provide more info.

**Comment by RazgrizHsu** [comment]
thanks for response, 
i mean i wanna get the client IP address from websocket_handle
because i need it for decide what is next step

it's my design or thinking direction is wrong?

thank you :)

**Comment by essen** [comment]
You need to put it in your state from the init/2 function.

**Comment by RazgrizHsu** [comment]
@essen sorry for my english, 
i don't understand how to get the req variable from handle function?
like this?

```
def init( req, state ) do
	IO.puts "[ws:init] req[#{inspect req}]"

	:ets.insert(:ips, { self(), req })

	:erlang.start_timer( 1000, self(), ["Hello?"])
	{:cowboy_websocket, req, state, %{ :idle_timeout => 3000 }}
end

def websocket_handle({:text, content} = _frame, state) do

	req = :ets.lookup(:ips, "foo")

	IO.puts "[ws] get client send[ #{ inspect _frame} ] from [ #{ inspect req } ]"

	{:reply, {:text, "got your message: [#{content}]"}, state}
end
```

thank you for your help

**Comment by RazgrizHsu** [comment]
@essen 
bcoz i wanna detect the message send from which client, please help me , thank you

**Comment by essen** [comment]
I am not really sure what your code does. All you need is to put the values you want in your state. Ask someone who knows Elixir for an example perhaps.

**Comment by RazgrizHsu** [comment]
@essen  thank you so much,
now i know the variable "state" will transfer to all handle function,
just put the "req" inner ip address to "state",
that is i need, thank you 👍
