### ISSUE TITLE
Ability to access the client SSL Certificate in V2.0

### ISSUE THREAD

**Issue by willemdj** [ninenines/cowboy#1147]
This feature in no longer available in 2.0 (or not in an easy way, anyway), but it would be good to have.

**Comment by essen** [comment]
Good point.

**Comment by sander** [comment]
As [suggested](https://github.com/ninenines/cowboy/issues/908#issuecomment-290938871) by @essen, there is a workaround:

1. Replace the `cowboy:start_tls` call with `start_tls_hack` and
```erlang
start_tls_hack(Ref, NumAcceptors, TransOpts0, ProtoOpts0) ->
    {TransOpts1, ConnectionType} = ensure_connection_type(TransOpts0),
    TransOpts = [
        {next_protocols_advertised, [<<"h2">>, <<"http/1.1">>]},
        {alpn_preferred_protocols, [<<"h2">>, <<"http/1.1">>]}
    |TransOpts1],
    ProtoOpts = ProtoOpts0#{connection_type => ConnectionType},
    ranch:start_listener(Ref, NumAcceptors, ranch_ssl, TransOpts, tls_with_socket, ProtoOpts).

ensure_connection_type(TransOpts) ->
    case proplists:get_value(connection_type, TransOpts) of
        undefined -> {[{connection_type, supervisor}|TransOpts], supervisor};
        ConnectionType -> {TransOpts, ConnectionType}
    end.
```
2. Implement `tls_with_socket`:
```erlang
-module(tls_with_socket).
-behaviour(ranch_protocol).

-export([start_link/4]).

start_link(Ref, Socket, Transport, Opts = #{env := Env0}) ->
    Env = Env0#{socket => Socket},
    cowboy_tls:start_link(Ref, Socket, Transport, Opts#{env := Env}).
```

3. Now you can access the client certificate in middleware, e.g.
```erlang
-module(middleware).
-behaviour(cowboy_middleware).

-export([execute/2]).

execute(Req, Env) ->
    #{socket := Socket} = Env,
    {ok, Cert} = ssl:peercert(Socket),
    {ok, IssuerID} = public_key:pkix_issuer_id(Cert, self),
    erlang:display({id, IssuerID}),
    {ok, Req#{issuer_id => IssuerID}, Env}.
```

**Comment by essen** [comment]
I don't like it but I think a good start would be to keep the socket in the Req object, write a few interface functions and hope people don't start sending things on the socket. Later on if necessary the socket can be removed from Req, but that would introduce latency and extra code that I am not sure is worth the pain.

I'm thinking about the following interface for all kinds of socket infos:

* peer/1 already exists
* sock/1 does inet:sockname/1 (might be worth storing it like we do peer)
* socket_info/1,2: does inet:getstat/1,2 ssl:connection_information/1,2
* cert/1 does ssl:peercert/1

If I'm missing something, do tell.

**Comment by willemdj** [comment]
Sounds good to me.

**Comment by essen** [comment]
Actually I think I will go this way: add sock/1 (same behavior as peer, directly in the Req, no socket call needed) and cert/1 (also stored directly in the Req, retrieve it once only when the connection gets established, and return `undefined` if there's no client certificate).

For getstat and connection_information it may be useful to have an interface to them BUT I somehow don't think handlers care about this. I'll leave them out for the time being.

**Comment by essen** [comment]
This should be done in ef58e15547ee171a716eaa768374e2e7e2f7d397. New functions `cowboy_req:sock/1` and `cowboy_req:cert/1`

Please try it!
