### ISSUE TITLE
cowboy2 stream_body seems to be timing out after 5s

### ISSUE THREAD

**Issue by drozzy** [ninenines/cowboy#1148]
I'm following along with the docs [here](https://ninenines.eu/docs/en/cowboy/2.0/guide/resp/#_stream_reply) and trying to send a user a file download (formed from many different sql queries).

But it seems like after about 5 seconds of `stream_body` loops, cowboy shuts down the connection.

Is there any way to keep it going?

Thanks!

**Comment by essen** [comment]
It's the bug referenced here: https://github.com/ninenines/cowboy/issues/1032#issuecomment-280765513

Temporary fix is to increase request_timeout.

**Comment by drozzy** [comment]
@essen Just a section on loop handlers: https://ninenines.eu/docs/en/cowboy/2.0/guide/loop_handlers/

Would that work instead?

**Comment by essen** [comment]
That's something you can use but it suffers from the same bug currently.

**Comment by drozzy** [comment]
@essen Ok thanks! Timeout works for now, and is probably a good idea anyway.

It would be nice if we could detect that the connection was _dropped_, so as to stop the further `stream_body` calls. Is that possible?

**Comment by essen** [comment]
It will be when you use loop handlers when the bug is fixed AND I make Cowboy not brutally kill the process when the connection is gone. So still some time away for now.

**Comment by drozzy** [comment]
:-) Ok, good to know it's coming!

P.S.: Cowboy is great!
