### ISSUE TITLE
Compilation warnings in dependencies

### ISSUE THREAD

**Issue by SergeyOvchinnik** [ninenines/cowboy#1151]
Compiling this project yields a large number of compilation warnings coming from `ranch` and `cowlib` dependencies.

As a developer using this project as dependency, I would like this project to compile without any warnings coming from its dependencies.

**Comment by essen** [comment]
There is no warning in current master.

You probably mean 1.0, which is old and unsupported, and probably has a few harmless deprecation warnings. They don't have warnings on the Erlang versions they were made for.
