### ISSUE TITLE
Cowboy examples - unable to make and run

### ISSUE THREAD

**Issue by cerubim** [ninenines/cowboy#1157]
Hello. 
For cowboy examples, it says to build and run them, execute 'make run' (https://github.com/ninenines/cowboy/tree/master/examples/file_server). I have tried this for a couple of the examples, 'file_server' and 'rest_hello_world' and the command does not terminate and it doesn't do anything. First time I rand it, it was mentioning that too many files are open and I had to increase the hard/soft limit.  Now it's jus,  using the CPU and there is no output, not even from Erlang VM. I have cowboy installed as a DEPS of the getting started 'hello_erlang' app and the commit level is master.
I have also tried downloading erlang.mk to the example's folder and running 'make -f erlang.mk run' with the same result.
Please let me know if any more information is needed,
V.

**Comment by essen** [comment]
Saw on IRC but you were gone already. If this is Windows, you need a graphical environment for `make run`, unfortunately. If this is another platform, please provide more info on OS, Erlang version and so on, and also try `make run V=1` and post the ouput.

**Comment by cerubim** [comment]
I am running on Ubuntu Mate 17.04, in Virtual Box, Erlang version 19.? and output:
valzant@valzant-VB:~/devel/study-cowboy/hello_erlang/deps/cowboy/examples/rest_hello_world$ erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2.1
valzant@valzant-VB:~/devel/study-cowboy/hello_erlang/deps/cowboy/examples/rest_hello_world$ make run v=1
^C
I had to stop it as nothing was happening.

**Comment by essen** [comment]
It's case sensitive so please make sure you use `make run V=1` and not v=1.

**Comment by cerubim** [comment]
Sorry, I did not see the capital 'V'. I have tried it and the same result: no output, high cpu usage. If you cannot reproduce it on your end it's probably an issue with my environment and I can just close this issue. 
valzant@valzant-VB:~/devel/study-cowboy/hello_erlang/deps/cowboy/examples/rest_hello_world$ make run V=1
^C

**Comment by essen** [comment]
Could still be useful to pinpoint why it happens, if you have the patience. Otherwise feel free to close.

If you just run `make`, does it complete? Or is it just `make run`?

If just `make run`, it would be good to look at your environment variables, or perhaps check if you have symlinks that something somewhere could walk through infinitely.

**Comment by cerubim** [comment]
I am attaching the output of 'env' command. The only custom symlink is to dropbox:
lrwxrwxrwx  1 valzant valzant    27 Apr 29 13:35 devel -> /home/valzant/Dropbox/devel
[env.txt](https://github.com/ninenines/cowboy/files/967025/env.txt)

**Comment by essen** [comment]
That's the only potential issue I see. See if you can reproduce outside devel.

**Comment by cerubim** [comment]
I have tried it outside 'devel' symlink and I could stil reproduce it but I'll close the issue since it seems to be an issue with my env.

**Comment by essen** [comment]
Thanks.
