### ISSUE TITLE
Can I pass env variable to handler?

### ISSUE THREAD

**Issue by JamesArthurHolland** [ninenines/cowboy#1160]
Hi, 

I'm currently writing middleware to handle authentication for all requests. 

An oauth token will be taken from the headers, then user associated with that token from the authentication server, will be returned (as a record).

I wish to pass the user record on to whichever handler is requested, is there a way of passing the Env variable, or should I manipulate the Req variable by adding the user record to that?

Regards,

 James

**Comment by essen** [comment]
Depending on the version, after the router runs, you should have a handler_opts or handler_state in the environment, that's your last argument to the init function.

**Comment by JamesArthurHolland** [comment]
Thanks.
