### ISSUE TITLE
Unable to build cowlib

### ISSUE THREAD

**Issue by Sviests** [ninenines/cowboy#1161]
I am getting the following error when building cowlib
DEPEND cowlib.d
 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_sse.erl cow_uri.erl cow_ws.erl
src/cow_sse.erl:32: syntax error before: ':='
src/cow_sse.erl:44: type event() undefined
erlang.mk:5068: recipe for target 'ebin/cowlib.app' failed
make[1]: *** [ebin/cowlib.app] Error 1
erlang.mk:4872: recipe for target 'app' failed
make: *** [app] Error 2

**Comment by essen** [comment]
Erlang 19+.
