### ISSUE TITLE
infinite loop on incomplete body in cowboy_req:read_part_body/2

### ISSUE THREAD

**Issue by geogriff** [ninenines/cowboy#1162]
an infinite loop occurs if parsing an empty multipart body with cowboy_req:read_part/2 (which returns {ok, _, _}) followed by cowboy_req:read_part_body/2. i'm currently trying to track down a fix for this, unless you want to give it a shot. i'm mainly not sure if incomplete requests will also infinite loop, so we'll probably want to test that as well, and keep that in mind with any fix for this. here's a quick test to plop into http_SUITE.erl which triggers the bug:
```
multipart_empty(Config) ->
	ConnPid = gun_open(Config),
	Body = <<>>,
	Ref = gun:post(ConnPid, "/multipart",
		[{<<"content-type">>, <<"multipart/x-makes-no-sense; boundary=OHai">>}],
		Body),
	gun:await(ConnPid, Ref),
	{ok, _} = gun:await_body(ConnPid, Ref),
	ok.
```

**Comment by essen** [comment]
Ah yes we need to have a special case when `read_body` is false or `has_read_body` is true.

**Comment by essen** [comment]
Wait is it the body empty or multipart segment body?

**Comment by geogriff** [comment]
completely empty request body, which i'm not sure may or may not be invalid for multipart (but I don't want spinning procs for invalid reqs either ;-)

**Comment by essen** [comment]
Then my first comment was OK, that's the likely reason. Thanks!

**Comment by geogriff** [comment]
FYI seems like empty multipart is not legal according to [RFC 2046 5.1.1](https://tools.ietf.org/html/rfc2046#section-5.1.1) "This [multipart] Content-Type value indicates that the content consists of one or more parts.."

**Comment by geogriff** [comment]
OK, after trying different tests, looks like it infinite loops any time a multipart is in any way incomplete, not just empty
