### ISSUE TITLE
trap websocket errors

### ISSUE THREAD

**Issue by fredr** [ninenines/cowboy#1166]
Is there any way of trapping errors when receiving websocket messages, i.e `{:error, :badencoding}`

I would like to prevent the connection from being closed when the client is sending weird data (I'm porting an old ws protocol, and there are some bugs in the clients that I can't fix)

I'm using cowboy 1.1.2, but I guess its the same in cowboy 2?

**Comment by essen** [comment]
It's not currently possible, and probably won't be anytime soon. On the other hand I would not be against an option that disables the UTF-8 encoding check.

**Comment by fredr** [comment]
Could a change like that be merged into 1.1.x, or would that only be for 2.x? 

If you think its a good idea, I can look into adding an option for it, however, I've no erlang experience (using cowboy in elixir), so I wont make any promises :)

**Comment by essen** [comment]
I have no further 1.x releases planned so while you are welcome to open a PR for it it's unlikely to lead anywhere.

**Comment by fredr** [comment]
Alright! Thanks for your quick responses

**Comment by essen** [comment]
There's a separate ticket for disabling the utf-8 check at https://github.com/ninenines/cowboy/issues/810

The other errors are not recoverable (configurable limits or real protocol errors). Closing this then, thanks!
