### ISSUE TITLE
Document differences between low level stream interface and the higher level

### ISSUE THREAD

**Issue by OvermindDL1** [ninenines/cowboy#1170]
As requested in:  https://github.com/ninenines/cowboy/issues/1169#issuecomment-305541333

Currently the differences between the low level (https://ninenines.eu/docs/en/cowboy/2.0/manual/cowboy_stream/) and high level interfaces are not documented.  At the very least the headers that are sent wildly differ, those and anything else should be documented so the user can re-create the necessary functionality that they may need that may be missing when using the low-level streaming interface.

**Comment by essen** [comment]
Done. Thanks!
