### ISSUE TITLE
cowboy 2.0 raw socket access

### ISSUE THREAD

**Issue by Licenser** [ninenines/cowboy#1171]
Before it was possible to get access to the raw TCP socket doing such horrible things as:

```erlang
    Socket = cowboy_req:get(socket, Req),
    Reply = <<"HTTP/1.1 101 UPGRADED\n"
              "Content-Type: application/vnd.docker.raw-stream\n"
              "Connection: Upgrade\n"
              "Upgrade: tcp\n\n">>,
    ssl:send(Socket, Reply),
```

and go on with crazy things like abusing a https connection as a TCP connection. the `get(socket)` option seems to be gone in 2.0 and I struggle to find a replacement. Any hints in the right direction would be appreciated.

**Comment by essen** [comment]
Cowboy will provide common things like retrieving socket info or certificate at a later time. For your example however you should just write a stream handler (cowboy_stream). You can return an upgrade tuple with the headers you want that then gives control to the module you want.

**Comment by Licenser** [comment]
Oh cool! I'll look into the docs on how to do that 👍 thanks for pointing me in the right direction! :D 

(I'll close this as it seems the approach was just wrong ;))
