### ISSUE TITLE
Raw HTTP request line for verifying HTTP signatures?

### ISSUE THREAD

**Issue by rvangraan** [ninenines/cowboy#1174]
Hi,

I need to implement cryptographic signature verification along the lines of this: https://github.com/joyent/node-http-signature/blob/master/http_signing.md

In order to do this, I need to access the raw request line (i.e. what I get in the `#{method, qs, version}` etc request values. I don't want the parsed value, because that means I've got to reassemble the string and that isn't a good way to verify signatures. Any suggestions?

**Comment by essen** [comment]
The request line is not kept. I don't think there is an easy way to get around that other than reading from the socket and then enqueuing the data back (by sending yourself a tcp/ssl message for example).
