### ISSUE TITLE
Plug + Cowboy

### ISSUE THREAD

**Issue by decentname** [ninenines/cowboy#1175]
I have a cowboy 1.0 project running. I want to use plug along with it to add more functionality to my project. I know plug uses cowboy but i have all handlers already setup. How do i direct plug to use my handlers? Also, i cannot find a community for cowboy where i can ask questions. Kindly suggest me the proper place too.

**Comment by essen** [comment]
This is currently the correct place to ask Cowboy questions, however this is not the right place to ask questions about Plug. You probably want some Elixir related forum for that.
