### ISSUE TITLE
SSE stay connected after the request pid dies

### ISSUE THREAD

**Issue by leoliu** [ninenines/cowboy#1176]
Set up an EventSource with `onerror` set to `console.log`. After the SSE is open kill its request pid on the Erlang side. The SSE connection stays on until it's eventually killed by the inactivity timer. The bug/question is should the SSE connection trigger the onerror handler? (Tested with chrome 59.0.3071.86)

[update]

Can reproduce with `cowboy/examples/eventsource/priv/index.html`.

**Comment by leoliu** [comment]
Another scenario that leads to leaking the request pid on the Erlang side.

After SSE is open turn on some VPN, the browser (chrome in my case) logs the error like this:
```
Failed to load resource: net::ERR_NETWORK_CHANGED
```

The request pid on the Erlang side continues living like nothing happens.

**Comment by essen** [comment]
For the second comment, I'm not sure what you mean by "continue living". If the server does not detect the connection being terminated (because it's not just about the request here), then it'll stay up until a timeout triggers.
