### ISSUE TITLE
start_tls Undefined

### ISSUE THREAD

**Issue by aShobhitSingh** [ninenines/cowboy#1177]
Till yesterday I am able to run my application. But after removing the deps folder it fetched the latest repo code and I am facing the below problem. This is from ssl hello world example

```
=INFO REPORT==== 18-Jun-2017::22:43:20 ===
    application: ssl_hello_world
    exited: {bad_return,
                {{ssl_hello_world_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{cowboy,start_tls,
                              [https,
                               [{port,8443},

```

Is there any other change I need to make or something in the API has changed?

**Comment by essen** [comment]
Recently the second argument of start_tls was removed. It looks like you did this change already. You might not be fetching the right Cowboy version.

**Comment by aShobhitSingh** [comment]
Thanks. Removed the acceptor process from my app and it works. Now is there no way to change the number of acceptor process?

**Comment by essen** [comment]
There is of course, it's now a transport option `{num_acceptors, N}`. It was hidden because it was confusing many people.

**Comment by essen** [comment]
Make sure you also update the Ranch dependency for the option to work.

**Comment by aShobhitSingh** [comment]
Thanks Essen. Added {num_acceptors, N} in the transport options. It works.
