### ISSUE TITLE
415 Unsupported Media Type 

### ISSUE THREAD

**Issue by SumitFlochat** [ninenines/cowboy#1179]
Server Code:

init(Req, State) ->
        {cowboy_rest, Req, State}.

is_authorized(Req, State) ->
        case cowboy_req:parse_header(<<"authorization">>, Req) of
                {basic, User = <<"a">>, <<"a">>} ->
                        {true, Req, User};
                _ ->
                        {{false,<<"UnAouthorized realm=\"cowboy\"">>}, Req, State}
        end.

content_types_provided(Req, State) ->
        {[
                {<<"application/json">>, to_json}
        ], Req, State}.

content_types_accepted(Req, State) ->
        io:format( "~n Content_Types_accepted ~n"),
        {[{{<<"application/json">>, <<"x-www-form-urlencoded">>, '*'},create_paste}],
                Req, State}.

create_paste(Req, State) ->
        io:format( "ENcoded Bosy = ~p ~n ",cowboy_req:read_urlencoded_body(Req)),
        case cowboy_req:method(Req) of
               <<"POST">> ->
                        io:format("~n POST IN CREATE PASTE ~n"),
                        {true, Req, State};
                _ ->
                        {true, Req, State}
        end.

allowed_methods(Req, State) ->
    {[<<"GET">>, <<"POST">>], Req, State}.

to_json(Req, State) ->
        Body = mochijson:encode({struct, [{status, <<"Success">>}]}),
        {Body, Req, State}.

===============================================================================
In Browser:

curl -u a:a -X POST -i http://localhost:8080
============================================================================
OUTPUT:

HTTP/1.1 415 Unsupported Media Type
content-length: 0
content-type: application/json
date: Tue, 20 Jun 2017 15:19:13 GMT
server: Cowboy

============================================================================

How to solve that ?
It works fine if i use GET instead of POST.

**Comment by essen** [comment]
Well you gotta pass a content-type header matching what you accept.
