### ISSUE TITLE
Response Body for Unauthorization.

### ISSUE THREAD

**Issue by SumitFlochat** [ninenines/cowboy#1180]
is_authorized(Req, State) ->
        case cowboy_req:parse_header(<<"authorization">>, Req) of
                {basic, User = <<"a">>, <<"a">>} ->
                        {true, Req, User};
                _ ->
                        {{false,<<"UnAouthorized realm=\"cowboy\"">>}, Req, State}
        end.

=======================================================================================

I do find Status but i need to send body too.?
How Can i Send Body for Unauthorization so that client can show message sent by Server..

**Comment by essen** [comment]
cowboy_req:set_resp_body
