### ISSUE TITLE
Question on response status

### ISSUE THREAD

**Issue by randysecrist** [ninenines/cowboy#1181]
I am logging request/response time using middleware and I would also like to log the response status.

However I can't see anyway to access the response status in either the request or the environment.

Am I going about this all wrong?

**Comment by essen** [comment]
If you are using Cowboy 1.0, it's a mess. The only place you can have it is the onresponse hook.

If Cowboy 2.0, use a stream handler. They get literally everything.

**Comment by randysecrist** [comment]
Using 2.0; stream handler makes a ton of sense.  Thanks for the tip!
