### ISSUE TITLE
Does the websocket connection process automatically stop after tcp notices a dead connection after sending?

### ISSUE THREAD

**Issue by lazercorn** [ninenines/cowboy#1184]
Let's say there was a disconnect somewhere along the network without the client initiating it. When a message gets sent by the server to the client, tcp will notice that the connection is dead. Will the websocket connection process then notice this immediately and proceed to stop?

**Comment by essen** [comment]
When sending there is at least one buffer involved, and it/they need to get full before the problem is detected.
