### ISSUE TITLE
Use tag for cowlib dependency

### ISSUE THREAD

**Issue by albertored** [ninenines/cowboy#1188]
It is only a suggestion but I think that, at least for tag and releases, all git dependencies should be locked to a tag and not to a branch.

`Elixir`'s `mix` tool (I think `rebar` acts in the same way) creates a lock file when installing/upgrading dependencies. If some dep is locked to a branch, new commits on that branch are not automatically fetched, one needs to manually remove the dep and reinstalling it. If instead a tag is used this does not happen.

I was in this situation. After upgrading cowboy from tag `2.0.0-pre.5` to `2.0.0-pre.9` I started having some errors saying some functions in `cowlib` package were not found. Checking out the github repo I indeed see that those functions were present. It took a while before I realized that my `cowlib` master bracch was behind the github one :-)

**Comment by essen** [comment]
I have no plans to have strict versioning for code that was so unstable. Proper release is coming soon anyway.
