### ISSUE TITLE
Handlers and other dependencies not loaded automatically.

### ISSUE THREAD

**Issue by Sumitforyou** [ninenines/cowboy#1195]
I have followed the document through
https://ninenines.eu/docs/en/cowboy/2.0/guide/

I was successful in building the project but found that the handlers that i make are not loaded automatically.
How can i ensure that all the handler (all modules in src folder are ) automatically loaded ?

Moreover i added a dependency jsx for Json Parsing but that too was unavailable when i started the console.How can i make sure everything is dynamically loaded when i start the project.

**Comment by essen** [comment]
Can you show what commands you did?

**Comment by SumitFlochat** [comment]
Makefile:

PROJECT = reservation
PROJECT_DESCRIPTION = Reservation
PROJECT_VERSION = 1.0.0
DEPS = cowboy
DEPS += jsx

include erlang.mk
==========================

I ran the command:
 make

Inside deps folder:
cowboy  cowlib  jsx  ranch

Now, Command to run start
./_rel/reservation_release/bin/reservation_release console

(reservation@127.0.0.1)1> code:is_loaded(jsx).
false

I have even checked in the path 
~/Erlang/reservation/_rel/reservation_release/releases/1 for reservation_release.script
But couldn't find jsx application.

**Comment by SumitFlochat** [comment]
Thank you 
Got the mistake.
I forgot to add jsx in application list of reservation.app.src

**Comment by Sumitforyou** [comment]
Thank you
Got the mistake.
I forgot to add jsx in application list of reservation.app.src

**Comment by essen** [comment]
Right if you use the .app.src you need to update it manually.
