### ISSUE TITLE
cowboy capitalises headers when chunked but not when regular response

### ISSUE THREAD

**Issue by motobob** [ninenines/cowboy#1196]
cowboy v2.0-rc1
i have a basic test handler:
```erlang
get([<<"chunked_body">>], Req) ->
    Fun = fun() ->
            {ok, <<"chunked_body">>, fun() -> {ok, <<"second_chunk">>} end}
          end,
    {ok, [{<<"chunked-header">>, <<"header">>}], Fun, Req};

get([<<"headers">>], Req) ->
    {ok, [{<<"x-header">>, <<"header">>}], <<>>, Req};
```

when using regular `httpc` client in first case it returns me:
`[{<<"Chunked-Header">>, <<"header">>}]`
in second case it returns me 
`[{<<"x-header">>, <<"header">>}]`

so somehow when chunking is enabled it changes the headers while they all should case insensitive.

bizarre thing is that happens only in chunked replies.

**Comment by essen** [comment]
You'll have to describe what you mean exactly. Which Cowboy version is concerned is also useful.

**Comment by motobob** [comment]
sorry. clicked too fast. issue description  updated

**Comment by essen** [comment]
Cowboy does not capitalize anything. Are you sure it's not httpc doing this? Try with curl for example.

**Comment by motobob** [comment]
hm...yeah. my bad. turns out one of my desp picked up very old lhttpC which did it to me. with latest proper lhttpC is works as it should be..
