### ISSUE TITLE
How to detect the websocket connect disconnect?

### ISSUE THREAD

**Issue by dcy** [ninenines/cowboy#1198]
Hi!
How can i detect the websocket connect disconnected, lost(js invoke ```ws.close```, refresh browser, close browser and so on)?
I checked the [websocket example](https://github.com/ninenines/cowboy/blob/master/examples/websocket/src/ws_handler.erl) and didn't find a method.

**Comment by essen** [comment]
In 2.0 Cowboy will call the optional `terminate/3` function with the reason set to `remote` or `{remote, CloseCode, Payload}` when the client disconnects.

**Comment by dcy** [comment]
Thanks! ```terminate/3``` works when disconnect.
