### ISSUE TITLE
cowboy 2.0.0-rc.1 crash: cowboy_stream_h:proc_lib_hack/3

### ISSUE THREAD

**Issue by casillic** [ninenines/cowboy#1200]
I'm using MAC OSX, erlang 20, rebar3 and have ssl and inets started too.
I'm using httpc to communicate with cowboy. I'm getting this initial error on start, but it works after that. 

`=CRASH REPORT==== 5-Aug-2017::19:49:19 ===
  crasher:
    initial call: cowboy_stream_h:proc_lib_hack/3
    pid: <0.141.0>
    registered_name: []
    exception exit: {badarg,
                        [{ets,lookup_element,[cowboy_clock,rfc1123,2],[]},
                         {cowboy_clock,rfc1123,0,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_clock.erl"},
                              {line,54}]},
                         {cowboy_req,response_headers,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},
                              {line,718}]},
                         {cowboy_req,do_reply,4,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},
                              {line,656}]},
                         {lms_server_license_total_count_handler,init,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/prodxyz/src/licenses/lms_server_license_total_count_handler.erl"},
                              {line,50}]},
                         {cowboy_handler,execute,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_handler.erl"},
                              {line,37}]},
                         {cowboy_stream_h,execute,3,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},
                              {line,179}]},
                         {cowboy_stream_h,proc_lib_hack,3,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},
                              {line,164}]}]}
      in function  cowboy_stream_h:proc_lib_hack/3 (/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl, line 169)
    ancestors: [<0.140.0>,<0.108.0>,<0.107.0>,ranch_sup,<0.100.0>]
    message_queue_len: 0
    messages: []
    links: [<0.140.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1135
  neighbours:

=ERROR REPORT==== 5-Aug-2017::19:49:19 ===
Ranch listener lms_license_server_listener, connection process <0.140.0>, stream 1 had its request process <0.141.0> exit with reason badarg and stacktrace [{ets,lookup_element,[cowboy_clock,rfc1123,2],[]},{cowboy_clock,rfc1123,0,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_clock.erl"},{line,54}]},{cowboy_req,response_headers,2,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,718}]},{cowboy_req,do_reply,4,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,656}]},{lms_server_license_total_count_handler,init,2,[{file,"/Users/userX/prodxyz/_build/default/lib/prodxyz/src/licenses/lms_server_license_total_count_handler.erl"},{line,50}]},{cowboy_handler,execute,2,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,179}]},{cowboy_stream_h,proc_lib_hack,3,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,164}]}]`

Full log:

`cmac:bin userX$ ./prodxyz console
Exec: /Users/userX/prodxyz/_build/default/rel/prodxyz/erts-9.0/bin/erlexec -boot /Users/userX/prodxyz/_build/default/rel/prodxyz/releases/2.0.0/prodxyz -boot_var ERTS_LIB_DIR /Users/userX/prodxyz/_build/default/rel/prodxyz/erts-9.0/../lib -config /Users/userX/prodxyz/_build/default/rel/prodxyz/releases/2.0.0/sys.config -args_file /Users/userX/prodxyz/_build/default/rel/prodxyz/releases/2.0.0/vm.args -- console
Root: /Users/userX/prodxyz/_build/default/rel/prodxyz
/Users/userX/prodxyz/_build/default/rel/prodxyz
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:30] [kernel-poll:true]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.81.0>},
                       {id,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.80.0>},
                       {id,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.82.0>},
                       {id,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: sasl
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: public_key
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: cowlib
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_admin_sup}
             started: [{pid,<0.91.0>},
                       {id,ssl_pem_cache},
                       {mfargs,{ssl_pem_cache,start_link,[[]]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_admin_sup}
             started: [{pid,<0.92.0>},
                       {id,ssl_manager},
                       {mfargs,{ssl_manager,start_link,[[]]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_sup}
             started: [{pid,<0.90.0>},
                       {id,ssl_admin_sup},
                       {mfargs,{ssl_admin_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_connection_sup}
             started: [{pid,<0.94.0>},
                       {id,tls_connection},
                       {mfargs,{tls_connection_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_connection_sup}
             started: [{pid,<0.95.0>},
                       {id,tls_socket},
                       {mfargs,{ssl_listen_tracker_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_connection_sup}
             started: [{pid,<0.96.0>},
                       {id,dtls_connection},
                       {mfargs,{dtls_connection_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_connection_sup}
             started: [{pid,<0.97.0>},
                       {id,dtls_udp_listener},
                       {mfargs,{dtls_udp_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ssl_sup}
             started: [{pid,<0.93.0>},
                       {id,ssl_connection_sup},
                       {mfargs,{ssl_connection_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,4000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: ssl
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ranch_sup}
             started: [{pid,<0.102.0>},
                       {id,ranch_server},
                       {mfargs,{ranch_server,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: ranch
          started_at: prodxyz@cmac
License_Mode:lms
LMS_Server_Mock:true
Starting LMS mock server
=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.107.0>,ranch_listener_sup}
             started: [{pid,<0.108.0>},
                       {id,ranch_conns_sup},
                       {mfargs,
                           {ranch_conns_sup,start_link,
                               [lms_license_server_listener,supervisor,5000,
                                ranch_tcp,5000,cowboy_clear]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.110.0>},
                       {id,{acceptor,<0.109.0>,1}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.111.0>},
                       {id,{acceptor,<0.109.0>,2}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.112.0>},
                       {id,{acceptor,<0.109.0>,3}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.113.0>},
                       {id,{acceptor,<0.109.0>,4}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.114.0>},
                       {id,{acceptor,<0.109.0>,5}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.115.0>},
                       {id,{acceptor,<0.109.0>,6}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.116.0>},
                       {id,{acceptor,<0.109.0>,7}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.117.0>},
                       {id,{acceptor,<0.109.0>,8}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.118.0>},
                       {id,{acceptor,<0.109.0>,9}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.109.0>,ranch_acceptors_sup}
             started: [{pid,<0.119.0>},
                       {id,{acceptor,<0.109.0>,10}},
                       {mfargs,
                           {ranch_acceptor,start_link,
                               [#Port<0.742>,ranch_tcp,<0.108.0>]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {<0.107.0>,ranch_listener_sup}
             started: [{pid,<0.109.0>},
                       {id,ranch_acceptors_sup},
                       {mfargs,
                           {ranch_acceptors_sup,start_link,
                               [lms_license_server_listener,10,ranch_tcp,
                                [{connection_type,supervisor},{port,9576}]]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,ranch_sup}
             started: [{pid,<0.107.0>},
                       {id,{ranch_listener_sup,lms_license_server_listener}},
                       {mfargs,
                        {ranch_listener_sup,start_link,
                         [lms_license_server_listener,10,ranch_tcp,
                          [{connection_type,supervisor},{port,9576}],
                          cowboy_clear,
                          #{connection_type => supervisor,
                            env =>
                             #{dispatch =>
                                [{'_',[],
                                  [{[<<"api">>,<<"licenseTotalCount">>],
                                    [],lms_server_license_total_count_handler,
                                    []}]}]}}]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup}
             started: [{pid,<0.124.0>},
                       {id,yaws_log},
                       {mfargs,{yaws_log,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup}
             started: [{pid,<0.125.0>},
                       {id,yaws_trace},
                       {mfargs,{yaws_trace,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup}
             started: [{pid,<0.126.0>},
                       {id,yaws_server},
                       {mfargs,
                           {yaws_server,start_link,
                               [{env,false,false,false,false,false,true,
                                    "default"}]}},
                       {restart_type,permanent},
                       {shutdown,120000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup_restarts}
             started: [{pid,<0.128.0>},
                       {id,yaws_session_server},
                       {mfargs,{yaws_session_server,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup_restarts}
             started: [{pid,<0.129.0>},
                       {id,yaws_rss},
                       {mfargs,{yaws_rss,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup_restarts}
             started: [{pid,<0.130.0>},
                       {id,yaws_event_manager},
                       {mfargs,
                           {gen_event,start_link,
                               [{local,yaws_event_manager}]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup_restarts}
             started: [{pid,<0.131.0>},
                       {id,yaws_sendfile},
                       {mfargs,{yaws_sendfile,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,yaws_sup}
             started: [{pid,<0.127.0>},
                       {id,yaws_sup_restarts},
                       {mfargs,{yaws_sup_restarts,start_link,[]}},
                       {restart_type,transient},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: yaws
          started_at: prodxyz@cmac

=INFO REPORT==== 5-Aug-2017::19:49:19 ===
Yaws: Listening to 0.0.0.0:8080 for <1> virtual servers:
 - http://localhost:8080 under /Users/userX/prodxyz/_build/default/rel/prodxyz/lib/prodxyz-2.0.0

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,inet_gethost_native_sup}
             started: [{pid,<0.139.0>},{mfa,{inet_gethost_native,init,[[]]}}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,kernel_safe_sup}
             started: [{pid,<0.138.0>},
                       {id,inet_gethost_native_sup},
                       {mfargs,{inet_gethost_native,start_link,[]}},
                       {restart_type,temporary},
                       {shutdown,1000},
                       {child_type,worker}]

=CRASH REPORT==== 5-Aug-2017::19:49:19 ===
  crasher:
    initial call: cowboy_stream_h:proc_lib_hack/3
    pid: <0.141.0>
    registered_name: []
    exception exit: {badarg,
                        [{ets,lookup_element,[cowboy_clock,rfc1123,2],[]},
                         {cowboy_clock,rfc1123,0,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_clock.erl"},
                              {line,54}]},
                         {cowboy_req,response_headers,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},
                              {line,718}]},
                         {cowboy_req,do_reply,4,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},
                              {line,656}]},
                         {lms_server_license_total_count_handler,init,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/prodxyz/src/licenses/lms_server_license_total_count_handler.erl"},
                              {line,50}]},
                         {cowboy_handler,execute,2,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_handler.erl"},
                              {line,37}]},
                         {cowboy_stream_h,execute,3,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},
                              {line,179}]},
                         {cowboy_stream_h,proc_lib_hack,3,
                             [{file,
                                  "/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},
                              {line,164}]}]}
      in function  cowboy_stream_h:proc_lib_hack/3 (/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl, line 169)
    ancestors: [<0.140.0>,<0.108.0>,<0.107.0>,ranch_sup,<0.100.0>]
    message_queue_len: 0
    messages: []
    links: [<0.140.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1135
  neighbours:

=ERROR REPORT==== 5-Aug-2017::19:49:19 ===
Ranch listener lms_license_server_listener, connection process <0.140.0>, stream 1 had its request process <0.141.0> exit with reason badarg and stacktrace [{ets,lookup_element,[cowboy_clock,rfc1123,2],[]},{cowboy_clock,rfc1123,0,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_clock.erl"},{line,54}]},{cowboy_req,response_headers,2,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,718}]},{cowboy_req,do_reply,4,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,656}]},{lms_server_license_total_count_handler,init,2,[{file,"/Users/userX/prodxyz/_build/default/lib/prodxyz/src/licenses/lms_server_license_total_count_handler.erl"},{line,50}]},{cowboy_handler,execute,2,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,179}]},{cowboy_stream_h,proc_lib_hack,3,[{file,"/Users/userX/prodxyz/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,164}]}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,kernel_safe_sup}
             started: [{pid,<0.142.0>},
                       {id,timer_server},
                       {mfargs,{timer,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,1000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,prodxyz_users_token_server_sup}
             started: [{pid,<0.144.0>},
                       {id,prodxyz_users_token_server},
                       {mfargs,{prodxyz_users_token_server,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,prodxyz_sup}
             started: [{pid,<0.143.0>},
                       {id,prodxyz_users_token_server_sup},
                       {mfargs,{prodxyz_users_token_server_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,60000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,prodxyz_users_server_sup}
             started: [{pid,<0.147.0>},
                       {id,prodxyz_users_server},
                       {mfargs,{prodxyz_users_server,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,brutal_kill},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,prodxyz_sup}
             started: [{pid,<0.146.0>},
                       {id,prodxyz_users_server_sup},
                       {mfargs,{prodxyz_users_server_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,60000},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: prodxyz
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,cowboy_sup}
             started: [{pid,<0.155.0>},
                       {id,cowboy_clock},
                       {mfargs,{cowboy_clock,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,5000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: cowboy
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: xmerl
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_sup}
             started: [{pid,<0.158.0>},
                       {id,mnesia_event},
                       {mfargs,{mnesia_sup,start_event,[]}},
                       {restart_type,permanent},
                       {shutdown,30000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_sup}
             started: [{pid,<0.159.0>},
                       {id,mnesia_ext_sup},
                       {mfargs,{mnesia_ext_sup,start,[]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.161.0>},
                       {id,mnesia_monitor},
                       {mfargs,{mnesia_monitor,start,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.162.0>},
                       {id,mnesia_subscr},
                       {mfargs,{mnesia_subscr,start,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.163.0>},
                       {id,mnesia_locker},
                       {mfargs,{mnesia_locker,start,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.164.0>},
                       {id,mnesia_recover},
                       {mfargs,{mnesia_recover,start,[]}},
                       {restart_type,permanent},
                       {shutdown,180000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.165.0>},
                       {id,mnesia_tm},
                       {mfargs,{mnesia_tm,start,[]}},
                       {restart_type,permanent},
                       {shutdown,30000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.166.0>},
                       {id,mnesia_checkpoint_sup},
                       {mfargs,{mnesia_checkpoint_sup,start,[]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.167.0>},
                       {id,mnesia_controller},
                       {mfargs,{mnesia_controller,start,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_kernel_sup}
             started: [{pid,<0.168.0>},
                       {id,mnesia_late_loader},
                       {mfargs,{mnesia_late_loader,start,[]}},
                       {restart_type,permanent},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,mnesia_sup}
             started: [{pid,<0.160.0>},
                       {id,mnesia_kernel_sup},
                       {mfargs,{mnesia_kernel_sup,start,[]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: mnesia
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: odbc
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,runtime_tools_sup}
             started: [{pid,<0.182.0>},
                       {id,ttb_autostart},
                       {mfargs,{ttb_autostart,start_link,[]}},
                       {restart_type,temporary},
                       {shutdown,3000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: runtime_tools
          started_at: prodxyz@cmac

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.187.0>},
                       {id,disksup},
                       {mfargs,{disksup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.188.0>},
                       {id,memsup},
                       {mfargs,{memsup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
          supervisor: {local,os_mon_sup}
             started: [{pid,<0.190.0>},
                       {id,cpu_sup},
                       {mfargs,{cpu_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 5-Aug-2017::19:49:19 ===
         application: os_mon
          started_at: prodxyz@cmac
Eshell V9.0  (abort with ^G)
(prodxyz@cmac)1> 
`

**Comment by essen** [comment]
Either you didn't start the Cowboy application (it starts a cowboy_clock process that maintains the ets table that is in the log) or something does a request on your service just as you start it and there's a tiny race condition.

**Comment by casillic** [comment]
The Cowboy application is started as shown in log above. 
So based on your comment, it must be a race condition.
I am sending calls to the cowboy server as soon the app starts. 
Is there anything I should be doing to see that cowboy is ready to receive requests?

**Comment by essen** [comment]
Yeah sorry, big log. :-)

I now see Cowboy is started *after* the error, which means race condition. My question is then why Cowboy is started after the listener is up. Did you not add Cowboy as a dependency to your application? If you are using a .app.src file it needs to be listed under `applications`.

**Comment by casillic** [comment]
Yes, that did the trick!
Like you stated above, I only had cowboy listed in rebar3's rebar3.config file, and not in the .app.src file. Once I added it there as well it works great.
Thanks! (BTW nice work, love what you are doing here)

**Comment by essen** [comment]
Thanks, good to know!
