### ISSUE TITLE
cowboy_rest:is_authorized/2 and OPTIONS method

### ISSUE THREAD

**Issue by benjamin-bergia** [ninenines/cowboy#1202]
Not sure about this, but I have been doing some testing with CORS and I was wondering if there is any reason for the OPTIONS requests to go through the `is_authorized/2` callback.
Since apparently browsers strip off any authentication header from the request.

The issue is not from a standard point of view but "less knowledgeable" users such as myself.
The first solution jumping to my mind is to always authorized requests with an `OPTIONS` method in my `is_authorized/2` callback but I have no idea if I am putting myself at risk by doing so.

**Comment by essen** [comment]
There's no reasons for any method NOT to go through is_authorized, authentication mechanisms being at the resource level, not resource+method.

If you use CORS then you have no choice but to allow OPTIONS requests to go through, so what you are doing is correct. Alternatively you could handle OPTIONS requests server-wide through stream handlers, but that only works well if you have a server-wide CORS configuration.
