### ISSUE TITLE
upgrade from 1.1.2 to 2.0

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1203]
I've been looking at your commits and examples to try and figure out what changed so I can update my code to 2.0 level.  What is the best way to find the changes that break code from 1.1.2?  Thanks.

I followed your changes in ssl example and put your basic handler in for my websockets_handler, but it still crashes on start when going from 2.0 pre 3 to pre 4.  I can't tell from the commits what would have changed.

**Comment by essen** [comment]
There's a guide for that: https://ninenines.eu/docs/en/cowboy/2.0/guide/migrating_from_1.0/

In addition, manual pages for Cowboy 2.0 have a changelog for each module and function.

If anything is missing, please do tell! Thanks.

**Comment by comptekki** [comment]
ok thanks!
