### ISSUE TITLE
websocket example crash

### ISSUE THREAD

**Issue by oliv3** [ninenines/cowboy#1204]
Hello,

HEAD is a2facaf2da2c95df32ffdc529bd3bdd9f91c080c

The websocket example crashes by itself, nothing to do

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
(websocket_example@yoda)1> 
=ERROR REPORT==== 21-Aug-2017::02:12:35 ===
Ranch listener http had connection process started with cowboy_clear:start_link/4 at <0.370.0> exit with reason: {badarg,[{erlang,iolist_size,[terminate],[]},{cow_ws,payload_length,1,[{file,"src/cow_ws.erl"},{line,594}]},{cow_ws,frame,2,[{file,"src/cow_ws.erl"},{line,537}]},{cowboy_websocket,websocket_send,2,[{file,"src/cowboy_websocket.erl"},{line,372}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,342}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,179}]},{cowboy_clear,proc_lib_hack,5,[{file,"src/cowboy_clear.erl"},{line,29}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by essen** [comment]
Right, makes sense. Working on a fix.

**Comment by essen** [comment]
Should be fixed in most recent commit. Thanks!
