### ISSUE TITLE
Queued messages sent in the wrong order?

### ISSUE THREAD

**Issue by willemdj** [ninenines/cowboy#1205]
https://github.com/ninenines/cowboy/blob/a2facaf2da2c95df32ffdc529bd3bdd9f91c080c/src/cowboy_http2.erl#L631

If the increment that is received through the window update is smaller than the amount of data in the queue, messages may be queued again. I think they end up at the wrong end of the queue.

As a result they are sent out in the wrong order.

**Comment by essen** [comment]
Ouch. I'll look into it, thanks.

**Comment by essen** [comment]
Please try the most recent commit and let me know.

**Comment by willemdj** [comment]
It works for me, thanks.
