### ISSUE TITLE
websocket issue

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1209]
I'm trying to change my erlang code from cowboy 1.1.2 to 2.0.0-rc.1, but I'm getting some errors.  Here are the ones I'm seeing:

=ERROR REPORT==== 29-Aug-2017::08:07:27 ===
Ranch listener https had connection process started with cowboy_tls:start_link/4 at <0.405.0> exit with reason: {function_clause,[{websocket_handler,terminate,[timeout,#{host => <<"0,0,0,0">>,method => <<"GET">>,path => <<"/websocket">>,peer => {{0,0,0,0},63721},port => 8443,qs => <<>>,scheme => <<"https">>,version => 'HTTP/1.1'},[]],[{file,"src/websocket_handler.erl"},{line,506}]},{cowboy_websocket,terminate,3,[{file,"src/cowboy_websocket.erl"},{line,421}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}

For this one, I increased the timeout in:

init(Req, State) ->
    Opts = #{ compress => true, idle_timeout => 36000000 },
    {cowboy_websocket, Req, State, Opts}.

---------------

I occasionally get this but it keeps going:

date: "2017-08-29 11:34:37" -> msg: {'EXIT',<0.478.0>,normal} 

---------------

I'm now getting this:

=ERROR REPORT==== 29-Aug-2017::11:34:37 ===
Ranch listener https had connection process started with cowboy_tls:start_link/4 at <0.470.0> exit with reason: {buf_error,[{zlib,call,3,[]},{zlib,deflate,3,[]},{cow_ws,deflate_frame,3,[{file,"src/cow_ws.erl"},{line,601}]},{cow_ws,frame,2,[{file,"src/cow_ws.erl"},{line,528}]},{cowboy_websocket,websocket_send,2,[{file,"src/cowboy_websocket.erl"},{line,372}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,351}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}

---------- 

Any ideas on what is happening?

Thanks.

**Comment by essen** [comment]
First one sounds like a clause you don't handle in the terminate function.

Second one no idea, would be good to get more info.

Third, I'll have to look up what this "buf_error" is.

**Comment by essen** [comment]
For the third case if you disable compression it won't happen (of course).

**Comment by comptekki** [comment]
OK.  Thanks.

**Comment by essen** [comment]
How much data are you trying to send at once?

**Comment by comptekki** [comment]
Under 1 k.  Small messages about which machines are up.  I removed the compress option and all is well.  Thanks for the help.

**Comment by comptekki** [comment]
I also changed:

terminate(Reason, undefined,  _State) ->
    io:format("~nTerminate Reason: ~p~n", [Reason]),
    ok.


to 

terminate(Reason, _Opts, _State) ->
    io:format("~nTerminate Reason: ~p~n", [Reason]),
    ok.

And it fixed the terminate issue.

I think the first terminate was from your docs/examples somewhere.

**Comment by essen** [comment]
OK I have fixed the docs locally and it'll be pushed in the next doc update this coming week. Thanks!
