### ISSUE TITLE
Missing example for a close frame

### ISSUE THREAD

**Issue by benbro** [ninenines/cowboy#1210]
There is an example with a stop tuple {stop, State} but a close tuple example is missing.
https://ninenines.eu/docs/en/cowboy/2.0/guide/ws_handlers/#_closing_the_connection

**Comment by essen** [comment]
Do we really need one? There's an example for sending frames so it shouldn't be too difficult to figure out.

**Comment by benbro** [comment]
Isn't the close tuple different?
```erlang
{reply, {close, Code, Reason}, Req, State}
```

**Comment by essen** [comment]
Or just 'close'. The real issue is that the manual does not list the frame types.

**Comment by essen** [comment]
Frames documented in Cowboy for now.
