### ISSUE TITLE
Dependency crypto is specified as a dependency but is not reachable by the system.

### ISSUE THREAD

**Issue by Captain-Smollett** [ninenines/cowboy#1211]
I have installed Erlang vesion 19.3 on CentOS 7 linux server. Yesterday, I downloaded Cowboy HTTP server. In the examples/hello_world directory I have run make command and got the following error

"Dependency crypto is specified as a dependency but is not reachable by the system."

 I didn't have such an issue at the older version of Cowboy

**Comment by essen** [comment]
I doubt it's Cowboy's fault. Most likely the crypto on your system is missing/wrong/other.

Try this:

```
$ erl
1> l(crypto).
```

**Comment by Captain-Smollett** [comment]
You are right "l(crypto)" gives me "{error,nofile}" , something is wrong with my Erlang installation.
