### ISSUE TITLE
example script to generate ssl certs

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1213]
Do you have a bash script example that can generate these certs:

https://github.com/ninenines/cowboy/tree/master/examples/ssl_hello_world/priv/ssl

Thanks

**Comment by comptekki** [comment]
In 1.x I could use ssl without ca cert, but with 2.x it seems it is required.  I couldn't run without.

**Comment by essen** [comment]
Nothing changed in Cowboy for this.

I don't have a bash script, I just use what I find on the Internet. I think the OpenSSL faq has the commands.

**Comment by comptekki** [comment]
Ok.  I'll need to check closer.  My ssl setup with 1.x was


{ok, _} =
  cowboy:start_https(
    https,
   100,
    [{port, 8443},
      {certfile, PrivDir ++ "/ssl/cert.pem"},
      {keyfile, PrivDir ++ "/ssl/key.pem"},
      {password, ""}],
    [{env, [{dispatch, Dispatch}]}]
  )


but with 2.0 it only runs with:

   {ok, _} =
        cowboy:start_tls(
          https,
          [{port, 8443},
           {cacertfile, PrivDir ++ "/ssl/cowboy-ca.crt"},
           {certfile, PrivDir ++ "/ssl/server.crt"},
           {keyfile, PrivDir ++ "/ssl/server.key"},
%          {certfile, PrivDir ++ "/ssl/cer.pem"},

%          {keyfile, PrivDir ++ "/ssl/key.pem"},

           {password, ""}],
          #{env => #{dispatch => Dispatch}
       }),

**Comment by Gazler** [comment]
In Phoenix we recommend the following command:

    openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem

https://github.com/phoenixframework/phoenix/blob/5d7571a21a9db2c7583a7e8032f381dca12d2690/installer/templates/phx_single/config/dev.exs#L23

I can confirm that it works on Cowboy 2 with only `certfile` and `keyfile` configured.

**Comment by comptekki** [comment]
OK.  Thanks. I'll try it.  For some reason my old ones don't work.

**Comment by comptekki** [comment]
That worked.  Thanks!
