### ISSUE TITLE
ranch see also link from cowboy docs is broken

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#1215]
in https://ninenines.eu/docs/en/cowboy/2.0/manual/cowboy.start_clear/

the link to ranch at the botom in the "See Also" section is broken (points to https://ninenines.eu/docs/en/cowboy/2.0/manual/ranch)

I guess it should point to https://ninenines.eu/docs/en/ranch/1.3/manual/

**Comment by essen** [comment]
There's probably a better way to do this but it should be fixed now. Thanks!
