### ISSUE TITLE
Error : exception exit

### ISSUE THREAD

**Issue by fiodinggo** [ninenines/cowboy#1216]
I have problems when requesting from client to server using POST method. request that I do using jquery ajax. following my script:
-module(restful_app).
-behaviour(application).

-export([start/2]).
-export([stop/1]).

start(_Type, _Args) ->
  Dispatch = cowboy_router:compile([
    {'_', [
      {"/", restful_handler, []},
      {"/home", home_handler, []}
    ]}
  ]),
  {ok, _} = cowboy:start_clear(my_http_listener,
    [{port, 8080}],
    #{env => #{dispatch => Dispatch}}
  ),
  restful_sup:start_link().

stop(_State) ->
	ok.
//------------------------------------------------------------------
-module(home_handler).
-behavior(cowboy_handler).

-export([init/2]).
-export([allowed_methods/2]).
-export([content_types_provided/2]).
-export([content_types_accepted/2]).
-export([datatojson/2]).
-export([create_paste/2]).
-export([posttojson/2]).

init(Req, Opts) ->
  {cowboy_rest, Req, Opts}.
allowed_methods(Req, State) ->
  Methods = [<<"POST">>,<<"GET">>,<<"OPTIONS">>],
  {Methods, Req, State}.
content_types_provided(Req, State) ->
    {[
  		{{<<"application">>, <<"json">>, []}, datatojson}
    ], Req, State}.
content_types_accepted(Req, State) ->
  Methods = cowboy_req:method(Req),
  case Methods of
    <<"POST">> ->
      {[
        {<<"application/json">>, posttojson},
        {<<"application/x-www-form-urlencoded; charset=UTF-8">>, posttojson}
      ], Req, State};
    <<"PUT">> ->
      {[
        {<<"application/json">>, create_paste},
        {<<"application/x-www-form-urlencoded">>, create_paste}
      ], Req, State};
    <<"OPTIONS">> ->
      {[
        {<<"application/json">>, create_paste},
        {<<"application/x-www-form-urlencoded">>, create_paste}
      ], Req, State}
  end.
datatojson(Req, State) ->
  Req1 = cowboy_req:set_resp_header(<<"server">>, <<"Apache">>, Req),
  Req2 = cowboy_req:set_resp_header(<<"access-control-allow-origin">>, <<"*">>, Req1),
  Req3 = cowboy_req:set_resp_header(<<"access-control-allow-methods">>, <<"GET, POST">>, Req2),
  Req4 = cowboy_req:set_resp_header(<<"Content-Type">>, <<"application/json">>, Req3),
  Methods = cowboy_req:method(Req4),
  Body = <<"{\"success\":true,\"title\":\"Home\",\"data\":\"ini adalah homex. ", Methods/binary, "\"}">>,
  {Body, Req4, State}.
create_paste(Req, State) ->
  Req1 = cowboy_req:set_resp_header(<<"server">>, <<"Apache">>, Req),
  Req2 = cowboy_req:set_resp_header(<<"access-control-allow-origin">>, <<"*">>, Req1),
  Req3 = cowboy_req:set_resp_header(<<"access-control-allow-methods">>, <<"GET, POST">>, Req2),
  Methods = cowboy_req:method(Req3),
  Body = <<"{\"success\":true,\"title\":\"Home\",\"data\":\"ini adalah homex. ", Methods/binary, "\"}">>,
  {Body, Req3, State}.
posttojson(Req0, Opt0) ->
  Body = <<"{\"success\":true,\"title\":\"Home\",\"data\":\"ini adalah home post.\"}">>,
  Req = cowboy_req:reply(200, #{
      <<"server">> => <<"Apache">>,
			<<"access-control-allow-origin">> => <<"*">>,
      <<"access-control-allow-methods">> => <<"GET, POST">>
	}, Body, Req0),
  {ok, Req, Opt0}.
//----------------------------------------------------------------------
and, i found this BUG:
=CRASH REPORT==== 13-Sep-2017::20:18:57 ===
  crasher:
    initial call: cowboy_stream_h:proc_lib_hack/3
    pid: <0.396.0>
    registered_name: []
    exception exit: {{case_clause,
                         {ok,#{bindings => #{},body_length => 6,
                               charset => undefined,has_body => true,
                               has_sent_resp => true,
                               headers =>
                                   #{<<"accept">> =>
                                         <<"application/json, text/javascript, */*; q=0.01">>,
                                     <<"accept-encoding">> =>
                                         <<"gzip, deflate">>,
                                     <<"accept-language">> =>
                                         <<"en-US,en;q=0.5">>,
                                     <<"connection">> => <<"keep-alive">>,
                                     <<"content-length">> => <<"6">>,
                                     <<"content-type">> =>
                                         <<"application/x-www-form-urlencoded; charset=UTF-8">>,
                                     <<"host">> => <<"localhost:8080">>,
                                     <<"origin">> => <<"http://localhost">>,
                                     <<"referer">> =>
                                         <<"http://localhost/web_riset/trial2/">>,
                                     <<"user-agent">> =>
                                         <<"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0">>},
                               host => <<"localhost">>,host_info => undefined,
                               media_type => {<<"application">>,<<"json">>,[]},
                               method => <<"POST">>,path => <<"/home">>,
                               path_info => undefined,
                               peer => {{127,0,0,1},33760},
                               pid => <0.395.0>,port => 8080,qs => <<>>,
                               ref => my_http_listener,scheme => <<"http">>,
                               streamid => 1,version => 'HTTP/1.1'},
                             []}},
                     [{cowboy_rest,process_content_type,3,
                          [{file,"src/cowboy_rest.erl"},{line,938}]},
                      {cowboy_rest,upgrade,4,
                          [{file,"src/cowboy_rest.erl"},{line,238}]},
                      {cowboy_stream_h,execute,3,
                          [{file,"src/cowboy_stream_h.erl"},{line,179}]},
                      {cowboy_stream_h,proc_lib_hack,3,
                          [{file,"src/cowboy_stream_h.erl"},{line,164}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  cowboy_stream_h:proc_lib_hack/3 (src/cowboy_stream_h.erl, line 169)
    ancestors: [<0.395.0>,<0.370.0>,<0.369.0>,ranch_sup,<0.358.0>]
    message_queue_len: 0
    messages: []
    links: [<0.395.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 818
  neighbours:

anyone can help me about this problem?

thanks before,...

**Comment by essen** [comment]
Your function post_to_json should return true or false, not ok.

**Comment by fiodinggo** [comment]
thanks for, but the conditions are the same
//---------------------
=CRASH REPORT==== 13-Sep-2017::22:17:11 ===
  crasher:
    initial call: cowboy_stream_h:proc_lib_hack/3
    pid: <0.397.0>
    registered_name: []
    exception exit: {function_clause,
                        [{cowboy_req,reply,4,
                             [{file,"src/cowboy_req.erl"},{line,633}]},
                         {cowboy_rest,respond,3,
                             [{file,"src/cowboy_rest.erl"},{line,1149}]},
                         {cowboy_rest,process_content_type,3,
                             [{file,"src/cowboy_rest.erl"},{line,949}]},
                         {cowboy_rest,upgrade,4,
                             [{file,"src/cowboy_rest.erl"},{line,238}]},
                         {cowboy_stream_h,execute,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,179}]},
                         {cowboy_stream_h,proc_lib_hack,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,164}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  cowboy_stream_h:proc_lib_hack/3 (src/cowboy_stream_h.erl, line 169)
    ancestors: [<0.395.0>,<0.370.0>,<0.369.0>,ranch_sup,<0.358.0>]
    message_queue_len: 0
    messages: []
    links: [<0.395.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 818
  neighbours:

**Comment by essen** [comment]
It's not a bug either, you are likely passing something wrong to the cowboy_req:reply function.

**Comment by Trioblack** [comment]
@fiodinggo 

The postojson callback may return one of three different return values.

> If an error occurred while processing the request body, it must return false and Cowboy will send an appropriate error response.
> 
> If the method is POST, then you may return true with an URI of where the resource has been created. This is especially useful for writing handlers for collections.
> 
> Otherwise, return true to indicate success. Cowboy will select the appropriate response to be sent depending on whether a resource has been created, rather than modified, and on the availability of a location header or a body in the response.

Not ok, as essen said.

More [https://ninenines.eu/docs/en/cowboy/2.0/guide/rest_flowcharts/](url)

**Comment by Trioblack** [comment]
@fiodinggo

This is an invalid structure in Erlang.

> <<"{"success":true,"title":"Home","data":"ini adalah homex. ", Methods/binary, ""}">>

To create formant json manually should do so:

<<"{\"title\": \"Home\"}">>

You can use the jsone, jsx or jiffy library for encoding, decoding JSON data.

**Comment by Trioblack** [comment]
I looked at the error message (function_clause exception) and checked the Cowboy documentation, for `cowboy_req:reply/2,3,4` function:

> The response is sent as soon as one of the reply or stream reply function is called.

> While only one response is allowed for every request [...]

> No further data can be transmitted after this function returns. This includes the push mechanism. Attempting to send two replies, or to push resources after a reply has been sent, will result in an error.

I also looked for the origin of the exception:

`exception exit: {function_clause,
                        [{cowboy_req,reply,4,
                             [{file,"src/cowboy_req.erl"},{line,633}]},
                         {cowboy_rest,respond,3,
                             [{file,"src/cowboy_rest.erl"},{line,1149}]},
                         {cowboy_rest,process_content_type,3,
                             [{file,"src/cowboy_rest.erl"},{line,943}]},
                         {cowboy_rest,upgrade,4,
                             [{file,"src/cowboy_rest.erl"},{line,238}]},
                         {cowboy_stream_h,execute,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,179}]},
                         {cowboy_stream_h,proc_lib_hack,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,164}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}`

This is my Req object, before the`cowboy_req:reply` function call:

`#{bindings => #{},body_length => 22,charset => undefined,has_body => true,
  headers =>
      #{<<"accept">> => <<"*/*">>,
        <<"accept-encoding">> => <<"gzip, deflate, br">>,
        <<"accept-language">> =>
            <<"en-US,en;q=0.8,pt;q=0.6,gl;q=0.4,la;q=0.2">>,
        <<"cache-control">> => <<"no-cache">>,
        <<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"22">>,
        <<"content-type">> => <<"application/json">>,<<"dnt">> => <<"1">>,
        <<"host">> => <<"localhost:8080">>,
        <<"origin">> =>
            <<"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop">>,
        <<"postman-token">> => <<"f5113f54-abb9-ac55-6e1a-6efd24e38419">>,
        <<"user-agent">> =>
            <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36">>},
  host => <<"localhost">>,host_info => undefined,
  media_type => {<<"application">>,<<"json">>,[]},
  method => <<"POST">>,path => <<"/home">>,path_info => undefined,
  peer => {{127,0,0,1},51804},
  pid => <0.12387.0>,port => 8080,qs => <<>>,ref => http_listener,
  resp_headers =>
      #{<<"content-type">> => [<<"application">>,<<"/">>,<<"json">>,<<>>]},
  scheme => <<"http">>,streamid => 1,version => 'HTTP/1.1'}`

This is my Req object, after the `cowboy_req:reply` function call:

`#{bindings => #{},body_length => 22,charset => undefined,has_body => true,
      has_sent_resp => true,
      headers =>
          #{<<"accept">> => <<"*/*">>,
            <<"accept-encoding">> => <<"gzip, deflate, br">>,
            <<"accept-language">> =>
                <<"en-US,en;q=0.8,pt;q=0.6,gl;q=0.4,la;q=0.2">>,
            <<"cache-control">> => <<"no-cache">>,
            <<"connection">> => <<"keep-alive">>,
            <<"content-length">> => <<"22">>,
            <<"content-type">> => <<"application/json">>,<<"dnt">> => <<"1">>,
            <<"host">> => <<"localhost:8080">>,
            <<"origin">> =>
                <<"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop">>,
            <<"postman-token">> => <<"f5113f54-abb9-ac55-6e1a-6efd24e38419">>,
            <<"user-agent">> =>
                <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36">>},
      host => <<"localhost">>,host_info => undefined,
      media_type => {<<"application">>,<<"json">>,[]},
      method => <<"POST">>,path => <<"/home">>,path_info => undefined,
      peer => {{127,0,0,1},51804},
      pid => <0.12387.0>,port => 8080,qs => <<>>,ref => http_listener,
      scheme => <<"http">>,streamid => 1,version => 'HTTP/1.1'}`

The relevant difference is in the `has_sent_resp => true` parameter .

And when the function call returns {true, Req, Opts}, somewhere someone tries to send another response.

And cowboy_req [https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L632](url) throws the exception because the `has_sent_resp => true` parameter is already there with a value of `true`. Which means the response has already been sent.

@essen, correct me if I'm wrong, please.

**Comment by fiodinggo** [comment]
i'm sorry about my language, but i think what about this?
//-------------------------
root@nidas-K43SD:/erlang/restful# make run
make[1]: Entering directory '/erlang/restful/deps/mysql_poolboy'
make[2]: Entering directory '/erlang/restful/deps/mysql'
make[2]: Leaving directory '/erlang/restful/deps/mysql'
make[2]: Entering directory '/erlang/restful/deps/poolboy'
make[2]: Leaving directory '/erlang/restful/deps/poolboy'
make[1]: Leaving directory '/erlang/restful/deps/mysql_poolboy'
make[1]: Entering directory '/erlang/restful/deps/cowboy'
make[2]: Entering directory '/erlang/restful/deps/cowlib'
make[2]: Leaving directory '/erlang/restful/deps/cowlib'
make[2]: Entering directory '/erlang/restful/deps/ranch'
make[2]: Leaving directory '/erlang/restful/deps/ranch'
 GEN    rebar.config
make[1]: Leaving directory '/erlang/restful/deps/cowboy'
 DEPEND restful.d
 ERLC   home_handler.erl
 APP    restful.app.src
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /erlang/restful/ebin
          /erlang/restful/deps
          /usr/lib/erlang/lib
          /erlang/restful/apps
          /erlang/restful/_rel
===> Resolved restful_release-1
===> rendering builtin_hook_status hook to "/erlang/restful/_rel/restful_release/bin/hooks/builtin/status"
===> Including Erts from /usr/lib/erlang
===> release successfully created!
===> tarball /erlang/restful/_rel/restful_release/restful_release-1.tar.gz successfully created!
Exec: /erlang/restful/_rel/restful_release/erts-9.0/bin/erlexec -boot /erlang/restful/_rel/restful_release/releases/1/restful_release -mode embedded -boot_var ERTS_LIB_DIR /erlang/restful/_rel/restful_release/lib -config /erlang/restful/_rel/restful_release/releases/1/sys.config -args_file /erlang/restful/_rel/restful_release/releases/1/vm.args -pa -- console
Root: /erlang/restful/_rel/restful_release
/erlang/restful/_rel/restful_release
heart_beat_kill_pid = 18149
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]


=PROGRESS REPORT==== 14-Sep-2017::00:46:36 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.388.0>},
                       {id,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 14-Sep-2017::00:46:36 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.387.0>},
                       {id,sasl_safe_sup},
                       {mfargs,
                           {supervisor,start_link,
                               [{local,sasl_safe_sup},sasl,safe]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]

=PROGRESS REPORT==== 14-Sep-2017::00:46:36 ===
          supervisor: {local,sasl_sup}
             started: [{pid,<0.389.0>},
                       {id,release_handler},
                       {mfargs,{release_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

=PROGRESS REPORT==== 14-Sep-2017::00:46:36 ===
         application: sasl
          started_at: 'restful@127.0.0.1'
Eshell V9.0  (abort with ^G)
(restful@127.0.0.1)1> 
=CRASH REPORT==== 14-Sep-2017::00:46:42 ===
  crasher:
    initial call: cowboy_stream_h:proc_lib_hack/3
    pid: <0.397.0>
    registered_name: []
    exception exit: {function_clause,
                        [{cowboy_req,reply,4,
                             [{file,"src/cowboy_req.erl"},{line,633}]},
                         {cowboy_rest,respond,3,
                             [{file,"src/cowboy_rest.erl"},{line,1149}]},
                         {cowboy_rest,process_content_type,3,
                             [{file,"src/cowboy_rest.erl"},{line,943}]},
                         {cowboy_rest,upgrade,4,
                             [{file,"src/cowboy_rest.erl"},{line,238}]},
                         {cowboy_stream_h,execute,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,179}]},
                         {cowboy_stream_h,proc_lib_hack,3,
                             [{file,"src/cowboy_stream_h.erl"},{line,164}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  cowboy_stream_h:proc_lib_hack/3 (src/cowboy_stream_h.erl, line 169)
    ancestors: [<0.395.0>,<0.370.0>,<0.369.0>,ranch_sup,<0.358.0>]
    message_queue_len: 0
    messages: []
    links: [<0.395.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 823
  neighbours:

bcs, I am a new player in this situation ...   @@(:lol)

**Comment by fiodinggo** [comment]
in addition to, I use erlang 20: Erlang / OTP 20 [erts-9.0] [source] [64-bit] [sms: 4: 4] [ds: 4: 4: 10] [async-threads: 10] [kernel-poll: false]

**Comment by essen** [comment]
If you send a response manually from a cowboy_rest handler, you are supposed to stop the processing by returning a `stop` tuple. Otherwise Cowboy tries to send a response itself and it crashes because one has already been sent.

**Comment by Trioblack** [comment]
@essen where do I find this explanation in the documentation?

**Comment by essen** [comment]
It's not explicitly stated like this I suppose, though both stop and the crash are explained independently.

**Comment by Trioblack** [comment]
@fiodinggo as the @essen said, do this `{stop, Req, Opts}` as a return of the posttojson function.

**Comment by Trioblack** [comment]
@essen It would be great if it were also described in the documentation, to avoid mistakes.

**Comment by essen** [comment]
PR welcome!

**Comment by fiodinggo** [comment]
:lol, very good... i've got it
thanks for u all...
happy coding

**Comment by fiodinggo** [comment]
hello, can i continue about that,
whether in the way as I said before, whether it will affect the performance of the system?
thanks before

**Comment by essen** [comment]
What would affect the performance?

**Comment by fiodinggo** [comment]
like this script:
create_paste(Req, State) ->
Req1 = cowboy_req:set_resp_header(<<"server">>, <<"Apache">>, Req),
Req2 = cowboy_req:set_resp_header(<<"access-control-allow-origin">>, <<"">>, Req1),
Req3 = cowboy_req:set_resp_header(<<"access-control-allow-methods">>, <<"GET, POST">>, Req2),
Methods = cowboy_req:method(Req3),
Body = <<"{"success":true,"title":"Home","data":"ini adalah homex. ", Methods/binary, ""}">>,
{Body, Req3, State}.
posttojson(Req0, Opt0) ->
Body = <<"{"success":true,"title":"Home","data":"ini adalah home post."}">>,
Req = cowboy_req:reply(200, #{
<<"server">> => <<"Apache">>,
<<"access-control-allow-origin">> => <<"*">>,
<<"access-control-allow-methods">> => <<"GET, POST">>
}, Body, Req0),
{ok, Req, Opt0}.

**Comment by essen** [comment]
I'm not seeing anything that would reduce the performance, you're just sending replies here.

**Comment by fiodinggo** [comment]
thanks for this info,

good job
