### ISSUE TITLE
REST: resource_exists/2 together with content_types_provided/2

### ISSUE THREAD

**Issue by wk8** [ninenines/cowboy#1218]
Let's consider the following cowboy handler module:

```
-module(my_rest_handler).

-export([
         init/2,
         to_json/2,
         resource_exists/2,
         content_types_provided/2
        ]).

init(Req, State) ->
    {cowboy_rest, Req, State}.

resource_exists(Req, State) ->
    {false, Req, State}.

content_types_provided(Req, State) ->
    {[{{<<"application">>, <<"json">>, '*'}, to_json}], Req, State}.

to_json(Req, State) ->
    {<<"{}">>, Req, State}.
```

This module always replies with
```
< HTTP/1.1 404 Not Found
< content-length: 0
< content-type: application/json
< date: Wed, 20 Sep 2017 00:33:06 GMT
< server: Cowboy
```
and an empty body, which is incorrect (notice the `content-type: application/json` header; that reply is incorrect, since an empty body is not a valid JSON).

It seems to me cowboy shouldn't set the content type header from `content_types_provided/2` if it never calls the provided callback (eg as in the example above because `resource_exists/2` returns false, but possibly in other cases).

@essen : do you agree this behaviour is not the intended? If yes, happy to propose a PR to fix it, please let me know :)

**Comment by essen** [comment]
It's a fairly old issue: https://github.com/ninenines/cowboy/issues/413

**Comment by wk8** [comment]
Thanks for the quick answer @essen , will follow that other thread
