### ISSUE TITLE
Keepalive connection in bad state

### ISSUE THREAD

**Issue by karlseguin** [ninenines/cowboy#1219]
I've been trying to figure out why we're getting "upstream prematurely closed connection while reading response header from upstream" in Nginx with a Phoenix upstream. The error is emitted by nginx under a very simple condition of [essentially] having `recv(socket) == 0` when a header was expected; this, and via past experience, makes me convinced that the error isn't in nginx. 

I'm able to force this error locally, with cowboy, but I admit that it requires having weird config and invalid cowboy code. Still, I wonder if it could be handled better:

Essentially, if cowboy is started with max_keepalive > 2, and very large bodies are supplied with a short read_timeout and throwing away the `req` value returned from `body(req, [...])`, we can reproduce it:

```
defmodule Timeouts do
  def run do
    dispatch = :cowboy_router.compile([
      {:_, [{:_, Timeouts.Handler, []}]}
    ])
    {:ok, _} = :cowboy.start_http(:timeouts, 100, [{:port, 8102}], [{:max_keepalive, 2}, {:env, [{:dispatch, dispatch}]}])

    HTTPoison.start()
    IO.inspect HTTPoison.post("http://127.0.0.1:8102/", [String.duplicate("a", 10_000_000)], [], hackney: [pool: :default])
    IO.inspect HTTPoison.post("http://127.0.0.1:8102/", [String.duplicate("a", 10_000_000)], [], hackney: [pool: :default])
  end
end

defmodule Timeouts.Handler do
  def init(_type, req, _opts), do: {:ok, req, %{}}

  def handle(req, state) do
    :cowboy_req.body(req, [{:read_length, 10_000_000}, {:length, 10_000_000}, {:read_timeout, 10}])
    {:ok, res} = :cowboy_req.reply(200, [], [], req)
    {:ok, res, state}
  end

  def terminate(_, _, _), do: :ok
end
```

(If we point HTTPoison  to 8101, which is a bare-bone nginx with keepalive to an upstream to 8102, we get that error).

I'm not actually sure this is the source of our problem. And I'm not sure how we're getting into this state. It's possible this is an issue with Plug.Parser prior to 1.2.1 which didn't properly handle error cases around this. I'll ask the team to upgrade plug and see if that fixes it.

Still, despite the fact that this requires questionable configuration and incorrect usage, and might be fixed in a newer version of plug, I still wonder if this isn't something Cowboy could improve. Given that this is tied to keepalive, I can't help but wonder if a connection is being placed back into the pool in an invalid state.

I believe net/http handles this by a) trying to empty the body  and b) past a certain size, closing the connection (the comment implies that reading the body is actually required by the RFC):

https://github.com/golang/go/blob/7e10a2f6f3bc509b27d02b3c5462e81798434fba/src/net/http/server.go#L1248

**Comment by karlseguin** [comment]
Happens against 1.0.4 and 1.1.2

**Comment by essen** [comment]
It's not surprising that bugs occur if you throw away the Req returned by cowboy_req:body. This was a major design flaw of Cowboy 1.0 that does not exist anymore in 2.0.
