### ISSUE TITLE
Is it possible to reply with a message and close the connection at same time?

### ISSUE THREAD

**Issue by lazercorn** [ninenines/cowboy#1220]
Possible to combine both statements below into one?
{reply, someText, State}
{stop, State}

Because if this isn't possible, I'll just close the connection on the client side upon receiving someText. so no big deal. Just wondering if it is possible.

**Comment by essen** [comment]
Yes you can do something like `{reply, [{text, "bye"}, close], State}`, the list is a list of frames and close frames are included (see cow_ws:frame() it's missing from the docs https://github.com/ninenines/cowboy/issues/1210 and will be added back before 2.0).
