### ISSUE TITLE
Got 406 response on example file_server

### ISSUE THREAD

**Issue by beenotung** [ninenines/cowboy#1222]
I run the file_server_example as is, but get 406 on whatever link.
Tried /test.txt and /video.html

Edit:
this error only appears in Chrome extension ARC (Advanced REST client)
(using header)
```
accept: html/html
accept-encoding: gzip, deflate
accept-language: en-US,en;q=0.8
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.50 Safari/537.36
```

It works well in google chrome

**Comment by essen** [comment]
Well you only accept `html/html` which not only does not exist, is not served by the example and even if you meant `text/html` that's not going to help you receive `text/plain`. Browsers always end the accept header with something like `*/*;q=0.1` to make sure they receive something if the server sends a media type they do not prefer.
