### ISSUE TITLE
using sql_bridge dep

### ISSUE THREAD

**Issue by fiodinggo** [ninenines/cowboy#1227]
how can i use this sql_bridge module in my cowboy project?
https://github.com/choptastic/sql_bridge

**Comment by essen** [comment]
What did you try? Should just be a matter of adding it as a dependency.

**Comment by fiodinggo** [comment]
thanx,
I've tried it.
after that I try to call from the handler as below:
Datax = db: plq ("select id, name from mhs", []),
Res = jiffy: encode (Datax),

but I still get errror.

**Comment by fiodinggo** [comment]
this is my sample.config file inside rel directory:

[
    {sql_bridge, [
        {module_alias, db},

        %% There are three adapters that can be used:
        %%  + sql_bridge_epgsql: PostgreSQL adapter using epgsql
        %%  + sql_bridge_mysql_otp: MySQL adapter using mysql-otp
        %%  + sql_bridge_emysql: MySQL adapter using the (mostly abandoned) Emysql driver.
        {adapter, sql_bridge_epgsql},

        %% connection parameters (self explanitory, I hope)
        {host, "127.0.0.1"},
        {port, 5432},
        {user, "postgres"},
        {pass, "postgres"},

        %% There are two different ways to determine database
        %%
        %% 1) All requests go to a single database, called 'database_name':
        {lookup, erlang}
        %%
		%% 2) Before a request is made, run the function
        %% `lookup_module:lookup_function()`, for which the return value will
        %% be the database name
        {lookup, {lookup_module, lookup_function}},

		%% Number of connections to establish per pool (which really means
		%% number of connections per database).
		{connections_per_pool, 10},

        %% If a connection pool is saturated, this allows additional "overflow"
        %% connections to be established up to the limit specified below.
        {overflow_connections_per_pool, 10},

        %% If you prefer your string types (varchars, texts, etc) to be returned as erlang lists rather than binaries, set the following to true:
        {stringify_binaries, false}
    ]}
].

and in my rest.app.src file, i add sql_bridge in application

**Comment by essen** [comment]
But what error do you get?

**Comment by fiodinggo** [comment]
this is my complete code:

-module(xhandler_rest).

-export([init/2,get/2, post/2, to_map/2]).

init(Req0, Opts) ->
  case cowboy_req:method(Req0) of
		<<"POST">> ->
      Echo = cowboy_req:has_body(Req0),
      {ok, post(Echo, Req0), Opts};
		<<"GET">> ->
      #{echo := Echo} = cowboy_req:match_qs([{echo, [], undefined}], Req0),
			{ok, get(Echo, Req0), Opts};
    _ ->
      {ok, invalidM(Req0), Opts}
  end.

get(Echo, Req) ->
  case Echo of
    undefined ->
      Datax = db:plq("select * from mhs", []),
      Jf = jiffy:encode(Datax),
      Body = <<"{\"success\":\"yoi\",\"data\":", Jf, "}">>,
    	cowboy_req:reply(200, #{
        <<"server">> => <<"Apache">>,
        <<"access-control-allow-origin">> => <<"*">>,
        <<"access-control-allow-methods">> => <<"GET, POST">>,
    		<<"content-type">> => <<"application/json">>
    	}, Body, Req);
    _ ->
      Body = <<"{\"success\":\"yoi\",\"data\":\"Welcome Service ", Echo/binary, "\"}">>,
    	cowboy_req:reply(200, #{
        <<"server">> => <<"Apache">>,
        <<"access-control-allow-origin">> => <<"*">>,
        <<"access-control-allow-methods">> => <<"GET, POST">>,
    		<<"content-type">> => <<"application/json">>
    	}, Body, Req)
  end.
post(Echo, Req0) ->
  case Echo of
    true ->
      {ok, PostVals, Req} = cowboy_req:read_urlencoded_body(Req0),
    	Username = proplists:get_value(<<"username">>, PostVals),
    	Password = proplists:get_value(<<"password">>, PostVals),

      {ok, C} = epgsql:connect("localhost", "postgres", "postgres", [
        {database, "erlang"},
        {port, 5432},
        {timeout, 4000}
      ]),
      {ok, Cl, Rw} = epgsql:equery(
        C, "select id, username, password from _t_account where username = $1 and password = $2", [Username, Password]
      ),
      ok = epgsql:close(C),
          Datax = to_map(Cl, Rw),
          Jf = jiffy:encode(Datax),
          Body = <<"{\"success\":\"yoi\",\"data\":", Jf/binary, ", \"token\":\"\",\"message\":\"Welcome Service ", Username/binary, "\"}">>,
          cowboy_req:reply(200, #{
            <<"server">> => <<"Apache">>,
            <<"access-control-allow-origin">> => <<"*">>,
            <<"access-control-allow-methods">> => <<"GET, POST">>,
          	<<"content-type">> => <<"application/json">>
          }, Body, Req);

    false ->
      cowboy_req:reply(400, #{
        <<"server">> => <<"Apache">>,
        <<"access-control-allow-origin">> => <<"*">>,
        <<"access-control-allow-methods">> => <<"GET, POST">>,
      	<<"content-type">> => <<"application/json">>
      }, <<"{\"success\":\"x\",\"token\":\"\",\"data\":\"\",\"message\":\"Parameter not found.\"}">>, Req0)
  end.
invalidM(Req) ->
	%% Method not allowed.
  Body = <<"Method not allowed.">>,
  cowboy_req:reply(405, #{
    <<"server">> => <<"Apache">>,
    <<"access-control-allow-origin">> => <<"*">>,
    <<"access-control-allow-methods">> => <<"GET, POST">>,
  	<<"content-type">> => <<"text/plain; charset=utf-8">>
  }, Body, Req).

to_map(Cols, Rows) ->
  Columns = [X || {_, X, _, _, _, _} <- Cols],
    [ maps:from_list(lists:zipwith(fun(N, V) -> {N, V} end,
                                        Columns, tuple_to_list(Row))) || Row <- Rows ].


and, this is error what i found:

Ranch listener my_http_listener, connection process <0.445.0>, stream 2 had its request process <0.447.0> exit with reason undef and stacktrace [{db,plq,["select * from mhs",[]],[]},{xhandler_rest,get,2,[{file,"src/xhandler_rest.erl"},{line,20}]},{xhandler_rest,init,2,[{file,"src/xhandler_rest.erl"},{line,12}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

**Comment by fiodinggo** [comment]
=CRASH REPORT==== 16-Oct-2017::22:43:28 ===
  crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.450.0>
    registered_name: []
    exception error: undefined function db:plq/2
      in function  xhandler_rest:get/2 (src/xhandler_rest.erl, line 20)
      in call from xhandler_rest:init/2 (src/xhandler_rest.erl, line 12)
      in call from cowboy_handler:execute/2 (src/cowboy_handler.erl, line 37)
      in call from cowboy_stream_h:execute/3 (src/cowboy_stream_h.erl, line 205) 
      in call from cowboy_stream_h:request_process/3 (src/cowboy_stream_h.erl, line 184)
    ancestors: [<0.445.0>,<0.415.0>,<0.414.0>,ranch_sup,<0.402.0>]
    message_queue_len: 0
    messages: []
    links: [<0.445.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 320
  neighbours:

=ERROR REPORT==== 16-Oct-2017::22:43:28 ===
Ranch listener my_http_listener, connection process <0.445.0>, stream 5 had its request process <0.450.0> exit with reason undef and stacktrace [{db,plq,["select * from mhs",[]],[]},{xhandler_rest,get,2,[{file,"src/xhandler_rest.erl"},{line,20}]},{xhandler_rest,init,2,[{file,"src/xhandler_rest.erl"},{line,12}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

=CRASH REPORT==== 16-Oct-2017::22:43:34 ===
  crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.451.0>
    registered_name: []
    exception error: undefined function db:plq/2
      in function  xhandler_rest:get/2 (src/xhandler_rest.erl, line 20)
      in call from xhandler_rest:init/2 (src/xhandler_rest.erl, line 12)
      in call from cowboy_handler:execute/2 (src/cowboy_handler.erl, line 37)
      in call from cowboy_stream_h:execute/3 (src/cowboy_stream_h.erl, line 205) 
      in call from cowboy_stream_h:request_process/3 (src/cowboy_stream_h.erl, line 184)
    ancestors: [<0.445.0>,<0.415.0>,<0.414.0>,ranch_sup,<0.402.0>]
    message_queue_len: 0
    messages: []
    links: [<0.445.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 321
  neighbours:

=ERROR REPORT==== 16-Oct-2017::22:43:34 ===
Ranch listener my_http_listener, connection process <0.445.0>, stream 6 had its request process <0.451.0> exit with reason undef and stacktrace [{db,plq,["select * from mhs",[]],[]},{xhandler_rest,get,2,[{file,"src/xhandler_rest.erl"},{line,20}]},{xhandler_rest,init,2,[{file,"src/xhandler_rest.erl"},{line,12}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

**Comment by essen** [comment]
I have never used it but there's no module of that name in that project. To confirm it's not a problem on my end can you run `m(sql_bridge).` in the shell and tell me what it gives you? If it gives proper module infos I'd suggest opening a ticket there instead.

**Comment by fiodinggo** [comment]
ok, thanks for your info...
happy coding

**Comment by fiodinggo** [comment]
erl -pa ebin/ -pa deps/*/ebin/ -eval "sql_bridge:start()" -config sample.config
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> SQL Bridge: Building sql_bridge_stringify. Binaries WILL automatically be converted to lists in query responses.
:2: Warning: export_all flag enabled - all functions will be exported
SQL Bridge: Building Alias module (db) to sql_bridge.
:2: Warning: export_all flag enabled - all functions will be exported
db:plq("select * from mhs", []).
[[{id,1},
  {nama,"Penidas FIodinggo"},
  {contact,"{\"email\":\"fiodinggo@gmail.com\",\"tlp\":\"081390484445\"}"}],
 [{id,2},
  {nama,"Penidas FIodinggo"},
  {contact,"{\"email\":\"fiodinggo@gmail.com\",\"tlp\":\"081390484445\"}"}],
 [{id,3},
  {nama,"Penidas FIodinggo"},
  {contact,"{\"email\":\"fiodinggo@gmail.com\",\"tlp\":\"081390484445\"}"}],
 [{id,4},
  {nama,"Penidas FIodinggo"},
  {contact,"{\"email\":\"fiodinggo@gmail.com\",\"tlp\":\"081390484445\"}"}],
 [{id,5},
  {nama,"Penidas FIodinggo"},
  {contact,"{\"email\":\"fiodinggo@gmail.com\",\"tlp\":\"081390484445\"}"}]]
2>

**Comment by essen** [comment]
Sounds like it works then?

**Comment by fiodinggo** [comment]
i just get that and i execute that module alone without cowboy. but i can not combine with cowboy, ..

**Comment by essen** [comment]
But did you do `sql_bridge:start()` when running with Cowboy too? Is it in your code somewhere? Because I don't think it's supposed to work without it.

**Comment by fiodinggo** [comment]
i'll try to add sql_bridge:start() in my code, but i'v got this:

SQL Bridge: Building sql_bridge_stringify. Binaries WILL NOT automatically be converted to lists in query responses.

=CRASH REPORT==== 16-Oct-2017::23:52:58 ===
  crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.446.0>
    registered_name: []
    exception error: undefined function merl:quote/1
      in function  sql_bridge_alias:build_stringify/1 (src/sql_bridge_alias.erl, line 12)
      in call from sql_bridge:start/0 (src/sql_bridge.erl, line 118)
      in call from xhandler_rest:get/2 (src/xhandler_rest.erl, line 17)
      in call from xhandler_rest:init/2 (src/xhandler_rest.erl, line 9)
      in call from cowboy_handler:execute/2 (src/cowboy_handler.erl, line 37)
      in call from cowboy_stream_h:execute/3 (src/cowboy_stream_h.erl, line 205) 
      in call from cowboy_stream_h:request_process/3 (src/cowboy_stream_h.erl, line 184)
    ancestors: [<0.445.0>,<0.415.0>,<0.414.0>,ranch_sup,<0.402.0>]
    message_queue_len: 0
    messages: []
    links: [<0.445.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 407
  neighbours:

=ERROR REPORT==== 16-Oct-2017::23:52:58 ===
Ranch listener my_http_listener, connection process <0.445.0>, stream 1 had its request process <0.446.0> exit with reason undef and stacktrace [{merl,quote,[["-module(sql_bridge_stringify).\n-compile(export_all).\n","maybe_string(null) -> undefined;\n\t maybe_string(B) -> B."]],[]},{sql_bridge_alias,build_stringify,1,[{file,"src/sql_bridge_alias.erl"},{line,12}]},{sql_bridge,start,0,[{file,"src/sql_bridge.erl"},{line,118}]},{xhandler_rest,get,2,[{file,"src/xhandler_rest.erl"},{line,17}]},{xhandler_rest,init,2,[{file,"src/xhandler_rest.erl"},{line,9}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]}]

and this is my code:

-module(xhandler_rest).

-export([init/2,get/2, to_map/2]).

init(Req0, Opts) ->
  case cowboy_req:method(Req0) of
		<<"GET">> ->
      #{echo := Echo} = cowboy_req:match_qs([{echo, [], undefined}], Req0),
			{ok, get(Echo, Req0), Opts};
    _ ->
      {ok, invalidM(Req0), Opts}
  end.

get(Echo, Req) ->
  case Echo of
    undefined ->
      sql_bridge:start(),
      Datax = db:plq("select * from mhs"),
      Dt = jiffy:encode(Datax),
      Body = <<"{\"success\":\"yoi\",\"data\":", Dt, "}">>,
    	cowboy_req:reply(200, #{
        <<"server">> => <<"Apache">>,
        <<"access-control-allow-origin">> => <<"*">>,
        <<"access-control-allow-methods">> => <<"GET, POST">>,
    		<<"content-type">> => <<"application/json">>
    	}, Body, Req);
    _ ->
      Body = <<"{\"success\":\"yoi\",\"data\":\"Welcome Service ", Echo/binary, "\"}">>,
    	cowboy_req:reply(200, #{
        <<"server">> => <<"Apache">>,
        <<"access-control-allow-origin">> => <<"*">>,
        <<"access-control-allow-methods">> => <<"GET, POST">>,
    		<<"content-type">> => <<"application/json">>
    	}, Body, Req)
  end.
invalidM(Req) ->
	%% Method not allowed.
  Body = <<"Method not allowed.">>,
  cowboy_req:reply(405, #{
    <<"server">> => <<"Apache">>,
    <<"access-control-allow-origin">> => <<"*">>,
    <<"access-control-allow-methods">> => <<"GET, POST">>,
  	<<"content-type">> => <<"text/plain; charset=utf-8">>
  }, Body, Req).

to_map(Cols, Rows) ->
  Columns = [X || {_, X, _, _, _, _} <- Cols],
    [ maps:from_list(lists:zipwith(fun(N, V) -> {N, V} end,
                                        Columns, tuple_to_list(Row))) || Row <- Rows ].

**Comment by essen** [comment]
Sounds like you'll also need to depend on whatever application contains merl in your .app.src file.

**Comment by fiodinggo** [comment]
i think merl already exists inside that module.
if i add again in my .app.src, i found this in my bug:

===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /erlang/rest/ebin
          /erlang/rest/deps
          /usr/local/lib/erlang/lib
          /erlang/rest/apps
          /erlang/rest/_rel
===> Resolved rest_release-1
===> rendering builtin_hook_status hook to "/erlang/rest/_rel/rest_release/bin/hooks/builtin/status"
===> Including Erts from /usr/local/lib/erlang
===> Errors generating release 
          Duplicated modules: 
	merl_transform specified in syntax_tools and merl
	merl specified in syntax_tools and merl

erlang.mk:6599: recipe for target 'relx-rel' failed
make: *** [relx-rel] Error 127

**Comment by essen** [comment]
It's possible that you have a version conflict and that this project doesn't work on your OTP version. I don't really know, I'm not familiar with that project. Either way there's no issues related to Cowboy so please open a ticket there (linking to this one). Thanks!

**Comment by fiodinggo** [comment]
ok, thanx for the information,..
thanx a lot
