### ISSUE TITLE
REST: Difficult to debug scenarios with malformed headers

### ISSUE THREAD

**Issue by lukebakken** [ninenines/cowboy#1229]
[This code](https://github.com/ninenines/cowboy/blob/master/src/cowboy_rest.erl#L909-L914) swallows the exception from `cowboy_req:parse_header` and returns a generic `415` response. In my case, this is the exception detail that I saw via tracing:

```
% cowboy_req:parse_header/2 -> {exit,
                                   {request_error,
                                       {header,<<"content-type">>},
                                       'Malformed header. Please consult the relevant specification.'}}
```

I did a quick search to see if it's acceptable to return a body with a `415` response but couldn't find information about that. So, I'm wondering if including a `text/plain` body in the above scenario would be appropriate:

```
Malformed header "content-type". Please consult the relevant specification.
```

If you're curious, this is the header that caused the exception:

```
<<"content-type">> => <<"application/json;charset=UTF-8, application/json">>
```

I'm using Cowboy 2.0. Thanks!

**Comment by essen** [comment]
Are you sure the 415 isn't enough here? It means the media type is not supported, and indeed this media type is not valid and therefore not supported. If you get a 415 all you gotta check is the content-type header you sent, it should be straightforward.

**Comment by michaelklishin** [comment]
In this specific case, perhaps. Providing more info one way or another would be appreciated (e.g. logging at debug level?).

**Comment by essen** [comment]
Not much point doing extra logging when we have tracing. I do have plans for an integrated tracing solution for debugging purposes though (will become work on that this or next week I think).

**Comment by lukebakken** [comment]
I'll leave this one up to you. *I* didn't find this straightforward but that's probably due to my unfamiliarity with cowboy.

**Comment by essen** [comment]
This is probably best handled at this time via `cowboy_tracer_h` (I'll document it in 2.7) and later on via #1336 when implemented. Since there's a corresponding ticket with more details I'll close this. Thanks!
