### ISSUE TITLE
"Content-Type" header and multiple values

### ISSUE THREAD

**Issue by lukebakken** [ninenines/cowboy#1230]
In #1229 I describe a scenario in which sending the `Content-Type` header twice resulted in a `415` response, which broke a test suite that worked against Cowboy `1.0`. I did a bit more digging and compared how the following request's headers are parsed by `1.1.2` and `2.0`:

```
curl -H 'Content-Type: application/json;charset=UTF-8' -H 'Content-Type: application/json' localhost:8080/ -d 'foo bar baz'
```

Cowboy `1.1.2` 

```
{<<"content-type">>,<<"application/json;charset=UTF-8">>},
{<<"content-type">>,<<"application/json">>},
```

Cowboy `2.0.0`:

```
<<"content-type">> =>
    <<"application/json;charset=UTF-8, application/json">>,
```

This explains why the upgrade to `2.0.0` resulted in the `415` error as `content_types_accepted` didn't match the `<<"application/json;charset=UTF-8, application/json">>` binary passed to it.

In the case of `Content-Type`, I don't believe multiple headers should be combined this way. The [BNF for Content-Type](https://tools.ietf.org/html/rfc1341) doesn't make any mention of multiple values allowed, and [this document](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) states the following:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list

I also tested the above `curl` request with a Sinatra app and only the first header is preserved: [ruby-transcript.txt](https://github.com/ninenines/cowboy/files/1405134/ruby-transcript.txt)

**Comment by essen** [comment]
Wrong RFC. :-)

https://tools.ietf.org/html/rfc7230#section-3.2.2

```
   A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

   A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.  The order
   in which header fields with the same field name are received is
   therefore significant to the interpretation of the combined field
   value; a proxy MUST NOT change the order of these field values when
   forwarding a message.
```

**Comment by lukebakken** [comment]
Ah ok thanks for finding that. Should the change in parsing behavior be mentioned [here](https://github.com/ninenines/cowboy/blob/master/doc/src/guide/migrating_from_1.0.asciidoc#changed-behaviors)?

**Comment by essen** [comment]
Sure, patch welcome. Something about duplicate headers being concatenated back into one.
