### ISSUE TITLE
How do I reload the certificate without taking Cowboy down?

### ISSUE THREAD

**Issue by Jeyhey** [ninenines/cowboy#1233]
I start cowboy (`cowboy:start_https`) with the following 3 files for tls
```
{cacertfile, PrivDir ++ "/chain.pem"},
{certfile, PrivDir ++ "/cert.pem"},
{keyfile, PrivDir ++ "/privkey.pem"}
```
Now these files expired and I want make cowboy reload the new files. How do I achieve this?

**Comment by essen** [comment]
Good question. I don't know how to do it even without Cowboy. I don't think Erlang allows changing the certificate without closing the listening socket right now.

**Comment by essen** [comment]
Someone on erlang-questions pointed out that if you replace the file on the disk the certificate will eventually be used by SSL without having to do anything, and to look at ssl_pem_cache.erl for implementation details.

**Comment by bullno1** [comment]
According to this, it will eventually reload but you can clear cache to make it happens sooner:
http://erlang.org/doc/man/ssl.html#clear_pem_cache-0

**Comment by essen** [comment]
I think this can be closed. In addition to all this, More recent Ranch versions allow suspending/resuming listeners and that can be used to update TLS options. Thanks!
