### ISSUE TITLE
[cowboy_http] I try to set `idle_timeout` to 'infinity'

### ISSUE THREAD

**Issue by fimars** [ninenines/cowboy#1234]
Like this, I use on the elixir.
```elixir
    { :ok, _ } = :cowboy.start_clear(:dev_files_server,
      [{ :port, port }],
      %{ :env => %{ :dispatch => build_dispath_config() }, :idle_timeout => :infinity }
    )
```
![image](https://user-images.githubusercontent.com/16299018/32180398-d75b5044-bd5f-11e7-8a57-78608bdcb048.png)

## More
Use 6_000_000`integer` work very well. But i find `idle_timeout` is `timeout()` type.

**Comment by essen** [comment]
I confirm it's missing a case for infinity.

**Comment by fimars** [comment]
I think you're right, thanks!

**Comment by essen** [comment]
I mean it's a bug so leave open if you want it fixed eventually. :-)

**Comment by fimars** [comment]
My fault, I just misunderstood what you mean. 😆  thank you again.

**Comment by essen** [comment]
This should be fixed in Cowboy master, thanks!
