### ISSUE TITLE
Use websocket causes the system restart when upgrading the release

### ISSUE THREAD

**Issue by feng19** [ninenines/cowboy#1235]
Hello! I use cowboy websocket to develop online chat site. but I encountered a serious problem when upgrading the release. From the source I found that because the system needs to scan the entire application of the supervisor process , but the websocket process is also a supervisor process.Because it does not handle the system message, and then throws the [bad match exception](https://github.com/erlang/otp/blob/OTP-19.3.6/lib/sasl/src/release_handler_1.erl#L657) that causes the system to restart.

**Comment by essen** [comment]
Right it's missing something.

**Comment by essen** [comment]
I will probably not take this on until at least 2.3, there's still quite a bit of work to be done to fully support sys. Let's leave it open and see what the calendar gods have to say about that.

**Comment by essen** [comment]
This should be fixed on master although I have not tested a full release upgrade yet. Please try and reopen if necessary.
