### ISSUE TITLE
Erlang/OTP >= 20.0 deprecates crypto:sha/1 to be replaced with crypto:hash/2

### ISSUE THREAD

**Issue by InfoSec812** [ninenines/cowboy#1236]
Need to implement a safe way to handle this in a backward compatible manner

**Comment by essen** [comment]
Cowboy 2.0 doesn't use crypto:sha/1.

**Comment by InfoSec812** [comment]
Aha! I found my problem... I was not removing the `rebar.lock` in my project and so nothing was getting updated. Thank you!
