### ISSUE TITLE
Return empty 200 after a REST POST request.

### ISSUE THREAD

**Issue by dxtr** [ninenines/cowboy#1240]
I am currently working on creating a server for a (broken?) application that expects a HTTP Status 200 with a Content-Length of 0 after a REST POST request. Cowboy will mainly return Status 204.

I honestly can't see any way to do this. Is my assessment correct?

I have been digging through the code a little and came to this in cowboy_req:
```
-spec has_resp_body(req()) -> boolean().
has_resp_body(#{resp_body := {sendfile, _, _, _}}) ->
	true;
has_resp_body(#{resp_body := RespBody}) ->
	iolist_size(RespBody) > 0;
has_resp_body(_) ->
	false.
```

I also looked in cowboy_rest and found:

```
has_resp_body(Req, State) ->
	case cowboy_req:has_resp_body(Req) of
		true -> multiple_choices(Req, State);
		false -> respond(Req, State, 204)
	end.
```

That makes sense with what I experienced - namely that etting the body to `<<"">>` resulted in cowboy_req:has_resp_body/1 returning false

So I tried this:
```
	    Resp = cowboy_req:set_resp_body({sendfile, 0, 0, "/dev/zero"}, Req),
```

That results in `cowboy_req:has_resp_body/1` returning true - but the response I am getting is still 204.
Am I simply missing something here?

I am running 2.1.0, by the way.

**Comment by dxtr** [comment]
I might have fired away too early. Might re-open the issue after some more testing.

**Comment by dxtr** [comment]
Okay, sorry about that.

This works for setting an empty body:
```
cowboy_req:set_resp_body({sendfile, 0, 0, "/dev/zero"}, Req)
```

While this doesn't:
```
cowboy_req:set_resp_body(<<"">>, Req)
```

**Comment by essen** [comment]
Just call cowboy_req:reply and return a stop tuple to stop the processing of the request.

**Comment by dxtr** [comment]
Yeah, that worked! Thanks!
