### ISSUE TITLE
Link stream_handler guide and manual (or any other topic really)

### ISSUE THREAD

**Issue by robertoaloi** [ninenines/cowboy#1241]
Hooks have been removed in Cowboy 2 as explained [here][migrating].

Specifically, the documentation states that:

> Hooks are gone, their functionality can now be achieved via stream handlers.

But the documentation for [stream handlers][streams] is a bit limited. It would be convenient to show an example of how a [onRequest/onResponse hook][hooks] would look like in Cowboy 2, when implemented as a stream handler.

[hooks]:https://ninenines.eu/docs/en/cowboy/1.0/guide/hooks/
[migrating]:https://ninenines.eu/docs/en/cowboy/2.1/guide/migrating_from_1.0/
[streams]:https://ninenines.eu/docs/en/cowboy/2.1/guide/streams/

**Comment by robertoaloi** [comment]
Stream handlers are actually documented in a lot more detail in the [reference manual][manual].
Probably a good idea to link the two sections.

[manual]:https://ninenines.eu/docs/en/cowboy/2.1/manual/cowboy_stream/

**Comment by essen** [comment]
This is fixed locally but you will need for 2.7 documentation to be uploaded to see it. Closing, thanks!
