### ISSUE TITLE
can't change environment after start of listener

### ISSUE THREAD

**Issue by mkrusemark** [ninenines/cowboy#1242]
Changing routes for an already running listener has no effect.

Start listener:
    Dispatch = cowboy_router:compile([]),
    {Res0, _} = cowboy:start_clear(http_listener,
                                  [{port, 8000}],
                                  #{env => #{dispatch => Dispatch}}
                                 ),

Change routes:
        Dispatch = cowboy_router:compile([{"_", [{"/", http_connector_handler, []}]}]),
        cowboy:set_env(http_listener, dispatch, Dispatch)

http_connector_handler:
init(Req0, State) ->
    throw(Req0),

requesting localhost:8000:// doesn't show anything. The same handler is called if used in cowboy:start_clear.

**Comment by essen** [comment]
Just to make sure, you tried opening a new connection? This only applies to new connections. Try with curl for example to make sure it's using separate connections before/after.

**Comment by mkrusemark** [comment]
$ curl -v localhost:8000
* STATE: INIT => CONNECT handle 0x600057a90; line 1423 (connection #-5000)
* Rebuilt URL to: localhost:8000/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x600057a90; line 1459 (connection #0)
*   Trying ::1...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x600057a90; line 1540 (connection #0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057a90; line 1592 (connection #0)
* Marked for [keep alive]: HTTP default
* STATE: SENDPROTOCONNECT => DO handle 0x600057a90; line 1610 (connection #0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.56.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600057a90; line 1689 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057a90; line 1814 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057a90; line 1824 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 400 Bad Request
< content-length: 0
< date: Wed, 06 Dec 2017 10:56:43 GMT
* Server Cowboy is not blacklisted
< server: Cowboy
<
* STATE: PERFORM => DONE handle 0x600057a90; line 1993 (connection #0)
* multi_done
* Connection #0 to host localhost left intact
* Expire cleared

**Comment by essen** [comment]
Actually I think your issue is that you used `"_"` for the hostname instead of `'_'`.

**Comment by mkrusemark** [comment]
Thank you for your extremly fast support!!!
