### ISSUE TITLE
Client PID

### ISSUE THREAD

**Issue by fiodinggo** [ninenines/cowboy#1243]
Hello everyone,
i'm confused, where is my real pid (client pid), because in init function, if i catch self() / erlang:self(), it doesn't same with - if i catch self() / erlang:self() from  websocket_init. please take a look my script:

-module(ws_handler).

-export([init/2]).
-export([websocket_init/1]).
-export([websocket_handle/2]).
-export([websocket_info/2]).

init(Req0, State) ->
  io:format("start#1 ~p~n", [self()]),
  {cowboy_websocket, Req0, State}.

websocket_init(State) ->
  io:format("start#2 ~p~n", [self()]),
  erlang:start_timer(10000, self(), <<"Hello!">>),
  {reply, State, hibernate}.

websocket_handle({text, Msg}, State) ->
	{reply, {text, << "That's what she said! ", Msg/binary >>}, State, hibernate};
websocket_handle(_Data, State) ->
	{ok, State, hibernate}.

websocket_info({timeout, _Ref, Msg}, State) ->
	erlang:start_timer(10000, self(), <<"How' you doin'?">>),
	{reply, {text, Msg}, State, hibernate};
websocket_info(_Info, State) ->
{ok, State}.

What is this supposed to be or not?
please, i need some reason for that...
Thanks alot

**Comment by essen** [comment]
websocket_init/1 is where you want to do your Websocket initialization. init/2 is where HTTP requests are handled, the pid changes after you return cowboy_websocket there because the Websocket connection takes over the HTTP connection.

**Comment by fiodinggo** [comment]
therefore, fair if client-1 connect to websocket and he got pid like <"0.412.0">, and client-2 got <"0.414.0">, client-3 got <"0.416.0">?
sorry if I am wrong..

**Comment by essen** [comment]
Well different clients always have different pids yes.

**Comment by fiodinggo** [comment]
ok, meaning if i have 1000 client, it means there will be 2000 PID. do we have to kill another PID or leave it?

**Comment by essen** [comment]
Cowboy does it for you, don't worry about it. The extra pid and init/2 call can be avoided if you grow large enough that it makes sense to avoid creating the extra process, by writing a stream handler, but until then don't worry about it.

**Comment by fiodinggo** [comment]
nice.

i'v need some reason and sugg from you, should i store any PID in mnesia, Syn, gproc, session, or what? i need it

**Comment by essen** [comment]
Yes of course no problem doing that.

**Comment by fiodinggo** [comment]
do you have a consideration from that option for me? please

**Comment by essen** [comment]
I'd start with syn.

**Comment by fiodinggo** [comment]
ok essen, thanks alot for that.
i have another question for u,
when one client is inactive or not connected to the server, its PID will automatically be deleted, if PID is deleted, can it be re-enabled the PID?

**Comment by essen** [comment]
Yes pids wrap but only after a very long time.

**Comment by fiodinggo** [comment]
ok essen, how long will it take?

**Comment by essen** [comment]
Depends on the system. I don't remember the details, never seen it myself.
