### ISSUE TITLE
Recommended way of redirecting http request to https

### ISSUE THREAD

**Issue by Ilyes512** [ninenines/cowboy#1246]
Hi, I am new to he platform and learning mainly Elixir at the moment. As you might now the "main" (web) framework for Elixir is Phoenix which uses Plug which in turn uses Cowboy as its server. I always like to go deep into the underlying libraries so thats why I started [this](https://github.com/Ilyes512/elixir_hello_world) to play around with Cowboy.

So at this point I have got cowboy(2) running either using start_clear or start_tls. At this point I want to use https, but I want all incoming http request to be redirected to https. I know how to do this with Nginx, but I was wondering if this was possible using cowboy (or using any other language feature in Erlang/Elixir). Besides the question if it's possible I would also like to know if this is the "best"/recommend way of doing it. If its not, should I use an external tools like Nginx/HAProxy for redirecting?

I have also tried running both http and https by calling both start_clear and start_tls, but it seems only one survives? Not sure what I should change to be able to run two cowboy instances (on two different ports I think in any case).

**Comment by essen** [comment]
Different listeners must have different names and ports, that's about it. There's no recommended way to redirect, up to you. RabbitMQ has this, for example:

- https://github.com/rabbitmq/rabbitmq-web-dispatch/blob/master/src/rabbit_web_dispatch.erl#L53
- https://github.com/rabbitmq/rabbitmq-web-dispatch/blob/master/src/rabbit_cowboy_redirect.erl
