### ISSUE TITLE
Safari hangs on certain H2 responses.

### ISSUE THREAD

**Issue by idyll** [ninenines/cowboy#1247]
### Background

I apologize but figuring out how to trigger the bug has exhausted my H2 knowledge. I am not sure if the issue is Safari not correctly handling an edge case or if Cowboy doesn't conform to the spec.

This is probably Cowboy triggering a Safari bug. And if so I have an open ticket with Apple. I just need to be able to explain to them what to fix.

### My Observation

Safari and the GO H2C command line client both hang when they receive a certain sequence of frames from Cowboy. I first triggered it in a Phoenix app but I am reproduce directly in Cowboy by calling `reply` with specially crafted iodata.

### To Reproduce
`reply` with the following iodata:
```
[[["" | ""]  | ""]  | "... string that contains at around 36,000 characters or so..." ]
```

I have a sample project here: (again I apologize it's elixir not erlang.)
https://github.com/idyll/safari

My guess is that the result is several small frames being sent to Safari which result in it triggering the bug. But your insight would be appreciated.

**Comment by essen** [comment]
It would help if you could convert it to Erlang, it shouldn't be difficult to convert the hello_world example to send this data.

I also don't have safari but I can probably use Go's h2c to reproduce.

**Comment by idyll** [comment]
Okay, I am going to convert this over the next day or two. You can see h2c hang on the issue as well. Everything else seems to work.

**Comment by idyll** [comment]
Here's a repos with an erlang example that will trigger the error, @essen:

https://github.com/idyll/safari_test_erlang

**Comment by idyll** [comment]
My theory is that the way I am structuring the IOData is triggering small or empty frames which is causing h2c and Safari fail before it gets to the end of the content.

But I am most certainly not the expert here...

**Comment by essen** [comment]
OK I got it setup, thanks. There's definitely a problem. I'll get back to you when I can look into it properly.

**Comment by essen** [comment]
I have fixed it locally and am now preparing a 2.2.1 release with this and a couple other fixes.

**Comment by essen** [comment]
Cowboy 2.2.1 https://ninenines.eu/docs/en/cowboy/2.2/guide/migrating_from_2.2/

**Comment by idyll** [comment]
THANKS!!!

**Comment by whitepaperclip** [comment]
@essen I think there's a regression with this bug. Only hangs with iodata output, not a binary. Still working on getting reliable data to cause the timeout.
