### ISSUE TITLE
src/cb3_handler.erl:2: behaviour cowboy_http_handler undefined

### ISSUE THREAD

**Issue by ToolwatchThunker** [ninenines/cowboy#1249]
The Cowboy Web Server fails on the Erlang statement ****-behaviour(cowboy_http_handler)**** 

I have tried Cowboy Web Server Versions 2.2.0 and 2.1.0 but they both have the same problems.

Here is the output of the make operation:

`[tomlinux@tomlinux cb3]$ make run
make[1]: Entering directory '/home/tmoriarty/cb3/deps/cowboy'
make[2]: Entering directory '/home/tmoriarty/cb3/deps/cowlib'
make[2]: Leaving directory '/home/tmoriarty/cb3/deps/cowlib'
make[2]: Entering directory '/home/tmoriarty/cb3/deps/ranch'
 DEPEND ranch.d
make[2]: Leaving directory '/home/tmoriarty/cb3/deps/ranch'
 DEPEND cowboy.d
 GEN    rebar.config
make[1]: Leaving directory '/home/tmoriarty/cb3/deps/cowboy'
 DEPEND cb3.d
 ERLC   cb3_app.erl cb3_handler.erl
compile: warnings being treated as errors
src/cb3_handler.erl:2: behaviour cowboy_http_handler undefined
erlang.mk:5141: recipe for target 'ebin/cb3.app' failed
make[1]: *** [ebin/cb3.app] Error 1
erlang.mk:4932: recipe for target 'app' failed
make: *** [app] Error 2`

**Comment by ToolwatchThunker** [comment]
make[1]: Entering directory '/home/tmoriarty/cb3/deps/cowboy'
make[2]: Entering directory '/home/tmoriarty/cb3/deps/cowlib'
make[2]: Leaving directory '/home/tmoriarty/cb3/deps/cowlib'
make[2]: Entering directory '/home/tmoriarty/cb3/deps/ranch'
 DEPEND ranch.d
make[2]: Leaving directory '/home/tmoriarty/cb3/deps/ranch'
 DEPEND cowboy.d
 GEN    rebar.config
make[1]: Leaving directory '/home/tmoriarty/cb3/deps/cowboy'
 DEPEND cb3.d
 ERLC   cb3_app.erl cb3_handler.erl
compile: warnings being treated as errors
src/cb3_handler.erl:2: behaviour cowboy_http_handler undefined
erlang.mk:5141: recipe for target 'ebin/cb3.app' failed
make[1]: *** [ebin/cb3.app] Error 1
erlang.mk:4932: recipe for target 'app' failed
make: *** [app] Error 2

**Comment by essen** [comment]
That's because there's no cowboy_http_handler in Cowboy 2, only cowboy_handler for the closest equivalent.

**Comment by ToolwatchThunker** [comment]
Changing the statement "-behaviour( cowboy_http_handler )" to "-behaviour(cowboy_http)" does NOT fix the problem. The compilation error is: _src/cb3_handler.erl:2: behaviour cowboy_http undefined_ .

How then do you fix the compilation error: **_src/cb3_handler.erl:2: behaviour cowboy_http undefined_** ?

**Comment by essen** [comment]
I said cowboy_handler, not cowboy_http.

**Comment by ToolwatchThunker** [comment]
make[1]: Entering directory '/home/tmoriarty/cb4/deps/cowboy'
make[2]: Entering directory '/home/tmoriarty/cb4/deps/cowlib'
make[2]: Leaving directory '/home/tmoriarty/cb4/deps/cowlib'
make[2]: Entering directory '/home/tmoriarty/cb4/deps/ranch'
make[2]: Leaving directory '/home/tmoriarty/cb4/deps/ranch'
 GEN    rebar.config
make[1]: Leaving directory '/home/tmoriarty/cb4/deps/cowboy'
 DEPEND cb4.d
 ERLC   cb4_handler.erl
compile: warnings being treated as errors
src/cb4_handler.erl:2: undefined callback function init/2 (behaviour 'cowboy_handler')
erlang.mk:5141: recipe for target 'ebin/cb4.app' failed
make[1]: *** [ebin/cb4.app] Error 1
erlang.mk:4932: recipe for target 'app' failed
make: *** [app] Error 2
[tmoriarty@tomlinux cb4]$

**Comment by ToolwatchThunker** [comment]
I just got an undefined callback function error with cowboy_handler .

**Comment by ToolwatchThunker** [comment]
My Handler module appears as follows;


-module(cb4_handler).
-behaviour(cowboy_handler).

-export([init/3]).
-export([handle/2]).
-export([terminate/3]).

-record(state, {
}).

init(_, Req, _Opts) ->
        {ok, Req, #state{}}.

handle(Req, State=#state{}) ->
        {ok, Req2} = cowboy_req:reply(200, Req),
        {ok, Req2, State}.

terminate(_Reason, _Req, _State) ->
        ok.

**Comment by essen** [comment]
If you didn't define an `init/2` function, that's the intended behavior. You need to update your Cowboy 1.0 code to work with Cowboy 2.0+. Check the migration chapters in the guide.

**Comment by ToolwatchThunker** [comment]
I am *NOT* migrating code from Cowboy 1.0 to Cowboy 2.0+ . I am following the "Getting Started" instructions on https://ninenines.eu/docs/en/cowboy/2.2/guide/getting_started/ .

**Comment by ToolwatchThunker** [comment]
Have the templates been upgraded from 1.0 to 2.0+? What templates should I use?

**Comment by essen** [comment]
The link you point to gives you the correct templates:

```
make new t=cowboy.http n=hello_handler
```

`cowboy.http` and NOT `cowboy_http`. The 2.0+ templates are included inside Cowboy directly instead of Erlang.mk, hence the change of name. The old templates will be removed at some point.

**Comment by essen** [comment]
Cheers!
