### ISSUE TITLE
How best to implement an Apache-style access log for Cowboy >=2.0?

### ISSUE THREAD

**Issue by nickelization** [ninenines/cowboy#1251]
Hi there, I'd really like to add support for Apache-style access logs to Cowboy (and maybe error logs too), but I'm not sure how best to go about it. I specifically say Apache-style logs because there are a lot of great tools that exist out there for parsing and dealing with logs that follow this particular format, so I'd really like the format of the logs to match an actual Apache log as closely as possible. I recently switched a big project from Webmachine over to Cowboy, and overall I've really loved Cowboy, but the one thing I've missed from Webmachine is the Apache-style logging features that it has. If we could get that added, Cowboy would really be perfect for my needs 😀

I can see this has been discussed before for pre-2.0 Cowboy, and it looks like the `onresponse` hook would work great, but it looks like that feature has been removed in 2.0 and later. I also looked into creating a middleware module for this, but it doesn't seem like you can get all the info you need to include stuff like the response code, since sending a response seems to follow a totally separate code path that doesn't involve the middleware stuff at all.

I'd be happy to submit a patch to Cowboy to help enable this, but I'm not sure what the best way to go about it would be from an architectural standpoint. Some sort of enhancement to middlewares? Bringing onresponse back? Maybe building better logging features directly into Cowboy as a first-class feature? Or something else entirely? I figured I'd better have a discussion about this before I start coding, to make sure whatever I implement has a shot at being accepted. Looking forward to hearing your thoughts!

**Comment by essen** [comment]
Look at the undocumented `cowboy_metrics_h` stream handler. You can configure a callback to receive all sorts of information about the request and response and build your logs from there.

It will be documented in a future release.

**Comment by nickelization** [comment]
Oh, very cool, thank you! Totally missed that module during my code spelunking the other day. Will look into it.

**Comment by essen** [comment]
It wasn't there in 2.0 and I wouldn't recommend using it before 2.2 as there was various small issues that were corrected since.

**Comment by nickelization** [comment]
Gotcha, thanks for the heads up. If/when I get this style of logging implemented, would you be interested in including the code in Cowboy directly, or would I be better off creating a separate repo for the supporting code?

**Comment by essen** [comment]
It should be kept separate for sure. People use a variety of different logging methods nowadays.

**Comment by nickelization** [comment]
Makes sense :thumbsup: Will do.

**Comment by ypaq** [comment]
How would you access the status code from a cowboy_rest handler?

**Comment by hachreak** [comment]
@essen Sorry for the naive question :smile: , but could `cowboy_metrics_h` be used to get metrics also in "normal" REST requests or only in streams requests?

**Comment by essen** [comment]
"Streams" are an HTTP/2 term for the set of request and response. It applies to everything except Websocket post-handshake (the handshake goes through stream handlers too).

**Comment by hachreak** [comment]
I was trying to use in REST requests but every request is going in timeout.

```erlang
   ...
   cowboy:start_clear(http, [{port, 8090}], #{
      metrics_callback => do_metrics_callback(),
      stream_handlers => [cowboy_metrics_h],
      env => #{dispatch => Dispatch}
  met_sup:start_link().

do_metrics_callback() ->
   fun(Metrics) ->
      error_logger:error_msg("@@ metrics~n~p~n", [Metrics]),
      ok
   end.
```

**Comment by essen** [comment]
Well sure if you remove `cowboy_stream_h` you got nothing left to handle your requests. Try:

``` erlang
      stream_handlers => [cowboy_metrics_h, cowboy_stream_h],
```

**Comment by hachreak** [comment]
Ok, now it's working! XD
Thanks for the help :)

**Comment by nickelization** [comment]
Hey @jordanchaitin I did implement a working solution based on `cowboy_metrics_h` but it was fairly tightly coupled with the project I was working on at the time, and I never got around to factoring it out into its own repository before I left my previous employer. I'll ping my teammates from the time though in case any of them has the time and inclination to open-source any of the code:

@franko-franicevich @alhambra1 @darrenklein (hey guys, hope everything's going great at Circles! :)
