### ISSUE TITLE
Elixir compilation fails if _build directory is a symlink to a nested directory

### ISSUE THREAD

**Issue by naps62** [ninenines/cowboy#1255]
Trying to compile a project in our CI, I noticed that this package failed to compile.

We were using a setup recommended by our CI, where the `_build` directory (where builds from Elixir projects go to) was symlinked to `$SEMAPHORE_CACHE_DIR/_build`. Under these conditions, cowboy failed to compile, with the following error:

```
** (Mix) Could not compile dependency :cowboy, "/home/runner/.mix/rebar3 bare compile --paths "/home/runner/platform/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile cowboy", update it with "mix deps.update cowboy" or clean it with "mix deps.clean cowboy"
```

Trying to reproduce this locally I noticed that it failed if `_build` was symlinked to `./first-dir/second-dir`, but it worked if it was symlinked directly to `./first-dir`, so without adding the extra level of nesting

I'm not if this is a cowboy issue though. Might also be rebar or some other tool (I'm not that familiar with the Erlang ecosystem), so apologies if this is the wrong place to report it

**Comment by essen** [comment]
I doubt I can help, but even if I could the error you got is not helpful so you should try to find a more verbose error.

**Comment by essen** [comment]
Please reopen when you got a better error message. Thanks!

**Comment by naps62** [comment]
@essen I can't really find a way to get a better one, this is the only output I get. Any suggestions on that?

The best I can come up with is a way to reproduce this:

```
$ mix phx.new testing
$ cd testing
$ mkdir -p one/two
$ ln -s $PWD/one/two _build
$ mix compile
```

that last command should give the error message and fail to compile

**Comment by essen** [comment]
I'm not a Elixir/Mix user so I don't really know what this does or how Mix compiles Cowboy. I'm also not sure this is a Cowboy issue.

**Comment by naps62** [comment]
Well, my bad on that part, I keep forgetting that erlang and elixir are two differente communities :)

I do believe that this is an issue of either cowboy or one of it's dependencies
The reason for that is that it seems to only happen with this package, and not any other erlang-based one.

I can try to find more info in the future, but erlang is outside my knowledge, so I can't make any promises

**Comment by OvermindDL1** [comment]
First step is to replicate the compile error with just rebar (should not be too hard actually, as you can see in the first post it is literally calling rebar, just call that same command and see if the same error happens, then it is replicated in pure erlang/rebar ^.^).

**Comment by essen** [comment]
Either way you're not going to get anywhere without more output. There's probably an option.

**Comment by naps62** [comment]
Ok, not sure if this is what's you're looking for:

```shell
$ export DEBUG=1
$ # this is where my rebar installation is
$ rebar=/home/naps62/.asdf/installs/elixir/1.6.0/.mix/rebar3

$ # this is the command suggested in the original error message:
$ $rebar bare compile --paths "/home/naps62/testing/_build/dev*/ebin"
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {bare,compile}]
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location:
[{rebar_prv_bare_compile,do,1,
                         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_bare_compile.erl"},
                          {line,45}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,153}]},
 {rebar_prv_do,do_tasks,2,
               [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                {line,68}]},
 {rebar_core,do,2,
             [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
              {line,153}]},
 {rebar3,main,1,
         [{file,"/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
          {line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,759}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]},
 {init,start_em,1,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`

And the report that this one asks for:

```shell
$ $rebar report "bare compile --paths \"/home/naps62/testing/_build/dev*/ebin\""                                                                                                    1s | 18:38
===> Expanded command sequence to be run: [{default,report}]
Rebar3 report
 version 3.3.6
 generated at 2018-01-24T18:41:15+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: bare
Entered as:
  bare compile --paths "/home/naps62/testing/_build/dev*/ebin"
-----------------
Operating System: x86_64-unknown-linux-gnu
ERTS: Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.3.0
certifi: 0.4.0
cf: 0.2.2
common_test: 1.15.3
compiler: 7.1.4
crypto: 4.2
cth_readable: 1.2.4
dialyzer: 3.2.3
edoc: 0.9.2
erlware_commons: 1.0.0
eunit: 2.3.5
eunit_formatters: 0.3.1
getopt: 0.8.2
inets: 6.4.5
kernel: 5.4.1
providers: 1.6.0
public_key: 1.5.2
relx: 3.22.3
sasl: 3.1.1
snmp: 5.2.9
ssl_verify_fun: 1.1.1
stdlib: 3.4.3
syntax_tools: 2.1.4
tools: 2.11.1

-----------------
Escript path: /home/naps62/.asdf/installs/elixir/1.6.0/.mix/rebar3
Providers:
  app_discovery as clean compile compile cover ct deps dialyzer do edoc escriptize eunit get-deps help install install_deps list lock new path pkgs release relup report shell state tar tree unlock update upgrade upgrade upgrade version xref 
```

**Comment by naps62** [comment]
Also, I just noticed that this fails if `_build` is symlinked to `$PWD/one/two`, but works if the symlink goes to `./one/two`. So it only fails for an absolute path, not a relative one

**Comment by naps62** [comment]
some more context (not sure if it is needed): in Elixir, the compiled code goes to `_build/dev` where dev is the current environment I'm running

**Comment by essen** [comment]
Sounds like you should open a ticket for Rebar3.

**Comment by naps62** [comment]
Ok, will do 👍
