### ISSUE TITLE
H2 content for large pages with multiple elements is scrambled in Chrome and Safari.

### ISSUE THREAD

**Issue by idyll** [ninenines/cowboy#1258]
Since the 2.2.1 updates release content is displayed out of order in Chrome and Safari.

Specifically in HTML I am seeing a portion of a sample page is rendered before the html header. It looks like the first two packets of data are being reversed.

Portions of the content are also missing.

I will provide a sample as soon as I can reliably replicate it. But it only triggered once a page reaches a certain size.

**Comment by essen** [comment]
I must have forgotten a lists:reverse, I'll look into it.

**Comment by essen** [comment]
Yeah I know where it happens, noob mistake.

**Comment by essen** [comment]
Fixed and released 2.2.2 which contains this fix. Thanks!

**Comment by idyll** [comment]
Thanks again. I have confirmed that everything is working in a couple production apps.

And thanks for fixing so quickly.

**Comment by essen** [comment]
Great! Two releases in two days is enough...
