### ISSUE TITLE
WebSocket connection disconnected after 1min with example

### ISSUE THREAD

**Issue by zombiecong** [ninenines/cowboy#1259]
Hi ,

I am a newbie of erlang , and I try the [example](https://github.com/ninenines/cowboy/tree/master/examples/websocket) of websocket.

It works well at the beginning,  but the connection was disconnected after 1min. And I got a `timeout` message from `terminate/3`.

I am confused , the timeout because of "ping/pong timeout" or something I missed.

Thanks.

**Comment by essen** [comment]
If the server doesn't receive anything from the client before the timeout occurs it will close the connection.

**Comment by zombiecong** [comment]
Thanks for your reply. I want to know how to disable this feature,  and I want to make connections disconnected only when I send a "close" signal.

**Comment by essen** [comment]
The `idle_timeout` option here: https://ninenines.eu/docs/en/cowboy/2.2/manual/cowboy_websocket/#_types - use `infinity`.

You should NOT disable it though because if you do then Cowboy has no way to detect and get rid of connections in the half-open state.

**Comment by zombiecong** [comment]
Make sense, I only use this in debug. Thanks.
