### ISSUE TITLE
cowboy_static: problems trying to return content-type with charset utf-8

### ISSUE THREAD

**Issue by madsflensted** [ninenines/cowboy#1263]
I have been trying to get cowboy_static to return a file with the following response header
```
content-type: text/html; charset=utf-8
```
I tried using the `mimetypes` parameter as described in the [docs](https://ninenines.eu/docs/en/cowboy/2.2/manual/cowboy_static/):
```erlang
  {"/someroute", cowboy_static,
    {priv_file, somemodule, "file.html",
      [{mimetypes, {<<"text">>, <<"html">>, [{<<"charset">>, <<"utf-8">>}]}}]
    }
  }
```
This makes cowboy return `406` status code when browser requests the file with this request header:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
If I manipulate the header before sending the request to be:
```
Accept: text/html;charset=utf-8,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
Then I get the desired response.

If on the other hand I change `cowboy_static.erl` to override the `cowboy_rest:charsets_provided()`:
```erlang
% in cowboy_static.erl
charsets_provided(Req, State) ->
    {[<<"utf-8">>], Req, State).
```
Then the standard browser accept header works and I get the desired `content-type` back.

I can easily workaround this by just serving the file from my own rest handler, so it is not a big issue, and I just wanted to understand if I am doing something wrong or if there is another way of doing this that I have not spotted.

**Comment by essen** [comment]
Sounds related to #1245 can you try the PR that was open for it?

**Comment by madsflensted** [comment]
I created a small unit test to capture this issue, and it fails for both master the code in #1245

**Comment by essen** [comment]
1. Yes I'm thinking it needs an option.
2. Yeah I would say that's a good idea and we probably should do this before 3.0, even if it's a breaking change I doubt anyone has non-utf-8 files.

I intend to look into this set of issues next week after releasing 2.3.

**Comment by madsflensted** [comment]
I guess the safe option could be to do

1. in 2.x
2. in 3.x

**Comment by essen** [comment]
I have done both things from the above comment. Pushing in a few minutes. Thanks!
