### ISSUE TITLE
Allow response body of any size to be compressed

### ISSUE THREAD

**Issue by stevedomin** [ninenines/cowboy#1265]
Hi @essen,

I've been looking for  a way to compress all responses, regardless of their size. I noticed that this is currently hardcoded in Cowboy [1](https://github.com/ninenines/cowboy/blob/1.1.x/src/cowboy_req.erl#L899) and [2](https://github.com/ninenines/cowboy/blob/master/src/cowboy_compress_h.erl#L112).

In Cowboy 2 there is [a comment](https://github.com/ninenines/cowboy/blob/master/src/cowboy_compress_h.erl#L104) to maybe make this configurable. I'd be happy to work my way around the codebase to make this happen if:

1/ that's still something you believe valuable
2/ implementation is not too difficult for a newcomer

Thanks

Cowboy version: 1.1.2
(Used via Phoenix 1.3.0)

**Comment by essen** [comment]
Yes it's still valuable. This module is actually still experimental so this kind of feedback is very useful.

https://github.com/ninenines/cowboy/blob/master/src/cowboy_metrics_h.erl#L139 has an example of option value, it's just a matter of calling maps:get and keeping the option around in the state. Just make sure the default is what's currently in the code and add a test in compress_SUITE with a custom value and that should be good. You can run the compress test exclusively via `make ct-compress`.

I have no plans for further Cowboy 1 versions though.

**Comment by stevedomin** [comment]
Ok, thanks, I'll have a go at it.

No problem for Cowboy 1, having this in Cowboy 2 will be good already.

**Comment by essen** [comment]
Merged with tweaks.
