### ISSUE TITLE
Content-length error crash the process due to wrong error handling

### ISSUE THREAD

**Issue by sauvainr** [ninenines/cowboy#1267]
The 'content-length' error emitted at
https://github.com/ninenines/cowboy/blob/master/src/cowboy_http2.erl#L942

doesnt match the 'terminate_reason' and crash
https://github.com/ninenines/cowboy/blob/master/src/cowboy_http2.erl#L817

Error:
`Process #PID<0.722.0> terminating
** (FunctionClauseError) no function clause matching in :cowboy_http2.terminate_reason/1    
(cowboy) /home/renaud/Workspace/pegasus_dispatcher/deps/cowboy/src/cowboy_http2.erl:817: :cowboy_http2.terminate_reason({:stream_error, 1, :protocol_error, :"The content-length header is invalid. (RFC7230 3.3.2)"})    
(cowboy) /home/renaud/Workspace/pegasus_dispatcher/deps/cowboy/src/cowboy_http2.erl:811: :cowboy_http2.terminate/2    
(cowboy) /home/renaud/Workspace/pegasus_dispatcher/deps/cowboy/src/cowboy_http2.erl:942: :cowboy_http2.stream_req_init/5    
(cowboy) /home/renaud/Workspace/pegasus_dispatcher/deps/cowboy/src/cowboy_http2.erl:293: :cowboy_http2.parse/2    
(cowboy) /home/renaud/Workspace/pegasus_dispatcher/deps/cowboy/src/cowboy_http.erl:256: :cowboy_http.parse/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: :cowboy_clear.connection_process/5
`

**Comment by essen** [comment]
Good find, thanks.

**Comment by essen** [comment]
This should be fixed in the most recent commit. Please try it and keep me informed! If a patch release for this would help I can probably have one ready in a week or two, just tell me.

Thanks!
