### ISSUE TITLE
How can I  update internal state periodically?

### ISSUE THREAD

**Issue by whitelilis** [ninenines/cowboy#1271]
My http handler need a dict to find something, and this dict need to be updated periodically, how can I do this?

**Comment by bullno1** [comment]
You can create a gen_server and make the handler query it. Then use ets if you want to optimize.

**Comment by essen** [comment]
Handlers are short lived, it's up to you to provide long lived processes as @bullno1 points out. Even applies to longer lived handlers like loop or Websocket since the connection can go down at any time.
