### ISSUE TITLE
Websocket over HTTP/2

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1272]
Please comment if you need it.

https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets-00

**Comment by OvermindDL1** [comment]
Not 'need' per-say, but it would be nice to have.

**Comment by bullno1** [comment]
If I do `new Websocket()` in the browser, which method would they use? I know it's different from browsers to browsers but what would the popular ones like IE, Firefox, Chrome do?

**Comment by essen** [comment]
If they connected via h2 and the server sent the flag indicating Websocket support they'll use that, otherwise http/1.1.

**Comment by essen** [comment]
I got a working implementation for Cowboy, it just needs more tests. I hope to push it tomorrow. Only Chrome implemented it so far.

**Comment by essen** [comment]
I have added an implementation at bbfc1569ccffab060c4c2b402a45119fb1f57495. It still has minor issues but it's compatible with `google-chrome-dev` at least. There's currently no other client to test it with.

**Comment by essen** [comment]
I'll close this ticket and do improvements over time. I don't plan to enable it by default for a while anyway, there's little to be gained from that until more support is added to clients. At least 2 Chrome versions off for any one client, we got time.
