### ISSUE TITLE
How to send msg to client before reply

### ISSUE THREAD

**Issue by dcy** [ninenines/cowboy#1276]
Hi!
I want to send a msg/bin to client before [reply](https://github.com/ninenines/cowboy/blob/master/examples/websocket/src/ws_handler.erl#L15)
```
websocket_handle({text, Msg}, State) ->
        %% Send <<"Hello">> to client
	{reply, {text, << "World" >>}, State};
```
In one ```websocket_handle```, I want to send the first msg ```<<"Hello">>``` to client, then send the second msg ```<<"World">>``` to client. The client should receive ```<<"Hello">>``` first.
Could you tell me how?

**Comment by essen** [comment]
`[{text, <<"Hello">>}, {text, <<"World">>}]`
