### ISSUE TITLE
Cowboy does not accept new connections after some sockets get stuck in CLOSE_WAIT state

### ISSUE THREAD

**Issue by awaise267** [ninenines/cowboy#1279]
Hey there,

I was doing some tests to figure out an optimal number for the acceptors (I am using cowboy for websockets). I started with 100 following your comment on http://erlang.org/pipermail/erlang-questions/2012-October/069570.html
>     NBAcceptor shouldn't be too low but shouldn't be too high either. I
>     found 100 to be a good values but it really depends on how many
>     connections come at once, how many cores you have, how many
>     concurrent connections you expect, and so on.

For my tests, I have created a "client" script using Gun (it just does `gun:open` followed by `gun:ws_upgrade` to open `N` connections). I'm not controlling the rate at which I open these connections in order to find out the maximum rate of incoming connections I can support with the 100 acceptors.

I noticed some failures starting when `N` is around 2000. If I stop my client script at this point and restart it, the server does not accept even a single connection. This makes me suspect that cowboy has crashed. However, I see no crash reports in my server console. `netstat` shows a lot of sockets stuck in the CLOSE_WAIT state though.

This seems similar to #232 at first glance but I'm testing with a http server (no SSL). Also, the main concern for me is that the server is not accepting new connections after the load is reduced.

On the server side, I'm using cowboy 2.0 and Erlang 19 for my tests.

Here's the barebones version of my handler:
```
init(Req, State) ->
    {cowboy_websocket, Req, State}.

handle(Req, State) ->
    {ok, Req, State}.

websocket_handle(_Any, Req, State) ->
    {reply, {text, <<"Handle">>}, Req, State, hibernate}.
websocket_info(_Any, Req, State) ->
    {reply, {text, <<"Info">>}, Req, State, hibernate}.

terminate(_Reason, _Req, _State) ->
    ok.
```

And here's how I start the server:
```
Dispatch = cowboy_router:compile([
    {'_', [{"/", my_handler, []}]}
]),
Opts = #{
    env => #{dispatch => Dispatch}
},
{ok, _} = cowboy:start_clear(http,
    [{port, ?MY_PORT}, {num_acceptors, 100}],
    Opts
).
```

Can you help me figure out where the issue can be? Thanks!

**Comment by essen** [comment]
It doesn't seem like you change the value for `max_connections` so my guess is that you hit the max connection limit + the backlog which should be around 2000 together. Try with `{max_connections, infinity}` in the transport options.

**Comment by awaise267** [comment]
Yup, that fixed it!

So the `max_connections` limit does not apply to websocket connections but does apply to the connections waiting to be upgraded from HTTP to websocket? That's a tricky scenario to keep in mind - especially since I wasn't hitting the limit in other tests because my scripts were limiting the rate at which I was creating new connections. Maybe this deserves a special mention in the documentation.

Since `max_connections` does seem to be the culprit, do you have any clue about why we do not recover after I stop the client script? We should start accepting new connections after we fall below the default 1024 limit but that doesn't happen. I wonder if that has something to do with the connections stuck in `CLOSE_WAIT` state.

**Comment by essen** [comment]
Yes the Websocket code removes the process from the max_connections count after the upgrade.

I do not know why it did not recover. Try inspecting the listener's processes to see what's up.

**Comment by essen** [comment]
If you have more info please reopen. I have added a test about creating 3000 concurrent Websocket connections with a limit of 1024 and did not see any issue so far.
