### ISSUE TITLE
Specify TLS Version

### ISSUE THREAD

**Issue by alanj853** [ninenines/cowboy#1281]
Hi,

I am wondering if it is possible to specify a specific version of TLS (and/or SSL) to use with this http server? Or if not, can someone please tell me what version it is currently using.

Regards,

Alan

**Comment by essen** [comment]
You can specify it as part of the transport options. Almost all options from the `ssl` application is accepted there, including the version.

**Comment by alanj853** [comment]
Thank you for your reply. Just to back up on why I want this functionality, I have an elixir application that I want to use as a web server, and I want to configure the phoenix endpoint to only accept connections from clients using the specified version(s) of TLS. I have tried adding the "protocol_version" to the config.exs file, but it seems to be having no effect as I am still able to connect to my web server using:

`"openssl s_client -connect my_address -tls"`

Below is a snippet of my config.exs file where the protocol version is configured.

`
config :test_app, TestApp.Endpoint,
    url: [host: "localhost"],
    server: true,
    secret_key_base: "kS6HGfFs+u/STAA7iUb+G5JPLf2WgzAiok9fu5zC6XsnhQutXefOad1pxpKvSH2z",
    render_errors: [view: TestApp.ErrorView, accepts: ~w(html json)],
    pubsub: [name: TestApp.PubSub,
            adapter: Phoenix.PubSub.PG2],
    https: [
      port: 4443,
      otp_app: :test_app,
      keyfile:  Path.absname("#{system_dir}/ssl/ssl_key.pem"),
      certfile: Path.absname("#{system_dir}/ssl/ssl_cert.pem"),
      protocol_options: [
        protocol_version: :"tlsv1.2"
      ]
    ],
  debug_errors: true,
  code_reloader: false,
  check_origin: false

`

**Comment by alanj853** [comment]
From further reading I found that in order to specify the tls version, one must add the "versions" key to the key word list, inside of the "https" key. For example:
`
config :test_app, TestApp.Endpoint,
url: [host: "localhost"],
server: true,
secret_key_base: "kS6HGfFs+u/STAA7iUb+G5JPLf2WgzAiok9fu5zC6XsnhQutXefOad1pxpKvSH2z",
render_errors: [view: TestApp.ErrorView, accepts: ~w(html json)],
pubsub: [name: TestApp.PubSub,
adapter: Phoenix.PubSub.PG2],
https: [
port: 4443,
otp_app: :test_app,
keyfile: Path.absname("#{system_dir}/ssl/ssl_key.pem"),
certfile: Path.absname("#{system_dir}/ssl/ssl_cert.pem"),
versions: [:"tlsv1.1", :"tlsv1.2"]
],
debug_errors: true,
code_reloader: false,
check_origin: false
`

where the above specifies only to accept clients using tls version 1.1 or 1.2

**Comment by essen** [comment]
Right I don't know Elixir but it sounds like the right thing. Cheers!
