### ISSUE TITLE
Sending informational responses results in a protocol error with H2 clients.

### ISSUE THREAD

**Issue by idyll** [ninenines/cowboy#1283]
I can't get `inform/3` or `inform/2` to work.
I've updated my sample server code to send back an early hint before it sends back the response.

https://github.com/idyll/safari_test_erlang

If you access this in Chrome you'll see: `ERR_SPDY_PROTOCOL_ERROR`

For curl you get: `curl: (92) HTTP/2 stream 1 was closed cleanly, but before getting  all response header fields, teated as error`

It looks like there's an error when sending the informational response around the time the header is sent?

**Comment by essen** [comment]
I'll take a look tomorrow, thanks. I probably missed something in the spec.

**Comment by idyll** [comment]
I could totally be wrong, but based on what I saw it looked like the stream was being closed after sending the inform, or maybe during the inform, before the rest of the responses could be sent.

**Comment by essen** [comment]
Looks like all that's needed is a:

``` diff
diff --git a/src/cowboy_http2.erl b/src/cowboy_http2.erl
index 7f5d738..0f9cd36 100644
--- a/src/cowboy_http2.erl
+++ b/src/cowboy_http2.erl
@@ -533,7 +545,7 @@ commands(State, Stream, [{error_response, _, _, _}|Tail]) ->
    commands(State, Stream, Tail);
 %% Send an informational response.
 commands(State0, Stream=#stream{local=idle}, [{inform, StatusCode, Headers}|Tail]) ->
-   State = send_headers(State0, Stream, StatusCode, Headers, fin),
+   State = send_headers(State0, Stream, StatusCode, Headers, nofin),
    commands(State, Stream, Tail);
 %% Send response headers.
 %%
```

But I have to write a test and don't have time now.

**Comment by idyll** [comment]
I will try this in a fork and confirm it resolves things. :)

Thanks, as always.

**Comment by idyll** [comment]
It needs a new release of cowlib, but it works. :)

**Comment by essen** [comment]
Of cowlib?

**Comment by idyll** [comment]
Without the cowlib update cowboy master complains about missing `enable_connect_protocol`

**Comment by essen** [comment]
You probably just need to update your cowlib. Erlang.mk won't do it for you. Cowboy currently depends on Cowlib master.

**Comment by essen** [comment]
I've pushed the fix. Thanks!
