### ISSUE TITLE
The most efficient way of sending response, big concatenated binary or deep iolist?

### ISSUE THREAD

**Issue by DOBRO** [ninenines/cowboy#1285]
Hi, 

I'm trying to figure out what is the best way of sending response using cowboy_req:reply.
Say, we have two variants, big concatenated binary and deep iolist.

Eg. 1:

init(Req0, State) ->
   BigBinBody = <<BigBin1/binary, BigBin2/binary, ...., BigBinN/binary>>,
   Req = cowboy_req:reply(200, #{<<"content-type">> => <<"text/html">>}, BigBinBody, Req0),
   {ok, Req, State}.

Eg 2:

init(Req0, State) ->
   DeepIoList = ["Very", ["Deep", ["IoList"]]],
   Req = cowboy_req:reply(200, #{<<"content-type">> => <<"text/html">>}, DeepIoList, Req0),
   {ok, Req, State}.

Which one of them is more efficient considering they are of the same iolist_size?

**Comment by essen** [comment]
Almost always iolists are better. If you can build the binary with an append loop though it's possible it'll be better (vs having to lists:reverse) but it won't be a big difference.

**Comment by DOBRO** [comment]
Thank you for the answer!

Does this line send the response body directly to the socket?
https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L752

**Comment by essen** [comment]
No it's sent to the connection process which may do some additional operations on it (like compression if configured to do so, or splitting it in the case of HTTP/2 when the window size is too small) before sending.

**Comment by DOBRO** [comment]
So, If I deal with HTTP/1.1 and need no additional operations to be done with body, could it be better to send body between processes as binary instead of iolist (because it's more compact structure)?

**Comment by essen** [comment]
It *could* but it generally *doesn't*. There are cases where an iolist will be worse because it needs to be copied while a large binary isn't. But as a general rule it shouldn't be something to consider, just use whichever is the easiest to manipulate.

**Comment by DOBRO** [comment]
OK, understood.
BTW, if I'm sure that the response body doesn't need extra operations to be done with it, does it make sense to add an option to the source of cowboy_req:reply which would allow to send body directly to the socket avoiding sending message between processes?

**Comment by essen** [comment]
No. There is a level of indirection because the different protocols have different requirements, for example HTTP/2 must be this body into frames and possibly split it in many parts.

**Comment by DOBRO** [comment]
What if HTTP/1.1 only, no compression and no other intermediate operations needed?

**Comment by essen** [comment]
I'm not going to do a complex solution for a minor optimization. If that's really something you need you can take Cowboy 1.x, it's not supported anymore but at least it'll be sent to the socket immediately. It wouldn't make much sense though because if you're concerned about efficiency you really want HTTP/2 instead of HTTP/1.1.

**Comment by DOBRO** [comment]
It's your decision, of course.
I'm using Cowboy as a backend behind nginx. So there is no benefit of HTTP/2

**Comment by essen** [comment]
Still, you'd get better benefits from enabling compression than doing what you were saying. The copying of most iolists is not really a concern, it'll happen faster than the underlying IO.
