### ISSUE TITLE
Cowboy 2.3.0, **(exit) :undef

### ISSUE THREAD

**Issue by MassiveFermion** [ninenines/cowboy#1288]
I'm just beginning to learn elixir and so I'm practicing with some simple codes I find on the internet. But when I use Cowboy, I get this weird error that I can find nothing about on the internet.

> 21:09:03.194 [error] Ranch protocol :error (:cowboy_protocol) of listener Example.Router.HTTP terminated
> ** (exit) :undef

I should mention that this happens when I use cowboy 2.3.0. cowboy 1.1.2 works fine.
The code I'm running is exactly the one given [here](https://elixirschool.com/en/lessons/specifics/plug/).

**Comment by essen** [comment]
`cowboy_protocol` only exists in Cowboy 1.

**Comment by MassiveFermion** [comment]
oh...thanks
So ranch tries to call cowboy_protocol and it can't find it, because it simply doesn't exist. So...I can't use cowboy 2 because ranch is not up to speed with it?

**Comment by essen** [comment]
Ranch has no knowledge of Cowboy, if it can't find `cowboy_protocol` it must be because whatever you are doing is configuring it to use `cowboy_protocol`.

If you call `cowboy:start_clear` or `cowboy:start_tls` directly then the correct protocol modules will be used.

**Comment by Gazler** [comment]
The master version of plug will raise when you use an incompatible adapter and cowboy version. This has not been released yet though.

To make the example you linked work with Cowboy 2, change:

```
    children = [
      Plug.Adapters.Cowboy.child_spec(:http, Example.HelloWorldPlug, [], port: 8080)
    ]
```

To:

```
children = [
  {Plug.Adapters.Cowboy2, scheme: :http, plug:  Example.HelloWorldPlug, options: [port: 8080]}
]
```

**Comment by MassiveFermion** [comment]
That worked, thanks.

**Comment by essen** [comment]
Thanks!
