### ISSUE TITLE
Adblocker causes errors

### ISSUE THREAD

**Issue by Spoowy** [ninenines/cowboy#1301]
Hello everyone,

with every request of users from adblockers I get this, and eventually sometime the server crashes(and it may be related to this):

<img width="1665" alt="bildschirmfoto 2018-06-27 um 10 20 22" src="https://user-images.githubusercontent.com/6298122/41961919-0e157ea6-79f4-11e8-98e1-5cec2e587750.png">

(I was not able to copy the text)

An adblocker - for some reason - calls this file: blob:https://domain.com/850e7edc-fbe6-452c-a05d-f07d85bc5a81

Can someone see whether this output and the blob request from the adblocker could be inter-linked?

Cheers,
Erwin

**Comment by essen** [comment]
Please upgrade to Cowboy 2 to see if there is still an issue.
