### ISSUE TITLE
cowboy_handler.erl compile error with erl 21.0.1

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1302]
I'm on erl 20.3 and thought I'd try 21.0.1 and get the following error when running make:

ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_children.erl cowboy_clear.erl cowboy_clock.erl cowboy_compress_h.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http.erl cowboy_http2.erl cowboy_iolists.erl cowboy_loop.erl cowboy_metrics_h.erl cowboy_middleware.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_static.erl cowboy_stream.erl cowboy_stream_h.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_tracer_h.erl cowboy_websocket.erl
compile: warnings being treated as errors
src/cowboy_handler.erl:47: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
make[2]: *** [ebin/cowboy.app] Error 1

I was using cowboy 2.2.2, so I tried 2.4.0 and got the same error.  Staying with cowboy 2.4.0 and then going back to 20.3 and running make, it compiles fine.  Is there something I can do to get erl 21.0.1 to work (other than change the compile time warning treated as error option)?

**Comment by comptekki** [comment]
I removed -Werror from erlang.mk in deps/cowboy and also had to update relx (rebar3).  Now it runs.

**Comment by essen** [comment]
When running make it's normal as the patch was added after 20.4. But when building as a dependency you shouldn't have this particular error at least since warning_as_errors is disabled in that case.

**Comment by comptekki** [comment]
I updated to your latest erlang.mk and that seems to have fixed it.  I now get erlexec permission denied error when trying to run the release.  It looks like some of the files in _rel/projects_name/erts-10.0.1/bin don't have +x set on them to be executable.  I'll have to poke around and see if that is a bug mentioned somewhere for rebar3.  Thanks.

**Comment by essen** [comment]
`rm -rf .erlang.mk` and try again.
