### ISSUE TITLE
Can't find documentation for running tests.

### ISSUE THREAD

**Issue by CrowdHailer** [ninenines/cowboy#1305]
I am trying to run the tests for cowboy and can't find documentation on how to do.

I am only trying to work out how to run erlang tests. specifically this one https://github.com/ninenines/cowboy/blob/1a6407d8a85100fd11e720b94bf5b0b1e089b884/test/rfc7230_SUITE.erl#L140

Would it be possible to add a Run tests section to the readme. I would happily write it once I know how.

**Comment by essen** [comment]
`make ct-rfc7230 t=http:timeout_before_request_line` in case you didn't figure it out. Cheers.

**Comment by CrowdHailer** [comment]
Thanks for the clarification.
