### ISSUE TITLE
Allow the user to trigger graceful shutdown for a connection

### ISSUE THREAD

**Issue by jimdigriz** [ninenines/cowboy#1312]
The documentation explains that for loop handlers you should use [`connection: close`](https://ninenines.eu/docs/en/cowboy/2.4/guide/loop_handlers/#_cleaning_up) but for HTTP/1 this causes the client side to complain (for example with cURL):
```
http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [connection], value: [close]
```

Two ways I can think of addressing this:
 * a documentation fix
 * for http/2 streams, cowboy removes/ignores any `connection` headers

**Comment by essen** [comment]
The documentation is wrong.

That being said, Cowboy should probably remove connection headers in responses regardless of protocol. Same as for transfer-encoding.

**Comment by essen** [comment]
Why do you want to force close the connection after that request? What I am saying is that you should not be able to do that and just let Cowboy decides.

**Comment by essen** [comment]
Ah well it's probably just a remnant of Cowboy 1.x, I'll look it up. It's not necessary.

**Comment by jimdigriz** [comment]
Though, actually for load-balancer health checks `connection: close` is useful so then externally running out of file descriptors is presented :)

**Comment by jimdigriz** [comment]
Maybe for HTTP/2 just interpret the `connection: close` as an instruction to send a [GOAWAY|https://tools.ietf.org/html/rfc7540#section-6.8] frame; though maybe an actual method on `cowboy_req:<something>/1` would be preferred?

For me when I send `connection: close` I am indicating to the client I want them to free up the file descriptor as there is nothing more for them to see/request (or I want to force a fresh TCP connection).  Not sure if others interpret/think the same way though :)

**Comment by essen** [comment]
For h2 it definitely should just be removed, a stream can't decide the fate of the whole connection, they don't own it.

For h1 I'm not sure I understand, as far as I can tell once the response ends Cowboy will either close the connection (when chunked was not used and the stream process ended) or keep it open for further requests. If you have a load balancer in front then that means the load balancer can continue using the connection for more requests.

Worth noting also that for long running requests Cowboy will stop the stream and close the connection on its own once the `idle_timeout` triggers too, since h1 has no ping mechanism.

Can you give an example scenario where closing the connection causes problems, indicating step by step what the various components do?

**Comment by jimdigriz** [comment]
[Graceful shutdowns](https://github.com/ninenines/cowboy/issues/915) on AWS/GCP, when I shutdown my applications I have a `prep_stop/1` that:

 * signals to the load-balancer health checks that the node is no longer healthly (the health check now returns an http status code of 503 rather than 200)
 * wait X seconds (where X is <period-of-check>*<number-to-mark-fail> + <period-of-check> + 1) to give time for the health check to flag the server as dead
 * call `ranch:set_max_connections(..., 0)` on all my listeners
 * for each listener poll for `ranch:procs(..., connections) == []`

The problem is AWS uses keep-alive on its health checks so the poll for open connections to fall to zero takes either a really long time or never completes.

If I used `connection: close` though, it forces the health check to reconnect which will fail after I drop max connections to zero.  I also want to make the test more thorough and force a full TCP handshake so that it also exercises if there are still file descriptors avaliable.

**Comment by essen** [comment]
Yeah. In Ranch 1.6 we have added suspend/resume of listeners and a function wait_for_connections. But that's only half the work. The other half is asking connections to shut down gracefully. Whatever the solution for that will be it can't be via the connection header which is specific to h1.

Before I start thinking too much into solutions can you clarify whether you apply connection:close to all responses or just to stream responses, and if it's the latter then why does it make a difference when you apply it only to these and not to other connections?

**Comment by jimdigriz** [comment]
I apply `connection: close` always on the health check probe and only to the existing requests when my application shutdowns (or marks its-self unhealthly) via a stream handler that slips in `connection: close`.

**Comment by essen** [comment]
Makes sense.

I can see two sides to this problem:

* We need a way to signal all open connections to shutdown gracefully within the `shutdown` timeout. Currently `shutdown` is not respected and if you stop the listener connections are brutally killed. Connection processes would apply the connection:close or start shutting down h2 connections (perhaps reject incoming requests, wait a little for existing requests to finish and then send GOAWAY).

* We need a way to signal that a request ought to be the last on a connection outside of the normal Cowboy rules. Essentially initiating the shutdown for a single connection. If it's only necessary for short-lived requests then I suppose a simple `exit(ConnPid, shutdown)` before replying would be enough (once shutdown is implemented) but I'm still confused about your health check probe. Your initial post has connection:close set for a text/event-stream process, is this the health check probe? Is it long-lived?

**Comment by jimdigriz** [comment]
Hah, ignore the initial post example, that was just me providing an example of how verbose it is to handle `connection:close`.  I can see why it is confusing.

Once I found out using `connection: close` on cowboy2 for loop handlers is pointless I removed it, but it got me thinking about how I handled graceful shutdowns.  So now, for me, working on a different chunk of code.

**Comment by essen** [comment]
OK then I think my suggestion of using shutdown on the connection process would work. It'd look a bit like this:

``` erlang
init(Req0=#{pid := Pid}, State) ->
    exit(Pid, shutdown),
    Req = cowboy_req:reply(200, Req0),
    ...
```

But of course the shutdown mechanism has to be implemented first.

**Comment by essen** [comment]
Graceful shutdown has been implemented for HTTP/2, but there's currently no interface for the user to trigger it.

**Comment by essen** [comment]
Closing in favor of https://github.com/ninenines/cowboy/issues/915 please subscribe to that ticket to continue this.
