### ISSUE TITLE
Multiple headers with the same name.

### ISSUE THREAD

**Issue by jimdigriz** [ninenines/cowboy#1313]
In this particular instance I have been looking at [`Server-Timing`](https://www.w3.org/TR/server-timing/), though there are other instances such as `Via`, `Forwarded` and `Link`, where it is desirable to include multiple headers with the same name in the response; especially if you want to proxy through a response with the HTTP headers left intact.

As cowboy2 uses a map internally for its headers, and then calls `maps:to_list()` which punts into `cow_http:headers()`, this would not be possible to do.

The only option I can think of is to amend the internal map to be `#{ Header => [ Value1, Value2, ... ], ... }`; the API of course would still accept `#{ Header => Value }`.

Thoughts?  Patches welcome?

**Comment by essen** [comment]
Server-Timing looks like a comma list, so the same rules apply as other headers and a list of headers is equivalent as a single header with the items separated by commas.

Via, Forwarded and Link are in the same boat.

The only header which does not respect this that I am aware of (and the only one mentioned in the RFCs) is Set-Cookie and Cowboy already special case it.

There's no rules against combining headers of the same name for proxies. But maybe you have a specific need I do not understand.

**Comment by jimdigriz** [comment]
Use case, I'm lazy =)

I'll write a wrapper to append headers in my application, thanks.

**Comment by essen** [comment]
I was thinking of accepting lists in the cowboy_req:reply and related functions to let Cowboy do this itself.
