### ISSUE TITLE
compress issue

### ISSUE THREAD

**Issue by lemon-li** [ninenines/cowboy#1314]
if i set 'opts#compress=>true' .. 

Which data type should I return to client data?
 text or binary ?

websocket_handle({text, Msg}, Req, State) ->
{reply, {text, Msg}, Req, State}; 
%% {reply, {binary, Msg}, Req, State}

**Comment by essen** [comment]
Doesn't matter, all payloads get compressed.

**Comment by lemon-li** [comment]
@essen thanks a lot.
