### ISSUE TITLE
Proposal: additional loop_handler

### ISSUE THREAD

**Issue by ostinelli** [ninenines/cowboy#1318]
Hello all,
In some of the protocols I work with HTTP is used only to provide an authentication & handshake request format. Simply put, after the initial HTTP authentication request is made by a client and it is successful, the socket is used as a bidirectional transport between clients & the server (and we exit the HTTP realm). If the request is _not_ successful, then the server replies still with the HTTP protocol.

We currently achieve this with Cowboy v1 using a custom sub-protocol. However, due to all the changes in Cowboy v2 AFAIK this is currently not feasible. I would like to ask if we could have a proper interface for this use-case. My suggestion is a new `loop_handler` that basically is also set to receive the raw data from the socket.

For instance the `init/2` of the handler could be something similar to:

```erlang
init(Req, State) ->
    {cowboy_socket_loop, Req, State}.
```
or hibernate:
```erlang
init(Req, State) ->
    {cowboy_socket_loop, Req, State, hibernate}.
```
And the loop could look something like:

```erlang
%% for data incoming from the socket
handle_socket(Data, Req, State) ->
    io:format("Received data from socket: ~p~n", [Data]),
    {ok, Req, State, hibernate}.

%% for erlang messages coming to the loop process
handle_info({send_to_client, Data}, Req, State) ->
    cowboy_req:send_raw(Data, Req),
    {ok, Req, State};
handle_info(_Msg, Req, State) ->
    {ok, Req, State, hibernate}.
```
The usual can then apply:
```erlang
terminate(_Reason, _Req, _State) ->
    ok.
```

Any opinions?

**Comment by essen** [comment]
If you do it at the request process level then it has to work and make sense for HTTP/2 and future HTTP protocols too. It has no chance of being included otherwise.

If you could summarize what the protocol looks like that would help, I'm not sure I fully understood last time. Still I think you probably just want `switch_protocol` and do things more or less like you did before. The 101 was a problem for you but I believe you can silence it because it's not sent directly, it first goes through stream handlers and therefore you can write a stream handler that returns an empty list of commands when it receives the 101 inform message.

**Comment by ostinelli** [comment]
More or less like this.

1. Client sends authentication request:

```
POST /connect
Host: www.nowhere123.com
Date: Tue, 14 Aug 2018 14:56:53 GMT
Authorization: Token c3499c2729730a7f807efb8676a92dcb6f8a3f8f
```

2a. If unsuccessful, server responds:

```
HTTP/1.1 401 UNAUTHORIZED
Date: Tue, 14 Aug 2018 14:56:54 GMT
Content-Length: 22
Connection: close
Content-Type: application/json
  
{ "error": "Invalid credentials" }
```

2b. if successful, server responds:

```
HTTP/1.1 200 OK
Date: Tue, 14 Aug 2018 14:56:54 GMT
Content-Length: 16
Transfer-Encoding: chunked
Content-Type: application/json
  
{ "time": 1534252609 }
```

3. From then on, client and server can both send messages to each other in the raw socket. To simplify, we often use the Chunked transfer encoding so the messages will look something like:

```
7\r\n
Example\r\n
```

And when it's time to close the connection:

```
0\r\n
\r\n
```

**Comment by essen** [comment]
The client doesn't send `Transfer-Encoding: chunked`? That alone would prevent it to work outside a custom protocol module.

The way I see it, you can have a stream handler to perform the auth, return switch_protocol if necessary, and then when it receives the `{inform, 101, Headers}` message after that silence it by returning `[]`. In any other case the stream handler would just defer to the next as normal. Then continue using the sub protocol you had before.

**Comment by ostinelli** [comment]
Thank you Loïc for your response. Not sure if I understood all the internals here but will dig in and do this instead then.

Thanks,
r.

**Comment by ostinelli** [comment]
Ok thank you. Will try this out.
