### ISSUE TITLE
cowboy_req:body_qs/1 returns empty list

### ISSUE THREAD

**Issue by vimal7370** [ninenines/cowboy#1321]
On Cowboy 1.1.2, when I run the below block of code, I see that `Body` has the correct url encoded post data, but `KeyValues` returns [].
```erlang
from_post(Req, State) -> % POST handler
	{ok, Body, Req2} = cowboy_req:body(Req),
	{ok, KeyValues, Req3} = cowboy_req:body_qs(Req2),
	io:format("Post Body:~n"),
	io:format("~p~n", [Body]),
	io:format("Body to Kv Pair:~n"),
	io:format("~p~n", [KeyValues]),
```
`cow_qs:parse_qs(Body)` stills gives me the result I am looking for, but I wonder why body_qs/1 does not return the correct value.

**Comment by essen** [comment]
Because you read the body in cowboy_req:body and therefore cowboy_req:body_qs has no more body to read and parse. Just call body_qs directly.
