### ISSUE TITLE
cowboy_loop timeout 

### ISSUE THREAD

**Issue by shamis** [ninenines/cowboy#1322]
From the documentation 
![image](https://user-images.githubusercontent.com/3499591/45822941-d8c6a180-bcec-11e8-84d0-8524a244455b.png)

but `cowboy_loop:upgrade/5` https://github.com/ninenines/cowboy/blob/master/src/cowboy_loop.erl#L50-L54 does not spport a tuple

**Comment by essen** [comment]
No such thing as a loop timeout in 2.x. This is a remnant of the 1.x documentation. I've removed the mention in my local copy, it'll be pushed later on. Thanks!
