### ISSUE TITLE
start_tls doesn't support Ranch 1.6's new map-style TransOpts

### ISSUE THREAD

**Issue by JayH5** [ninenines/cowboy#1324]
The `ranch:start_tls` function takes the `TransOpts0` argument of type `ranch:opts()`. As of Ranch 1.6, this type should be a map instead of a list as the list format is deprecated (when specifying both Ranch and socket options).

Cowboy assumes the `TransOpts0` format is a list when it adds the ALPN/NPN options to the options in `ranch:start_tls`:
https://github.com/ninenines/cowboy/blob/06a3a93de0bb6bdd0759f658b7826f38a50bb8a6/src/cowboy.erl#L52-L59
This makes it impossible to specify `TransOpts0` as a map.

Cowboy then passes the TransOpts to `ranch:normalize_opts` which will log a deprecation warning if both Ranch and socket options are specified (and also convert the TransOpts into a map).

This should only impact (as of writing) the unreleased version 2.5.0 of Cowboy.

**Comment by essen** [comment]
Good point. Wondering why the warning isn't printed when I run the Cowboy tests...

**Comment by essen** [comment]
Because the tests don't mix socket and Ranch options.

**Comment by essen** [comment]
Done. Thanks! If the current build looks good I will release Cowboy 2.5 in the afternoon.

**Comment by JayH5** [comment]
Thank you 🙏
