### ISSUE TITLE
Bad type spec in cowboy_req

### ISSUE THREAD

**Issue by hommeabeil** [ninenines/cowboy#1327]
The type specification in the module cowboy_req is not consistent.  [Here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L537), the function cowboy_req:read_part/1 return cow_multipart:hearders() which is defined as [{binary(), binary()}]. The next overload, [here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L542) defined the return as a map. When using the function, the return is indeed a map, so maybe the fix should be to change the type spec in cowlib.

When running dialyzer in other project with cowlib included, the function cowboy_req:read_part/1 cause type checking failure at every call.

**Comment by essen** [comment]
Cowboy is the one converting from list to map, so Cowboy should be fixed.

**Comment by essen** [comment]
I've fixed this on my local copy. Will push soon. Thanks!
