### ISSUE TITLE
`headers_to_list` in cowboy_http can`t process `cowboy:http_headers` correctly

### ISSUE THREAD

**Issue by DavidAlphaFox** [ninenines/cowboy#1329]
I use `cowboy 2.5.0` in my project.
When I put `<<"set-cookie">>` into  `cowboy:http_headers` with a binary cookie, it will crash.
The code  in `cowboy_http.erl`  on line 1115 assumes the `<<"set-cookie">>`  which is always a list.
   
     Headers1 ++ [{<<"set-cookie">>, Value} || Value <- SetCookies];

**Comment by essen** [comment]
Yes because it must be set exclusively by `cowboy_req:set_resp_cookie`. The reason for that is that the set-cookie header does not conform to the spec and it is not possible to combine multiple of them into one, so Cowboy has to handle it specially.

**Comment by DavidAlphaFox** [comment]
Yes, `<<"set-cookie">>` should not have multiple items. 
I think `Cowboy` should keep the ability of processing an assembled binary cookie, so I can  pass the headers  received from `gun` to `Cowboy` directly.
