### ISSUE TITLE
metrics stream handler doesn't understand `error_response` command

### ISSUE THREAD

**Issue by velimir0xff** [ninenines/cowboy#1330]
When cowboy env has 2 stream handlers configured (`[cowboy_metrics_h, cowboy_stream_h]`) and unexpected error happens in one of request handlers, `cowboy_http` [receives](https://github.com/ninenines/cowboy/blob/c998673eb009da2ea4dc0e6ef0332534cf679cc4/src/cowboy_http.erl#L220) an 'EXIT' message, which is [translated](https://github.com/ninenines/cowboy/blob/c998673eb009da2ea4dc0e6ef0332534cf679cc4/src/cowboy_stream_h.erl#L147-L162) into the following chain of commands by `cowboy_stream_h` stream handler (example):

``` erlang 
[{error_response,500,#{<<"content-length">> => <<"0">>},<<>>},
 {log,error,
     "Ranch listener ~p, connection process ~p, stream ~p had its request process ~p exit with reason ~999999p and stacktrace ~999999p~n",
     [bower_app,<0.366.0>,1,<0.367.0>,
      {badmatch,2},
      [<STACKTRACE>]]},
 {internal_error,
     {'EXIT',<0.367.0>,
         {{badmatch,2},
          [<STACKTRACE>]}},
     'Stream process crashed.'}]
```

`cowboy_metrics_h` [does not understand](https://github.com/ninenines/cowboy/blob/c998673eb009da2ea4dc0e6ef0332534cf679cc4/src/cowboy_metrics_h.erl#L196-L245) `error_respone` and does not update state with the response information as it [does](https://github.com/ninenines/cowboy/blob/c998673eb009da2ea4dc0e6ef0332534cf679cc4/src/cowboy_metrics_h.erl#L210) for `response` command.

This results in undefined information about response on terminate step.

**Comment by essen** [comment]
I'm afraid you're right. Nice find, thanks! I'll see if I can fix it next week.

**Comment by essen** [comment]
Fixed locally, push soon.
