### ISSUE TITLE
cowboy_req.set_resp_cookie docs missing info about opts

### ISSUE THREAD

**Issue by benbro** [ninenines/cowboy#1334]
cowboy_req.set_resp_cookie [docs](https://ninenines.eu/docs/en/cowboy/2.0/manual/cowboy_req.set_resp_cookie/) is missing info about cookie opts.
Examples do cover the options but it'll probably be better to have a list of all options with a description.

if secure => true also implies http_onlly => true it will be nice to indicate it.

**Comment by benbro** [comment]
Thanks

**Comment by essen** [comment]
I will see if I can start documenting Cowlib tomorrow.

**Comment by essen** [comment]
The `cow_cookie` manual was added to Cowlib: https://github.com/ninenines/cowlib/commit/bd32d879e151ba6fa1732b4eee6cac064846e9cc

All that's needed is add this documentation to the website now. Links between projects don't work at the moment on the website so I won't link it yet (there's a ticket about improving that already).

**Comment by essen** [comment]
https://ninenines.eu/docs/en/cowlib/2.7/manual/

Closing, thanks!

**Comment by benbro** [comment]
Thanks

**Comment by benbro** [comment]
Maybe Cowboy [set_resp_cookie](https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_req.set_resp_cookie/) docs  can link to [cow_cookie](https://ninenines.eu/docs/en/cowlib/2.7/manual/cow_cookie/) docs?
