### ISSUE TITLE
Returning custom status code from GET requests triggers error:function_clause (has_sent_resp) even if halt is returned

### ISSUE THREAD

**Issue by aufziehvogel** [ninenines/cowboy#1337]
## Summary

There might be an issue with handling the `halt` command in `GET` requests in REST applications (or I am using it wrong).

When I send out a custom status code and response on a GET request with `cowboy_req:reply` and then return `{halt, Resp, State}` to tell cowboy to stop further execution, I get:

1. The status code and response data correctly displayed in the browser
2. An error `function_clause` in the console which seems to come from a check whether another response has already been sent out

Thus, I assume that cowboy does not handle my `halt` command and instead tries to send a second response.

I do not see the same behaviour with `POST` requests. `POST` requests work fine for me.

## Description

To return a custom status code in a cowboy REST application, you [should normally execute][1]

    Resp = cowboy_req:set_resp_body(<<"HELLO POST\n">>, Req),
    {ok, Resp3} = cowboy_req:reply(201, Resp),
    {halt, Resp3, State}.

(according to my knowledge this has changed to `Resp3 = cowboy_req:reply(201, Resp)` in cowboy 2)

However, I cannot get this method to work 100% correctly for `GET` requests. It does return the response as requested, but the process crashes with the error `exception error: function_clause`

Let's take this example:

    -module(debug_handler).
    -export([
        init/2,
        allowed_methods/2,
        content_types_accepted/2,
        content_types_provided/2,
        debug_from_json/2,
        debug_to_json/2
    ]).

    init(Req, Opts) ->
        {cowboy_rest, Req, Opts}.

    content_types_accepted(Req, State) ->
        {[
            {<<"application/json">>, debug_from_json}
        ], Req, State}.

    content_types_provided(Req, State) ->
        {[
            {<<"application/json">>, debug_to_json}
        ], Req, State}.

    allowed_methods(Req, State) ->
        Methods = [<<"GET">>, <<"POST">>],
        {Methods, Req, State}.

    debug_from_json(Req, State) ->
        same_code(Req, State).

    debug_to_json(Req, State) ->
        same_code(Req, State).

    same_code(Req, State) ->
        Resp = cowboy_req:set_resp_body(<<"{\"test\": \"test-value\"}">>, Req),
        Resp2 = cowboy_req:reply(202, Resp),
        {halt, Resp2, State}.

This will provide endpoints for both GET and POST doing the same. Both return the JSON value `{"test": "test-value"}` with a status code of 202. I selected 202 instead of 200 to make sure that cowboy actually returns my status code and not a default 200 status code from somewhere else.

We can now query this endpoint via POST

```bash
$ curl -v -XPOST -H'Content-Type: application/json' http://127.0.0.1:8080/debug

[...]
< HTTP/1.1 202 Accepted
< content-length: 22
< content-type: application/json
< date: Sun, 11 Nov 2018 10:13:12 GMT
< server: Cowboy
< 
* Connection #0 to host 127.0.0.1 left intact
{"test": "test-value"}
```

And it gives no error message in the running application window.

If we, however, try to use the endpoint via `GET`, the following happens:

```bash
$ curl -v -XGET http://127.0.0.1:8080/debug

[...]
< HTTP/1.1 202 Accepted
< content-length: 22
< content-type: application/json
< date: Sun, 11 Nov 2018 10:20:03 GMT
< server: Cowboy
< 
* Connection #0 to host 127.0.0.1 left intact
{"test": "test-value"}
```

But in the running erlang window, I get the following error:

```
=CRASH REPORT==== 11-Nov-2018::11:19:48.642978 ===
  crasher:
    initial call: cowboy_stream_h:request_process/3
    pid: <0.270.0>
    registered_name: []
    exception error: function_clause
      in function  cowboy_req:reply/4 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_req.erl, line 746)
      in call from cowboy_rest:respond/3 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_rest.erl, line 1208)
      in call from cowboy_rest:set_resp_body/2 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_rest.erl, line 1081) 
      in call from cowboy_rest:upgrade/4 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_rest.erl, line 264)
      in call from cowboy_stream_h:execute/3 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_stream_h.erl, line 293)
      in call from cowboy_stream_h:request_process/3 (/home/brati/Programming/molehill/_build/default/lib/cowboy/src/cowboy_stream_h.erl, line 271)
```

On a side note: With curl this does only happen during the first request, even if I use `-H 'Cache-Control: no-cache'`, but I still believe there is some caching happening with curl. From Firefox it is reproducible on every single request, not only on the first one.

I am using cowboy 2.5.0, where this line seems to be [a check whether the response has already been sent](https://github.com/ninenines/cowboy/blob/2.5.0/src/cowboy_req.erl#L746). Since my response actually gets sent out with the right status code, I assume that there is an issue with handling the `halt` command in `GET` requests.

  [1]: https://stackoverflow.com/questions/17030849/how-to-set-status-code-in-rest-post-in-cowboy

**Comment by essen** [comment]
`halt` has been renamed to `stop` in Cowboy 2.0.

**Comment by aufziehvogel** [comment]
Eh sorry, that was an easy one. Now that you said it, I also found the [migration guidelines from 1 to 2](https://ninenines.eu/docs/en/cowboy/2.1/guide/migrating_from_1.0/). Should help with a lot of the examples from Google.

Thanks!

**Comment by aufziehvogel** [comment]
btw, tested it with `stop` and works.
