### ISSUE TITLE
Forcing HTTP/1.0 behaviour

### ISSUE THREAD

**Issue by adrianroe** [ninenines/cowboy#1338]
We have client devices making HTTP/1.1 requests to us that don't actually support chunked responses.  I was hoping to be able to force a HTTP/1.0 response by patching the version in the request as part of a middleware, but unfortunately that is too late in the chain.

The decision is made in cowboy_http:commands (line 979) and (as far as I can tell) is before there is any ability to patch the incoming request.

Needless to say, it's the client device at fault, but I'm not even sure how to patch this.  I'm in a position where I could have dedicated URLs for the misbehaving clients, but again I'm not sure that gives me any options to force a streamed (rather than chunked) response.

Any suggestions?  Happy to make a pull request if you can see a clean way forward.

**Comment by essen** [comment]
Yes I remember the problem.

Most recent Cowboy will stream responses without using chunked transfer-encoding if the content-length is set in the response. I do not remember if that was enough for your case though, or if you want a stream + close connection for all responses.

**Comment by essen** [comment]
Note that the spec requires us to respond with HTTP/1.1 regardless of what the client is and how we send the response, that's why it's no longer possible to override it.

Just let me know if the content-length workaround is good enough. If it's not, then I'll add an option to force disable chunked. I recently added a way to override options on a per request basis so I could let you enable it per request as well if that would work better for you (for example you could do that for the badly behaving clients and leave chunked for others, if you can detect them).

**Comment by adrianroe** [comment]
Unfortunately the content-length workaround isn’t an option for us (we don’t know how much data we’ll send). Some sort of mechanism to enable / disable it on a per request basis would be perfect!

Thanks

Adrian

**Comment by essen** [comment]
OK. I'll see if I can squeeze it into 2.6 which is supposed to be released Monday. No promises though.

**Comment by essen** [comment]
Something like this probably. Still need to write tests though:

``` patch
diff --git a/src/cowboy_http.erl b/src/cowboy_http.erl
index 17c19ed..15a08db 100644
--- a/src/cowboy_http.erl
+++ b/src/cowboy_http.erl
@@ -25,6 +25,7 @@
 -export([system_code_change/4]).
 
 -type opts() :: #{
+	chunked => boolean(),
 	compress_buffering => boolean(),
 	compress_threshold => non_neg_integer(),
 	connection_type => worker | supervisor,
@@ -963,21 +964,28 @@ commands(State0=#state{socket=Socket, transport=Transport, out_state=wait, strea
 	end,
 	commands(State, StreamID, Tail);
 %% Send response headers and initiate chunked encoding or streaming.
-commands(State0=#state{socket=Socket, transport=Transport, streams=Streams0, out_state=OutState},
+commands(State0=#state{socket=Socket, transport=Transport,
+		opts=Opts, overriden_opts=Override, streams=Streams0, out_state=OutState},
 		StreamID, [{headers, StatusCode, Headers0}|Tail]) ->
 	%% @todo Same as above (about the last stream in the list).
 	Stream = #stream{version=Version} = lists:keyfind(StreamID, #stream.id, Streams0),
 	Status = cow_http:status_to_integer(StatusCode),
 	ContentLength = maps:get(<<"content-length">>, Headers0, undefined),
+	%% Chunked transfer-encoding can be disabled on a per-request basis.
+	Chunked = case Override of
+		#{chunked := Chunked0} -> Chunked0;
+		_ -> maps:get(chunked, Opts, true)
+	end,
 	{State1, Headers1} = case {Status, ContentLength, Version} of
 		{204, _, 'HTTP/1.1'} ->
 			{State0#state{out_state=done}, Headers0};
 		{304, _, 'HTTP/1.1'} ->
 			{State0#state{out_state=done}, Headers0};
-		{_, undefined, 'HTTP/1.1'} ->
+		{_, undefined, 'HTTP/1.1'} when Chunked ->
 			{State0#state{out_state=chunked}, Headers0#{<<"transfer-encoding">> => <<"chunked">>}};
-		%% Close the connection after streaming without content-length to HTTP/1.0 client.
-		{_, undefined, 'HTTP/1.0'} ->
+		%% Close the connection after streaming without content-length
+		%% to all HTTP/1.0 clients and to HTTP/1.1 clients when chunked is disabled.
+		{_, undefined, _} ->
 			{State0#state{out_state=streaming, last_streamid=StreamID}, Headers0};
 		%% Stream the response body without chunked transfer-encoding.
 		_ ->
@@ -1099,12 +1107,18 @@ commands(State0=#state{ref=Ref, parent=Parent, socket=Socket, transport=Transpor
 %% Set options dynamically.
 commands(State0=#state{overriden_opts=Opts},
 		StreamID, [{set_options, SetOpts}|Tail]) ->
-	State = case SetOpts of
+	State1 = case SetOpts of
 		#{idle_timeout := IdleTimeout} ->
 			set_timeout(State0#state{overriden_opts=Opts#{idle_timeout => IdleTimeout}});
 		_ ->
 			State0
 	end,
+	State = case SetOpts of
+		#{chunked := Chunked} ->
+			State1#state{overriden_opts=Opts#{chunked => Chunked}};
+		_ ->
+			State1
+	end,
 	commands(State, StreamID, Tail);
 %% Stream shutdown.
 commands(State, StreamID, [stop|Tail]) ->
```

**Comment by essen** [comment]
Done in most recent commit. Please try it!

**Comment by adrianroe** [comment]
Perfect!  Very much appreciated.

**Comment by essen** [comment]
2.6 is out!
