### ISSUE TITLE
Support sending of multiple files

### ISSUE THREAD

**Issue by srstrong** [ninenines/cowboy#1339]
I have a cowboy handler that is dynamically building an mp4 file to send back to the client.  The nature of mp4 files is that they have a large data section and a relatively small header;  the header cannot be created until the data has been generated, but it is advantageous to clients if they can receive the header first.

In cowboy 1.0, I was using cowboy_req:set_resp_body_fun, and then inside my fun, I could simply call Transport:send_file/2 twice, which gave an efficient way of streaming both the header and the data back to the client in the best order.

In cowboy 2.x, it looks like I can no longer do this - I can either concatenate the files together so that I can send back a sendfile tuple, or I can switch to a cowboy_loop and stream the files back.  The first is going to incur a big disk-io hit (the data will have to be concatenated onto the header, and the data can be big).  The second will read all the data from the disk into userspace and back out again.

Would it be possible to provide support for a resp_body to be a list of sendfile tuples?

**Comment by essen** [comment]
It's already available in master, `cowboy_req:stream_body/3` accepts a sendfile tuple. It'll be part of 2.6 released later today.

**Comment by essen** [comment]
It's out!
