### ISSUE TITLE
benchmark for performance about our cowboy

### ISSUE THREAD

**Issue by dvlp123456** [ninenines/cowboy#1341]
I want to do stress test for my project which base on cowboy, so I want to get same official data about benchmark for performance.
I try to find any official documents about benchmark for performance about our cowboy, but I failed. Can I 
get same official documents anywhere?
Thank you for your time.

**Comment by essen** [comment]
There are no official benchmark results for Cowboy. All I can say is that if you want good performance you should favor HTTP/2 over HTTP/1.1.
