### ISSUE TITLE
Cowboy Rest handler PUT request flow chart process order

### ISSUE THREAD

**Issue by dynamite-ready** [ninenines/cowboy#1345]
Shouldn't `content_types_accept` run before `is_conflict`?

I have an application when I make a PUT request from a client, and use the payload to determine if the resource already exists in `is_conflict`. The problem though, is that I'd really like to check the content type first, and reject anything that's not `application/json`, before any further processing.

Is there a way to change the order of callback processing somehow?

**Comment by essen** [comment]
No. If you need to 409 after reading the body then you should do so in the `AcceptCallback` and return a `{stop, ...}` tuple after manually sending the 409 response.

This is the case with many callbacks. In this case `is_conflict` is useful if you have versioning information outside of the body, like in the query string.

**Comment by dynamite-ready** [comment]
Wow! Thank you for the prompt reply!

That makes sense. I'll rework the handler to manually return a 409.
Happy to see this issue closed.
