### ISSUE TITLE
Hound + Selenium/Firefox does not work with `find_element`

### ISSUE THREAD

**Issue by Qqwy** [ninenines/cowboy#1347]
When running Hound with Selenium, using Firefox as browser, `find_element` and related functions do not work. Hound has problems parsing the return value if the element is found.

For instance, you get errors like this:

```find_element(:name, "new-message-field", 10)
** (Hound.Error) could not get element {:name, "new-message-field"}: %{"element-6066-11e4-a52e-4f735466cecf" => "d53bc0d4-3aed-4739-931a-1f278cab5d86"}                                                                                                            
    (hound) lib/hound/helpers/page.ex:53: Hound.Helpers.Page.find_element/3
```

Firefox version 63.0.3 (64-bit), Selenium server version: 3.14.0, revision: aacccce0.

**Comment by essen** [comment]
I have no idea what that means. Wrong project?

**Comment by Qqwy** [comment]
No, not at all. Switching to `driver: "selenium", browser: "chrome"` makes the same code work fine.

**Comment by Qqwy** [comment]
Yes, you are right, apologies!
