### ISSUE TITLE
“Match any” parameter '`*`' not allowed by `content_types_accepted/2` typespec

### ISSUE THREAD

**Issue by ehamberg** [ninenines/cowboy#1348]
The special content type `'*'` will always match a content type¹, but the typespec for `content_types_accepted/2` does not allow this special value. It is also not mentioned in the docs.

[1] https://github.com/ninenines/cowboy/blob/037b286aa85acaaf439011bd7d2ae38685ce2f2e/src/cowboy_rest.erl#L1086

**Comment by essen** [comment]
Done. Thanks!
