### ISSUE TITLE
Safari and nghttp hang on large JSON output

### ISSUE THREAD

**Issue by whitepaperclip** [ninenines/cowboy#1352]
Only happens over encrypted connections. I created a test server here that uses Cowboy 2.6:

https://github.com/whitepaperclip/safari_bug

After compiling/running, visit https://localhost:4000/iodata to see the timeout, and https://localhost:4000/binary to see the same output work.

Note that this doesn't happen over HTTP 1.1, only HTTP 2.

**Comment by adrianroe** [comment]
I wonder if this is related to https://github.com/ninenines/gun/issues/150 <https://github.com/ninenines/gun/issues/150> or more specifically  https://bugs.erlang.org/browse/ERL-371 <https://bugs.erlang.org/browse/ERL-371> - the (second!) underlying bug in the Erlang runtime relating to dropping messages in TLS connections.  Since moving to OTP 21.2.4 we no longer see the problem…

Adrian

**Comment by whitepaperclip** [comment]
@adrianroe Upgrading to OTP 21.2.4 doesn't prevent Safari from hanging.

**Comment by essen** [comment]
I don't have a Safari handy. Please try tracing all Cowboy and ssl modules and report back with the result.

**Comment by whitepaperclip** [comment]
@essen I also managed to reproduce it with the nghttp client. `$ nghttp https://localhost:4000/iodata` causes a hang.

**Comment by whitepaperclip** [comment]
@essen Here's a gist of the working `/binary` output: https://gist.github.com/whitepaperclip/e02560fd5c9cc801e89c9a6ecff264d9

Here's a gist of the iodata that causes a hang: https://gist.github.com/whitepaperclip/46bf4ff8fb1440b681fb3058c89358ad

**Comment by essen** [comment]
Sure but that's not terribly helpful. I need a trace of what Erlang is doing. I can try myself but that might take a while since I can't work 100% right now.

**Comment by whitepaperclip** [comment]
@essen All Cowboy and `:ssl` calls traced: https://gist.github.com/whitepaperclip/fe830eefdc38095d088ce4e4d1043c93

**Comment by josevalim** [comment]
I am taking a closer looked at this issue. To recap what has been said, the issue happens on HTTP 2.

On the failing case (iodata), the server sends 4 data frames and then it gets stuck, with the following size and fin status:

    {4817,nofin}
    {5601,nofin}
    {4928,nofin}
    {5320,nofin}
    ...STUCK...

On the successful case (binary), the following frames are sent:

    {16384,nofin}
    {16384,nofin}
    {16384,nofin}
    {16383,nofin}
    {2095,fin}

In both cases, the headers are the same (except for Date):

    #{<<"cache-control">>=><<"max-age=0, private, must-revalidate">>,<<"content-length">>=><<"67630">>,<<"content-type">>=><<"application/json">>,<<"date">>=><<"Mon, 25 Mar 2019 07:37:43 GMT">>,<<"server">>=><<"Cowboy">>,<<"x-request-id">>=><<"2m7i721o693j0ub7a4000062">>}

Now I will start to dig up in the code and take a look at how the iodata is being split.

**Comment by essen** [comment]
If the sizes are not the same then the bug is probably in https://github.com/ninenines/cowlib/blob/master/src/cow_iolists.erl

Because when sending we go through the same code for both binaries and iolists: https://github.com/ninenines/cowlib/blob/master/src/cow_http2_machine.erl#L1262

**Comment by josevalim** [comment]
@essen yup, it is in cow_iolists. PR incoming.

**Comment by josevalim** [comment]
@essen PR sent here: https://github.com/ninenines/cowlib/pull/76

**Comment by essen** [comment]
This should be fixed, Cowboy release pending depending on CI build results. Cowlib 2.7.1 has already been released with the fix for this. Thanks!

**Comment by essen** [comment]
Cowboy 2.6.2 is out: https://ninenines.eu/docs/en/cowboy/2.6/guide/migrating_from_2.6/#_cowboy_2_6_2

Also released Cowlib 2.7.2 because 2.7.1 had an issue with OTP-19.

Enjoy!
