### ISSUE TITLE
Content-type required when no body

### ISSUE THREAD

**Issue by sammyraul** [ninenines/cowboy#1357]
For sending a PUT request without body requires header "content-type" to be set.
If the header is not set then Cowboy returns 415 Unsupported Media Type.

I am using Cowboy version 2.2.2
Is there a way I can avoid sending the header.

Thanks

**Comment by etxemag75** [comment]
Had the same issue with a REST client, have to handle this in content_types_provided/2 and/or content_types_accepted/2 and add it to the Req that is returned.
```
HeadersMap = maps:get(headers,Req),
NewHeadersMap = maps:put(<<"content-type">>, <<"application/json">>,HeadersMap),
Req2 = maps:put(headers,NewHeadersMap,Req),
```

Would be good if cowboy had a function to set the default content-type if missing.

**Comment by essen** [comment]
For provided you can use `'_'` to match any media type.

For accepted your solution can be written as:

``` erlang
content_types_accepted(Req=#{headers := #{<<"content-type">> := _}}, State) ->
    do_it();
content_types_accepted(Req=#{headers := Headers}, State) ->
    content_types_accepted(Req#{headers => Headers#{<<"content-type">> => <<"application/json">>}}, State).
```

It's too much of an edge case to require a new function.

PS: Must not be much of a REST client if it doesn't handle media types properly. :-)
