### ISSUE TITLE
Implement cowboy_static:upgrade/5

### ISSUE THREAD

**Issue by abalazsik** [ninenines/cowboy#1362]
Hi!

I have a rest handler where the user can upload,download,list and delete files. To the download operation i don't want to reimplement what already works well in the cowboy_static module.
So i do this:

```
	<<"GET">> ->
            case cowboy_req:binding(name, Req) of 
                undefined ->
                    {jsone:encode(getFileNames(Folder)), Req, Folder};
                BinFileName ->
                    FileName = erlang:binary_to_list(BinFileName),
                    Path = Folder ++ "/" ++ FileName,
                    {{switch_handler, cowboy_static, {file, Path, []}}, Req, State}
            end;
	<<"POST">> ->
		...
	<<"DELETE">> ->
		...
```

This fails with an
	`undefined function cowboy_static:upgrade/5`

I know i could put the download operation into an another cowboy_static handler, but this single module criteria is crucial.
I'm not qualified enough to make a PR. Or is there an another solution?

**Comment by essen** [comment]
I'm not sure it makes sense to go from a `cowboy_rest` module to another `cowboy_rest` module. On the other hand you can just call the functions in `cowboy_static` when the method is GET.

**Comment by abalazsik** [comment]
My module is a cowboy_rest nodule, if call the cowboy_static:init i get an error, because the term is not in the correct format. I tried to convert it to the right format, but it didn't work. And if i write the module as a cowboy_handler, the framework somehow wants to call the upgrade in my module(I'm not sure why) witch is not exist.
Anyway it turns out, it is not so important to make all the functionality in a single module. So I made the download with a cowboy_static module. Anyways, it works, so the issue can be closed.

**Comment by essen** [comment]
I'm not sure I understand, what error do you get when calling `cowboy_static:init/2`? You need to provide the correct initial state of course, the same you'd do from the routes.

**Comment by abalazsik** [comment]
It looks like my initial code example is bad (failed to CTRL + C, CTRL + V), because Folder == State. So, in my module the env/opts variable is the folder's path. If i call the cowboy_static:init/2 function i will lose this variable after the first request. Therefore i tried to convert the result of this function to the right format, with my env/opts variables. I completely missed the fact that the cowboy_rest module does the file transfer. I thought this function fills the response body etc, and after that i can convert its return value, to return my Folder variable. But that obviously wouldn't work with big files, so this method is understandable.

**Comment by essen** [comment]
So I think we're good here? Closing, thanks!
