### ISSUE TITLE
2.6.1 Warning: behaviour cowboy_stream undefined

### ISSUE THREAD

**Issue by richardkmichael** [ninenines/cowboy#1366]
(I am new to Erlang, I'm sorry if this isn't something which should be reported.  I did search both open and closed issues for a similar report.)

I installed Phoenix from the master branch (currently at this [commit](https://github.com/phoenixframework/phoenix/commit/387c6f775192cb69a4c93e5d67ce23ebeb637e57)), during which cowboy 2.6.1 was installed and I noticed this warning. I am unsure if it is significant.

`cowboy/src/cowboy_tracer_h.erl:16: Warning: behaviour cowboy_stream undefined`

Here is what I did, and all the information I have about Erlang, Elixir, etc. --

```
$ mix archive.install github phoenixframework/phoenix branch master

# Only relevant output included here..
# Git clones, then deps installation starts.

New:
  cowboy 2.6.1
  cowlib 2.7.1

===> Compiling cowlib
===> Compiling cowboy
/private/var/folders/bk/t3bt4lt54kjf7r0hxgldtj_w0000gn/T/mix-local-installer-fetcher--Muhqw/deps/cowboy/src/cowboy_tracer_h.erl:16: Warning: behaviour cowboy_stream undefined

/private/var/folders/bk/t3bt4lt54kjf7r0hxgldtj_w0000gn/T/mix-local-installer-fetcher--Muhqw/deps/cowboy/src/cowboy_stream_h.erl:16: Warning: behaviour cowboy_stream undefined

# Remaining deps continue installing.
```

Erlang is version `21.3.2`, Elixir is `1.8.1`.  Both installed via Homebrew.

```
$ erl --version
Erlang/OTP 21 [erts-10.3.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe] [dtrace]
```

**Comment by essen** [comment]
I don't know how mix compiles it but no that's not important. You could bring it up to mix developers if you want.

**Comment by richardkmichael** [comment]
Thanks for the quick reply, sorry for the noise!
