### ISSUE TITLE
cowboy_req:read_body hangs indefinitely when called from a non-handler process

### ISSUE THREAD

**Issue by adamdaugherty** [ninenines/cowboy#1374]
I am using a `cowboy_loop` handler to service a web request. I am reading the request body in another process, and sending messages to the `cowboy_loop` process to do stuff asynchronously via a series of `info` callbacks. When I call `cowboy_req:read_body` from the (non-`cowboy_loop` handler) process, a catch-all `info` callback in the `cowboy_loop` handler receives a `{request_body, ref, :fin, 2, "xx"}` tuple and `read_body` never returns a value.

From looking at the source ([line 490 of cowboy_req.erl in master as of this writing](https://github.com/ninenines/cowboy/blob/fbfec873f6026b858c3604d74d88470ce45f4296/src/cowboy_req.erl#L490)), it seems like the reason that `read_body` is hanging is because it's waiting for a message that never arrives, since the `cowboy_loop` handler seems to send the message to its own mailbox (where it gets picked up by my `info` callback), *instead of* sending it to the process that `read_body` was called from (which is dutifully waiting to receive the message that will never be sent to its mailbox).

I suspect that this isn't something that's strictly related to `cowboy_loop`, and I wouldn't be surprised if other handlers were similarly impacted, but I have only experienced it with a `cowboy_loop` handler and haven't looked at the source for any of the other handlers to verify it.

I am currently using cowboy 2.6, though I had the same issue with 2.3 (as I changed which version I was using in the hopes of resolving this issue).

**Comment by essen** [comment]
That's normal, support for using `cowboy_req` across multiple processes was removed in 2.0. What you want is probably this: https://github.com/ninenines/cowboy/issues/1143 - it is currently already possible and will be documented in the next release. Cheers!

**Comment by adamdaugherty** [comment]
Thank you for taking the time to respond.

I appreciate the suggestion of using `auto` mode, but I don't think it fits my use case very well (my goal was to pass something that could lazily enumerably provide the pieces of a request body that the receiver could use without having to know anything about the underlying implementation).

Unless it's already there and I somehow missed it, it is probably worth augmenting cowboy's documentation to call out the limitation that `cowboy_req` can only be used in a handler process, so other people can avoid the design pitfall I fell into.

**Comment by essen** [comment]
I mean `auto` mode is one half of what you want, the other half is a parser combinator, or a parser that simply returns a fun to continue, or a module+state or similar. You don't need to accumulate the body or make the parser know it works over HTTP or whatever.

I suppose the functions that do not work across processes should be indicated as such in their manual page. I'll open a ticket for that.

**Comment by adamdaugherty** [comment]
Thank you for opening the ticket, and thanks again for your help.
