### ISSUE TITLE
Write in manual pages which cowboy_req functions only work from the request process

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1375]
Confusion otherwise. #1374

**Comment by maxmellen** [comment]
Hey @essen, just also spent a lot of time debugging a similar issue to the one described in #1374 only to finally find that issue. It's definitely worth documenting this as explicitly as possible. I was wondering if it wouldn't even be better to have the caller fail if it calls such a function (like `cowboy_req:read_body`) from the wrong process.

Something like the following should be possible:
```erlang
-spec read_body(Req, read_body_opts()) -> {ok, binary(), Req} | {more, binary(), Req} when Req::req().
read_body(Req=#{has_body := false}, _) ->
	{ok, <<>>, Req};
read_body(Req=#{has_read_body := true}, _) ->
	{ok, <<>>, Req};
read_body(Req=#{pid := Pid, streamid := StreamID}, Opts) ->
	case self() of
		Pid ->
			Length = maps:get(length, Opts, 8000000),
			Period = maps:get(period, Opts, 15000),
			Timeout = maps:get(timeout, Opts, Period + 1000),
			Ref = make_ref(),
			Pid ! {{Pid, StreamID}, {read_body, Ref, Length, Period}},
			receive
				{request_body, Ref, nofin, Body} ->
					{more, Body, Req};
				{request_body, Ref, fin, BodyLength, Body} ->
					{ok, Body, set_body_length(Req, BodyLength)}
			after Timeout ->
				exit(timeout)
			end;
		_ ->
			error(badprocess)
	end.
```

Would it be me making a PR for this? Maybe with less nesting and a more meaningful error.

**Comment by essen** [comment]
Let's first agree on which functions are not allowed in other processes and document them properly.

**Comment by essen** [comment]
OK I will remove the restriction in 2.7. On the other hand a new restriction has been added to `stream_body` to enable backpressure, in order to remove it for 2.7 as well I will need to introduce a new message type `{data, Pid, IsFin, Data}` and I suppose the backpressure will only be applied when this message is sent, not when the old style message is sent (but it can be kept around for compatibility and in order to circumvent the backpressure I guess).

**Comment by essen** [comment]
Done! Thanks.
