### ISSUE TITLE
cowboy_req:req() typespec is too strict

### ISSUE THREAD

**Issue by bullno1** [ninenines/cowboy#1379]
As the doc has stated, `cowboy_req:req()` is meant to be expandable by user. However, matching an user field like this:

```erlang
-spec match(cowboy_req:req()) -> ok.
match(#{user_field := UserField} = Req) -> ok.
```

would result in dialyzer complaining about wrong spec since `user_field` is not part of the spec.

What do you think about adding `_ => _` to the spec to denote free extension? I have tested and it solves all dialyzer issues.

**Comment by essen** [comment]
Yeah that's probably what's missing.

**Comment by essen** [comment]
I've fixed this locally, corrected the example and added a test. Push soon. Thanks!
