### ISSUE TITLE
Error, function_clause, cow_http2:window_update [0,infinity] 

### ISSUE THREAD

**Issue by ergenius** [ninenines/cowboy#1380]
Cowboy is crushing when submitting a large form. Works well with forms containing less information/fields. The crush is happening when cowboy is trying to read the request body (i'm not sure this is the cause of the problem but i noticed it so i wrote it here maybe it gives you a hint on what's going on).

**Crush is happening in cowlib, function 
window_update(StreamID, Increment) when Increment =< 16#7fffffff
StreamID = 0 and Increment = infinity atom and because this =< guard do not match**

== Browser == 

Google Chrome Version 74.0.3729.131 (Official Build) (64-bit) on Fedora

== ERLANG crash_report == 

PLEASE NOTICE: Data was removed from messages and replaced with ...>> because it contains sensitive information from my project posted through the form. However i kept the first bytes from the urlencoded body because they look quite suspect to me including those 0 bytes.

I also shorten cowboy source files paths (the part related to my project) so the crush report will be more easily readable.

[[{initial_call,{cowboy_tls,connection_process,['Argument__1','Argument__2','Argument__3','Argument__4','Argument__5']}},
   {pid,<0.2014.0>},
   {registered_name,[]},
   {error_info,{error,function_clause,[{cow_http2,window_update,[0,infinity],[{file,"/cowlib/src/cow_http2.erl"},{line,461}]},{cowboy_http2,commands,3,[{file,"/cowboy/src/cowboy_http2.erl"},{line,578}]},{cowboy_http2,loop,2,[{file,"/cowboy/src/cowboy_http2.erl"},{line,198}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},
   {ancestors,[<0.277.0>,<0.276.0>,ranch_sup,<0.263.0>]},
   {message_queue_len,1},
   {messages,[{ssl,{sslsocket,{gen_tcp,#Port<0.62>,tls_connection,<0.280.0>},[<0.2013.0>,<0.2012.0>]}, 
                   <<0,11,36,0,0,0,0,0,1,98,108,101,...>>}]},
   {links,[<0.277.0>,<0.2015.0>]},
   {dictionary,[]},
   {trap_exit,true},
   {status,running},
   {heap_size,1598},
   {stack_size,27},
   {reductions,2318}],
  [{neighbour,[{pid,<0.2015.0>},
               {registered_name,[]},
               {initial_call,{cowboy_stream_h,request_process,['Argument__1','Argument__2','Argument__3']}},
               {current_function,{cowboy_req,read_body,2}},
               {ancestors,[<0.2014.0>,<0.277.0>,<0.276.0>,ranch_sup,<0.263.0>]},
               {message_queue_len,0},
               {links,[<0.2014.0>]},
               {trap_exit,false},
               {status,waiting},
               {heap_size,610},
               {stack_size,52},
               {reductions,597},
               {current_stacktrace,[{cowboy_req,read_body,2,[{file,"/cowboy/src/cowboy_req.erl"},{line,491}]},{cowboy_req,read_urlencoded_body,2,[{file,"/cowboy/src/cowboy_req.erl"},{line,513}]},{xhttp_lib_request,parse_post,3,[{file,"src/xhttp_lib_request.erl"},{line,64}]},{xadmin_lib_router,init,2,[{file,"src/xadmin_lib_router.erl"},{line,50}]},{cowboy_handler,execute,2,[{file,"/cowboy/src/cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"/cowboy/src/cowboy_stream_h.erl"},{line,296}]},{cowboy_stream_h,request_process,3,[{file,"/cowboy/src/cowboy_stream_h.erl"},{line,274}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}]}]]=CRASH REPORT==== 5-Jun-2019::09:12:53.272567 ===
  crasher:
    initial call: cowboy_tls:connection_process/5
    pid: <0.2014.0>
    registered_name: []
    exception error: no function clause matching 
                     cow_http2:window_update(0,infinity) (/cowlib/src/cow_http2.erl, line 461)
      in function  cowboy_http2:commands/3 (/cowboy/src/cowboy_http2.erl, line 578)
      in call from cowboy_http2:loop/2 (/cowboy/src/cowboy_http2.erl, line 198)
    ancestors: [<0.277.0>,<0.276.0>,ranch_sup,<0.263.0>]
    message_queue_len: 1
    messages: [{ssl,
                      {sslsocket,
                          {gen_tcp,#Port<0.62>,tls_connection,<0.280.0>},
                          [<0.2013.0>,<0.2012.0>]},
                      <<0,11,36,0,0,0,0,0,1,98,108,101,...>>}]
    links: [<0.277.0>,<0.2015.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 2318
  neighbours:
    neighbour:
      pid: <0.2015.0>
      registered_name: []
      initial call: cowboy_stream_h:request_process/3
      current_function: {cowboy_req,read_body,2}
      ancestors: [<0.2014.0>,<0.277.0>,<0.276.0>,ranch_sup,<0.263.0>]
      message_queue_len: 0
      links: [<0.2014.0>]
      trap_exit: false
      status: waiting
      heap_size: 610
      stack_size: 52
      reductions: 597
      current_stacktrace: [{cowboy_req,read_body,2,
                      [{file,
                           "/cowboy/src/cowboy_req.erl"},
                       {line,491}]},
                  {cowboy_req,read_urlencoded_body,2,
                      [{file,
                           "/cowboy/src/cowboy_req.erl"},
                       {line,513}]},
                  {xhttp_lib_request,parse_post,3,
                      [{file,"src/xhttp_lib_request.erl"},{line,64}]},
                  {xadmin_lib_router,init,2,
                      [{file,"src/xadmin_lib_router.erl"},{line,50}]},
                  {cowboy_handler,execute,2,
                      [{file,
                           "/cowboy/src/cowboy_handler.erl"},
                       {line,41}]},
                  {cowboy_stream_h,execute,3,
                      [{file,
                           "/cowboy/src/cowboy_stream_h.erl"},
                       {line,296}]},
                  {cowboy_stream_h,request_process,3,
                      [{file,
                           "/cowboy/src/cowboy_stream_h.erl"},
                       {line,274}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,249}]}]

**Comment by essen** [comment]
Are you calling read_body or similar function with a length set to `infinity`?

**Comment by ergenius** [comment]
Let me check everything in my handler until the crush occurs and come back with the answer.

**Comment by ergenius** [comment]
**You where right. Thank you very much!**

```
%% somewhere along my code 
ReadLength = infinity,
%% later i call:
cowboy_req:read_urlencoded_body(Req, #{length => ReadLength, period => Timeout})
```
I can't understand how i came up with this. Is it possible older version of cowboy used infinity? (I reused some code from an old application using old cowboy < 2 version)
