### ISSUE TITLE
Can't set elapsed-time response header.

### ISSUE THREAD

**Issue by imgrey** [ninenines/cowboy#1383]
I can't set response header.

content_types_provided(Req, State) ->
    {[
        {{<<"application">>, <<"json">>, '*'}, to_json}
    ], Req, State}.

to_json(Req0, State) ->
    Delta = binary:encode_unsigned(1560238796411),
    Req1 = cowboy_req:set_resp_header(<<"elapsed-time">>, Delta, Req),
    {jsx:encode([{list, [something, something]}]), Req1, []}

Ranch listener middleware_http_listener, connection process <0.711.0>, stream 1 had its request process <0.712.0> exit with reason badarith and stacktrace [{list_handler,to_json,2,[{file,"src/list_handler.erl"},{line,78}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,1128}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,1019}]},{cowboy_rest,upgrade,4,[{file,"src/cowboy_rest.erl"},{line,238}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

**Comment by essen** [comment]
`badarith` is a math operation exception, for example divide by 0 or trying to add a number and a string, so you must be doing something that fails that's not in this snippet. The error occurs in your `to_json` function.

**Comment by imgrey** [comment]
Right. My mistake.
