### ISSUE TITLE
Examples and Docs

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1387]
Reading the websocket example I can not distinguish mandatory parts from illustrative parts.
A similar issue exists with the websocket descr in the docs: it is impossible to discern what is the minimal boilerplate, and how to construct a valid websocket handler from all the factual information that the doc provides. In other words the "intended use" info is missing.

**Comment by essen** [comment]
Not sure what you mean, the Websocket example is fairly minimal, there's only like 5 extra lines to make it do something more than just keeping the connection open.

**Comment by eugene-panferov** [comment]
right! which are this 5 lines is the question exactly.
particularly it is unclear if the pinger component necessary for keeping the connection alive?
or was the entire pinger just an example of how you can receive messages.

**Comment by essen** [comment]
It doesn't send pings, it sends text data.

Typically the client will be the one sending pings to keep the connection open and it's all handled transparently. Or reconnect automatically if that failed.

**Comment by essen** [comment]
The easiest way to get a minimal handler is to just use the template:

```
$ make new t=cowboy.ws n=my_ws_h
```

Assuming you configured Cowboy as a `DEP_PLUGINS`.

**Comment by eugene-panferov** [comment]
thanks! this is great feature, how did i miss it in "getting started"? is it mentioned?
still i ask you to add few comments to the example saying that the periodic {reply,...} is not necessary.

**Comment by essen** [comment]
The getting started tells you to make a normal handler: https://ninenines.eu/docs/en/cowboy/2.6/guide/getting_started/#_handling_requests

You can use `make list-templates` to get all the templates.

Feel free to open a PR with suggested comments.

Thanks!
