### ISSUE TITLE
[Websocket] Websocket connection always exit(normal).

### ISSUE THREAD

**Issue by gilbertwong96** [ninenines/cowboy#1388]
Hi, @essen, I'm an emqx developer, we integrated cowboy in emqx to handle the mqtt packets in websocket connection. However, we found some problems when we use websocket behavior in the `cowboy`.

Here is the code used to resolve the shutdown of the process:

https://github.com/emqx/emqx/blob/master/src/emqx_ws_channel.erl#L346-L349

Why do we not just return `{stop, State}` instead of sending a `{stop, State}` msg to self() pid? Because when a websocket mqtt connection is creating and if the connect packet is refused by mqtt broker, the MQTT broker has to send a connack packet which contains error code to mqtt client before the connection pid stopped. So we do a trick that send `{stop, State}` msg to websocket pid which aims to delay the pid stop of the websocket connection to resolve this problem.

However, there are still some problems in websocket behavior. For example, In mqtt spec, there is a concept called `will msg`, In emqx architecture, we implemented this feature in session processes. When emqx_session process receive a exit signal from connection process with abnormal reason, it should send will msg to specified will topic. In the cowboy_websocket module, I found that we can not pass mqtt reason code to websocket pid and let it stop with abnormal reason. I'm stuck in this problem. I hope that I can refactor this code snippets:

https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L617-L619

let the terminate function in handler module return the real reason code, like this
```
HandlerReasonCode = handler_terminate(State, HandlerState, Reason),
exit(HandlerReasonCode).
```

**Comment by essen** [comment]
I am afraid I do not really understand. For the `{stop, State}` in particular you can return a list of commands, allowing you to reply then close (either via `{reply, [{text|binary, Data}, close], State}` or the new `{[{text|binary, Data}, close], State}`.

The latter part of the ticket seems to be about wanting a better exit signal, I think we have a ticket about that and I wouldn't mind changing it to `{shutdown, Reason}` but we cannot use what the terminate callback returns as that is ignored. It'd have to be the argument we pass to it.

**Comment by Gilbert-Wong** [comment]
Thanks for your reply, what about add one case in handler_call function of the cowboy_websocket module like this `{stop, HandlerState2, Reason}` ?

**Comment by essen** [comment]
Again I do not understand the purpose. I need to understand what you're trying to do before discussing any interface changes.

**Comment by Gilbert-Wong** [comment]
Sorry for my vague description, I want to let the websocket process exit with the reason which is not normal, and let the linked process to get the abnormal exit signal. Let me show you the code 

https://github.com/emqx/emqx/blob/master/src/emqx_session.erl#L618-L647

**Comment by essen** [comment]
And this exit reason is different from the Websocket close code I assume?

**Comment by Gilbert-Wong** [comment]
Yes, because we use websocket to wrap mqtt packet, the reason should be consistent with the reason defined in the mqtt protocol.

**Comment by essen** [comment]
OK makes sense. Then I guess we need a new command to set the exit reason so that it becomes `{shutdown, Reason}` instead of `normal`, for the cases where it exits normally.

**Comment by Gilbert-Wong** [comment]
Yes.:) Indeed we need it.

**Comment by essen** [comment]
You're in luck! Done in d52e84bdd97b93d7d9cea827de57bd4a0edea9a8 just in time for Cowboy 2.7. Closing, thanks!

**Comment by gilbertwong96** [comment]
Haha, thanks, essen !

**Comment by gilbertwong96** [comment]
When will cowboy 2.7 be released ?
