### ISSUE TITLE
websocket packet types are confused

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1389]
i have no idea why packets are explicitly divided into {'text', Data} and {'binary', Data} and i do not require this distinction, but the following bug is apparent, the Data does not correspond to the declared type.

handler code:

websocket_handle({text, Data}, State) ->
  io:format("ws text received: ~p~n", [Data]),
  {reply, {text, Data}, State};
websocket_handle({binary, Data}, State) ->
  io:format("ws binr received: ~p~n", [Data]),
  {reply, {binary, Data}, State};

console output:

ws text received: <<"req 1562770068161">>

the handler was called with {'text', BinaryString}

My Browser: 
Chromium 57.0.2987.98 (Developer Build) Built on 8.7, running on Debian 9 (64-bit)
Revision a6a06b78087c9fdb4b12fe0ac1b87fdc10179f8b
JavaScript V8 5.7.492.63

My Erlang:
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit]
cowlib (2.7.3)
ranch (1.7.1)

**Comment by essen** [comment]
I am not sure what you are showing.

In the Websocket protocol there are two types of data frames: text (utf-8) and binary. The type sent by an implementation will depend based on what it wants to do or what input types it uses. For example from Javascript you will send a text or binary frame depending on the type of data you give to the function.

The binary frame is unrelated to the binary Erlang type.

**Comment by eugene-panferov** [comment]
so i am supposed to ALWAYS receive Data as binary?
and this distinction is some JS bullshit and i need to ignore it.
THANX!
it was not clear to me.

**Comment by essen** [comment]
It really depends on what the client is doing. It's not always a significant distinction. Just note that text involves utf-8 validation while binary doesn't (but sometimes that's fine, for example if you receive JSON you'll validate utf-8 while decoding the JSON).

**Comment by eugene-panferov** [comment]
what do you mean utf-8 validation?
i only want to receive exactly what i send.

**Comment by essen** [comment]
The text frame can only contain UTF-8 data. If the data is not UTF-8 then the server will reject the frame and close the connection.

**Comment by eugene-panferov** [comment]
oh! shit! good to know.

**Comment by eugene-panferov** [comment]
is it possible to switch off this validation?
just to be on the safe side.

**Comment by essen** [comment]
Not yet, there's an open ticket to add this option I think.

**Comment by eugene-panferov** [comment]
thank you.

**Comment by leeyisoft** [comment]
I also want to know how to configure the client when using "websocket_handle({text, Data}, State)" and B "websocket_handle({binary, Data}, State)"
@essen

**Comment by eugene-panferov** [comment]
On 4/22/22 03:10, leeyi wrote:
>
> I also want to know how to configure the client when using 
> "websocket_handle({text, Data}, State)" and B 
> "websocket_handle({binary, Data}, State)"
> @essen <https://github.com/essen>
>
in my exp all packets are 'text'.

to be on the safe side i do:


%% equate faux-binary to text
websocket_handle({binary, Data}, State) ->
   ?LOG_WARNING("binary ws-frame ~p ~p",[State,util:part(Data,0,4)])
, websocket_handle({text, Data}, State)
;
