### ISSUE TITLE
websocket doesn't work when using a domain name

### ISSUE THREAD

**Issue by fiodinggo** [ninenines/cowboy#1390]
hy essen,
if you may know, what is the right step when I apply websocket using a domain name?
because when I connect using IP, the web socket is not a problem. when I use a domain name, the request cannot even be read in the cowboy
sorry if there is a language usage error.

regards, penidas

**Comment by essen** [comment]
I would check that the domain name points to the right IP. I would also check to see if it's not an Origin or CORS related issue. You may need to send additional headers back to the client.

**Comment by fiodinggo** [comment]
thank you essen, i will find out again
