### ISSUE TITLE
Document you have to ensure websocket handlers are loaded which export websocket_init

### ISSUE THREAD

**Issue by mmzeeman** [ninenines/cowboy#1391]
When your websocket handler exports `websocket_init/1` you will have to make sure this module is loaded. If you don't do this the first websocket request to a server which has just been started will fail to call `websocket_init/1` because internally cowboy uses `erlang:function_exported/3` to check if the function is exported. This call will only work when the module is already loaded.

This is easily achieved by calling `code:ensure_loaded/1` or `code:ensure_modules_loaded/1` for the websocket handlers.

I think this behaviour should be documented somewhere as it leads to strange behavior for the first time a websocket is opened. Later requests will use `websocket_init` as the handler module will be loaded then.

Do you agree? (I'm willing to add the documentation)

**Comment by essen** [comment]
What version is this? In 2.0 Cowboy will normally call init first and that loads the module. Or do you do something unusual?

**Comment by mmzeeman** [comment]
We call `cowboy_websocket:upgrade/5` directly in https://github.com/zotonic/cowmachine.

https://github.com/zotonic/cowmachine/blob/master/src/cowmachine_websocket_upgrade.erl

Where is the init call located to load the websocket handler?

**Comment by essen** [comment]
In `cowboy_handler`, but I suppose you don't use it. It's common to all handlers. I don't think this is worth documenting, the normal way of doing things doesn't require it.

**Comment by mmzeeman** [comment]
Yep found it... Indeed, I think so too. This is a special use case.

Thanks for your help.
