### ISSUE TITLE
cowboy_req:read_body(Req) returns {more, <<>>, Req1}

### ISSUE THREAD

**Issue by shamis** [ninenines/cowboy#1394]
```erlang
{more,<<>>,
#{bindings => #{},body_length => 19,cert => undefined,
has_body => true,
headers =>
    #{<<"accept">> => <<"*/*">>,
        <<"accept-language">> => <<"de-CH">>,
        <<"cache-control">> => <<"no-cache">>,
        <<"connection">> => <<"Keep-Alive">>,
        <<"content-length">> => <<"19">>,
        <<"content-type">> => <<"text/plain;charset=U"...>>,
        <<"cookie">> => <<"SESSIO"...>>,
        <<"host">> => <<"web.test"...>>,
        <<"referer">> => <<"https://"...>>,
        <<"reve"...>> => <<"test"...>>,<<...>> => <<...>>,...},
host => <<"web.root.net">>,host_info => undefined,
method => <<"POST">>,
path => <<"/event/1/xhr-polling/g2dkACF"...>>,
path_info => [<<"xhr-polling">>,<<"g2dkACFzYnNndWlA"...>>],
peer => {{1,1,1,3},64969},
pid => <0.1234.430>,port => 8445,qs => <<"t=156352"...>>,
ref => https,resp_headers => #{...},...}}}}
```
Trying to read_body returns `{more, <<>>, Req}`. Body length as seen from the request above is 19, but reading the body returns `<<>>` with more to be fetched ?

Is this behavior expected ?

**Comment by essen** [comment]
What read_body options did you give? The function returns either when the amount of body you want was read, when the body was completely read, or when the waiting period ended. In your case I would guess this is the latter and that the client simply didn't send you the data.

See https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_req.read_body/ for details.

**Comment by shamis** [comment]
No options where given to read_body. `cowboy_req:read_body/1` was called.

**Comment by essen** [comment]
From what you told me here then yes the behavior is expected, but only as long as it waited the configured period. I'll close for now but if there is really an issue please reopen. Thanks!
