### ISSUE TITLE
Ranch listener crashes on cowboy_http:timeout/2 function caluse

### ISSUE THREAD

**Issue by shamis** [ninenines/cowboy#1395]
>CRASH REPORT Process <0.30836.430> with 0 neighbours crashed with reason: no function clause matching cowboy_http:timeout({state,<0.1468.0>,https,{sslsocket,{gen_tcp,#Port<0.739844>,tls_connection,<0.1470.0>},<0.6988.431>},...}, request_timeout) line 239

It seems like in the following code in_state has a different value
https://github.com/ninenines/cowboy/blob/5b4e78fac483c5eb277fec4ab7e8c6a62821bf4b/src/cowboy_http.erl#L275-L284

**Comment by essen** [comment]
Can I have the full crash report instead of this truncated message? I can't do anything if it's truncated.

**Comment by shamis** [comment]
Crash report. 
> 2019-07-08 12:09:01 =CRASH REPORT====
  crasher:
    initial call: cowboy_tls:connection_process/5
    pid: <0.12962.389>
    registered_name: []
    exception error: {function_clause,[{cowboy_http,timeout,[{state,<0.1442.0>,https,{sslsocket,{gen_tcp,#Port<0.504948>,tls_connection,<0.1444.0>},<0.18354.389>},ranch_ssl,#{connection_type => supervisor,env => #{dispatch => [{'_',[],[{[<<"probe.html">>],[],dderl,'$path_probe'},{[<<"metrics">>],[],dderl_prometheus,metrics},{[<<"dderl">>],[],dderl,[]},{[<<"dderl">>,<<"app">>,'...'],[],dderl_resource,[]},{[<<"dderl">>,<<"saml">>],[],dderl_saml_handler,[]},{[<<"dderl">>,'...'],[],cowboy_static,{dir,"d:/K2Informatics/test/lib/dderl-3.5.1/priv"}},{[<<"app">>,<<"test">>,'...'],[],test_resource,'$path_ajax'},{[<<"test">>],[],dderl_saml_handler,#{app => test}},{[],[],test_resource,{index,"d:/K2Informatics/test/lib/test-3.5.1/priv/public/index.html"}},{[<<"event">>,<<"1">>,'...'],[],socketio_handler,[{config,5000,30000,30000,test_wss,socketio_data_protocol,undefined}]},{['...'],[],test_static,{dir,"d:/K2Informatics/test/lib/test-3.5.1/priv/public",[{mimetypes,cow_mimetypes,all}]}}]}]},middlewares => [cowboy_router,dderl_cow_mw,test_cow_mw,cowboy_handler],stream_handlers => [cowboy_compress_h,cowboy_stream_h]},{{10,185,108,38},34978},{{10,66,148,82},8445},undefined,#Ref<0.3337732128.3354132482.201509>,14,{ps_body,94,0,#Fun<cow_http_te.stream_identity.2>,{0,94}},15,wait,100,[],[]},request_timeout],[{file,"e:/k2_build/test/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,239}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1442.0>,<0.1441.0>,ranch_sup,<0.196.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1442.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 40703
  neighbours:
2019-07-08 12:09:01 =ERROR REPORT====
Ranch listener https had connection process started with cowboy_tls:start_link/4 at <0.12962.389> exit with reason: {function_clause,[{cowboy_http,timeout,[{state,<0.1442.0>,https,{sslsocket,{gen_tcp,#Port<0.504948>,tls_connection,<0.1444.0>},<0.18354.389>},ranch_ssl,#{connection_type => supervisor,env => #{dispatch => [{'_',[],[{[<<"probe.html">>],[],dderl,'$path_probe'},{[<<"metrics">>],[],dderl_prometheus,metrics},{[<<"dderl">>],[],dderl,[]},{[<<"dderl">>,<<"app">>,'...'],[],dderl_resource,[]},{[<<"dderl">>,<<"saml">>],[],dderl_saml_handler,[]},{[<<"dderl">>,'...'],[],cowboy_static,{dir,"d:/K2Informatics/test/lib/dderl-3.5.1/priv"}},{[<<"app">>,<<"test">>,'...'],[],test_resource,'$path_ajax'},{[<<"saml">>],[],dderl_saml_handler,#{app => test}},{[],[],test_resource,{index,"d:/K2Informatics/test/lib/test-3.5.1/priv/public/index.html"}},{[<<"event">>,<<"1">>,'...'],[],socketio_handler,[{config,5000,30000,30000,test_wss,socketio_data_protocol,undefined}]},{['...'],[],test_static,{dir,"d:/K2Informatics/test/lib/test-3.5.1/priv/public",[{mimetypes,cow_mimetypes,all}]}}]}]},middlewares => [cowboy_router,dderl_cow_mw,test_cow_mw,cowboy_handler],stream_handlers => [cowboy_compress_h,cowboy_stream_h]},{{10,185,108,38},34978},{{10,66,148,82},8445},undefined,#Ref<0.3337732128.3354132482.201509>,14,{ps_body,94,0,#Fun<cow_http_te.stream_identity.2>,{0,94}},15,wait,100,[],[]},request_timeout],[{file,"e:/k2_build/test/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,239}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by essen** [comment]
Sounds like we are missing a cancel of the `request_timeout` or are not flushing messages when we cancel, somewhere, after the headers have been fully read.

Or, we are forgetting to update the `in_state` somewhere after finishing to process a request. Considering there is no current stream running this is what I would guess happens here.

**Comment by shamis** [comment]
Crash report. 
> 2019-07-08 12:09:01 =CRASH REPORT====
  crasher:
    initial call: cowboy_tls:connection_process/5
    pid: <0.12962.389>
    registered_name: []
    exception error: {function_clause,[{cowboy_http,timeout,[{state,<0.1442.0>,https,{sslsocket,{gen_tcp,#Port<0.504948>,tls_connection,<0.1444.0>},<0.18354.389>},ranch_ssl,#{connection_type => supervisor,env => #{dispatch => [{'_',[],[{[<<"probe.html">>],[],dderl,'$path_probe'},{[<<"metrics">>],[],dderl_prometheus,metrics},{[<<"dderl">>],[],dderl,[]},{[<<"dderl">>,<<"app">>,'...'],[],dderl_resource,[]},{[<<"dderl">>,<<"saml">>],[],dderl_saml_handler,[]},{[<<"dderl">>,'...'],[],cowboy_static,{dir,"d:/K2Informatics/test/lib/dderl-3.5.1/priv"}},{[<<"app">>,<<"test">>,'...'],[],test_resource,'$path_ajax'},{[<<"test">>],[],dderl_saml_handler,#{app => test}},{[],[],test_resource,{index,"d:/K2Informatics/test/lib/test-3.5.1/priv/public/index.html"}},{[<<"event">>,<<"1">>,'...'],[],socketio_handler,[{config,5000,30000,30000,test_wss,socketio_data_protocol,undefined}]},{['...'],[],test_static,{dir,"d:/K2Informatics/test/lib/test-3.5.1/priv/public",[{mimetypes,cow_mimetypes,all}]}}]}]},middlewares => [cowboy_router,dderl_cow_mw,test_cow_mw,cowboy_handler],stream_handlers => [cowboy_compress_h,cowboy_stream_h]},{{1,1,1,1},378},{{1,1,1,1},845},undefined,#Ref<0.3337732128.3354132482.201509>,14,{ps_body,94,0,#Fun<cow_http_te.stream_identity.2>,{0,94}},15,wait,100,[],[]},request_timeout],[{file,"e:/k2_build/test/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,239}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1442.0>,<0.1441.0>,ranch_sup,<0.196.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1442.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 40703
  neighbours:
2019-07-08 12:09:01 =ERROR REPORT====
Ranch listener https had connection process started with cowboy_tls:start_link/4 at <0.12962.389> exit with reason: {function_clause,[{cowboy_http,timeout,[{state,<0.1442.0>,https,{sslsocket,{gen_tcp,#Port<0.504948>,tls_connection,<0.1444.0>},<0.18354.389>},ranch_ssl,#{connection_type => supervisor,env => #{dispatch => [{'_',[],[{[<<"probe.html">>],[],dderl,'$path_probe'},{[<<"metrics">>],[],dderl_prometheus,metrics},{[<<"dderl">>],[],dderl,[]},{[<<"dderl">>,<<"app">>,'...'],[],dderl_resource,[]},{[<<"dderl">>,<<"saml">>],[],dderl_saml_handler,[]},{[<<"dderl">>,'...'],[],cowboy_static,{dir,"d:/K2Informatics/test/lib/dderl-3.5.1/priv"}},{[<<"app">>,<<"test">>,'...'],[],test_resource,'$path_ajax'},{[<<"saml">>],[],dderl_saml_handler,#{app => test}},{[],[],test_resource,{index,"d:/K2Informatics/test/lib/test-3.5.1/priv/public/index.html"}},{[<<"event">>,<<"1">>,'...'],[],socketio_handler,[{config,5000,30000,30000,test_wss,socketio_data_protocol,undefined}]},{['...'],[],test_static,{dir,"d:/K2Informatics/test/lib/test-3.5.1/priv/public",[{mimetypes,cow_mimetypes,all}]}}]}]},middlewares => [cowboy_router,dderl_cow_mw,test_cow_mw,cowboy_handler],stream_handlers => [cowboy_compress_h,cowboy_stream_h]},{{1,1,1,3},378},{{1,1,1,1},845},undefined,#Ref<0.3337732128.3354132482.201509>,14,{ps_body,94,0,#Fun<cow_http_te.stream_identity.2>,{0,94}},15,wait,100,[],[]},request_timeout],[{file,"e:/k2_build/test/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,239}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by indrekj** [comment]
I think we are encountering something similar. It usually happens about once a day and then it spams around few hundred of these:
```
Ranch listener TransporterWeb.PubSubEndpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.8519.449> exit with reason: {:function_clause, [{:cowboy_http, :timeout, [{:state, #PID<0.4355.0>, TransporterWeb.PubSubEndpoint.HTTP, #Port<0.2093302>, :ranch_tcp, :undefined, %{env: %{dispatch: [{:_, [], [{:_, [], Phoenix.Endpoint.Cowboy2Handler, {TransporterWeb.PubSubEndpoint, []}}]}]}, max_header_name_length: 64, max_header_value_length: 16386, max_headers: 100, max_request_line_length: 8096, request_timeout: 15000, stream_handlers: [TransporterWeb.CowboyErrorsMiddleware]}, %{}, {{10, 0, 129, 154}, 10808}, {{10, 0, 138, 110}, 4001}, :undefined, #Reference<0.2791976931.2934964227.68645>, 10, {:ps_body, 47, 0, &:cow_http_te.stream_identity/2, {0, 47}}, 11, :wait, 100, [], []}, :request_timeout], [file: '/app/deps/cowboy/src/cowboy_http.erl', line: 276]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```

**Comment by essen** [comment]
The crash is Cowboy's fault but it happening for many separate connections all at once isn't, so you probably need to look at an issue in your environment or applications.

**Comment by essen** [comment]
Should be fixed in my copy, will push later today. It was possible for Cowboy to cancel the timer while having the timeout message in its queue already. Closing, thanks!
