### ISSUE TITLE
Cowboy handler terminate/3 exits before returning

### ISSUE THREAD

**Issue by aleklisi** [ninenines/cowboy#1397]
I create a simple handler with init just returning <<"hello world">> and status `200` and terminate that executes for a bit longer time (like 1 second) and instantaneously after receiving response from server I disconnect client which closes socket and kills process running terminate before it menages to finish its execution and return.

The minimal example (with detailed description) is here: https://github.com/aleklisi/cowboy_termiante_exit

**Comment by essen** [comment]
Yes you have to trap exits otherwise the process will stop when Cowboy calls `exit(Pid, shutdown)`.

**Comment by aleklisi** [comment]
@essen I could not find a word about it in the docs, and in fact they claim otherwise:
"The optional `terminate/3` callback will ultimately be called with the reason for the termination of the handler. Cowboy will terminate the process right after this. There is no need to perform any cleanup in this callback."
from
https://ninenines.eu/docs/en/cowboy/2.6/manual/cowboy_handler/
regarding this description it is a bug, right?

**Comment by essen** [comment]
It seems none of this is mentioned in the docs indeed. But the description isn't incorrect, this is what happens when the handler terminates normally. It's just missing details on what happens when shutdowns occur when the client closes the connection.

**Comment by aleklisi** [comment]
I mean (it is just intuition and I know we all may have different once but ) I would expect the terminate to end and return regardless of user being connected or not, right?

**Comment by essen** [comment]
No because the connection process is a supervisor, so when it stops it does a normal process shutdown of all its children. Note that this shutdown process is also used in HTTP/2 when the client cancels a stream.

**Comment by essen** [comment]
I should also add that there's no guarantee that terminate is ever called, because depending on the type of handler it might be stuck in user code longer than the configured shutdown timeout.

**Comment by OvermindDL1** [comment]
> I should also add that there's no guarantee that terminate is ever called

Among other reason: 
 https://gist.github.com/mrallen1/806fe5506132260574af33e99dadd499

**Comment by aleklisi** [comment]
@essen @OvermindDL1 thanks for explanation guys, it was very helpful as we had issue with that in https://github.com/esl/MongooseIM tests and I fixed it with: https://github.com/esl/MongooseIM/pull/2395
