### ISSUE TITLE
add hostname

### ISSUE THREAD

**Issue by fiodinggo** [ninenines/cowboy#1401]
hy essen, if you may know, what steps can I use to replace the hostname (which originally contained IP) in my http header?

Thank you in advance

**Comment by essen** [comment]
Edit the Req and return it? It's a public map.

Not sure I understand the question though.

**Comment by fiodinggo** [comment]
in my Req0, only show <<"host">> => <<"localhost:8910">>
but not show my hostname

**Comment by fiodinggo** [comment]
![Untitled 1](https://user-images.githubusercontent.com/17215221/64537470-10d35400-d345-11e9-8e4d-1669852e5307.png)

**Comment by essen** [comment]
That's what the connected client is sending. If you have a proxy in front, then that's what the proxy is sending. Cowboy just reads it.

**Comment by fiodinggo** [comment]
ok essen, thanx
