### ISSUE TITLE
How to obtain the current connection count?

### ISSUE THREAD

**Issue by Joker-vD** [ninenines/cowboy#1407]
What is the correct way to obtain the number of currently active HTTP/WebSocket connections? I've tried to count them manually in `init/2`+`terminate/3`+`websocket_init/1`, but it doesn't work reliably — for example, if the process running plain HTTP handler is killed while in `init/2` (for example, if the client closes the connection) then its `terminate/3` is never called.

**Comment by essen** [comment]
Hm wrong project? You want https://ninenines.eu/docs/en/ranch/2.0/manual/ranch.info/ In Cowboy the Websocket connections are `all_connections - active_connections`.

**Comment by Joker-vD** [comment]
@essen Thanks! And it's not "wrong project": the fact that Cowboy's WebSocket connections don't count as Ranch's `active_connections` is Cowboy's (undocumented) implementation detail.

**Comment by essen** [comment]
If Websocket connections not being counted is not in the current documentation please open a PR addressing that, it was not intentional.
