### ISSUE TITLE
Problems with a lot of data via SSE on many clients

### ISSUE THREAD

**Issue by Azer0s** [ninenines/cowboy#1408]
## Description

We are working on an [application](http://github.com/Accenture/reactive-interaction-gateway) that utilizes cowboy to send CloudEvents via SSE. I am currently working on performance tests for said application. When trying to run these performance tests I noticed some peculiar behaviour (100k CloudEvents (each 1kb) sent to n clients, connected via HTTP 1).

In the test, I the client just waits to receive 100k messages and checks how long that takes.

When connecting with about 10 clients, everything works as expected and all is good. But when I connect with more than 15 clients, things start to go sideways very quickly.

## Problems

We get these events via a Kafka consumer. Sometimes, clients would receive all 100k messages as soon as they have been produced. As soon as the client received 100k messages, it would then disconnect. One would assume that when one client disconnects, the other clients receive the messages quicker than they did before, but one would assume wrong. The contrary is the case and the clients actually take longer to receive the full 100k messages the more clients are done receiving their messages.

When connecting with 100 clients, the slowest client takes 3051s to receive the full 100k messages. 

<img width="551" alt="run2_100_clients" src="https://user-images.githubusercontent.com/16290284/66817526-220f1200-ef3c-11e9-8d31-e6509b9066a1.png">

When inspecting the application state with observer, I saw that the message queues of `cowboy_clear:connection_process/4` were ginormous. 

<img width="962" alt="msgq" src="https://user-images.githubusercontent.com/16290284/66817716-71554280-ef3c-11e9-995b-3e34f2cf65c1.png">

## Related

I saw both #1376 and #1402. I checked out from master to check if the fix actually worked for our system. Unfortunately, it didn't. The only change I could observe were a, sort-of, QoS like behaviour when sending.

Of course, it might just be that our SSE implementation is flawed. https://github.com/Accenture/reactive-interaction-gateway/blob/master/lib/rig_inbound_gateway_web/v1/sse.ex 

## Fix

I think a good solution would be implementing the same backpressure mechanism for HTTP 1 as was done for HTTP 2 in #1402. 

Does that sound like a plausible solution to you?

Thanks!

**Comment by essen** [comment]
There's no flow control in HTTP/1.1 so I'm not sure what you want me to implement.

**Comment by Azer0s** [comment]
@essen I know. But the main problem here is that our MsgQ's are overflowing (see 2nd image) and we sorta need a fix for that. Any ideas on that matter?

**Comment by essen** [comment]
I'm not sure why you end up with so many messages considering you should get stuck waiting for Cowboy's ack when streaming the response body, at least on master. See https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L871

**Comment by kevinbader** [comment]
So if `stream_events` _blocks_, the high number of queued-up messages could mean there's a problem within our application. Still, the performance of the SSE loop handler seems really bad: see below for an example that sends a MB of random events. With a client running on localhost I get only ~120 kB/s on my machine. Any thoughts on this?

```elixir
defmodule MySSE do
  @behaviour :cowboy_loop

  require Logger

  @alphabet Enum.to_list(?a..?z) ++ Enum.to_list(?0..?9)
  @chunk_size_b 1_000
  @total_size_b 1_000_000

  @impl :cowboy_loop
  def init(req, state) do
    req =
      :cowboy_req.stream_reply(
        200,
        %{
          "content-type" => "text/event-stream; charset=utf-8",
          "cache-control" => "no-cache",
          "access-control-allow-origin" => "*"
        },
        req
      )

    send(self(), :run)
    {:cowboy_loop, req, state}
  end

  @impl :cowboy_loop
  def info(:run, req, state) do
    {time, n_streamed_bytes} = :timer.tc(&stream_data/1, [req])
    IO.puts("Streamed #{n_streamed_bytes / 1_000} kB in #{time / 1_000_000} seconds.")

    finalize(req)

    {:stop, req, state}
  end

  # We generate @total_size_b of data by streaming random @chunk_size_b strings.
  defp stream_data(req, n_streamed_bytes \\ 0)

  defp stream_data(req, n_streamed_bytes) when n_streamed_bytes < @total_size_b do
    event = random_string() |> to_server_sent_event()
    send_via(event, req)

    event_as_string = Jason.encode!(event)
    stream_data(req, n_streamed_bytes + byte_size(event_as_string))
  end

  defp stream_data(_, n_streamed_bytes), do: n_streamed_bytes

  defp random_string, do: for(_ <- 1..@chunk_size_b, into: "", do: <<Enum.random(@alphabet)>>)

  defp to_server_sent_event(data) when byte_size(data) > 0 do
    %{
      data: data,
      event: "data_generated"
    }
  end

  defp send_via(event, cowboy_req) do
    :cowboy_req.stream_events(event, :nofin, cowboy_req)
  end

  defp finalize(cowboy_req) do
    :cowboy_req.stream_events(%{}, :fin, cowboy_req)
    Logger.debug(fn -> "Finalized SSE stream" end)
  end
end
```

**Comment by essen** [comment]
I don't really know what your code is doing. It doesn't look like you need a loop handler if you're going to just loop yourself. Other than that, I don't know what the code is doing exactly, but if you're creating random strings by choosing characters randomly one by one at runtime, that's probably your issue.

Cowboy has a test that sends 32MB of data streaming (not events, but it's not formatting the event that's gonna slow things down this much anyway). It takes between 0.9s and 3.5s depending on configuration, while other tests are running in parallel.

So I would say either there's something wrong with the test, or there's something wrong with the environment. If it's the latter then perhaps there's something I can do about it, but at this point I can't       say.

**Comment by kevinbader** [comment]
@essen you're right, the example wasn't really minimal, sorry about that. I've updated the example, removing the parts that aren't needed (including the randomizing part) and added some comments. These are the numbers I get:

n_total_bytes | n_data_bytes | kB/s | server time [s] | client time [s]
-- | -- | -- | -- | --
100000 | 10 | 0.179 | 10.84 | >5min
100000 | 100 | 5.89 | 4.1 | >5min
100000 | 1000 | 5500 | 2.45 | 17.3
1000000 | 10 | - | out of memory (total-vm:21145076kB) | -
1000000 | 100 | 0.646 | 44.45 | >5min
1000000 | 1000 | 60 | 23.27 | >5min

Executed on: Intel i5-4590S @ 3.00GHz / 4 cores, 16G total memory

Some observations:
- There is only one combination that lets the client finish in a reasonable amount of time.
- The real-world-ish use case of many small messages does not work (but maybe the machine is just too small).
- The server always finishes way before the client does, which is why we thought it'd be about message queues and missing backpressure of some sort. If the messages aren't on Cowboy's queues at that point, where could they be?

**Comment by essen** [comment]
Again there's not much I can do or look at here, please provide an Erlang example I can easily run if you want me to look at it.

Note that on localhost depending on the environment the socket buffers can be really big and if the client is too slow to consume them then the data may just accumulate there.

**Comment by Azer0s** [comment]
I rewrote the test in Erlang. I am using Cowboy 2.6.3 and jsone 1.5.1

### sse_handler.erl

```erlang
-module(sse_handler).
-behaviour(cowboy_loop).

-export([init/2, info/3]).

%% The size of a message's data value in bytes:
-define(n_data_bytes, 1000).
%% The total transmission size in bytes:
-define(n_total_bytes, 100000000).

init(Req0, State) ->
    Headers = #{
        "content-type" => <<"text/event-stream; charset=utf-8">>,
        "cache-control" => <<"no-cache">>,
        "access-control-allow-origin" => <<"*">>
    },

    %% Set up the connection:
    Req = cowboy_req:stream_reply(200, Headers, Req0),

    self() ! run,

    {cowboy_loop, Req, State}.

info(run, Req, State) ->
    %% Run stream_data and measure execution time:
    {Time, N_streamed_bytes} = timer:tc(fun() -> stream_data(Req) end),

    io:format("Streamed ~w kB in ~w seconds.", [N_streamed_bytes, Time / 1000000]),

    %% Close the SSE connection:
    cowboy_req:stream_events(#{}, fin, Req),

    %% ..and stop the loop handler:
    {stop, Req, State}.

duplicate(Str, Times) ->
    string:join(lists:duplicate(Times, Str),"").

stream_data(Req) ->
    stream_data(Req, 0).

%% Sends at least @n_total_bytes of data through the SSE stream.
stream_data(Req, N_streamed_bytes) when N_streamed_bytes < ?n_total_bytes ->
    Event = #{data => duplicate("X", ?n_data_bytes)},
    cowboy_req:stream_events(Event, nofin, Req),

    %% Estimate the message size (lower bound) and count it to the number of sent bytes:
    Event_as_string = jsone:encode(Event),
    io:write(Event_as_string),
    stream_data(Req, N_streamed_bytes + byte_size(Event_as_string));
stream_data(_, N_streamed_bytes) ->
    N_streamed_bytes.
```

### mysse_app.erl

```erlang
-module(mysse_app).
-behaviour(application).

-export([start/2]).
-export([stop/1]).

start(_Type, _Args) ->
    Dispatch = cowboy_router:compile([
        {'_', [{"/", sse_handler, []}]}
    ]),
    {ok, _} = cowboy:start_clear(my_http_listener,
        [{port, 8080}],
        #{env => #{dispatch => Dispatch}}
    ),
    mysse_sup:start_link().

stop(_State) ->
	ok.
```

### mysse_sup.erl

```erlang
-module(mysse_sup).
-behaviour(supervisor).

-export([start_link/0]).
-export([init/1]).

start_link() ->
	supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
	Procs = [],
	{ok, {{one_for_one, 1, 5}, Procs}}.
```

**Comment by Azer0s** [comment]
I rewrote the test in Erlang. I am using Cowboy 2.6.3 and jsone 1.5.1
I am testing with cURL like so `curl -X GET 'localhost:8080' -H 'Expect:'`.

### sse_handler.erl

```erlang
-module(sse_handler).
-behaviour(cowboy_loop).

-export([init/2, info/3]).

%% The size of a message's data value in bytes:
-define(n_data_bytes, 1000).
%% The total transmission size in bytes:
-define(n_total_bytes, 100000000).

init(Req0, State) ->
    Headers = #{
        "content-type" => <<"text/event-stream; charset=utf-8">>,
        "cache-control" => <<"no-cache">>,
        "access-control-allow-origin" => <<"*">>,
        "connection" => <<"keep-alive">>
    },

    %% Set up the connection:
    Req = cowboy_req:stream_reply(200, Headers, Req0),

    self() ! run,

    {cowboy_loop, Req, State}.

info(run, Req, State) ->
    %% Run stream_data and measure execution time:
    {Time, N_streamed_bytes} = timer:tc(fun() -> stream_data(Req) end),

    io:format("Streamed ~w kB in ~w seconds.", [N_streamed_bytes, Time / 1000000]),

    %% Close the SSE connection:
    cowboy_req:stream_events(#{}, fin, Req),

    %% ..and stop the loop handler:
    {stop, Req, State}.

duplicate(Str, Times) ->
    string:join(lists:duplicate(Times, Str),"").

stream_data(Req) ->
    stream_data(Req, 0).

%% Sends at least @n_total_bytes of data through the SSE stream.
stream_data(Req, N_streamed_bytes) when N_streamed_bytes < ?n_total_bytes ->
    Event = #{data => duplicate("X", ?n_data_bytes)},
    cowboy_req:stream_events(Event, nofin, Req),

    %% Estimate the message size (lower bound) and count it to the number of sent bytes:
    Event_as_string = jsone:encode(Event),
    stream_data(Req, N_streamed_bytes + byte_size(Event_as_string));
stream_data(_, N_streamed_bytes) ->
    N_streamed_bytes.
```

### mysse_app.erl

```erlang
-module(mysse_app).
-behaviour(application).

-export([start/2]).
-export([stop/1]).

start(_Type, _Args) ->
    Dispatch = cowboy_router:compile([
        {'_', [{"/", sse_handler, []}]}
    ]),
    {ok, _} = cowboy:start_clear(my_http_listener,
        [{port, 8080}],
        #{env => #{dispatch => Dispatch}}
    ),
    mysse_sup:start_link().

stop(_State) ->
	ok.
```

### mysse_sup.erl

```erlang
-module(mysse_sup).
-behaviour(supervisor).

-export([start_link/0]).
-export([init/1]).

start_link() ->
	supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
	Procs = [],
	{ok, {{one_for_one, 1, 5}, Procs}}.
```

**Comment by essen** [comment]
I don't really understand. Your `duplicate/2` function is still doing a lot of pointless operations. If you really want to test Cowboy you need to use literals, like `<<"aaaaaaaaaaaaaaaaaaaaaaa...">>`. Macros can help build large strings at compile time. Then there's the `jsone:encode/1` which seems entirely unnecessary and not at all representative of how much data was sent? SSE doesn't use JSON.

Anyway after fixing this, and using the following handler:

```
%% Feel free to use, reuse and abuse the code in this file.

%% @doc Hello world handler.
-module(toppage_h).

-export([init/2]).

-define(data, <<"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">>).
%% The size of a message's data value in bytes:
-define(n_data_bytes, 1000).
%% The total transmission size in bytes:
-define(n_total_bytes, 100000000).

init(Req0, Opts) ->
    Headers = #{
        "content-type" => <<"text/event-stream; charset=utf-8">>,
        "cache-control" => <<"no-cache">>,
        "access-control-allow-origin" => <<"*">>,
        "connection" => <<"keep-alive">>
    },

    %% Set up the connection:
    Req = cowboy_req:stream_reply(200, Headers, Req0),

    {Time, N_streamed_bytes} = timer:tc(fun() -> stream_data(Req) end),

    io:format("Streamed ~w kB in ~w seconds.", [N_streamed_bytes, Time / 1000000]),

    %% Close the SSE connection:
    cowboy_req:stream_events(#{}, fin, Req),

	{ok, Req, Opts}.

stream_data(Req) ->
    stream_data(Req, 0).

%% Sends at least @n_total_bytes of data through the SSE stream.
stream_data(Req, N_streamed_bytes) when N_streamed_bytes < ?n_total_bytes ->
	Data = ?data,
    Event = #{data => Data},
    cowboy_req:stream_events(Event, nofin, Req),

    %% Estimate the message size (lower bound) and count it to the number of sent bytes:
    stream_data(Req, N_streamed_bytes + ?n_data_bytes);
stream_data(_, N_streamed_bytes) ->
    N_streamed_bytes.
```

With your command I get:

```
Streamed 100000000 kB in 5.527956 seconds.
curl -X GET 'localhost:8080' -H 'Expect:'  0,05s user 0,48s system 8% cpu 6,194 total
```

But curl prints all the events in the terminal. Terminals are super slow, so let's pipe the curl output to a file instead:

```
Streamed 100000000 kB in 1.079534 seconds.
$ time curl -X GET 'localhost:8080' -H 'Expect:' > /tmp/out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96.1M    0 96.1M    0     0  89.0M      0 --:--:--  0:00:01 --:--:-- 89.0M
curl -X GET 'localhost:8080' -H 'Expect:' > /tmp/out  0,30s user 0,46s system 70% cpu 1,089 total
$ ls -l /tmp/out 
-rw-r--r-- 1 essen essen 100800001 16 oct.  14:19 /tmp/out
```

1 second is pretty good for streaming 100MB of events. The culprit was therefore `curl` which probably does a receive+print loop and printing to the terminal is slower than sending/receiving data, at least for localhost.

**Comment by Azer0s** [comment]
Even when piping `curl` into `/tmp/out` or `/dev/null`, it is still taking about 16-20 seconds. I can assure you that it is not my machine as it is plenty powerful.

**Comment by essen** [comment]
If you think Cowboy is slow then you should demonstrate that using only Cowboy. If you add JSON on top, then it might be the JSON code that's slow, not Cowboy. If you do duplicate operations, then it might be those. And so on. When benchmarking something you have to make sure it's not the benchmark tool or other external software that slows things down.

As far as I can see, whatever your issue is (and I'm not saying there isn't one because obviously something is going on), it does not appear to be in Cowboy. Cowboy can stream 100MB of events in 1 second. And like I said there's a 32MB stream test running fine as well (except on Windows when using TLS, but that's probably because the CI VM is misconfigured or something). So as far as Cowboy is concerned the ticket is closed unless you can show otherwise.
