### ISSUE TITLE
perf testing:  reducing client errors related to connection_closing

### ISSUE THREAD

**Issue by randysecrist** [ninenines/cowboy#1409]
I am trying to (in a application I have) trying to reducing client side `connection_closing` errors (while cowboy is under load) and I haven't been able to fully eliminate them.  I'm down to a handful (10-20) over the course of a 60 second test at max load; but I've had to strip out (of my cowboy app) functionality to get this number to drop from what was initially 1500-2000 of them.  Usually the errors start to occur about 15 to 25 seconds into the test run.

So after a bit of effort ... I figured I would pause and ask and see if I could be missing something more ... fundamental.  If this isn't the right place to ask; just let me know how we could engage.  Thanks!

some usage / config information:
* latest release (2.6.3)
* single handler that supports a GET request which returns a few bytes of content type `text/plain`
* `max_connections` at infinity
* `max_keepallive` at 1_000
* test concurrency at 750
* 4.15.0-1039-aws #41-Ubuntu SMP Wed May 8 10:43:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* CPU: 2
* t1.micro
* h1 (http 1.1)
* erlang 22

**Comment by essen** [comment]
Could you explain what `connection_closing` means?

**Comment by randysecrist** [comment]
The client is [basho_bench](https://github.com/basho/basho_bench) using [ibrowse](https://github.com/cmullaparthi/ibrowse) and I believe it is reporting whatever socket state it detects when it can't establish a connection.  This is where `connection_closing` comes from.  Using `ss` I can see *some* (more work required) connections are in `CLOSING` state.  TBH I'm wondering if I am bumping up against the 64k port limit and the OS is trying to keep up with providing enough sockets ... ?

A few additional observations:

- h2load (another perf tool I used for a double blind) only shows failures using h1.  h2 ... no errors.
- ibrowse (v4.1.1) reports the following errors (using h1 only)

* `{error, connection_closed_no_retry}`
* `{error, connection_closing}`
* `{error, req_timedout}`

**Comment by essen** [comment]
Cowboy has a `linger_timeout` during which it will wait for a proper TCP close after having shutdown the connection for writing. You may want to disable it `linger_timeout => 0` to see if that's simply what you're seeing.

HTTP/2 has a proper shutdown mechanism so it's not surprising that the client would not see errors.

By the way the latest release is 2.7.0, not 2.6.3.

**Comment by stofel** [comment]
Get same error and cowboy crash 
`Ranch listener my_http_listener had connection process started with cowboy_clear:start_link/4 at <0.30213.62> exit with reason: {badarith,[{erlang,'+',[infinity,64000],[]},{cowboy_http,commands,3,[{file,"/home/alexs/work/psp/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,948}]},{cowboy_http,loop,1,[{file,"/home/alexs/work/psp/_build/default/lib/cowboy/src/cowboy_http.erl"},{line,234}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
`

**Comment by essen** [comment]
I've fixed a timeout and a crash issue in 69aafd5b74fba390968e87a2494f6ac0da99497b so you may want to try this commit and see if you still see connection_closing during perf testing.

**Comment by randysecrist** [comment]
Initial tests seem much better.  Perhaps I forgot how I was testing; let me try to reproduce under 2.7.0 to make sure.

**Comment by essen** [comment]
I'll close the ticket for now, please open a new one if there's still an issue. If you test, make sure to test `master` which has the fixes, and not 2.7.0 which doesn't (or at least not all of them). Thanks!
