### ISSUE TITLE
bad argument in arithmetic expression

### ISSUE THREAD

**Issue by schnittchen** [ninenines/cowboy#1413]
Hello,

our error monitoring caught this exception (is it badarg in Erlang land?) a few days ago:

```
:erlang.+/2
(cowboy) /app/deps/cowboy/src/cowboy_http.erl:948: :cowboy_http.commands/3
(cowboy) /app/deps/cowboy/src/cowboy_http.erl:234: :cowboy_http.loop/1
proc_lib.erl:249 :proc_lib.init_p_do_apply/3
```

We are using cowboy 2.7.0 from hex inside an Elixir Phoenix application.

**Comment by ehamberg** [comment]
Looks like this could be the same as #1411.

**Comment by essen** [comment]
See #1411
