### ISSUE TITLE
Downloading file with cowboy

### ISSUE THREAD

**Issue by imgrey** [ninenines/cowboy#1414]
Hello

I'm trying to serve file from Riak CS object storage using Cowboy, but sometimes browser hangs for eternity. Sometimes it starts download, but then connection terminates. I assume this is because of timeout, built-in to Cowboy.

How to serve big file with Cowboy ?

init(Req0, Opts) ->
                    ContentDisposition = << <<"attachment;filename=">>/binary, OrigName/binary >>,
                    Req1 = cowboy_req:stream_reply(200, #{
                        <<"content-type">> => ContentType,
                        <<"content-disposition">> => ContentDisposition,
                        <<"content-length">> => Bytes
                    }, Req0),
                    {ok, RequestId} = riak_api:get_object(BucketId, RealPath, self()),
                    receive
                        {http, {RequestId, {_StatusLine, _Headers, Body}}} ->
                            cowboy_req:stream_body(Body, nofin, Req1)
                    end,
                    cowboy_req:stream_body(<<>>, fin, Req1),
                    {ok, Req1, Opts}

**Comment by essen** [comment]
Check the `idle_timeout` option: https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_http/

**Comment by imgrey** [comment]
How to use the idle_timeout option ?
I've tried it in past, but it never worked.
Could you provide a usage example ?

**Comment by essen** [comment]
``` erlang
{ok, _} = cowboy:start_clear(Name, [], #{
    env => #{dispatch => Dispatch},
    idle_timeout => 300000 %% 5 minutes
}),
