### ISSUE TITLE
Required has_body missing for response with code = 400

### ISSUE THREAD

**Issue by kpy3** [ninenines/cowboy#1417]
Here is an error message from log:

```
Log access failed for: [400, #{<<"connection">> => <<"close">>,<<"content-length">> => <<"0">>}, #{headers => #{<<"accept">> => <<"image/gif, i"...>>,<<"accept-chars"...>> => <<"iso-8859-1,*"...>>,<<"accept-langu"...>> => <<"en">>,<<"cache-co"...>> => <<"no-cache">>,...},method => <<"GET">>,path => <<"/acute-cp/">>,peer => {{10756,18944,...},48951},...}]
with: error:function_clause
stacktrace: in call to cowboy_req:has_body(#{headers => #{<<"accept">> => <<"image/gif, image/x-xbitm...">...) at /home/jenkins/jenkins-agent/jenkins-agent/workspace/ey_private_fistful-server_master/_build/default/lib/cowboy/src/cowboy_req.erl:466
	called from cowboy_access_log_h:get_request_body_length/1 at /home/jenkins/jenkins-agent/jenkins-agent/workspace/ey_private_fistful-server_master/_build/default/lib/cowboy_access_log/src/cowboy_access_log_h.erl:122
	called from cowboy_access_log_h:prepare_meta/3 at /home/jenkins/jenkins-agent/jenkins-agent/workspace/ey_private_fistful-server_master/_build/default/lib/cowboy_access_log...
```

It look like there is no `has_body` attribute in request, possibly because where is a problem with request and it goes thru `cowboy_http:error_terminate/4`.

**Comment by essen** [comment]
What do you mean by required? If it goes through `error_terminate` then it calls `early_error` which gives you a `PartialReq :: map()` and not a `cowboy_req:req()`. In other words you get the values Cowboy figured out up until that point.

**Comment by kpy3** [comment]
I mean it required by type specification [here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L146) and by code [here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L497).

**Comment by kpy3** [comment]
So if I get PartialReq :: map() how can I detect it?

**Comment by essen** [comment]
You are under the impression that `early_error` receives the Req, it does not, see https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_stream/#_callbacks

```
PartialReq  - cowboy_req:req(), except all fields are optional
```

It doesn't really matter if there's a body or not as far as Cowboy is concerned because it will just close the connection without attempting to read more. Sometimes it has not read enough to be able to know there is or is not a request body.

**Comment by kpy3** [comment]
I see, thanks!
