### ISSUE TITLE
cowboy_req:parse_header vs "X-Something" header

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1418]
(cowboy 2.7.0, OTP 21)

the call:
 {undefined, BClientIP} = cowboy_req:parse_header(<<"x-real-ip">>, Req0)

throws:
{request_error, {header,<<"x-real-ip">>}, 'Malformed header. Please consult the relevant specification.'}

Req0 contains:
headers = #{....., <<"x-real-ip">> => <<"127.0.0.1">>}

The doc promised:
Unknown headers result in
parse_header(_, Req) -> {undefined, RawValue}

?

**Comment by essen** [comment]
So the correct documentation is https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_req.parse_header/#_description

The part at the bottom about unknown headers must be a leftover from Cowboy 1.x that was not noticed when changing the description. I'll fix it soon, thanks!

**Comment by essen** [comment]
Done locally, push soon, thanks!
