### ISSUE TITLE
Cowboy+TLS vs SPDY

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#1419]
while having my Cowboy exposed to the internet I have stumbled upon an SPDY error, as reported by chromium: "net::ERR_SPDY_PROTOCOL_ERROR" (while firefox drops the request SILENTLY)
the problem was solved by moving the Cowboy behind an Nginx (keeping my code intact) so it is likely Cowboy's failure to comply to some quirks of SPDY.

the problem appeared exactly when the functional website moved from HTTP to HTTPS.
only AJAX queries failed (cowboy's ws handlers are working fine) (and everything works fine without TLS)

the failed query gets to its handler, properly handled, and the handler terminates normally, and even the response gets delivered (i can see its headers in firefox).

i dont know what parts of my code could be relevant, since everything worked without errors. (CORS was satisfied too)

**Comment by eugene-panferov** [comment]
Cowboy 2.7, OTP 22

**Comment by essen** [comment]
It's probably the TLS requirements for HTTP/2 which Cowboy doesn't enforce. You need to make sure the certificate and TLS options are correct.

**Comment by eugene-panferov** [comment]
the Nginx in this setup runs with the exactly same certificate.

**Comment by essen** [comment]
So the TLS options.

**Comment by essen** [comment]
Hope you solved the issue. Closing, thanks!
