### ISSUE TITLE
cowboy:reply error

### ISSUE THREAD

**Issue by imgrey** [ninenines/cowboy#1420]
The following code raises error:
    Req1 = cowboy_req:set_resp_body(jsx:encode([{error, MsgCode}]), Req0),  %% binary
    Req2 = cowboy_req:reply(400, #{
        <<"content-type">> => <<"application/json">>
    }, Req1),
    {true, Req2, []}.

[error] CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: no function clause matching cowboy_req:reply/4 line 684 in cowboy_req:reply/4 line 684

But the reply is sent to client ok.

**Comment by essen** [comment]
If you are using `cowboy_rest` and send the response manually you have to return `stop`. But considering you seem to be in an `AcceptResource` function perhaps you should just call `set_resp_header` and then return `false` and Cowboy will send the error automatically.
