### ISSUE TITLE
Fail2Ban

### ISSUE THREAD

**Issue by bachehkaraji** [ninenines/cowboy#1423]
How To Protect a Cowboy Server with Fail2Ban?

**Comment by essen** [comment]
Sounds like a tool that does things based on log files? So start by writing log files perhaps with the metrics stream handler and then ???

It's a bit out of scope to be honest.

**Comment by OvermindDL1** [comment]
Yeah it's definitely not a cowboy side issue.  The OP will just need to write logs in either an existing format that fail2ban already knows (nginx, apache, etc...), which is pretty easy to do, or write a new fail2ban log parser for whatever custom log format they actually output, which is also not hard to it, but it's definitely on the application or fail2ban side, not cowboy.  :-)
