### ISSUE TITLE
Cowboy can't serve file, when content-disposition has a long name

### ISSUE THREAD

**Issue by imgrey** [ninenines/cowboy#1425]
The code below works with shorter filenames. But with name of 112 bytes, it raises exception

[error] CRASH REPORT Process <0.757.0> with 0 neighbours exited with reason: {{undef,[{stop,upgrade,[#{bindings => #{},body_length => 0,has_body => false,has_sent_resp => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"identity">>,<<"host">> => <<"xentime.com">>,<<"user-agent">> => <<"Wget/1.18 (linux-gnu)">>,<<"x-forwarded-for">> => <<"31.28.168.162">>,<<"x-real-ip">> => <<"31.28.168.162">>},host => <<"xentime.com">>,host_info => undefined,method => <<"GET">>,path => <<"/riak/download/the-greenhouse-test-res/life.in.pieces.s01e01.720p.hdtvr...">>,...},...],...},...]},...}

receive_streamed_body(Req0, RequestId) ->
    receive
        {http, {RequestId, stream, BinBodyPart}} ->
            cowboy_req:stream_body(BinBodyPart, nofin, Req0),
            receive_streamed_body(Req0, RequestId);
        {http, {RequestId, stream_end, _Headers}} ->
            cowboy_req:stream_body(<<>>, fin, Req0);
        {http, Msg} ->
            ?ERROR("[download_handler] error receiving stream: ~p", [Msg]),
            cowboy_req:stream_body(<<>>, fin, Req0)
    end.

receive_streamed_body(Req0, RequestId, Pid) ->
    httpc:stream_next(Pid),
    receive
        {http, {RequestId, stream, BinBodyPart}} ->
            cowboy_req:stream_body(BinBodyPart, nofin, Req0),
            receive_streamed_body(Req0, RequestId, Pid);
        {http, {RequestId, stream_end, _Headers}} ->
            cowboy_req:stream_body(<<>>, fin, Req0);
        {http, Msg} ->
            ?ERROR("[download_handler] error receiving stream body: ~p", [Msg]),
            cowboy_req:stream_body(<<>>, fin, Req0)
    end.

                    ContentDisposition = << <<"attachment;filename=">>/binary, OrigName/binary >>,
                    Headers0 = #{
                        <<"content-type">> => ContentType,
                        <<"content-disposition">> => ContentDisposition,
                        <<"content-length">> => Bytes
                    },
                    Headers1 =
                        case Range of
                            undefined -> Headers0;
                            _ -> maps:put(<<"range">>, Range, Headers0)
                        end,
                    Req1 = cowboy_req:stream_reply(200, Headers1, Req0),
                    {ok, RequestId} = riak_api:get_object(OldBucketId, RealPath, stream),
                    receive
                        {http, {RequestId, stream_start, _Headers}} ->
                            receive_streamed_body(Req1, RequestId);
                        {http, {RequestId, stream_start, _Headers, Pid}}  ->
                            receive_streamed_body(Req1, RequestId, Pid);
                        {http, Msg} ->
                            ?ERROR("[download_handler] stream error: ~p", [Msg])
                    end,

**Comment by essen** [comment]
It's probably not the whole story.

Do you return `stop` somewhere and if so where?

**Comment by imgrey** [comment]
So the reason of the issue was in missing quotes around filename, containing ",".

Chrome returned error:
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

Sorry for bothering.

**Comment by essen** [comment]
Yeah, and you should return `ok` not `stop` as well.
