### ISSUE TITLE
Timeout handler cowboy_http:timeout/2 crashes on "ps_body"

### ISSUE THREAD

**Issue by eseres** [ninenines/cowboy#1426]
The cowboy_http:timeout/2 (cowboy 2.6.3) is called internally with ‘ps_body’ which cowboy_http:timeout/2 doesn’t implement a clause for:

`2019-12-20T04:13:39.556507+00:00 error: Ranch listener my_redacted_listener had connection process started with my_redacted_listener:start_link/4 at <0.22918.101> exit with reason: {function_clause,[{cowboy_http,timeout,[{state,<0.1604.0>,my_redacted_listener,{sslsocket,{gen_tcp,#Port<0.307538>,tls_connection,undefined},[<0.22924.101>,<0.22814.101>]},ranch_ssl,#{env => #{protocol_opts => #{idle_timeout => 300000,inactivity_timeout => 320000,request_timeout => 15000}},idle_timeout => 300000,inactivity_timeout => 320000,middlewares => [my_redacted_middleware,cowboy_handler],request_timeout => 15000,stream_handlers => [cowboy_stream_h]},{{127,0,0,1},24442},{{127,0,0,1},2055},undefined,#Ref<0.868493489.54263809.1954>,1,{ps_body,46766,32483,fun cow_http_te:stream_identity/2,{32483,46766}},2,wait,100,[],[]},request_timeout],[{file,"/opt/app/releases/default/lib/cowboy/src/cowboy_http.erl"},{line,239}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}`

**Comment by essen** [comment]
https://github.com/ninenines/cowboy/issues/1395 probably. Please try 2.7.0.
