### ISSUE TITLE
TLS fatal unexpected message with self-signed SSL certificate for localhost

### ISSUE THREAD

**Issue by michelleran** [ninenines/cowboy#1431]
I'm trying to run Cowboy with HTTPS on localhost:8080 (using Elixir and Plug) and have generated a key and certificate with the following command (as per https://letsencrypt.org/docs/certificates-for-localhost/):

```
openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

However, when I navigate to localhost:8080, this error is produced several times:

```
[info]  TLS :server: In state :hello at tls_record.erl:471 generated SERVER ALERT: Fatal - Unexpected Message
```

The app is a simple chatting test over Websockets but this error still occurs with that code commented out. Here's what's passed into `Plug.Cowboy.child_spec`:

```
Plug.Cowboy.child_spec(
    scheme: :https,
    plug: WebsocketChat.Router,
    options: [
          dispatch: dispatch(),
          port: 8080,
          cipher_suite: :compatible,
          otp_app: :websocket_chat,
          keyfile: "priv/ssl/localhost.key",
          certfile: "priv/ssl/localhost.crt"
    ]
)
```

I also tried using the .key and .cert files in [ssl_hello_world](https://github.com/ninenines/cowboy/tree/master/examples/ssl_hello_world) (trusted the root certificate authority).

Any help would be appreciated!

**Comment by michelleran** [comment]
Got it working with the .key and .cert files from ssl_hello_world - turns out I missed trusting the localhost certificate!

**Comment by essen** [comment]
Glad I could help. :-)
