### ISSUE TITLE
Fix HTTP/2 CVEs commit - how to work with change

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1433]
Commit ab44985a9eeb1f664f38d6049a2532d83de7fa18 made it so my upload a file to server code stops at 20-30%.  I found some options that can be changed, but I'm not sure which to change.  Can you give some tips?

in someapp_app.erl in this code:

{ok, _} = cowboy:start_tls(https, [
		{port, 8443},
		{cacertfile, PrivDir ++ "/ssl/cowboy-ca.crt"},
		{certfile, PrivDir ++ "/ssl/server.crt"},
		{keyfile, PrivDir ++ "/ssl/server.key"}
	], #{env => #{dispatch => Dispatch}})

Is there something I can change in the #{env => #{dispatch => Dispatch}} to allow up to 5 gig size files to be copied to the server?

Thanks

**Comment by essen** [comment]
It's probably the `max_received_frame_rate` option. It is currently too low by default. It will be increased in 2.8.

You can probably make it x10 the default value.

https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_http2/

**Comment by comptekki** [comment]
OK.  I did something like this:

#{env => #{dispatch => Dispatch, max_received_frame_rate => {10000,
100000}}}

and it's working again.

Thanks!

**Comment by comptekki** [comment]
I just tried this and it worked:

#{env => #{dispatch => Dispatch, max_received_frame_rate => {10000, 10000}}}

I'll stick with this.
