### ISSUE TITLE
Cowboy 2.7.0 download 10Gb file from object storage by HTTP

### ISSUE THREAD

**Issue by imgrey** [ninenines/cowboy#1437]
Hello

I'm trying to download 10 Gb file using Cowboy 2.7.0 and the following code.

https://github.com/xentime/dubstack-middleware/blob/master/src/download_handler.erl

I can download up to 400 MB, then I receive bad gateway error from nginx, as Cowboy closes connection, I assume.

Memory consumption do not increase on the server at all. This is good.

**Comment by essen** [comment]
Probably just need to increase `idle_timeout` if it's HTTP/1.1. You can do it dynamically in more recent releases.

**Comment by imgrey** [comment]
But the idle_timeout is 12 hours: https://github.com/xentime/dubstack-middleware/blob/master/src/middleware_app.erl#L55

**Comment by essen** [comment]
Then try to trace or find the Cowboy reason for closing the connection, I can't do anything from the above report.
