### ISSUE TITLE
No way to retrieve the url decoded/routed URL

### ISSUE THREAD

**Issue by bipthelin** [ninenines/cowboy#1438]
Is there a way to retrieve the resolved URL used for routing from a handler? Consider this routing:
```erlang
{"/a/:key", toppage_h, [a]},
{"/b/:key", toppage_h, [b]}
```
and the following cURL:
```bash
$ curl -vvv --path-as-is localhost:8080/a/../b/123
```
Cowboy will route this to the `b` endpoint and execute that handler based on a resolved path like `localhost:8080/b/123`. But the path-object in the `Req` object will have the path as it was sent in, i.e. `localhost:8080/a/../b/123`.

It would be nice if you could somehow retrieve the resolved path which is the actual url that Cowboy is using to do its internal routing, maybe like: `cowboy_req:resolved_path/1`.

**Comment by essen** [comment]
You mean it will have `/a/../b/123`.

You should be able to just call `uri_string:normalize` to get the normalized path.

**Comment by bipthelin** [comment]
Nice, haven't seen that function before.
Is that what Cowboy is using underneath? If not there's still the issue possible(probable?) discrepancy and bugs existing which would have corner cases in which they will provide different outputs. I.e. Cowboy routes to a handler whereas `uri_string:normalize/1` is reporting something different.

**Comment by essen** [comment]
It's the same algorithm but not the same function... yet. `uri_string` was introduced relatively recently. I will probably update `cowboy_router` at some point to remove this unnecessary code. Or I might end up changing the router to https://github.com/ninenines/farwest/blob/master/src/farwest_router.erl#L107 which already uses `uri_string:normalize` (follow link for an example usage).

No real plans to do anything at this point though.

**Comment by bipthelin** [comment]
Thanks for feedback. Closing this issue.
