### ISSUE TITLE
`cowboy_router` failing to serve requests

### ISSUE THREAD

**Issue by Zenohate** [ninenines/cowboy#1439]
Erlang OTP/22.0
Elixir 1.9.1
Debian / WSL

`cowboy_router` crashes on every request sent, not sending a reply. 

## Expected Behavior

A reply is sent, if the route is unknown it may be a 40X reply.

## Current Behavior
No reply is sent. An error message is printed back on the shell:
```
12:29:12.151 [error] Ranch listener :http_listener, connection process #PID<0.208.0>, stream 1 had its request process #PID<0.209.0> exit with reason :function_clause and stacktrace [{:cowboy_router, :execute, [%{body_length: 0, cert: :undefined, has_body: false, headers: %{"accept" => "*/*", "host" => "localhost:8080", "user-agent" => "curl/7.67.0"}, host: "localhost", method: "GET", path: "/", peer: {{127, 0, 0, 1}, 56460}, pid: #PID<0.208.0>, port: 8080, qs: "", ref: :http_listener, scheme: "http", sock: {{127, 0, 0, 1}, 8080}, streamid: 1, version: :"HTTP/1.1"}, [dispatch: [{:_, [], []}]]], []}, {:cowboy_stream_h, :execute, 3, [file: '/home/archivist/web/deps/cowboy/src/cowboy_stream_h.erl', line: 320]}, {:cowboy_stream_h, :request_process, 3, [file: '/home/archivist/web/deps/cowboy/src/cowboy_stream_h.erl', line: 302]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]
```

## Steps to Reproduce
1. Unpack the test project [web.zip](https://github.com/ninenines/cowboy/files/4244310/web.zip)
2. With Elixir installed and Erlang OTP/22, run `mix deps.get & mix deps.compile`
3. Run `iex -S mix` to start the project, then `Web.start` to start the server
4. Try to connect to `localhost:8080/` in http

## Additional information
I am sorry to provide the project in Elixir but I don't trust ly Erlang to translate the project into it accurately and am not sure if the error may be related to Elixir. The project is expected to return a 404 in the provided example but it does not.

**Comment by essen** [comment]
The `env` is a map. You gave a proplist.
