### ISSUE TITLE
setting idle timeout past 120_000 doesn't seem to work.

### ISSUE THREAD

**Issue by phlare** [ninenines/cowboy#1441]
recently updated a number of deps in my elixir app including cowboy (from 1.2.1)  and noticed that my long running scripts were all stopping at exactly 60 seconds.

this led me to the cowboy docs where i discovered the idle_timeout setting, which i'm setting in the config of my umbrella app.

http: [
  port: 4000,
  protocol_options: [idle_timeout: :infinity]
],

this seemed to work, but then i noticed that the longer of my long-running scripts are STILL timing out silently at exactly 2 minutes.

I've testing setting this setting to 110_000 and it forces those scripts to time out properly, and adjusting it certainly extended past the default of 60_000 but the max seems to be 120_000 for some reason.

I also tried 150_000 to  see if maybe :infinity was being parsed strangely, but that didn't help either.

any thoughts?    My guess is that some other timeout somewhere else is triggering and it's not cowboy, but since there is no log or error or any emission of any sort when this happens I'm at a loss.

EDIT: worth noting that scripts locally will run indefinitely with the same configs, but this two-minute wall only occurs when i test in my staging cluster, and if i downgrade back to plug_cowboy 1.2.1 without changing any other deps, the scripts will run indefinitely again.

**Comment by essen** [comment]
Enable `cowboy_metrics_h` stream handler and log what it gives you.

**Comment by phlare** [comment]
@essen how would i do that?  (I've never used a stream handler that i'm aware of)

**Comment by OvermindDL1** [comment]
Are you sure one or the other side OS isn't closing the non-transmitting TCP connection after 2 minutes, or the client side program isn't closing it?

**Comment by phlare** [comment]
calling from postman, so it's not my client killing the connection, but i wonder if it's something in the network chain on the server end, the ingress node or load balancer perhaps.

thanks for the suggestions on where to check.   going to close this for now as it's not likely a cowboy issue, but just through i might get a few pointers from you all.   thanks

**Comment by phlare** [comment]
yup.  it was my Google Cloud backend service for the load balancer.   d'oh
