### ISSUE TITLE
docker alpine cowboy

### ISSUE THREAD

**Issue by kklepper** [ninenines/cowboy#1443]
I want to use Cowboy like Yaws or Caddy or Apache or NGINX in a stack serving PHP. 

This should be possible, but I have no clue how to do that.

After many hours of research for something which should be very easy to find (docker alpine cowboy) I run out of ideas. 

https://github.com/erlang/docker-erlang-example/ does produce a docker alpine container with cowboy, but I don't understand what happens there - see https://github.com/erlang/docker-erlang-example/issues/11

**Comment by essen** [comment]
I do not have one such example for a few simple reasons: Cowboy is a server library, not a full-fledged server. In other words, Cowboy is NOT like Yaws, Caddy, Apache or Nginx. You could write a server like those if you wanted to, but that's out of scope of Cowboy itself.

Amongst other things does not include support for FCGI, CGI or other similar mechanisms. Maybe https://github.com/unix1/cowboy_fcgi would work, but I did not try it.

It's also not a server that sets up itself from a configuration file, it's just a library and you therefore need to write code.

That said it's not that I'm against writing or maintaining proper FCGI support (or other mechanisms), it's just that customers haven't needed it.

**Comment by kklepper** [comment]
Ok, thanks, understood.
