### ISSUE TITLE
Compilation error in cowboy_handler.erl:45: illegal pattern

### ISSUE THREAD

**Issue by hviagov** [ninenines/cowboy#1444]
Trying to compile with OTP/19 leads to the following error:

===>      Compiled cowboy_middleware.erl
===> Compiling _build/default/lib/cowboy/src/cowboy_handler.erl failed
_build/default/lib/cowboy/src/cowboy_handler.erl:45: illegal pattern
_build/default/lib/cowboy/src/cowboy_handler.erl:46: variable 'Reason' is unbound
_build/default/lib/cowboy/src/cowboy_handler.erl:47: variable 'Stacktrace' is unbound

===> Compilation failed: {error,
                                    [["_build/default/lib/cowboy/src/cowboy_handler.erl:45: illegal pattern\n",
                                      "_build/default/lib/cowboy/src/cowboy_handler.erl:46: variable 'Reason' is unbound\n",
                                      "_build/default/lib/cowboy/src/cowboy_handler.erl:47: variable 'Stacktrace' is unbound\n"]],
                                    []}
wappler@uknown:~/development/Projects/Erlang/spawnpool$ vim _build/default/lib/cowboy/src/cowboy_handler.erl
wappler@uknown:~/development/Projects/Erlang/spawnpool$ vim _build/default/lib/cowboy/src/cowboy_handler.erl
wappler@uknown:~/development/Projects/Erlang/spawnpool$ man erl
No manual entry for erl
See 'man 7 undocumented' for help when manual pages are not available.
wappler@uknown:~/development/Projects/Erlang/spawnpool$ erl --help
Erlang/OTP 19 [erts-8.3.5.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [systemtap]

Eshell V8.3.5.3  (abort with ^G)

What i am doing wrong?

cheers, hristo

**Comment by essen** [comment]
Support for OTP-19 was dropped in Cowboy 2.7. Current Cowboy version (future 2.8) requires OTP-22+.
