### ISSUE TITLE
Is Cowlib 2.9.0 still compatible with Cowboy 2.7.0

### ISSUE THREAD

**Issue by ostrovsky** [ninenines/cowboy#1445]
We need to upgrade to the latest version of gun and cowlib (2.9.0) in out project.  However, cowboy has not been officially moved to the latest cowlib.  There seems to be a lot of changes in cowlib compared to 2.8.0, even though they look backwards compatible upon a quick look.

Is cowboy 2.7.0 compatible with cowlib 2.9.0?

Thank you, 

Karol

**Comment by essen** [comment]
Yes. Master will move to 2.9.0 once I push my changes.

**Comment by ostrovsky** [comment]
Just one small additional question: do you plan to bump cowboy to 2.8.0 after those changes?

**Comment by essen** [comment]
Probably not unless a customer/sponsor requests it as my priorities lie elsewhere.
