### ISSUE TITLE
Lack of env in the document of cowboy_http/cowboy_http2 in 2.6 and onward

### ISSUE THREAD

**Issue by EzoeRyou** [ninenines/cowboy#1446]
Until the 2.5, the document explain env at cowboy_http/cowboy_http2.

https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/
https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http2/

In 2.6 and onward, env was silently removed without mentioned in changelog or migration.
Yet the User Guide is inconsistent and it still explaining things with assumption that env is supported like 2.5.

What happened to the env in 2.6 and onward? Is it deprecated? or simply the document is  wrong?

**Comment by essen** [comment]
It's because `env` and others are not used by those modules, but by `cowboy_stream_h`: https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_stream_h/

Maybe the text of `cowboy:start_clear/tls` can be updated to point out additional options may be set for stream handlers.

**Comment by EzoeRyou** [comment]
So the `ProtocolOpts` parameter of `start_cear/start_tls` is a merge of map() in Protocols and Stream handlers sections? The document definitely need an update.

**Comment by essen** [comment]
Done in https://github.com/ninenines/cowboy/commit/f58189df19a297dd9dd3911fe1f7631165fac5e8 thanks!
