### ISSUE TITLE
Pass information from the query object to error logger

### ISSUE THREAD

**Issue by ehamberg** [ninenines/cowboy#1447]
When a Ranch listener crashes, I get the `Ranch listener ~p, connection process ~p, stream ~p […]` report:

https://github.com/ninenines/cowboy/blob/db0d6f8d254f2cc01bd458dc41969e0b96991cc3/src/cowboy_stream_h.erl#L148-L151

It would be good to also get the request object, or some pertinent information from it (url, headers, method, query string, client IP), so that can be logged.

**Comment by essen** [comment]
I don't think I will change this except perhaps shorten a bit the logged message in a future release. If you need to get further information you should enable `cowboy_metrics_h` and log what you want from there. See https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_metrics_h/ for the documentation.

The log message you mention is really most useful for development and testing.

Thanks!
