### ISSUE TITLE
cowboy router: catchall host and concrete host don't work together

### ISSUE THREAD

**Issue by farao** [ninenines/cowboy#1448]
I am trying to start a websockethandler on all available "hosts" (networks) and an http handler only on localhost. Even though this shouldn't be a contradiction, it always only works for the first entry, the second entry seems to be ignored:
```
:cowboy_router.compile([
  {:_,          [{"/[..]", WebsocketHandler, []}]},
  {"localhost", [{"/metrics", HTTPHandler, []}]}
])
```
lets the websocket handler work but not the http handler (returns 404) and
```
:cowboy_router.compile([
  {"localhost", [{"/metrics", HTTPHandler, []}]}
  {:_,          [{"/", WebsocketHandler, []}]}
])
```
the other way round. In both cases it opens the chosen port on 0.0.0.0 (all hosts).
How can I make both work at the same time?

**Comment by essen** [comment]
The second one is half correct. You however need to specify the Websocket handler in all hosts you want it to work on (so both localhost and `_`), because the host match stops once a match was found.

**Comment by farao** [comment]
Thanks! Could I have found this information somewhere (except in the code)?

**Comment by essen** [comment]
Don't know if it's explicitly stated, please double check.
