### ISSUE TITLE
204 response with a body

### ISSUE THREAD

**Issue by benbro** [ninenines/cowboy#1450]
I'm getting a timeout on https when cowboy respond with 204 with a body.
```erlang
httpc:request(delete, {Url, Headers}, [{timeout, 500}], [])
```

```erlang
cowboy_req:reply(204, #{}, <<"test">>, Req).
```

**Comment by essen** [comment]
The `cowboy_req:reply/4` call in your report will now crash and produce a 500 response. Pushing later today.

**Comment by benbro** [comment]
Thanks.
