### ISSUE TITLE
It's take too much time to accpet a request sometimes

### ISSUE THREAD

**Issue by Ami-Kawashima** [ninenines/cowboy#1452]
I use the cowboy of version 2.6.0. Recently I found that it take serveral seconds to accpet some request. It might up to 30 seconds. Is there any policy from cowboy could make that question? Or anyone had gotten the same problem？Thanks
（I found that by pinpoint, and I use module httpc to do this request）

**Comment by essen** [comment]
You'll have to be a bit more specific about your environment, how you measured this (is it Cowboy slow to accept or the client or hostname resolution?), whether other components are involved (DNS might be your culprit, or slow network), what your TCP options are and any other relevant information.

**Comment by Ami-Kawashima** [comment]
> You'll have to be a bit more specific about your environment, how you measured this (is it Cowboy slow to accept or the client or hostname resolution?), whether other components are involved (DNS might be your culprit, or slow network), what your TCP options are and any other relevant information.

thank you for your attention. They are two service in k8s and indeed images in docker, and they are in the same space in k8s, so that I don't think network or dns would be the root (I will check it).  I do the request by default httpc:request/5。Now the question is that,  there is up to 30s from I do the request and cowboy indeed accept that (I mean cowboy use ranch to listen for connceting, would that up to 30s). Thank you.

**Comment by essen** [comment]
It's not normal, if that's what you're asking. But I've never heard of anything like this and DNS would be what I would look at first. I highly doubt that Cowboy or Ranch is responsible for this. Maybe the network code in OTP but I doubt that as well. I'll close this for now since there's nothing I can do for the time being.
