### ISSUE TITLE
Use correct timeout on inform requests

### ISSUE THREAD

**Issue by Gazler** [ninenines/cowboy#1455]
The timeout used for a request which uses `cowboy_req:inform/3` has changed from 5s (request_timeout) to 60s (idle_timeout) between cowboy 2.7.0 and 2.8.0

I believe the incorrect timeout value is being used. This can be demonstrated with this sample application:

https://github.com/Gazler/inform_test

From IRC:

```
<essen> 2.8.0 fixed a timeout issue that leads to the connection being closed later now
<essen> evidently it doesn't pick the right one in this particular case, but it's not terribly important, before i was sometimes closing the connection too early instead
<essen> to handle better cowboy should keep track of what timeout it is currently running
```

**Comment by essen** [comment]
Done in 1a175e7b563110c4a47c41f2b9c78cdafbcaf063 and now comes with tests. Closing, thanks!
