### ISSUE TITLE
accepting connections with proxy protocol enabled

### ISSUE THREAD

**Issue by sh3d2** [ninenines/cowboy#1458]
https://github.com/ninenines/cowboy/blob/de955079f90d52cc626baebb52154f116c1ab5dd/src/cowboy_clear.erl#L38

i bumped into a case when proxy protocol is enabled in options, but incoming connection has no proxy protocol information ex. connection wasnt made via balancer (haproxy) but directly.
in that case im unable to accept that kind of connection.

tl;dr im unable to accept a valid connection when proxy protocol setting is enabled. 

Are you considering a fallback to make it possible to accept that kind of connection?

**Comment by essen** [comment]
You should use a separate listener/port without this option if you need to access directly. Or send a "local" proxy header on connect.

**Comment by michaelklishin** [comment]
From the [Proxy Protocol specification](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt):

```
The receiver MUST be configured to only receive the protocol described in this
specification and MUST not try to guess whether the protocol header is present
or not. This means that the protocol explicitly prevents port sharing between
public and private access. Otherwise it would open a major security breach by
allowing untrusted parties to spoof their connection addresses. The receiver
SHOULD ensure proper access filtering so that only trusted proxies are allowed
to use this protocol.
```

So such "fallback" is explicitly prohibited by the Proxy protocol spec. Using a separate port sounds like a reasonable workaround for clients that cannot go through a compatible proxy.

**Comment by sh3d2** [comment]
@michaelklishin a perfect explanation. sounds reasonable, thanks. 

closing the issue then
