### ISSUE TITLE
Could not compile cowboy 2.8.0, was the rollback the problem?

### ISSUE THREAD

**Issue by alansousa** [ninenines/cowboy#1459]
Since a **rollback** in cowboy 2.8.0 in May, 28, I can't install the cowboy version 2.8.0 (latest).

And hex.pm shows that after a rollback, the fix was published with the same version, could it be the reason of this (deps.get/compile) problem?

A downgrade to 2.7.0 has been worked for me, but I want to understand if its a problem to investigate? If publishing another versoin could work for this problem?

```elixir
# create new phoenix app
# than run or iex -S mix phx.server
mix ecto.create 
```
```sh
===> Compiling cowboy
===> Compiling src/cowboy_http.erl failed
src/cowboy_http.erl:361: illegal pattern
src/cowboy_http.erl:364: variable 'Exception' is unbound
src/cowboy_http.erl:364: variable 'Stacktrace' is unbound
src/cowboy_http.erl:383: illegal pattern
src/cowboy_http.erl:386: variable 'Exception' is unbound
src/cowboy_http.erl:386: variable 'Stacktrace' is unbound
src/cowboy_http.erl:939: illegal pattern
src/cowboy_http.erl:942: variable 'Exception' is unbound
src/cowboy_http.erl:942: variable 'Stacktrace' is unbound
src/cowboy_http.erl:1332: illegal pattern
src/cowboy_http.erl:1335: variable 'Exception' is unbound
src/cowboy_http.erl:1335: variable 'Stacktrace' is unbound
src/cowboy_http.erl:1432: illegal pattern
src/cowboy_http.erl:1435: variable 'Exception' is unbound
src/cowboy_http.erl:1435: variable 'Stacktrace' is unbound

** (Mix) Could not compile dependency :cowboy, "/home/.asdf/installs/elixir/1.7.4/.mix/rebar3 bare compile --paths "/home/sidepro/app/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile cowboy", update it with "mix deps.update cowboy" or clean it with "mix deps.clean cowboy"

```

I tried with a few versions I have installed with asdf, 1.7.0, 1.7.4, 1.10.3 and erlang 20.3.8.9, 21.3.8.11.

**Comment by essen** [comment]
I don't know what you mean by rollback, and note that I'm not the hex package owner. However the illegal pattern error is most likely due to you using an Erlang version that's too old. Cowboy 2.8.0 has been tested on Erlang/OTP 22.0+. It might also work with 21.3 but it was not tested.
