### ISSUE TITLE
Streaming from multiple requests on HTTP/2 simultaneously may cause blocking

### ISSUE THREAD

**Issue by josevalim** [ninenines/cowboy#1460]
This was originally reported here: https://github.com/elixir-plug/plug_cowboy/issues/44

Looking at the code, it seems the described scenario can happen when an alarm is sent but the connection was already blocked. The following clause will therefore override the `blocked` state to `blocking`, which will never become `blocked`. This means that, even if the alarm is removed, the client is never notified, hanging forever:

https://github.com/ninenines/cowboy/blob/5aac00d60c7f22d717375e45a69769f53ad9555c/src/cowboy_stream_h.erl#L238-L240

My suggestion would be to check the `Status` and only set it to `blocking` if the status is `normal`.

For simplicity, I would also suggest changing the `stream_body_status` field to `normal | blocking | {blocked, Pid}`. This way you don't need to keep a separate field only for the PID. :)

This seems to affect Cowboy versions 2.7.0 and 2.8.0.

Thank you for your time and for Cowboy!

**Comment by essen** [comment]
Thanks. I think I ran into something similar and fixed it, guess it wasn't fixed everywhere.

For clarity you mean streaming over multiple streams over the same connection, not multiple connections, correct?

**Comment by josevalim** [comment]
Yes! I meant to say streaming from multiple requests. I will edit it accordingly.

**Comment by essen** [comment]
Fixed in 03d306e. Thanks!

**Comment by binaryseed** [comment]
Howdy folks, I ran into this too and see that it's fixed. I'm going to try running `master`, but is there a cowboy release planned in the near future?

**Comment by essen** [comment]
There'll be one to support OTP-24 (Ranch needs updating).
