### ISSUE TITLE
Can I have the flexibility to skip the version number upgrade, such as going directly from 0.1.1 to 0.1.5

### ISSUE THREAD

**Issue by leeyisoft** [ninenines/cowboy#1467]
1 Can the '.appup' file be automatically generated in 'erlang.mk'
2 Can I have the flexibility to skip the version number upgrade, such as going directly from 0.1.1 to 0.1.5
3 can be flexibly downgrade to specified version number; For example, the latest version number is 0.1.5. Can I switch to 0.1.1 or 0.1.3 at will

**Comment by essen** [comment]
No it doesn't generate automatically, automatic generation gives very mixed results anyway though it depends on the application. The appup must have the instructions for the version switch you request or you must do it in multiple steps.

Note that this is not related to Cowboy, nor are most of these questions about Erlang.mk either. I suggest you ask on the erlang-questions mailing list where more people will be able to help you.
