### ISSUE TITLE
Should cowboy care that an HTTP header as \r\n in its value?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/cowboy#1473]
I'm thinking about the CRLF Injection Attack.

**Comment by essen** [comment]
If you mean the four characters string `\r\n` then no there's no problem with that as far as Cowboy is concerned. Also if you use `cowboy_req:parse_header` it will most likely reject them. The user should however not consider headers to be sanitized.

**Comment by paulo-ferraz-oliveira** [comment]
> The user should however not consider headers to be sanitized.

That's what I thought, but it was worth asking.

> Also if you use cowboy_req:parse_header it will most likely reject them.

I'll check this. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, wait, I closed this too soon. I mean in the reply: if `cowboy` should care about that if we set it to that, \r\n, in the reply (prevent shooting my own foot, basically).

**Comment by paulo-ferraz-oliveira** [comment]
Nevermind, I'll figure something out. I was the one who pulled the trigger, any way 😄

**Comment by essen** [comment]
Ah in the response? Cowboy doesn't check anything so there's plenty of areas where things could go wrong in theory, at least when using HTTP/1.1.
