### ISSUE TITLE
Slow processing of WebSocket

### ISSUE THREAD

**Issue by lzaiko** [ninenines/cowboy#1475]
Hi Loic,

We are facing a speed issue with Cowboy2.8.0 handling WebSockets (on both MacOS Catalina 10.15 + Ubuntu 18.04 LTS).

Steps to reproduce:
1. Install websocat ([https://github.com/vi/websocat](https://github.com/vi/websocat)) and NodeJS
```
$ brew install websocat
$ npm install ws
```
Websocat also exist for Ubuntu, Fedora and FreeBSD

2. Run the WebSocket server:
2.1 Cowboy (Erlang handler attached)
2.2 NodeJS
```
$ node node_ws.js
```
3. Generate a random (ex. 17MiB) test file and send it
```
$ head -c 17825792 </dev/urandom >foo.bin
$ cat foo.bin | websocat -b ws://127.0.0.1:8081/ws
```
Cowboy is very very slow to recieve the file in comparison with NodeJS server.
Enclosed the Cowboy handler and NodeJS server to reproduce the test.

Help appreciated.
[test_code.zip](https://github.com/ninenines/cowboy/files/5447369/test_code.zip)

**Comment by essen** [comment]
I wouldn't recommend sending 17MB files via Websocket, the protocol isn't really made for that.

Do you perhaps have compression enabled in one or the other? In Cowboy it's not enabled by default.

**Comment by lzaiko** [comment]
Thanks for your swift reply.

17MiB was just an example. Even with 1MiB, Cowboy struggles to get it fast enough. And to answer your question, no, we do not use compression. Can you please show me how to enable it in Cowboy?

Were you able to reproduce the behaviour on your side?

By the way, there's no reason for a WebSocket frame to be small (see [https://stackoverflow.com/a/20658569](https://stackoverflow.com/a/20658569)).

We want to switch from Node to Erlang. Our current Node-based WebSocket service is pretty stable and can sustain +1TiB of data per WebSocket connexion. But we couldn't horizontaly scale it. Hence, the idea to switch to Erlang.

**Comment by essen** [comment]
I didn't say Websocket can't accept large frames, just that the protocol is not good for this in the general case. No flow control, scheduling and other useful features to make sure the connection isn't just stuck sending this one big file.

I do not have time right now to investigate and won't have until at least next week. Cowboy runs against `wstest` and it has a few performance related tests where it performs fine uncompressed and not very fast compressed (`#{compress => true}`). I have never used `websocat`. Please try to trace and see exactly how the file is sent.

**Comment by lzaiko** [comment]
Thanks Loic.
I tried with compression enabled and the situation is still the same. I wish you can have a look at it next week.
In the meantime, please do not hesitate if you want me to try anything else.

**Comment by essen** [comment]
Like I said, please try and trace to see what is sent exactly. Right now I don't even know if there's an actual issue so it's unlikely to be prioritized without you providing additional information.

**Comment by qiuqi** [comment]
cowboy
./websocat -b ws://127.0.0.1:8080/ws/file 
real	0m1.058s
user	0m1.046s
sys	0m0.018s

nodejs
time cat foo.bin| ./websocat -b ws://127.0.0.1:8081/ws 
real	0m1.030s
user	0m1.012s
sys	0m0.032s

almost same.

**Comment by essen** [comment]
What about very large files?

**Comment by essen** [comment]
I'll close this for now. Please provide more info if you think there's a real problem. Thanks!

**Comment by madasebrof** [comment]
I see that this was closed, but we're having the same issue. Cowboy is very slow to process binary websocket data. We are sending binary messages over websockets (typically about 2mb per message) and the speeds are roughly 10x slower than the same thing sent to a simple python server. Bummer. Like, super bummer.

This is a total shock to me, as I've used Cowboy on the web server side for years, and it has always been insanely fast.

I get that this is open source--we are willing to pay to get this fixed! Please let me know if there is anything I can do, Patreon, etc.

I'm going to play around with the websocket options to see if there is anything I can tweak to make it faster, but this is night and day difference. Normally, I find elixir/erlang is I/O bound, but I am only able to saturate 15% of a gig Ethernet link with WS if I connect to cowboy (around 100-130 Mbps), where I can get 90+% of potential bandwidth with simple 10 loc Python server (around 850 Mbps).

We're using Cowboy 2.9

Thanks in advance!

**Comment by essen** [comment]
Please open a new ticket with full instructions to reproduce and I will take a look when possible.
