### ISSUE TITLE
Update to Ranch 2.0

### ISSUE THREAD

**Issue by smedegaard** [ninenines/cowboy#1476]
I'm using Ranch 2.0 in a project.

Adding Telemetry which uses Cowboy results in a dependency conflict.

**Comment by essen** [comment]
Not a bug. You're probably using Mix. Mix made the choice to enforce consistency between all deps, while Erlang build tools have a "first dep fetched wins" approach. There's a way to make Mix behave but I don't use it therefore don't know it. Ask around, it's a common issue.

**Comment by smedegaard** [comment]
RIght. It might be a Telemetry thing then.

I'm doing `{:ranch, "~> 2.0.0", override: true},` in my mix.exs to get around the conflict.

that results in the following when starting the application:
```
** (Mix) Could not start application ctc_socket: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyAppSocket.Telemetry
    ** (EXIT) shutdown: failed to start child: :prometheus_metrics
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: %{id: {:ranch_embedded_sup, TelemetryMetricsPrometheus.Router.HTTP}, start: {:ranch_embedded_sup, :start_link, [TelemetryMetricsPrometheus.Router.HTTP, :ranch_tcp, %{max_connections: 16384, num_acceptors: 100, socket_opts: [port: 12345]}, :cowboy_clear, %{env: %{dispatch: [{:_, [], [{:_, [], Plug.Cowboy.Handler, {TelemetryMetricsPrometheus.Router, [name: :prometheus_metrics]}}]}]}, stream_handlers: [:cowboy_telemetry_h, :cowboy_stream_h]}]}, type: :supervisor}
                (plug_cowboy 2.4.0) lib/plug/cowboy.ex:207: Plug.Cowboy.child_spec/1
                (telemetry_metrics_prometheus 0.6.0) lib/telemetry_metrics_prometheus/supervisor.ex:15: TelemetryMetricsPrometheus.Supervisor.init/1
                (stdlib 3.9.2) supervisor.erl:295: :supervisor.init/1
                (stdlib 3.9.2) gen_server.erl:374: :gen_server.init_it/2
                (stdlib 3.9.2) gen_server.erl:342: :gen_server.init_it/6
                (stdlib 3.9.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/
```

Thanks for the quick reply.

**Comment by essen** [comment]
You may need to force a more recent Cowboy version as well to have one that supports both Ranch 1.x and 2.x.

**Comment by smedegaard** [comment]
Thanks for the hint. But I'm getting the error even with Cowboy 2.8.0

```
  cowboy 2.8.0
  cowboy_telemetry 0.3.0
  cowlib 2.9.1
  credo 1.5.0-rc.4
  file_system 0.2.9
  ink 1.2.0
  jason 1.2.2
  mime 1.4.0
  plug 1.10.4
  plug_cowboy 2.4.0
```

At this point the path of least friction seems to be downgrading to Ranch 1.7.1.

Again thanks for the help

**Comment by sgessa** [comment]
I agree this is not a bug.
Still, is there a plan to support Ranch 2.0? Currently it doesn't work even overriding `ranch` in `mix.exs`.
I tried it in a Phoenix project with the latest version of Phoenix.

**Comment by essen** [comment]
From the sound of it it's either plug or telemetry_metrics_prometheus that need to support Ranch 2.0. Cowboy already supports both 1.x and 2.0. Nothing more I can do.

**Comment by sgessa** [comment]
You're right, sorry.
The problem is in https://github.com/elixir-plug/plug_cowboy/blob/v2.4.1/lib/plug/cowboy.ex#L207
`:ranch.child_spec/5` is returning a map (if I'm not wrong) while `plug_cowboy` is expecting a tuple.

**Comment by asabil** [comment]
I submitted a PR for this on elixir-plug/plug_cowboy#64
