### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR on redirect with TLS

### ISSUE THREAD

**Issue by jpjodoin** [ninenines/cowboy#1478]
On Cowboy 2.8.0, I am seeing a problem with redirect when HTTP2 is enabled on the browser and using TLS. 

On Chrome 86, I get a ERR_HTTP2_PROTOCOL_ERROR. I get a generic failure on firefox. 

Here's a basic code that reproduce the issue:
```
init(Req, State) ->
	Reply = cowboy_req:reply( 307, #{<<"Location">> => <<"https://github.com/">>}, <<>>, Req),
	{ok, Reply, State}.
```
If I disable http2 on Firefox, I don't see the issue anymore. If I don't use cowboy tls, I don't see the issue either.

I would appreciate any insight you might have on this issue. Thanks.

**Comment by essen** [comment]
Does it do the same with `reply/3`?

**Comment by essen** [comment]
Oh, probably because you have an uppercase L in the header name. Header names must be lowercase.

**Comment by jpjodoin** [comment]
Oh !!! You are right. Weird that it was probably redirecting with http. Thanks.

**Comment by essen** [comment]
Header names are only required to be lowercase in HTTP/2. Browsers don't use HTTP/2 over plain TCP. Mystery solved!
