### ISSUE TITLE
cowboy shouldn't close connection after 60s when it's streaming a response

### ISSUE THREAD

**Issue by JoeZ99** [ninenines/cowboy#1484]
as it says in: https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/
> idle_timeout (60000)
>    Time in ms with no data received before Cowboy closes the connection.

cowboy will close the connection after 60 seconds of not hearing from the client.
This is, in most of the cases, a reasonable measure: if you take more than 60 seconds to process a response, then the problem is you, not the server.

However, when **streaming responses** (such a video, or a large csv, for instance) using `send_chunked()` and `chunk()`, this is an annoyance, because in order for it to work you need to set `idle_timeout` as `:infinity` for every kind of response (streamed and not streamed) and that's not cool.

**Comment by essen** [comment]
Cowboy can't differentiate between legitimate and illegitimate long running requests when using HTTP/1.1. That's why https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_stream/#_set_options was introduced a while back. You can use it to update `idle_timeout` for this request/response specifically. There's an example for this at https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_req.cast/#_examples

**Comment by JoeZ99** [comment]
Oh boy! I have to say I'm having the hardest time trying to figure out how to use `cowboy_req.set_options` inside `phoenix` infrastructure, this is clearly beyond my league :-(

**Comment by essen** [comment]
You just need to send a message to the Cowboy connection process, you don't have to use cowboy_req.

**Comment by JoeZ99** [comment]
well, for the sake of anybody who's going through the same trouble, thanking @essen and also this [more than great post](https://medium.com/frame-io-engineering/stripping-server-cowboy-from-response-headers-5fc557b7ce2b), I've managed to dinamically change idle_timeout for a cowboy server on a per requests basis:

in `config.exs`, added a custom cowboy stream handler, `MyApp.Middleware.TimeoutHandler`:
```elixir
config :api, MyApp.Endpoint,
  http: [port: 4000, stream_handlers: [MyApp.Middleware.TimeoutHandler, :cowboy_stream_h]],
  render_errors: [view: MyApp.ErrorView, accepts: ~w(json)]
```

and the stream handler itself. who icreases `idle_timeout` for a certain request path
```elixir
defmodule MyApp.Middleware.TimeoutHandler do
  @moduledoc """
  A cowboy stream handler -called for every request- that checks if it needs
  to maintain connection open for longer than a minute in case it's a streamed response
  """
  
  @behaviour :cowboy_stream

  @doc """
  called during several stages of the request-response lifecycle. (info defines that)
  """
  def info(stream_id, info, state), do: :cowboy_stream.info(stream_id, info, state)

  def init(stream_id, req, opts) do
    # if it's a streaming response, keep conn open
    if String.contains?(req.path , "/stats/query_log") do
      :cowboy_req.cast({:set_options, %{idle_timeout: :infinity}}, req)
    end
    :cowboy_stream.init(stream_id, req, opts)
  end

  def data(stream_id, is_fin, info, state),
    do: :cowboy_stream.data(stream_id, is_fin, info, state)

  def early_error(stream_id, reason, partial_req, resp, opts),
    do: :cowboy_stream.early_error(stream_id, reason, partial_req, resp, opts)

  def terminate(stream_id, reason, state), do: :cowboy_stream.terminate(stream_id, reason, state)
end
```

@essen, as embarrassing as it sounds, I couldn't find how to send a message to the cowboy connection process, I couldn't even find how to reference it :disappointed:  so I have to settle with this not-entirely-elegant solution instead :disappointed_relieved:

**Comment by essen** [comment]
Oh well. At least you got it working so that's fine. And now you know about stream handlers, which might help you again in the future.
