### ISSUE TITLE
Q: How do you return a JSON doc with an error in cowboy_rest?

### ISSUE THREAD

**Issue by stephb9959** [ninenines/cowboy#1488]
Hi,

I have been scratching my head on how to return an error with a json content from within cowboy_rest. I have tried things with 

`Rqe1=cowboy_req:reply(404,Req),
 {JSONDoc,Req1,State}`

And that crashes.

So I moved things into resource_exists() and try returning
`{{false,JSON},Req,State}` 
and I see a 404 but I do not get the JSON doc.

I have looked at the sample code but I cannot find anything that looks like this. Where am I going wrong?

**Comment by essen** [comment]
Calling `cowboy_req:set_resp_body` is typically enough. If you need a specific status code you will have to return a `stop` tuple.

**Comment by stephb9959** [comment]
Thanks @essen ! This is working now. Much appreciated.
