### ISSUE TITLE
WebSocket intermittent disconnection

### ISSUE THREAD

**Issue by sklassen** [ninenines/cowboy#1489]
Hello,

Intermittently cowboy web sockets is crashing with the below message. 

```
=CRASH REPORT==== 17-Dec-2020::20:16:25.102893 ===
  crasher:
    initial call: cowboy_clear:connection_process/4
    pid: <0.829.0>
    registered_name: []
    exception error: bad argument
      in function  iolist_size/1
         called as iolist_size(#Port<0.14>)
      in call from cow_ws:payload_length/1 (src/cow_ws.erl, line 725)
      in call from cow_ws:frame/2 (src/cow_ws.erl, line 666)
      in call from cowboy_websocket:websocket_send/2 (src/cowboy_websocket.erl, line 626)
      in call from cowboy_websocket:handler_call/6 (src/cowboy_websocket.erl, line 551)
    ancestors: [<0.804.0>,<0.803.0>,ranch_sup,<0.766.0>]
    message_queue_len: 0
    messages: []
    links: [#Port<0.14>,<0.804.0>]
    dictionary: []
    trap_exit: true 
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 965542
  neighbours:

=ERROR REPORT==== 17-Dec-2020::20:16:25.104220 ===
Ranch listener http had connection process started with cowboy_clear:start_link/4 at <0.829.0> exit with reason: {badarg,[{erlang,iolist_size,[#Port<0.14>],[]},{cow_ws,payload_length,1,[{file,"src/cow_ws.erl"},{line,725}]},{cow_ws,frame,2,[{file,"src/cow_ws.erl"},{line,666}]},{cowboy_websocket,websocket_send,2,[{file,"src/cowboy_websocket.erl"},{line,626}]},{cowboy_websocket,handler_call,6,[{file,"src/cowboy_websocket.erl"},{line,551}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
```
My build Erlang/OTP 22; cowboy-2.8.0; ranch-1.7.1; and cowlib-2.10.1. 

I am invoking cowboy with the options #{idle_timeout=>infinity}. 

Has anyone seen anything similar? 

Cheers

**Comment by essen** [comment]
Do you manipulate ports in your Websocket handlers?

**Comment by sklassen** [comment]
No static port, nothing special, the implementation is pretty close to the examples given. The code has run pretty much as is for near ten years now  -- a decade of cowboy approaches! -- and it's been super stable. It's only on a recent Ubuntu 20.04 box that I see intermittent -- by which I mean once every three or four days -- disconnections. An older instance running on Ubuntu 18.04 Erlang/OTP 21; cowboy-2.8.0; ranch-1.7.1; and cowlib-2.9.1 seems fine. I'll try installing on a third machine to see if it is repeatable.

**Comment by essen** [comment]
That's going to be hard to track down. I would otherwise suggest upgrading the Erlang version to the most recent one to make sure it's not just a bug that has been corrected since. Also even if running 22 you should make sure that you have the most recent patch version.

If it appears to be a problem in Cowboy then I suppose the easiest way to catch it would be some clever tracing on `cowboy_websocket:websocket_send/2` to obtain the state of the process before the crash occurs.

**Comment by sklassen** [comment]
Well noted. I'll close the issue now until I'm able to replicate on a second machine and have added tracing.
