### ISSUE TITLE
Question: set the limit of number connections per host

### ISSUE THREAD

**Issue by halturin** [ninenines/cowboy#1491]
Hi

I wonder is there any way to specify the max number of simultaneous connection for the specific host? number of req/sec?

**Comment by essen** [comment]
Ranch has `max_connections`. Not sure what the point of limiting the number of reqs/s would be.

**Comment by halturin** [comment]
I have seen this option, but question was about "for the specific host"

**Comment by essen** [comment]
You can always have a separate listener per host. Otherwise no, especially since it's requests that have a host, not connections.
