### ISSUE TITLE
May keep connection led to arise of CPU?

### ISSUE THREAD

**Issue by Ami-Kawashima** [ninenines/cowboy#1492]
I have received request and send message out by httpc. However, httpc stock by the unlimit of receive timeout. When there was about 1200 connections, the CPU arise and there was no more log.
Will keep too much connection cause this question?  CPU arise and can't accept connection?
if any idea, thank you!

**Comment by essen** [comment]
1200 is not a lot. And it really depends on what the connections are doing. It isn't the networking or HTTP part that ought to take resources. Compression could, either payload or HPACK if using HTTP/2, though 1200 is still low for the latter. And of course the handler code is the most likely culprit.

Note that Erlang does busy waits so CPU usage is not directly related to capacity. You may have 100% CPU and still a lot of capacity left.
