### ISSUE TITLE
Websocket async send

### ISSUE THREAD

**Issue by yhuangsh** [ninenines/cowboy#1493]
The cowboy_websocket module does not seem to support WebSocket server initiated data send. This is should be a useful feature for use cases where there is 1:n server-to-client connections and the server wants to broadcast a message to all clients. I would love to give it a go with some hints.

**Comment by essen** [comment]
That's out of scope and can easily be implemented at the application level, for example using process groups such as `pg`.

**Comment by yhuangsh** [comment]
Looking more closely at the source code in cowboy_websocket.erl, I think there is an easy way for server to initiate send without any code change. It works like this: 

1. At websocket_init callback, send Pid = self() to another process X
2. Later process X does Pid ! {ws_send, MessageToWebsocketClient}
3. The callback websocket_info should capture this message, then returns a Frame object just like websocket_handle would have. 

Et viola.

I haven't actually tried it yet, but looks promising.

**Comment by yhuangsh** [comment]
> That's out of scope and can easily be implemented at the application level, for example using process groups such as `pg`.

Perhaps I didn't make myself clear earlier. My original question wasn't about sending message 1:n. It was about I didn't find an explicit API in cowboy_websocket to send an async message to websocket client

**Comment by essen** [comment]
I don't know what an async message means exactly but yes you can send a message to yourself to defer handling later.

**Comment by leeyisoft** [comment]
“ WebSocket server initiated data send.” -- I assume this is what you want?

 erlang:start_timer The second parameter is pid; 

Each websocket link corresponds to a PID, save the {uid, PID} relationship(like this https://github.com/imboy-pub/imboy/blob/main/src/chat_online.erl), 
you can obtain the UID by token, then obtain the corresponding PID by uid, 
you can use Erlang :start_timer(1, ToPid, Msg) communication

erlang:start_timer 第二个参数 是 pid；
每个websocket链接对应一个pid，把{uid,pid}关系保存起来(like this https://github.com/imboy-pub/imboy/blob/main/src/chat_online.erl)，
就可以通过token获取uid，再通过uid获取对应的pid，
就可以用 erlang:start_timer(1, ToPid, Msg) 通讯了

```
-module(ws_h).

-export([init/2]).
-export([websocket_init/1]).
-export([websocket_handle/2]).
-export([websocket_info/2]).

init(Req, Opts) ->
	{cowboy_websocket, Req, Opts}.

websocket_init(State) ->
	erlang:start_timer(1000, self(), <<"Hello!">>),
	{[], State}.

websocket_handle({text, Msg}, State) ->
	{[{text, << "That's what she said! ", Msg/binary >>}], State};
websocket_handle(_Data, State) ->
	{[], State}.

websocket_info({timeout, _Ref, Msg}, State) ->
	erlang:start_timer(1000, self(), <<"How' you doin'?">>),
	{[{text, Msg}], State};
websocket_info(_Info, State) ->
	{[], State}.
```
code from https://github.com/ninenines/cowboy/blob/master/examples/websocket/src/ws_h.erl
