### ISSUE TITLE
Q: Websocket browser side messages

### ISSUE THREAD

**Issue by stephb9959** [ninenines/cowboy#1496]
Hi,

I am attempting to send several JSON documents over a WebSocket to a client. This information is updated every second for example. On the client-side, I receive the onmessage events and parse the JSON doc. The only problem is that I seem to miss some documents. I have verified that they are sent on the web_socket side in Erlang. For some reason, I do not get them all in the client. These JSON docs are sent as text frames. 

Am I missing something? Is there something else I should be setting?

Thanks

**Comment by essen** [comment]
Don't know. Not heard of such a problem before.

**Comment by stephb9959** [comment]
This is not a cowboy issue. Some 3rd party library is failing. Sorry for the trouble.
