### ISSUE TITLE
Cowboy request reply crashing

### ISSUE THREAD

**Issue by outminder** [ninenines/cowboy#1499]
I have a POST request which accepts json and returns json. I have added both content_types_accepted/2 and content_types_provided/2.
In my handler I am manually setting the response data like this

```
    Req2 = cowboy_req:set_resp_body(Response, Req),
    Req3 = cowboy_req:set_resp_header(<<"content-type">>, 
             <<"application/json">>, Req2),
    Req4 = cowboy_req:reply(200, Req3),
    {true, Req4, State}.
```

I see this error

```
18:51:19.749 [error] CRASH REPORT Process <0.798.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:reply/4 line 796
18:51:19.749 [error] Cowboy stream 1 with ranch listener http and connection process <0.797.0> had its request process exit with reason: no function clause matching cowboy_req:reply/4 line 796
```
What is the cause of this error, any help highly appreciated?

**Comment by paulo-ferraz-oliveira** [comment]
It appears you might be trying to reply twice, which is what's causing the crash.
First you do `:reply`, which sends a reply.
Then you return (from your "handler") `{true, _, _}`, which would send a new reply.
You should try with `stop`, instead of `true` and see if that helps.

**Comment by outminder** [comment]
It resolved the error. Thanks
