### ISSUE TITLE
Compile-time warnings under rebar3

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/cowboy#1500]
I get issued two warnings of type:

```erlang
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref},
otherwise updating the dep may not work as expected.
```

One for `cowlib` and another one for `ranch`.

Would you accept a pull request where `"master"` is updated to `{branch, "master"}` and `"1.7.1"` is updated to `{git, "1.7.1"}`?

Not doing that also seems to implicate (upon `rebar3 upgrade`) `ranch` get constantly re-fetched/re-compiled, something which could be avoided.

**Comment by essen** [comment]
No because the file is automatically generated. I'm only welcome to a solution that modifies the generator code in Erlang.mk.
