### ISSUE TITLE
How to handle double slash in the routes

### ISSUE THREAD

**Issue by outminder** [ninenines/cowboy#1501]
One of the request is sending double slash in the API like this api/v1//test. I added the route for the same, but when I make a request using curl for the same API, Cowboy says 404 not found. Is there a way I can handle double slash in the routes?
Any help would be highly appreciated.

**Comment by essen** [comment]
Sorry I didn't come back sooner for an answer, but I don't really know. I guess you could have a stream handler that fixes the // into a single /.
