### ISSUE TITLE
Cowboy 2.8.0 and OTP 24 rc1

### ISSUE THREAD

**Issue by comptekki** [ninenines/cowboy#1505]
I saw OTP 24 rc1 came out so I tried my app with it (Cowboy 2.8.0).  It compiles and runs, but when I try to access the app I get this:

Erlang/OTP 24 [RELEASE CANDIDATE 1] [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:20] [jit]

Eshell V12.0  (abort with ^G)
(node@ip)1> =CRASH REPORT==== 24-Feb-2021::08:17:53.479362 ===
  crasher:
    initial call: cowboy_tls:connection_process/4
    pid: <0.489.0>
    registered_name: []
    exception error: undefined function ssl:ssl_accept/3
      in function  ranch_ssl:handshake/3 (src/ranch_ssl.erl, line 142)
      in call from ranch:handshake/2 (src/ranch.erl, line 243)
      in call from cowboy_tls:connection_process/4 (src/cowboy_tls.erl, line 43)
    ancestors: [<0.462.0>,<0.461.0>,ranch_sup,<0.449.0>]
    message_queue_len: 0 
    messages: []
    links: [<0.462.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 224
  neighbours:

=ERROR REPORT==== 24-Feb-2021::08:17:53.479877 ===
Ranch listener https had connection process started with cowboy_tls:start_link/4 at <0.489.0> exit with reason: {undef,[{ssl,ssl_accept,[{sslsocket,{gen_tcp,#Port<0.12>,tls_connection,[{option_tracker,<0.464.0>},{session_tickets_tracker,disabled},{session_id_tracker,<0.465.0>}]},[<0.488.0>,<0.487.0>]},[],5000],[]},{ranch_ssl,handshake,3,[{file,"src/ranch_ssl.erl"},{line,142}]},{ranch,handshake,2,[{file,"src/ranch.erl"},{line,243}]},{cowboy_tls,connection_process,4,[{file,"src/cowboy_tls.erl"},{line,43}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

**Comment by essen** [comment]
See https://github.com/ninenines/ranch/issues/314
