### ISSUE TITLE
Question about Cowboy with Rabbit MQ

### ISSUE THREAD

**Issue by ahmedalshamary** [ninenines/cowboy#1507]
Hi, this question likely stems from my ignorance about Erlang, OTP and Cowboy.

I am setting up an RPC using RabbitMQ so that REST requests coming into erlang will be sent as RPC messages. So far what I have done is implement a module that I call every time I get a REST request (code below).  This work just fine but it seems to be inefficient to create and close a channel every time I get a rest request. So I was looking to create one client that I use and found this https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_rpc_client.erl. However, looking at how it works I am a bit confused on where to put this in my code so that my cowboy handlers have access to the PID to use the client. Could you explain how this would work? My understanding so far is that the _app.erl will start the supervisor but I am confused for what reason it does this as it seems the supervisor is doing nothing ? I tested this out by removing start_link and everything worked correctly. 

```
-module(rabbit_mq_interface).

-include_lib("amqp_client/include/amqp_client.hrl").

-export([send/1]).
-export([response/0]).

% Might me more optimal to open the connection once and use it. Think about this some more.

send(Request_Data) ->

    Local_Device_Exchange = <<"local_device_exchange">>,
    Response_Queue = <<"response_queue">>,

    {ok, Connection} =
        amqp_connection:start(#amqp_params_network{host = "localhost"}),
    {ok, Channel} = amqp_connection:open_channel(Connection),

    % Queue to Local Channel
    amqp_channel:call(Channel, #'exchange.declare'{exchange  = Local_Device_Exchange}),

    % Define a REST Response Queue
    #'queue.declare_ok'{queue = Response_Queue} = amqp_channel:call(Channel, #'queue.declare'{queue = Response_Queue}),

    Props = #'P_basic'{reply_to = Response_Queue},
  	BasicPublish = #'basic.publish'{exchange = Local_Device_Exchange},
    
    amqp_channel:cast(Channel,
                      BasicPublish,
                      #amqp_msg{
                        props = Props,
                        payload = Request_Data
                      }),

    io:format(" [x] Sent 'Hello World!'~n"),
  
    amqp_channel:subscribe(Channel, #'basic.consume'{queue = Response_Queue,
                                                     no_ack = true}, self()),

    Body = response(),

    ok = amqp_channel:close(Channel),
    ok = amqp_connection:close(Connection),
    Body.


response() ->     
    receive
        {#'basic.deliver'{}, #amqp_msg{payload = Body}} ->
            io:format(" [x] ~p~n", [Body])
    end,
    Body.
```

**Comment by essen** [comment]
Closing this because this is not a Cowboy question but rather a general Erlang one. The only relevant piece of advice is that Cowboy requests are their own process, as are connections, and do not map well with a persistent direct connection to RabbitMQ, as you have noted.

What you currently do in this module should be its own process, perhaps managed by your own supervisor, and you should communicate with it to do the work you need it to do.

Please refer to the erlang-questions mailing list, #erlang IRC or Slack channel or any other Erlang help channels instead.

**Comment by leeyisoft** [comment]
把 amqp_channel:cast 相关逻辑，放到一个特定的gen_server 里面，能否解决问题？

Would putting the amqp_channel:cast logic into a specific gen_server solve the problem?
