### ISSUE TITLE
Does middleware work with websockets? How? Is it broken?

### ISSUE THREAD

**Issue by igorclark** [ninenines/cowboy#1508]
Hi, I'm investigating how to throttle incoming messages from a websocket client. I'm starting off just by trying to get a basic middleware running but even just having `execute/2` which passes back `{ok, Req, Env}` or even `{stop, Req}`, the client gets a `204 No Content`. The `execute/2` callback gets called, but neither `websocket_init` nor `init` in the ws handler module get called. Can't work out from the documentation whether this is something I'm supposed to be able to do, and if so how, or whether something's broken. Any clues v welcome! Thanks.

**Comment by essen** [comment]
Middlewares are what ultimately executes HTTP handlers, and HTTP handlers may become Websocket handlers. You're not looking at the right thing.

Websocket handlers can return `active` commands to enable/disable reading from the socket: https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_websocket/#_types
