### ISSUE TITLE
websocket_info {ping,<<>>} doesn't receive pong

### ISSUE THREAD

**Issue by okeuday** [ninenines/cowboy#1512]
With cowboy1 source code using `{ping,<<>>}` worked.  However, with the current master branch source code `{ping,<<>>}` may be provided though the connection doesn't get a `{pong, _}` in the future.  Was using source code like:

    websocket_info(_, State) ->
        {[{ping, <<>>}], State};

(with the result based on a timer and other details)

**Comment by essen** [comment]
A failing test case in ws_SUITE would be helpful.

**Comment by trueFireblade** [comment]
Tried to reproduce it with this code
```erlang
websocket_handle(pong, State) ->
    io:format("Got pong!~n"),
    {[], State};

% ...

websocket_info({timeout, _Ref, _Msg}, State) ->
    erlang:start_timer(1000, self(), <<>>),
    {[{ping, <<>>}], State};
```
And I get the pong messages, is this issue still reproducable for others or did it get fixed and just never closed?

**Comment by okeuday** [comment]
@trueFireblade The issue is from cowboy 1.x (https://github.com/ninenines/cowboy/tree/1.1.x)  which last had a change in 2017.  I filed the issue because it was a difference between cowboy 1.x and 2.x that I saw when looking at the differences between the usage of [cloudi_service_http_cowboy1](https://github.com/CloudI/CloudI/blob/develop/src/lib/cloudi_service_http_cowboy1/src/cloudi_service_http_cowboy1.erl) and [cloudi_service_http_cowboy](https://github.com/CloudI/CloudI/blob/develop/src/lib/cloudi_service_http_cowboy/src/cloudi_service_http_cowboy.erl).  The cowboy 1.x source code likely won't get active development, so the issue is safe to close.

**Comment by essen** [comment]
It's left open so that a test can be added so we are sure whichever behavior is correct remains working. Also to double check which behavior is correct at the same time.

**Comment by essen** [comment]
It seems that the handler does receive the pong frame. However note that when the contents of the frame are empty Cowboy will parse it as `pong`, not as `{pong, <<>>}` so you may just be missing that clause. I am adding a test to confirm this behavior and will push it soon.

**Comment by essen** [comment]
Please check 08a8d7b9e981002545bf77af367c734d9ea162ab for the test and handler confirming this behavior. Closing, thanks!
