### ISSUE TITLE
examples echo_post bug

### ISSUE THREAD

**Issue by 405412460** [ninenines/cowboy#1518]
bug: 
Missing echo parameter
 crasher:
    initial call: cowboy_stream_h:request_process/3

echo(undefined, Req) ->
	cowboy_req:reply(400, [], <<"Missing echo parameter.">>, Req);
echo(Echo, Req) ->
	cowboy_req:reply(200, #{
		<<"content-type">> => <<"text/plain; charset=utf-8">>
	}, Echo, Req).
	
==》》	
echo(undefined, Req) ->
	cowboy_req:reply(400, #{}, <<"Missing echo parameter.">>, Req);
echo(Echo, Req) ->
	cowboy_req:reply(200, #{
		<<"content-type">> => <<"text/plain; charset=utf-8">>
	}, Echo, Req).

**Comment by essen** [comment]
Note to self: this is about headers given as a list instead of a map.
