### ISSUE TITLE
badarith,[{erlang,'+',[64271,:infinity]

### ISSUE THREAD

**Issue by michelboaventura** [ninenines/cowboy#1519]
I'm having an error similar to https://github.com/ninenines/cowboy/issues/1411 but instead of `flow = infinity`, I've got `Size = infinity`. I'm using cowboy 2.9.0 and Elixir 1.12-otp24. It only happens from time to time and I can't figure out what is causing the issue.

(Formatted to improve readability)
```
[error] Ranch listener #Reference<foo> had connection process started with
:cowboy_clear:start_link/4 at #PID<0.1074.0> exit with reason: 
```
```Elixir
{:badarith, [{:erlang, :+, [64271, :infinity], [error_info: %{module: :erl_erts_errors}]},
{:cowboy_http, :commands, 3, [file: '.../cowboy/src/cowboy_http.erl', line: 985]},
{:cowboy_http, :loop, 1, [file: '...cowboy/src/cowboy_http.erl', line: 257]},
{:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
```

**Comment by essen** [comment]
Sounds like you are requesting for `infinity` data and that hasn't been handled properly.

**Comment by michelboaventura** [comment]
@essen thanks for replying. After further digging I think I found the issue. If you take a look at https://github.com/ninenines/cowboy/blob/master/doc/src/guide/req_body.asciidoc it says I can use `cowboy_req:read_body(Req0, #{length => infinity})` to disable length limit. But doing so I got the above error.

I'm not too used to Erlang, so I did the easiest way to reproduce the issue. I've cloned cowboy repo and changed a single test from `cowboy_req:read_body(Req0)` to `cowboy_req:read_body(Req0, #{length => infinity})` and the same error happens.

**Comment by essen** [comment]
Yes that's what I meant by "not handled properly". It's a bug in Cowboy. If you want you can add a test case in `req_SUITE` in a PR and try writing a fix. But if not that's OK too, I'll get around to it eventually. In the meantime you can use a very large value like `99999999999` for example. But note that in that case it'll wait for the period timeout before giving you data. So perhaps that's not what you want.

**Comment by michelboaventura** [comment]
Gotcha! I thought you were saying I was using Cowboy in a wrong way. Thanks for the clarification, I'll try to fix this and send a PR. Thanks!

**Comment by essen** [comment]
I removed the part about `infinity` from the guide. I documented the "auto" mode that is a better replacement for this. Closing, thanks!
