### ISSUE TITLE
cow_qs:parse_qs  can't handler base64 img data

### ISSUE THREAD

**Issue by helloyan** [ninenines/cowboy#1521]
if the url param has a base64 image , it's end with "=", then cow_qs:parse_qs can't handler it right

**Comment by benbro** [comment]
The equal sign "=" is a reserved character [1]. You should use base64 url encode instead of the usual base64 [2].
https://tools.ietf.org/rfc/rfc3986.html#section-2.2
https://en.wikipedia.org/wiki/Base64#The_URL_applications
