### ISSUE TITLE
WebSocket close with custom code to support WebSocket extension

### ISSUE THREAD

**Issue by sax** [ninenines/cowboy#1525]
I've been building a custom WebSocket handler in Phoenix that implements a WebSocket extension, [GraphQL over WebSockets](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md). An important part of this extension is the use of custom error codes, which the [WebSocket specification](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#status_codes) reserves in the range 2000-2999 for extensions and 4000-4999 for applications.

I was able to hack my way around it, but it would be slightly easier if cowboy did not throw away the error message.

https://github.com/ninenines/cowboy/blob/db0d6f8d254f2cc01bd458dc41969e0b96991cc3/src/cowboy_websocket.erl#L671-L672

In this case `remote` is not exactly true. The server process may decide to close the socket with a custom code and error message. This might imply a new `Reason` tuple to match on?

More info about how this relates to Phoenix here: https://elixirforum.com/t/phoenix-socket-transport-custom-websocket-transports-and-the-interop-between-phoenix-and-cowboy/40440

**Comment by sax** [comment]
I would be happy to issue a pull request with any changes to support this feature. The main desire is for the server to be able to close the socket with a custom code and message, and have those communicated to clients.

**Comment by essen** [comment]
You should be able to just return a close tuple if it's server-initiated.

**Comment by sax** [comment]
Ah, I see that now: https://github.com/ninenines/cowboy/blob/db0d6f8d254f2cc01bd458dc41969e0b96991cc3/src/cowboy_websocket.erl#L506-L507

That leaves the problem that error messages are ignored in `websocket_send_close` and replaced with `<<>>`. If I was to match on a binary message in the `{remote, Code, _} ` tuple, and pass that to `transport_send`, would you accept that as a pull request?

**Comment by essen** [comment]
You're looking at close frames sent by the client. Server-initiated frames send their payload: https://github.com/ninenines/cowboy/blob/db0d6f8d254f2cc01bd458dc41969e0b96991cc3/src/cowboy_websocket.erl#L622-L645

**Comment by sax** [comment]
This is wonderful. Thanks so much for taking the time to point out the code. I'll trace this back up into Phoenix and see if I can solve my problem there (or document how to take advantage of this feature of cowboy websockets).
