### ISSUE TITLE
Custom body in cowboy_rest

### ISSUE THREAD

**Issue by snakeduse** [ninenines/cowboy#1527]
Hello,

Can I set a custom response body in case of error in cowboy_rest? For example, when a client specified the Content-Type incorrectly and I want to set the error description in response body for "415 Unsupported Media Type" status.

**Comment by essen** [comment]
cowboy_req:set_resp_body

**Comment by snakeduse** [comment]
Do I need to call this function in every cowboy_rest callback?

**Comment by essen** [comment]
Depends, stream handlers are an option if you need the same behavior everywhere.

**Comment by snakeduse** [comment]
Ok. Thank you.
