### ISSUE TITLE
Cowboy Crashes; function clause error I can't discern

### ISSUE THREAD

**Issue by unaffiliatedstudios** [ninenines/cowboy#1530]
My searches for an answer led me to #1355 but I'm not sending a cert, so that's not the case for me. The error I'm receiving I posted [here](https://gist.github.com/unaffiliatedstudios/e7b8728ce7b4b69ac5022ac6d16de1c8). I can't quite figure out what's going on, if it's one dependency breaking another, etc. If it helps, these are what I have installed (so far):

```
  defp deps do
    [
      {:phoenix, "~> 1.5.7"},
      {:phoenix_ecto, "~> 4.1"},
      {:dotenv_parser, "1.2.0"},
      {:ecto_sql, "~> 3.4"},
      {:excoveralls, "~> 0.14.1", only: :test},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_dashboard, "~> 0.4"},
      {:telemetry_metrics, "~> 0.4"},
      {:telemetry_poller, "~> 0.4"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:credo, "~> 1.5", only: [:dev, :test], runtime: false},
      {:ex_machina, "~> 2.7.0"},
      {:faker, "~> 0.16", only: :test},
      {:bamboo, "~> 2.2.0"},
      {:bamboo_phoenix, "~> 1.0.0"}
    ]
  end
```

**Comment by essen** [comment]
A response has already been sent and you are trying to send a 302.

**Comment by unaffiliatedstudios** [comment]
> A response has already been sent and you are trying to send a 302.

Took me a bit to figure out how this was happening, as there is exactly one spot even calling a redirect. Turns out, there was a second one just hanging out. Thank you for that.
