### ISSUE TITLE
Obscure error: Bad value on output port 'tcp_inet'

### ISSUE THREAD

**Issue by leoliu** [ninenines/cowboy#1534]
To reproduce set a header like this for a response:

```
cowboy_req:reply(204, #{ test => "ok" }, Req).  % example 1
cowboy_req:reply(204, #{ <<"test">> => 123123 }, Req). % example 2
```

Example logger output:
```
=ERROR REPORT==== 24-Aug-2021::13:16:11.450275 ===
Bad value on output port 'tcp_inet'
```

Such errors are incredibly difficult to debug. Is it possible to produce full error instead?

**Comment by essen** [comment]
Not without inspecting deeply both headers and body, the latter which may be an iolist. Doing so would be incredibly costly. Try using Dialyzer to see if the error comes up.

**Comment by leoliu** [comment]
Sorry I don't mean to suggest checking iolist. I thought the error is obscured because cowboy caught it. After some experiment with `gen_tcp` the error is generated whenever non-iolist is sent to a socket.

**Comment by essen** [comment]
Yes.

I'm wondering if that will change with `socket` by the way. Never tried.
