### ISSUE TITLE
Cowboy should use permissive file mode for local sockets

### ISSUE THREAD

**Issue by derek-zhou** [ninenines/cowboy#1537]
Cowboy allows listening on Unix domain socket as of now; but it is hard to use due to permission issues. HTTP over Unix domain socket is unspeced, and is only useful in a situation of a local reverse proxy. Right now the socket file inherits user's umask (usually 0644), so the permission is not as open as it could be. HTTP does not make sense to be read only, so it is preferable to have a more permissive mode. 

Ranch HEAD just added an optional callback to do exactly that:

https://github.com/ninenines/ranch/pull/322

I suggest cowboy to make use of this callback and change all local socket's permission to 0666 or 0777.

**Comment by essen** [comment]
There's nothing to do in Cowboy as the user is expected to provide socket options and can therefore provide a post_listen_callback that sets the permissions as they choose.

**Comment by derek-zhou** [comment]
That's fair; however, I think this is a common thing needed by all cowboy users and can save them from doing it themselves. A generic socket may need specific mode for user based access control; however, an HTTP socket has no such need; and users expect it to just work.

**Comment by essen** [comment]
You're making assumptions about what people use HTTP for, what environment they run Cowboy in or what security requirements they may have. We cannot make such assumptions. Users are expected to look into the transport and protocol configurations and adapt to their needs.

You are also the only user I have heard that needed this so I do not think it is fair to say that all users need it. Cheers.

**Comment by tfwright** [comment]
FWIW I had this same problem and ended up just modifying the permissions after app start. Is there a better way currently?

**Comment by essen** [comment]
We added a `post_listen_callback` transport option in Ranch 2.1.

**Comment by tfwright** [comment]
Awesome. For posterity, after upgrading Ranch to 2.1 I was able to solve the issue in my prod Phoenix app Endpoint config like so:

```
      http: [
        ip: {:local, System.fetch_env!("SOCKET_FILE_PATH")},
        port: 0,
        transport_options: [
          post_listen_callback: fn _ -> File.chmod!(System.fetch_env!("SOCKET_FILE_PATH"), 0o666) end
        ]
```
