### ISSUE TITLE
Cowboy Getting Started guide - postscript about gitignore?

### ISSUE THREAD

**Issue by frou** [ninenines/cowboy#1542]
Hi there. Thanks for the library and the guide:

https://ninenines.eu/docs/en/cowboy/2.9/guide/getting_started/

After following that guide, we have a lot of files in the project directory. My suggestion is that the guide could include a postscript explaining that if we were to commit the result to git, what should be included and what should be gitignore'd.

```
hello_erlang $ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.erlang.mk/
	Makefile
	_rel/
	config/
	deps/
	ebin/
	erlang.mk
	hello_erlang.d
	relx.config
	src/
```

**Comment by essen** [comment]
The only real temporary files are in `.erlang.mk`. The rest may be committed depending on your needs. Typically `_rel`, `deps`, `ebin/` (except perhaps .app/.appup files) or the `.d` files are not committed.
