### ISSUE TITLE
Error - compiling cowboy on orangepi

### ISSUE THREAD

**Issue by leondavi** [ninenines/cowboy#1547]
I get the following error message when trying to compile cowboy on my orangepi:

===> Compiling cowboy
Function: request_process/3
===> Compiling _build/default/lib/cowboy/src/cowboy_stream_h.erl failed
_build/default/lib/cowboy/src/cowboy_stream_h.erl:none: internal error in sys_co                            re_dsetel;
crash reason: {case_clause,
    {'EXIT',
        {{case_clause,
             #{0 => 1,1 => 1,2 => 1,4 => 1,5 => 1,6 => 1,14 => 0,
               'Reason' => 3}},
         [{sys_core_dsetel,visit,2,[{file,"sys_core_dsetel.erl"},{line,98}]},
          {lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},
          {lists,mapfoldl,3,[{file,"lists.erl"},{line,1355}]},
          {sys_core_dsetel,visit,2,[{file,"sys_core_dsetel.erl"},{line,188}]},
          {lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},
          {lists,mapfoldl,3,[{file,"lists.erl"},{line,1355}]},
          {sys_core_dsetel,visit,2,[{file,"sys_core_dsetel.erl"},{line,188}]},
          {sys_core_dsetel,visit,2,
              [{file,"sys_core_dsetel.erl"},{line,144}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from compile:'-do_compile/2-anonymous-1-'/1 (compile.erl, line 190)

Erlang version: Erlang/OTP 21 
Cowboy version 2.9.0

**Comment by essen** [comment]
https://ninenines.eu/docs/en/cowboy/2.9/guide/introduction/

> Cowboy is developed for Erlang/OTP 22.0 and newer.
