### ISSUE TITLE
Some help for message passing between requests (Loop handlers).

### ISSUE THREAD

**Issue by GeorgiouJohn** [ninenines/cowboy#1548]
Hi,
I need some help in loop handlers. 
Let's say with have a request1 from client1 in a loop handler. 
A request2 from client2 needs to send a message in the mail box of the request1 process. 
How the request2 knows the process identifier, or pid of  request1 process to send a message?
Thanks for your time.

**Comment by essen** [comment]
Using process groups like `pg` or a process registry like `erlang:register`.
