### ISSUE TITLE
High memory usage cowboy_clear:connection_process/4

### ISSUE THREAD

**Issue by phanmn** [ninenines/cowboy#1553]
- erlang: 24.1
- elixir: 1.12.3
- Cowboy: 2.9.0
- plug_cowboy: 2.5.2
- phoenix: 1.6.2

<img width="843" alt="Screen Shot 2021-11-26 at 00 52 38" src="https://user-images.githubusercontent.com/3765536/143485418-e2fa71d7-d92f-4adf-808d-5ec80968e9bc.png">

Need to run manually `Process.list |> Enum.each(&:erlang.garbage_collect/1)` to fix the issue

Please help, thanks!

**Comment by essen** [comment]
Please open a ticket in Phoenix or Plug. I cannot spend time on this without knowing for sure that there's a problem in Cowboy. Websocket handlers are run inside this process so in all likelihood the memory is used by the Plug/Phoenix code. If it is a problem in Cowboy please come back with a minimal Erlang example that can reproduce the issue.
