### ISSUE TITLE
How can increment send timeout in :cowboy.start_clear

### ISSUE THREAD

**Issue by luongtt** [ninenines/cowboy#1554]
Hi,

We are experiencing failed file send download when using Cowboy 2.9. API will be download as failed when internet slow keep > 30s, success when <30s.

How we configure Cowboy in our Elixir project.

```elixir
            ranch_opts = %{
              num_acceptors: 20,
              max_connections: :infinity,
              socket_opts: [
                {:port, 8080}
              ]
            }
            :cowboy.start_clear(:http, ranch_opts, %{env: %{dispatch: {:persistent_term, :dispatch}}})
```

```elixir
            req = :cowboy_req.stream_reply(200, req)
            Enum.each(0..(chunk_size - 1), fn x ->
              content = read_chunk(path, x)
              :cowboy_req.stream_body(content, :nofin, req)
            end)
            content = read_chunk(path, chunk_size)
            :cowboy_req.stream_body(content, :fin, req)
```

Version:
```
Cowboy (2.9.0)
Elixir (1.12.3) 
Erlang/OTP 23
```

**Comment by essen** [comment]
Sounds like you want to configure the `idle_timeout` protocol option.

**Comment by luongtt** [comment]
> Sounds like you want to configure the `idle_timeout` protocol option.

We try 
```elixir
:cowboy.start_clear(:bpm_http, ranch_opts, %{idle_timeout: 120_000, env: %{dispatch: {:persistent_term, :dispatch}}})
```
but this is not working

**Comment by luongtt** [comment]
> Sounds like you want to configure the `idle_timeout` protocol option.

We try
```elixir
:cowboy.start_clear(:http, ranch_opts, %{idle_timeout: 120_000, env: %{dispatch: {:persistent_term, :dispatch}}})
```
but this is not working

**Comment by essen** [comment]
Do you perhaps have a proxy in-between that could be dropping the connection? You can use wireshark to see what's going on exactly, as well as Erlang tracing to see what Cowboy is doing (the `cowboy_http` module will be of particular interest).
