### ISSUE TITLE
Server crashing - how to debug / set logging level

### ISSUE THREAD

**Issue by jordanchaitin** [ninenines/cowboy#1555]
I am starting and running cowboy using the guide in the docs. 

When I check in `_rel/project_release/log/` the log files seem to be rotated alright, but they are mostly empty. I am not sure how I can change the logging level. 

Is there something like setting the log severity level? I think this is a simple/obvious question but I can't seem to find the answer.

As a suggestion, it would be nice if the docs could include some guidance on setting up logging for cowboy.

**Comment by jordanchaitin** [comment]
Basically the server strangely crashes sometimes with the error message. I am unable to figure out why it is crashing because I can find no logs. 

The logs on the date of the crash are completely empty. 

```
> heart: Thu Dec 23 08:31:33 2021: Erlang has closed.
heart: Thu Dec 23 08:31:33 2021: Would reboot. Terminating.
gmake: *** [erlang.mk:7564: run] Killed
```
Lines 7564 in erlang.mk is 
```
7563 run:: all
7564 $(verbose) $(RELX_OUTPUT_DIR)/$(RELX_REL_NAME)/bin/$(RELX_REL_NAME)$(RELX_REL_EXT) $(RELX_REL_CMD)

**Comment by essen** [comment]
You probably have a crash dump: https://www.erlang.org/doc/apps/erts/crash_dump.html

Otherwise you might want to check the core dump (getting it depends on the OS).

For logging https://www.erlang.org/doc/man/kernel_app.html#logger and other pages have the relevant documentation.

The reason none of that is documented in Cowboy is because it's unrelated to Cowboy.

**Comment by jordanchaitin** [comment]
> You probably have a crash dump: https://www.erlang.org/doc/apps/erts/crash_dump.html
> 
No, there were no crash dumps either. I had checked already. Which is why I am puzzled. 

I will look for the core dump. 

Another thing - all requests to Cowboy are via Nginx and nginx logs indicate no requests around the time of the crash.

**Comment by jordanchaitin** [comment]
> Otherwise you might want to check the core dump (getting it depends on the OS).

Ok, I checked and there are no core dumps either. It is like suddenly it crashed and did not restart without any obvious reason. Any tips on how to troubleshoot would be very appreciated.
