### ISSUE TITLE
serve static files based on path parameter

### ISSUE THREAD

**Issue by linchengcs** [ninenines/cowboy#1556]
Hi, I am trying to serve static files in different folders based on path parameters. The path parameter contains a `username`, and the handler shall serve the according user's folder.

The current cowboy repository provides an example that serves static files in one folder for one path without parameter. This example doesn't solve my problem. I am thinking of possible solutions:
- use a regular handler. basically reimplement the `cowboy_static` handler
- write a wrapper function for `cowboy_static`, add an `upgrade` function to make `cowboy_static` upgradable. Then from a regular handler, upgrade to cowboy static handler

I would like some suggestions.
Or can Essen make `cowboy_static` upgradable if it is a good idea? I wonder why it is not upgradable. Thanks

**Comment by linchengcs** [comment]
Maybe I shall just upgrade to `cowboy_rest` from a regular handler

**Comment by essen** [comment]
I guess an upgrade would be nice but it's not there now. For the time being you can wrap `cowboy_static` callbacks, deferring to it, except that in init you modify the `InitialState` to behave the way you intend (getting the user from the path and updating InitialState folder to read based on that info). Not perfect but better than alternatives.

**Comment by linchengcs** [comment]
Thank you Essen. 
I made it work following your suggestion.

**Comment by essen** [comment]
Yes it's normal you need to defer all functions you require because the handler from Cowboy's point of view is yours, not `cowboy_static`. So it can't find `cowboy_static` magically. Seems like you're good, closing, thanks!
