### ISSUE TITLE
WebSocket Performance Issues with Large(ish) Messages (OSX?)

### ISSUE THREAD

**Issue by madasebrof** [ninenines/cowboy#1561]
Cowboy is very slow to process large(ish) binary websocket data. We are sending binary messages over websockets (typically about 2 MB per message) and the speeds are roughly 7x slower than sending the same message to a simple python ws server. When sending WS data locally, the speeds are roughly 50-100x slower.

Normally, I find Elixir/Erlang is I/O bound, but I am only able to saturate 15% of a gig Ethernet link with WS if I connect to cowboy (around 140 Mbps), whereas I can get 90+% of potential bandwidth connecting to simple Python server (around 730 Mbps).

We're using Cowboy 2.9

Thanks in advance!

ps here is a repo to reproduce the issue:

https://github.com/madasebrof/cowboy-ws-test

to cowboy ws server (on OSX, Mac M1):

```
python client -> cowboy ws server
FPS = 8.62, websocket send time = 116.0ms
FPS = 8.55, websocket send time = 117.0ms
FPS = 8.70, websocket send time = 115.0ms
FPS = 8.33, websocket send time = 120.0ms
```

python client ->  python ws server (on OSX, Mac M1)

```
python client -> python ws server
FPS = 55.56, websocket send time = 18.0ms
FPS = 50.01, websocket send time = 20.0ms
FPS = 58.81, websocket send time = 17.0ms
FPS = 52.63, websocket send time = 19.0ms
```

## EDIT

**Looks like it might be somehow OSX specific???** Still around 20% slower vs. Python, but that's not a big deal.

Just ran PC -> Ubuntu...

`python client -> cowboy ws server on ubuntu`

```
FPS = 47.59, websocket send time = 21.0ms
FPS = 46.77, websocket send time = 21.4ms
FPS = 50.51, websocket send time = 19.8ms
FPS = 49.91, websocket send time = 20.0ms
FPS = 47.73, websocket send time = 21.0ms
FPS = 46.72, websocket send time = 21.4ms
FPS = 50.02, websocket send time = 20.0ms
FPS = 99.99, websocket send time = 10.0ms
FPS = 50.00, websocket send time = 20.0ms
FPS = 49.89, websocket send time = 20.0ms
FPS = 50.00, websocket send time = 20.0ms
FPS = 50.00, websocket send time = 20.0ms
FPS = 33.35, websocket send time = 30.0ms
FPS = 50.00, websocket send time = 20.0ms
FPS = 50.03, websocket send time = 20.0ms
```

`python client -> python server`

```
FPS = 142.86, websocket send time = 7.0ms
FPS = 166.70, websocket send time = 6.0ms
FPS = 23.26, websocket send time = 43.0ms
FPS = 166.73, websocket send time = 6.0ms
FPS = 167.07, websocket send time = 6.0ms
FPS = 999.83, websocket send time = 1.0ms
FPS = 23.70, websocket send time = 42.2ms
FPS = 82.95, websocket send time = 12.1ms
FPS = 117.39, websocket send time = 8.5ms
FPS = 93.33, websocket send time = 10.7ms
FPS = 85.83, websocket send time = 11.7ms
FPS = 22.29, websocket send time = 44.9ms
FPS = 167.11, websocket send time = 6.0ms
FPS = 27.13, websocket send time = 36.9ms
FPS = 159.19, websocket send time = 6.3ms
FPS = 18.16, websocket send time = 55.1ms
FPS = 23.77, websocket send time = 42.1ms
FPS = 152.29, websocket send time = 6.6ms
FPS = 124.92, websocket send time = 8.0ms
FPS = 142.88, websocket send time = 7.0ms
FPS = 66.72, websocket send time = 15.0ms
FPS = 496.66, websocket send time = 2.0ms
FPS = 200.04, websocket send time = 5.0ms
FPS = 199.99, websocket send time = 5.0ms
```

**Comment by madasebrof** [comment]
Just spent the past few days digging in to this, trying over 10 gig ethernet, etc. It does look like the Erlang/Cowboy WS is tuned for large number of connections and small messages, vs. fewer connections and large messages. Although, just looking through the WS Erlang code (which I partially understand--I know Elixir--but I can follow the logic in Erlang as it's so similar), it all seems pretty clean and straightforward. 

Anyway, if you do dig in to this, maybe just do some testing with bigger binary messages to see if you see anything odd and/or easily fixable?

Thanks!!!

**Comment by essen** [comment]
There's probably a frame size threshold at which point it is more efficient to do a recv than receiving messages passively. That said, the size of the buffer values will also matter here and they're probably not tweaked well for larger messages by default (`buffer`, `recvbuf` and `sndbuf`). Have you tried tweaking those?

**Comment by madasebrof** [comment]
Thanks for the reply! I was looking for those options, but I couldn't find them!

Night and day difference. Posting here just in case someone else stumbles across this issue.

```elixir
defmodule FrameServer.Application do
  @moduledoc false
  use Application
  require Logger

  @port 8765
  @buf_size 1024 * 1024 * 2

  @impl true
  def start(_type, _args) do
    dispatch =
      :cowboy_router.compile([
        {:_,
         [
           {"/", FrameServer, []}
         ]}
      ])

    :cowboy.start_clear(
      :server,
      [{:recbuf, @buf_size}, {:sndbuf, @buf_size}, {:buffer, @buf_size}, {:port, @port}],
      %{:env => %{:dispatch => dispatch}}
    )
  end
end
```

Reduced times to:

```
FPS = 58.84, websocket send time = 17.0ms
FPS = 23.81, websocket send time = 42.0ms
FPS = 166.65, websocket send time = 6.0ms
FPS = 62.50, websocket send time = 16.0ms
FPS = 125.01, websocket send time = 8.0ms
FPS = 143.03, websocket send time = 7.0ms
FPS = 166.45, websocket send time = 6.0ms
FPS = 166.66, websocket send time = 6.0ms
FPS = 142.83, websocket send time = 7.0ms
FPS = 143.08, websocket send time = 7.0ms
FPS = 166.63, websocket send time = 6.0ms
FPS = 16.44, websocket send time = 60.8ms
FPS = 166.65, websocket send time = 6.0ms
```

Note that this is sending a 2 MB binary file via WebSockets over 10 Gb ethernet. I am getting around 1.0 Gps throughput, so not bad!

There seem to be some hiccups, but whatever! Sooo much faster! Thanks!!!

ps there is a deadlink from this page:

https://ninenines.eu/docs/en/cowboy/2.9/manual/cowboy.start_clear/

under **TransportOpts**

to https://ninenines.eu/docs/en/cowboy/2.9/manual/ranch_tcp

Should go to

https://ninenines.eu/docs/en/ranch/2.1/manual/ranch_tcp/
