### ISSUE TITLE
sendfile not working on linux 5.16

### ISSUE THREAD

**Issue by kuon** [ninenines/cowboy#1562]
After upgrading to linux 5.16, static files in my phoenix app stopped being served.

When I try to `curl` a file, I got the following error `curl: (18) transfer closed with 203 bytes remaining to read`.

After some investigation, I found with strace the following error `sendfile(19, 22, [0], 203)              = -1 EINVAL (Invalid argument)` 

Disabling sendfile in my phoenix app, with

`protocol_options: [sendfile: false]`

did fix the issue.

I am not 100% sure the kernel upgrade is the cause, because I upgraded my whole box (archlinux) and more that just the kernel was upgraded.

I am still investigating and I will update this issue with additional finding.

**UPDATE 1**: I downgraded to 5.15.12 and rebooted, and the issue is gone, so now I am quite positive it is caused by kernel 5.16.

**UPDATE 2**: issue is still present with kernel 5.16.2.

**Comment by zevv** [comment]
Are you running ZFS by chance?

https://github.com/openzfs/zfs/issues/12971

**Comment by kuon** [comment]
Yes, good catch. I guess this is it.
