### ISSUE TITLE
regular handler handles http basic authentication

### ISSUE THREAD

**Issue by linchengcs** [ninenines/cowboy#1563]
I can handle http basic authentication with cowboy rest handler, but cannot do it with cowboy regular handler.
Is it possible to let the cowboy regular handler be able to handle basic authentication as well?

**Comment by essen** [comment]
You can do it manually yes. Check the `cowboy_rest` code if necessary.

**Comment by linchengcs** [comment]
Yes, it worked. Thank you, @essen !
`
    Auth = cowboy_req:header(<<"authorization">>, Req0),                                                                                                                                                  
    case Auth of                                                                                                                                                                                          
        undefined ->                                                                                                                                                                                      
            cowboy_req:reply(401, #{<<"www-authenticate">> => <<"Basic realm=\"cowboy\"">>}, Req0);                                                                                                       
        _ ->                                                                                                                                                                                              
            cowboy_req:reply(200, #{                                                                                                                                                                      
                                    <<"content-type">> => <<"text/plain">>                                                                                                                                
                                   }, <<"Hello world!">>, Req0)                                                                                                                                           
    end
`

**Comment by linchengcs** [comment]
closed
