### ISSUE TITLE
Doc. for parse_qs states /3 instead of /1

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/cowboy#1565]
At: https://ninenines.eu/docs/en/cowboy/2.9/manual/cowboy_req.parse_qs/

**Comment by paulo-ferraz-oliveira** [comment]
@essen, if you point me to the source I can pull request. Thank you.

**Comment by essen** [comment]
doc/src/manual/cowboy_req.parse_qs

**Comment by paulo-ferraz-oliveira** [comment]
Hm... it seems I might've mistaken the `(3)`, at the top of the doc. page, for the function's arity. There's a lot of pages that start with `(3)` and their related function's arity is 1. 😄

**Comment by ehamberg** [comment]
I guess these refer to the [man page section](https://en.wikipedia.org/wiki/Man_page#Manual_sections) and mean that these are library functions.

**Comment by essen** [comment]
Right that's what it means.
