### ISSUE TITLE
Cowboy websock example

### ISSUE THREAD

**Issue by CAD1986** [ninenines/cowboy#1570]
I am enjoying learning Eralng with your wonderful projects, thankyou.

I am working on windows 10 using mysys2.
I am getting the following error on make run (i have git, erlang.mk, etc installed)

 c:/spacetre/mysys2/home/cm/websocket/_rel
===> Resolved websocket_example-1
*WARNING* Missing application sasl. Can not upgrade with this release
===> Tarball generation error for error reason {badmatch,
                                           {error,
                                            {"c:/Users/cm/AppData/Local/Temp/.tmp_dir673476510027/releases",
                                             enoent}}}
make: *** [erlang.mk:7511: relx-rel] Error 127
``

I installed sasl from msys2 repositories page using command 
`pacman -S mingw-w64-x86_64-cyrus-sasl`

I am still getting same error,
ANY Ideas most appreciated,
cm

**Comment by essen** [comment]
Hm can you try setting `RELX_TAR = 0` before `include erlang.mk` in your Makefile?

**Comment by CAD1986** [comment]
Works great, thanks for fast response, apologies for slow reply!
