### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [ninenines/cowboy#1576]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@lethanhtrung22) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by essen** [comment]
You can send me an email at [contact@ninenines.eu](mailto:contact@ninenines.eu) if you want.

If this is related to the distribution cookie, please see this comment: https://github.com/ninenines/cowboy/issues/1574#issuecomment-1171217446

**Comment by JamieSlome** [comment]
Thanks for the follow-up @essen :)

Happy to create a `SECURITY.md` with this e-mail address for you 👍 

Just for reference, the report can be found directly here:
https://huntr.dev/bounties/ffd5c11f-aec1-476c-823f-0fcca493d179/

It is private and only accessible to maintainers with repository write permissions.

**Comment by essen** [comment]
That's exactly the same issue I linked, please read the comment. This is not a security vulnerability in Cowboy, the distribution cookie is meant to separate clusters, not to provide authentication. It is up to product developers to configure, expose or implement restrictions depending on their needs.
