### ISSUE TITLE
Connection (Transfer) close middle of the stream

### ISSUE THREAD

**Issue by 0x2C6** [ninenines/cowboy#1587]
Hi. I updated the cowboy to the latest version (prev was 1.0). After that, I found out a long-running request (streaming data) fails randomly. So it starts to stream and in the middle, it terminates with "transfer closed with 102346764 bytes remaining to read". I checked docs and saw new parameters had been added. so I updated idel_timout and set it to 15 minutes. it seemed it helped at first and it continue to run and finish successfully. but then I see it fails randomly this time (sometimes finishes sometime give the same error). I am not sure what should be updated at the same time.

**Comment by essen** [comment]
Please try against the most recent master branch, and if it's still an issue, please provide a way to reproduce (even if it takes a while to get the problem).
