### ISSUE TITLE
relx can't find cowboy app

### ISSUE THREAD

**Issue by lightuponcloud** [ninenines/cowboy#1593]
I can't run cowboy app using Erlang 23.

Error:
`init terminating in do_boot ({{error,{rlx_resolve,{app_not_found,middleware,undefined}}},[{rlx_resolve,find_app_in_code_path,2,[{_},{_}]},{rlx_resolve,subset,6,[{_},{_}]},{rlx_resolve,solve_release,2,
`

Makefile:
```
PROJECT = middleware
PROJECT_DESCRIPTION = Rest interface for Riak CS
PROJECT_VERSION = 0.1.0

DEPS = cowboy erlydtl jsx ux lager sqlite3
REL_DEPS = relx
LOCAL_DEPS = inets xmerl
DEP_PLUGINS = cowboy
TEST_DEPS = meck

dep_cowboy_commit = 2.9.0
dep_meck = git https://github.com/eproxus/meck.git master
dep_ux = git https://github.com/erlang-unicode/ux.git master
dep_jsx = git https://github.com/talentdeficit/jsx v2.11.0
dep_sqlite3 = git https://github.com/processone/erlang-sqlite3 master
dep_lager = git https://github.com/erlang-lager/lager 3.9.2
dep_relx = git https://github.com/erlware/relx v4.5.0

APP_VERSION = $(shell cat rel/version)

middleware: all
        echo APP_VERSION = $(APP_VERSION)

messages:
        erl -pa ./ebin -pa ./deps/gettext/ebin -noshell -run makemessages generate_pos uk

include erlang.mk

ERLC_OPTS += +'{parse_transform, lager_transform}'

```

relx.config:
```
{release, {middleware, "0.1.0"}, [middleware, sasl, inets, lager, runtime_tools]}.
{dev_mode, true}.
{include_erts, true}.
{extended_start_script, true}.
{sys_config, "rel/sys.config"}.
{vm_args, "rel/vm.args"}.
{overlay, [
    {template, "rel/version", "version"}
]}.
```

What could be the reason ?

**Comment by essen** [comment]
Your working directory has to match the application name. A dash followed by a version may be present. So you must rename your directory to `middleware` or `middleware-something`. Then it'll be found.

**Comment by essen** [comment]
Let's leave this ticket open because this problem is common and I think Erlang.mk can catch the error and print a nice error message instead explaining what's wrong.

**Comment by rlipscombe** [comment]
Is there an open issue for this in the erlang.mk project? I had a quick look and couldn't find one.

**Comment by essen** [comment]
Please open one, I didn't realise this is the wrong repo. Thank you!
