### ISSUE TITLE
Cowboy TLS verifies SAN and CN

### ISSUE THREAD

**Issue by lauragrechenko** [ninenines/cowboy#1597]
Hello,
we have a server which uses Cowboy with the ssl option {verify, verify_peer}.
But the server accepts the client requests and ignores SAN values.

Does Cowboy (ssl verify_peer option) validate SAN and CN or should it be implemented by users (in verify_fun for ex.)?
Thank you for your time and help.

**Comment by essen** [comment]
Cowboy doesn't do anything it only gives the options you provide to the ssl application. Cowboy only sets ALPN.

**Comment by lauragrechenko** [comment]
@essen Thank you. I saw that it gives all provided options to ssl.
But maybe you know if setup veify_peer in Cowboy, as a result, SAN is verified or not because on different forums I saw different answers.

**Comment by essen** [comment]
I'm not following ssl closely. I suspect it might differ depending on Erlang version, but I don't really know.
