### ISSUE TITLE
Release a new cowboy with updated cowlib

### ISSUE THREAD

**Issue by josevalim** [ninenines/cowboy#1610]
Hi @essen, could you please release a new cowboy that depends on cowlib 2.12.1? As you know, earlier cowlib is broken on Erlang/OTP 26. I pinged them to see if they could rollback the typespec error to a warning but I have received no confirmation yet. Thank you!

**Comment by essen** [comment]
The test suite completely crashes OTP-25.3 so I am waiting for https://github.com/erlang/otp/issues/7085 to be resolved first. It's all ready otherwise.

**Comment by jbernardo95** [comment]
Waiting for this new release 👀

**Comment by essen** [comment]
Soon after OTP-25.3.1 is available with the linked fix. Depending on your needs you may use the most recent commit from master.

**Comment by essen** [comment]
Working on it.

**Comment by essen** [comment]
2.10.0 is out. I will make a new Gun version to finish the OTP-26 compatibility and then probably post something about all this on the website. Cheers!
