### ISSUE TITLE
Docs for `cowboy_stream` module include broken links

### ISSUE THREAD

**Issue by weaversam8** [ninenines/cowboy#1618]
The documentation for the `cowboy_stream` module includes links to docs pages for the 5 functions it exports, but these links are broken. No documentation has been written for these functions.

https://github.com/ninenines/cowboy/blob/22adc4de517bf54661795f6e18b6b2e62aec4140/doc/src/manual/cowboy_stream.asciidoc?plain=1#L313-L317

**Comment by essen** [comment]
Good find, thanks.

**Comment by essen** [comment]
Done in 5fe1be70078d7970c9e3bb687294d438918d7925. Closing, thanks!
