### ISSUE TITLE
Reject responses that have explicit set-cookie

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1619]
This causes confusion otherwise. See https://github.com/ninenines/cowboy/issues/1483#issuecomment-1790344344

We want users to call set_resp_cookie or to manually set the raw resp_cookies value in the Req. A function to do that may be welcome. This is mainly useful for proxies though so not sure how much we should do.

**Comment by geeksilva97** [comment]
I am looking for issues in Erlang to practice more. Would you say I could pick this one?

**Comment by essen** [comment]
Hello @geeksilva97 sorry I had not received an email following your comment, guess it got lost. Yes it would be a good choice. Basically the functions `set_resp_header`, `set_resp_headers`, `inform`, `reply`, `stream_reply` and `stream_trailers` should fail if the headers given in argument contain `set-cookie`.

**Comment by geeksilva97** [comment]
Thank you, @essen . Will give it try, starting tomorrow.

**Comment by geeksilva97** [comment]
Just a confirmation, @essen . Should I throw an error? If so, are you expecting anything special?

**Comment by essen** [comment]
Please use something of the form:

```
exit({response_error, invalid_header,
    'The set-cookie header is special and must be set using cowboy_req:set_resp_cookie/3,4.'})
```

See a40bab8fb3491a587c93bedb53404decacfe49dc for a more extensive example.

**Comment by geeksilva97** [comment]
> Please use something of the form:
> 
> ```
> exit({response_error, invalid_header,
>     'The set-cookie header is special and must be set using cowboy_req:set_resp_cookie/3,4.'})
> ```
> 
> See [a40bab8](https://github.com/ninenines/cowboy/commit/a40bab8fb3491a587c93bedb53404decacfe49dc) for a more extensive example.

Thank you. Will do.

**Comment by essen** [comment]
Done. Closing, thank you!
