### ISSUE TITLE
I want to use Cowboy 2.11's Websocket over HTTP/2 feature, How do I configure nginx

### ISSUE THREAD

**Issue by leeyisoft** [ninenines/cowboy#1632]
I use the NGINX cowboy agent service, NGINX configuration is as follows: https://github.com/imboy-pub/imboy/blob/main/doc/nginx_dev.imboy.pub.conf

I want to use Cowboy 2.11's Websocket over HTTP/2 feature,
How do I configure nginx

**Comment by leeyisoft** [comment]
<img width="423" alt="image" src="https://github.com/ninenines/cowboy/assets/6138668/786becd4-b89a-4399-bd4c-6031f74728fc">

**Comment by essen** [comment]
I don't know nginx much. You should try stackoverflow or other forums for help. Please only open a ticket if there's an issue in Cowboy.
