### ISSUE TITLE
sys protocol in websocket handler

### ISSUE THREAD

**Issue by maxlapshin** [ninenines/cowboy#454]
I've got bad situation with leaking websocket handler:

(flussonic@127.0.0.1)5> sys:get_status(pid(0,30511,29)).
22:38:01.936 <0.30511.29> api_handler:272 api_websocket msg: {system,{<0.30811.81>,#Ref<0.0.163.218563>},get_status}
*\* exception exit: {timeout,{sys,get_status,[<0.30511.29>]}}
     in function  sys:send_system_msg/2 (sys.erl, line 231)
(flussonic@127.0.0.1)6> 
(flussonic@127.0.0.1)6> process_info(pid(0,30511,29)).  
[{current_function,{cowboy_websocket,handler_loop,4}},
 {initial_call,{cowboy_protocol,init,4}},
 {status,waiting},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.188.0>,<0.196.0>,#Port<0.669854>]},
 {dictionary,[]},
 {trap_exit,false},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.89.0>},
 {total_heap_size,2514875},
 {heap_size,832040},
 {stack_size,14},
 {reductions,272853732},
 {garbage_collection,[{min_bin_vheap_size,46368},
                      {min_heap_size,233},
                      {fullsweep_after,65535},
                      {minor_gcs,6}]},
 {suspending,[]}](flussonic@127.0.0.1)7> process_info(pid(0,30511,29),memory).
{memory,20119888}

20 megabytes in small websocket =)

And I cannot inspect it with sys protocol.

If you are going to merge pull request, I can add support for sys protocol to websockets.

**Comment by essen** [comment]
This is already in master. Closing, thanks!

**Comment by essen** [comment]
Actually let me reopen because I think this is not finished. I will check again later. Sorry for the noise!

**Comment by essen** [comment]
This now works on master.
