### ISSUE TITLE
{function_clause,[{lists,zip,[[transport,connection,pid......

### ISSUE THREAD

**Issue by emqplus** [ninenines/cowboy#555]
18:39:58.377 [error] Error in process <0.187.0> on node 'nextim@ubuntu' with exit value: {function_clause,[{lists,zip,[[transport,connection,pid,method,version,peer,host,host_info,port,path,path_info,qs,qs_vals,bindings,headers,p_headers,cookies,meta,body_state,multipart,buffer,resp_compress... 

reply function: 

reply200(Req, Term, State) ->
    {ok, cowboy_req:reply(200, [{"Content-Type", "text/plain"}], jsonify(Term), Req), State}.

**Comment by martinpritchard** [comment]
the getting stared docs http://ninenines.eu/docs/en/cowboy/HEAD/guide/getting_started/ produce this error. 
```
init(Req, Opts) ->
    Req2 = cowboy_req:reply(200,
        [{<<"content-type">>, <<"text/plain">>}],
        <<"Hello Erlang!">>,
        Req),
    {ok, Req2, Opts}.
```

should be ({ok, Req2}, not just Req2:
```
init(Req, Opts) ->
    {ok, Req2} = cowboy_req:reply(200,
        [{<<"content-type">>, <<"text/plain">>}],
        <<"Hello Erlang!">>,
        Req),
    {ok, Req2, Opts}.
```

**Comment by essen** [comment]
Those are for master, click on 1.0 for the 1.0 docs, where indeed you need to return {ok, Req2}.

**Comment by martinpritchard** [comment]
Ah, ok. I'm using erlang.mk defaults and google search for getting started, giving me a mismatching versions.

**Comment by essen** [comment]
Fixing this is something I am hoping to do in the next few days.
