### ISSUE TITLE
deploy and hot upgrade

### ISSUE THREAD

**Issue by ZhenguoYang** [ninenines/cowboy#595]
It is not an issue.

As a rookie, If I have a web server developed on cowboy to deploy, how to do that?

My steps are:
1. ssh to the remote server
2. set up erlang environment
3. copy beam files
4. run erl -pa ebin deps/*/ebin -s web_server 

However, I found the server will stop after a while.

And then, I found -detached can let the server run all the time.

My question is,
How to deploy and hot upgrade (mantaince) a cowboy based http server remotely?
Any sample?

Thanks in advance

**Comment by shailen1** [comment]
I'm also interested in using vm.arg and sys.config to configure mnesia for use in an app. Could you let me know the steps please ?
(I think I need to have [{mnesia, [{dir, "/home/x/data/"}]}]. in my rel/sys.config; what do I need to have in vm.arg?)
Thanks in advance

**Comment by essen** [comment]
Shouldn't need anything in vm.args.

Please don't ask questions on old tickets.

**Comment by shailen1** [comment]
OK thanks, sorry about the question on a closed ticket, got googled here and didn't want to opena new one ...
