### ISSUE TITLE
Allow limiting message size for WebSocket

### ISSUE THREAD

**Issue by alco** [ninenines/cowboy#612]
Currently, cowboy seems to collect the whole message before invoking the user-provided handler. This poses a security threat if an adversarial client pushes large chunks of data to the server.

There should be a way to specify the maximum message size to prevent memory exhaustion.

**Comment by essen** [comment]
So an idea to solve this fell short: https://twitter.com/MSch/status/561570971069714432

I think what we need first is an option to limit the max size of incoming data (total of all fragments). It should be applied on both fragmented and normal frames and default to a sensible value.

I'm not sure why I said 16MB is the limit for frame size, the maximum size is much much larger.

The default value could be the same value we use for body reading, 8MB.

**Comment by cybernetlab** [comment]
Any progress with it? I think that this is a serious security hole. This allows DDOS by sending a number of huge fragments. WS header has a fragment length field that can be used to drop unwanted packets on early state. I think that there should be something like `max_frag_size` in [cowboy_websocket:state](https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L56) that can be setted to `infinity` by default and would be used to check length [here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L234). If it looks applicable I can prepare PR.

Regards

**Comment by essen** [comment]
Was hoping for something useful to come out of max_heap_size but that doesn't include binaries.

I am fine with an option, but it needs to apply to both fragmented and non-fragmented frames (the maximum size for *one* frame is already way too large for most applications). We could name it simply `max_frame_size`. The default should be reasonable, something like 8MB is a good compromise.

**Comment by cybernetlab** [comment]
Can't figure right way to pass this option into state. Should I extend [upgrade](https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L73) with extra argument for this? If so then should I extend `sub_protocol` behaviour - is it breaking change? Other option - use message like `{set_option, max_frame_size, Value}` and catch it in [handler_loop](https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L206). Both approaches doesn't looks good, but the second is more reasonable for me - could you give some hint

**Comment by essen** [comment]
Right, I almost forgot, I have a breaking change to make there to allow passing any number of options. I'd suggest that you start your work with a hardcoded value set at state initialization, and then we can see together. I can probably get it done on Wednesday at most.

**Comment by cybernetlab** [comment]
Great. I'll be waiting for your changes. I'm already with hardcoded value and tests are ready. Could you notice here after your changes will be in master?

**Comment by essen** [comment]
Sure. I suggest opening what you have with a PR though, to not lose it if I run out of time. Cheers!

**Comment by cybernetlab** [comment]
Sorry - I fogot to specify issue number in commit message. So [here is](https://github.com/ninenines/cowboy/pull/1081) the PR.

**Comment by cybernetlab** [comment]
Sorry - I fogot to specify issue number in commit message. So [here is](https://github.com/ninenines/cowboy/pull/1081) the PR.

**Comment by essen** [comment]
Just an FYI: I am almost done with the required changes, but with the time I have it might take a week or two before they are added to master. Hang in there... :-)

**Comment by essen** [comment]
Done. There's now a `max_frame_size` option (about to push). The default is `infinity` for now but will be changed in 3.0 whenever that gets released. Thanks!
