### ISSUE TITLE
m3u8 mimetype

### ISSUE THREAD

**Issue by skvamme** [ninenines/cowboy#685]
Hi,
Tested HTTP Live Streaming (HLS) from Cowboy to iOS device and Safari. Works great but would be even better if there was a mimetype for m3u8 in cow_mimetypes.erl:

web_ext(<<"m3u8">>) -> {<<"application">>, <<"x-mpegURL">>, []};

With that in place http://localhost:8080/static/raspi.m3u8 will play the playlist, not download it.

/Stina Kvamme

**Comment by leeyisoft** [comment]
@skvamme  

Can you show me your code "Tested HTTP Live Streaming (HLS) from Cowboy to iOS device and Safari."

I want to implement an HLS or RTMP service based on cowboy

https://erlangforums.com/t/how-to-convert-the-misultin-api-to-cowboy-api/2795
