### ISSUE TITLE
Creating custom cowboy_protocol to deal with proxy protocol

### ISSUE THREAD

**Issue by khia** [ninenines/cowboy#708]
We use cowboy in combination with sockjs library on aws. We need to find out a client's IP address. However ELB cannot provide it in websocket case. Unless we use [proxy protocol](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/TerminologyandKeyConcepts.html#proxy-protocol). Basically what that protocol does is adding single line before the request. We don't want to reimplement the equivalent of cowboy_protocol.erl. We want to extract first line store it in middleware env for example (ideally we want to put it in http header but this is hard to achieve at this stage of request parsing). We want to pass the rest of the request back to existent cowboy_protocol.erl. Since init of cowboy_protocol calls ranch:accept_ack(Ref) we cannot do Transport:recv from our protocol wrapper module. Since init of cowboy_protocol is blocking and wait_request is private we cannot pass the reminder of a request to cowboy_protocol. 
What would be the best way to achieve the goal of supporting proxy protocol?

**Comment by ahmadster** [comment]
Hi Khia, Essen,
I'm running into this exact problem now. So what do I have to modify exactly? the cowboy_protocol.erl file? Khia, anything you can share? 
Thx

**Comment by essen** [comment]
You have to create your own protocol that parses the beginning and then calls cowboy_protocol:parse_request.

**Comment by ahmadster** [comment]
Got it, thanks.

**Comment by ferd** [comment]
For what it's worth, Heroku has a Ranch transport we use in production with cowboy for proxy protocol support: https://github.com/heroku/ranch_proxy_protocol

**Comment by ahmadster** [comment]
Excellent, thanks Fred.

**Comment by comtihon** [comment]
@ahmadster @ferd 
Hi! Is starting cowboy with `{ok, _} = ranch:start_listener(client_handler, Acceptors, ranch_proxy,
[{port, Port}], cowboy_protocol, [{env, [{dispatch, Dispatch}]}])` is enough for [ranch_proxy](https://github.com/heroku/ranch_proxy_protocol) to make this scheme working? I have the same case, as TS.

**Comment by ferd** [comment]
yes.
