### ISSUE TITLE
compress: true + onresponse hook

### ISSUE THREAD

**Issue by zyro** [ninenines/cowboy#724]
I'm running into some strange behaviour related to Gzip compression when my server sends an error response. I've defined an `onresponse` hook to send error responses in JSON format that looks something like this:

``` erlang
http_response_hook(Status, Headers, <<>>, Req) when Status >= 400 ->
    Body = function_that_returns_a_json_string(),
    ContentLengthHeader = {<<"content-length">>, integer_to_list(byte_size(Body))},
    Headers1 = lists:keyreplace(<<"content-length">>, 1, Headers, ContentLengthHeader),
    {ok, Req1} = cowboy_req:reply(Status, Headers1, Body, Req),
    Req1.
```

What I'm seeing on the client side is a (apparently) garbled response that is actually my Gzip-compressed JSON, but isn't automatically decompressed by `curl`, browsers performing AJAX calls, or anywhere else I've tried.

This only happens for responses that go through this hook, HTTP 2xx responses are correctly compressed/decompressed transparently.

Have I misunderstood the usage pattern for the response hook? Am I mis-configuring something? Is it a header issue?

**Comment by maxlapshin** [comment]
Yes, I confirm this issue:

https://gist.github.com/maxlapshin/7cd5a06250cb94e28e1d

**Comment by maxlapshin** [comment]
Loïc, is there any way to make a proper workaround for this?

Maybe I should edit some fields in onresponse hook?

**Comment by maxlapshin** [comment]
I've found workaround. Problem is that I capitalize header and double-gzip protection in reply_may_compress gets broken.

```
capitalize_hook(Status, Headers, Body, Req) ->
  Headers2 = [{case K of
    <<"content-encoding">> -> K;
    _ -> cowboy_bstr:capitalize_token(iolist_to_binary(K))
  end,iolist_to_binary(V)} || {K,V} <- Headers],
  {ok, Req2} = cowboy_req:reply(Status, Headers2, Body, Req),
  Req2.
```

This helps.  @zyro check it on your code.

**Comment by essen** [comment]
This is no longer an issue in 2.0. Closing, thanks!
