### ISSUE TITLE
Capitalising headers causes Gzip failure in browsers

### ISSUE THREAD

**Issue by zyro** [ninenines/cowboy#725]
I've found a few old issues indicating that if I want Cowboy to respond with capitalised headers, I have to define my own response hook. I'm defining one that looks like this:

``` erlang
http_response_hook(Status, Headers, Body, Req) ->
    NewHeaders = [{cowboy_bstr:capitalize_token(Name), Value} || {Name, Value} <- Headers],
    {ok, Req1} = cowboy_req:reply(Status, NewHeaders, Body, Req),
    Req1.
```

What I'm seeing however is that when `compress` is enabled in Cowboy, this hook results in any browser AJAX call failing to transparently decompress the Gzipped response, so it appears garbled. This is despite the fact that the headers are recognised correctly - for example they appear correct in the browser network monitor.

If I remove the hook everything works as expected.

Is there some internal logic being thrown off by the capitalised headers?

**Comment by nhooyr** [comment]
any updates?

**Comment by essen** [comment]
Hooks are gone, reply_may_compress is gone, closing.
