### ISSUE TITLE
part_body function and friends do not account for timeouts

### ISSUE THREAD

**Issue by priestjim** [ninenines/cowboy#730]
While parsing a multipart request through a sufficiently slow connection, the socket times out and a badarg error bubbles up the cowboy function call stack, instead of returning either an error (so it can be caught with try-catch) or a proper return value.

Example:

```
stream_uploaded_file(Req, Binary) ->
    case cowboy_req:part_body(Req, [{length, 16 * 1024 * 1024}, {read_length, 16 * 1024 * 1024}, {read_timeout, 60}]) of
        {ok, FullBinary, Req2} ->
            {ok, FullBinary, Req2};
        {more, PartialBinary, Req2} ->
            stream_uploaded_file(Req2, <<Binary/binary, PartialBinary/binary>>)
    end.
```

This will immediately fail with a 60ms timeout but instead of returning either `{error, timeout, Req2}` or throwing a proper error that can be caught, it crashes with a badmatch.

Relevant crash report:

```
{[{reason,{badmatch,{error,timeout}}},{mfa,{http_handler_upload,handle,2}},{stacktrace,[{cowboy_req,stream_multipart,2,[{file,"src/cowboy_req.erl"},{line,788}]},{cowboy_req,part_body,4,[{file,"src/cowboy_req.erl"},{line,764}]}
```

**Comment by essen** [comment]
The way the body is read has changed in 2.0. It will no longer error out when the body is read too slow (instead it will return whatever it could read in that duration. I will therefore close this. Thanks!
