### ISSUE TITLE
cowboy_static + onresponse hook

### ISSUE THREAD

**Issue by MrMemento** [ninenines/cowboy#738]
When the response reaches the 'onresponse' hook serving a static file, the Body parameter is empty (guess it will be later served from disk with some low-cost approach). This way it is not possible, to modify the headers in the response hook, because replying is not possible without the contents of the body, and simply returning the original Request has no effect on the Headers.

For a workaround, I am currently reading the files myself, and sending a response, which I can handle by the hook. Would be nice, if this hook could be used when serving static files (and streams?) too, maybe somehow being able to modify the already computed Headers, when the Body is still not available?

Keep up the great work, cheers!

**Comment by essen** [comment]
Hope you got it working. As the onresponse interface has another ticket, I'm closing, thanks!

**Comment by timclassic** [comment]
@essen This workaround worked for me on 2.0.0-pre.1.  Is there a different issue that represents the eventual fix?  I searched around but couldn't find one.

**Comment by essen** [comment]
The onresponse interface is removed entirely in Cowboy 2 as it is no longer needed, the low-level Cowboy interface allows you to do the same and much more.
