### ISSUE TITLE
cowboy_req:parse_header x-forwarded-for returns {error, badarg} with ipv6 

### ISSUE THREAD

**Issue by RaoH** [ninenines/cowboy#741]
Hi,
We noticed some interesting crashes on our application which we could pin down to when we try to parse the http header and retrieve x-forwarded-for. It only fails if the key has a ipv6 address.

Could follow the flow to when cowboy_http:token gets a ':' char in the binary.

Now I'm not certain why ':' isn't allowed in the binary, could not find anything in any rfc (could have missed something). But ipv6 should still be allowed in the header.

**Comment by essen** [comment]
I've just pushed a fix to Cowlib for this.
