### ISSUE TITLE
Fix flowchart of cowboy_rest for PUT on new resource

### ISSUE THREAD

**Issue by sstrigler** [ninenines/cowboy#755]
http://ninenines.eu/docs/en/cowboy/1.0/guide/rest_flowcharts/ suggests that for a PUT on a new resource the resulting status code depends on whether a resp location or body has been set. Apparently this doesn't match the current state of the implementation (v1.0.0 and beyond) as within cowboy_rest:maybe_created/2 a PUT on a new resource always ends up with status code 201 without any further conditions.

Most likely the flowchart has to be fixed in order to reflect this new behaviour.

**Comment by essen** [comment]
It took almost 5 years but I've finally gotten around to it. Thanks!
