### ISSUE TITLE
How to start cowboy hello world application? (DOC Improve needed)

### ISSUE THREAD

**Issue by ghost** [ninenines/cowboy#758]
I am very new to cowboy, I tried read the quick start guide, but still can not run my first cowboy application hello world .

I also learn webmachine, which has a good tutorial how to start application

```
Quick Start

A shell script is provided in the webmachine repository to help users quickly and easily create a new webmachine application.

git clone git://github.com/basho/webmachine.git
cd webmachine
./scripts/new_webmachine.sh mydemo
A destination path can also be passed to the new_webmachine.sh script.

./scripts/new_webmachine.sh mydemo ~/webmachine_applications
Once a new application has been created it can be built and started.

cd mydemo
make
./start.sh
The application will be available at http://localhost:8080.

To learn more continue reading here.
```

**Comment by shlokspeare** [comment]
unable to start the hello_world cowboy app.

Getting the error below as we hit the localhost:8080:

=ERROR REPORT==== 22-Apr-2015::13:53:46 ===
Error in process <0.163.0> on node 'hello_world_example@127.0.0.1' with exit value: {[{reason,undef},{mfa,{toppage_handler,init,3}},{stacktrace,[{toppage_handler,init,[{tcp,http},{http_req,#Port<0.549>,ranch_tcp,keepalive,<0.163.0>,<<3 bytes>>,'HTTP/1.1',{{127,0,0,1},52310},<<9 bytes>>,undefined,8080,<<1 byte>>,undefined,<<0 bytes>>,undefined,[],[{<<4 bytes>>,<<14 bytes>>},{<<10 bytes>>,<<10 bytes>>},{<<13 bytes>>,<<9 bytes>>},{<<6 bytes>>,<<74 bytes>>},{<<10 bytes>>,<<120 bytes>>},{<<15 bytes>>,<<19 bytes>>},{<<15 bytes>>,<<14 bytes>>}],[{<<10 bytes>>,[... 


=ERROR REPORT==== 22-Apr-2015::13:53:46 ===
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.163.0> exit with reason: {[{reason,undef},{mfa,{toppage_handler,init,3}},{stacktrace,[{toppage_handler,init,[{tcp,http},{http_req,#Port<0.549>,ranch_tcp,keepalive,<0.163.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52310},<<"localhost">>,undefined,8080,<<"/">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:8080">>},{<<"connection">>,<<"keep-alive">>},{<<"cache-control">>,<<"max-age=0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>}],[{<<"connection">>,[<<"keep-alive">>]}],undefined,[],waiting,<<>>,undefined,false,waiting,[],<<>>,undefined},[]],[]},{cowboy_handler,handler_init,4,[{file,"src/cowboy_handler.erl"},{line,64}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.549>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.163.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},52310}},{host,<<"localhost">>},{host_info,undefined},{port,8080},{path,<<"/">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:8080">>},{<<"connection">>,<<"keep-alive">>},{<<"cache-control">>,<<"max-age=0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36">>},{<<"accept-encoding">>,<<"gzip, deflate, sdch">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>}]},{p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,[]}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}

**Comment by essen** [comment]
You are somehow fetching Cowboy 1.x instead of master.

**Comment by shlokspeare** [comment]
This is the code as it is from the github repo. Example: hello_world

**Comment by essen** [comment]
I am guessing that you installed Erlang from Erlang Solutions and didn't pick the "standard" package. Please install the "standard" one.

**Comment by achempion** [comment]
To run dependencies via shell:
```erlang
1> application:start(ranch), application:start(cowlib),  application:start(cowboy).
ok
2> application:start(your_app_here).
ok
```
