### ISSUE TITLE
1.0.1 docs do not adequately explain separation of init and handle for HTTP requests

### ISSUE THREAD

**Issue by davidw** [ninenines/cowboy#764]
I've read through the documentation, and did not get a good feel for why there is an init/3 function and a handle function, or why they are separate, other than init/3 being common to all requests.  I see in HEAD that there is just init, for instance.   Googling, I found this:

http://erlang.org/pipermail/erlang-questions/2012-December/071368.html

Which, for whatever reason, gave me a clearer picture of how things actually work and how code ought to be organized.  

I'd be happy to work on the docs a bit to add something that gives a bit more explanation.

**Comment by essen** [comment]
Hey, as pointed out it all got simplified, and I'm not actively working on 1.0.x other than fixing bugs and merging patches. That said feel free to send patches to improve the 1.0.x docs. Closing, thanks for the feedback!
