### ISSUE TITLE
User's Guide could use improved navigation

### ISSUE THREAD

**Issue by davidw** [ninenines/cowboy#765]
In most multi-page tutorials, there is a way to navigate between sections.

Different mechanisms used include:
- Next / Previous buttons: http://tcl.apache.org/rivet/manual2.2/internals.html
- Some kind of navigation area that lets you click on the next thing: http://www.erlang.org/doc/getting_started/seq_prog.html#id60264

Postgres has nice navigation, letting you do previous/next/up: http://www.postgresql.org/docs/current/static/continuous-archiving.html

It'd be handy to have this for the cowboy user guide so that it's easier to read it sequentially.

**Comment by essen** [comment]
Think it's done. Please do tell if the current solution is not enough. Thanks!

**Comment by davidw** [comment]
Looks great - thank you!
