### ISSUE TITLE
spdy protocol doesn't handle HTTP/1.X requests

### ISSUE THREAD

**Issue by camshaft** [ninenines/cowboy#772]
### Steps to reproduce

Start a spdy server

```erlang
Dispatch = cowboy_router:compile([
	{'_', [
		{"/", toppage_handler, []}
	]}
]),
PrivDir = code:priv_dir(spdy_test),
{ok, _} = cowboy:start_spdy(spdy, 100, [
	{port, 4433},
	{cacertfile, PrivDir ++ "/ssl/cowboy-ca.crt"},
	{certfile, PrivDir ++ "/ssl/server.crt"},
	{keyfile, PrivDir ++ "/ssl/server.key"}
], [{env, [{dispatch, Dispatch}]}]).
```

use curl to connect to the server

```sh
$ curl https://localhost:4433 -v
* Adding handle: conn: 0x7ff1a3003a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7ff1a3003a00) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 4433 (#0)
*   Trying ::1...
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4433 (#0)

** ssl info snip **

> GET /api HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:4433
> Accept: */*
>
```

The request hangs at this point. I've identified the problem to be in the [`cowboy_spdy:parse_frame/2`](https://github.com/ninenines/cowboy/blob/999dc5b7c1665fb620c14f6303610793313efe58/src/cowboy_spdy.erl#L238) function. I've played around with it a bit and got it working but for something more serious it would require a refactor of `cowboy_protocol`, as it hijacks the request in `parse_request/3` and in this case the request may or may not be a HTTP/1.X request.

If this isn't fixed, the advertised http/1.x protocols should probably be removed:

```sh
$ openssl s_client -connect localhost:4433 -nextprotoneg ''
CONNECTED(00000003)
Protocols advertised by server: spdy/3, http/1.1, http/1.0
```

**Comment by essen** [comment]
I'll close this because it has a PR for it. Cheers!
