### ISSUE TITLE
undefined function observer:start/0 ?

### ISSUE THREAD

**Issue by sitstone** [ninenines/cowboy#774]
Hello, I am exploring cowboy and erlang. Everything works fine, but when I ran the "hello_erlang" example in the user's guide using command
./_rel/hello_erlang_release/bin/hello_erlang_release console
,  and then in the erlang shell, I input the command:
(george@127.0.0.1)1> observer:start().
I got:
** exception error: undefined function observer:start/0

So, what am I wrong, and how can I get observer:start/0 started?

**Comment by essen** [comment]
Closing, cheers!
