### ISSUE TITLE
Empty chunk in chunked responses

### ISSUE THREAD

**Issue by rgrinberg** [ninenines/cowboy#777]
Modifying the chunked hello world example:

```
-module(toppage_handler).

-export([init/2]).

init(Req, Opts) ->
	Req2 = cowboy_req:chunked_reply(200, Req),
	cowboy_req:chunk("Hello\r\n", Req2),
	timer:sleep(1000),
	cowboy_req:chunk("World\r\n", Req2),
	timer:sleep(1000),
	cowboy_req:chunk("", Req2),
	timer:sleep(1000),
	cowboy_req:chunk("Chunked!\r\n", Req2),
	{ok, Req2, Opts}.
```

The last chunk (`"Chunked!\r\n`") is omitted. Just want to confirm that this is expected behavior.

**Comment by maxlapshin** [comment]
Perhaps, it should be a return flag:

send_chunk(Req, <<>>) -> {error, bad_chunk};
send_chunk(Req,Bin) when size(Bin) > 0 -> ....., ok.
?

So user will be able to crash or not to crash.

**Comment by essen** [comment]
Do you have a good use case where crashing would make sense?

**Comment by maxlapshin** [comment]
Sending empty chunk in chunked transfer encoding means closing connection for a peer.

So in terms of transport, sending empty chunk as a part of stream is an error, because it will lead to strange bugs: client will silently disconnect. As for me, it is good to have an option to get an error in logs for it.

**Comment by essen** [comment]
Yes but we were talking of ignoring empty chunks and not sending them through the chunk/2 function (Cowboy has a last_chunk/1 function for this purpose that it uses internally). So the stream would be uninterrupted regardless of what the Erlang code tries to send. No more strange bugs.

**Comment by maxlapshin** [comment]
So you think that it is better to have  ok = send_chunk(<<>>) ?  Not  {error, empty_chunk} = send_chunk(<<>>) ?

**Comment by rgrinberg** [comment]
@maxlapshin I'd prefer the former

**Comment by essen** [comment]
It is more in line with the rest of the socket code everywhere. If you gen_tcp:send an empty value, it will do exactly that.

**Comment by essen** [comment]
Pushed a fix. Thanks for the thoughts and report!
