### ISSUE TITLE
Cannot establish a connection from TCP

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [ninenines/cowboy#778]
hi, i have the same issue with him 
https://github.com/ninenines/cowboy/issues/646

i write a erlang websocket demo with cowboy, test it with http://www.websocket.org/echo.html, it works fine.

i change the cocos2d-x sample code ws url from ws://echo.websocket.org to ws://127.0.0.1:8080/websocket, erlang told me connection terminated with {error,closed}.

i searched the code and add log, at last i found the suspicious code 

cowboy_websocket.erl,line 211
'
handler_loop(State=#state{socket=Socket, messages={OK, Closed, Error},
		timeout_ref=TRef}, Req, HandlerState, SoFar) ->
	receive
		{OK, Socket, Data} ->
			State2 = handler_loop_timeout(State),
			websocket_data(State2, Req, HandlerState,
				<< SoFar/binary, Data/binary >>);
		{Closed, Socket} ->
%%--------------------------------------------------------------------------
%%here will cause the error code, but i don't know why
			handler_terminate(State, Req, HandlerState, {error, closed});
'

when i use cocoa-websocket to do the same test, cowboy has the same issue.
cocoa-websocket url   https://github.com/talkative/cocoa-websocket

**Comment by essen** [comment]
That's Cowboy detecting the socket was closed.

**Comment by essen** [comment]
I can't test cocoa-websocket as I run Linux. I do not know why one or the other would close the connection early.

**Comment by essen** [comment]
Actually I remember now, `cocos2d-x` is expecting the server to respond to frames sent over Websocket in a specific manner, and the Websocket example just echoes back. So it closed the connection upon receiving incorrect values, and that has nothing to do with the Websocket protocol.

**Comment by essen** [comment]
Disregard previous (now deleted) comment.

**Comment by ziyouchutuwenwu** [comment]
thank you for your response, let me try to build one sample

**Comment by ziyouchutuwenwu** [comment]
i test a sample code on debian, it works fine, maybe i need to make a feedback to cocos2d team, thanks very much.
