### ISSUE TITLE
Does cowboy has access log and firewall?

### ISSUE THREAD

**Issue by sugus-seu** [ninenines/cowboy#781]
I track access log in my own handler which is not elegant.
And How can I configure white/black IP list?

**Comment by rlipscombe** [comment]
You can add access logging with the onresponse hook: https://github.com/ninenines/cowboy/blob/master/examples/error_hook/src/error_hook_app.erl#L19

**Comment by rlipscombe** [comment]
You can add IP filtering with custom middleware: http://ninenines.eu/docs/en/cowboy/1.0/guide/middlewares/

**Comment by essen** [comment]
Hope your problem is solved. Closing. Cheers.
