### ISSUE TITLE
Timeout issue when using cowboy_req:reply/2 and a {stop, Req, State} response

### ISSUE THREAD

**Issue by gmr** [ninenines/cowboy#784]
I'm having a weird issue with what I assume is using ``cowboy_req:reply/n`` from within my handlers invoked by ``content_types_accepted/2``. I've unsuccessfully tried a variety of ways to solve this, so I'm reaching out for help. I don't doubt the problem exists between the keyboard and chair, but hopefully you can set me on the right path or identify the problem. I'm using ``master`` in the current repo.

What I am trying to do is conditionally set the response code in the response from a request. To do this, I've tried a variety of ways, including using ``cowboy_req:reply/4`` before returning ``{stop, Req1, State}`` where ``Req1`` is the return from ``cowboy_req:reply/4``. The current implementation of the handler can be seen in [this handler](https://github.com/gmr/privatepaste/blob/master/src/privpaste_handler_paste.erl#L43).

My issue is the POST calls always timeout, blocking any new requests and do not close the connections. GET calls are always very speedy and do not have this issue. Both process the return content in the same way. I'm guessing the difference is in how POST is invoked differently than the GET (``content_types_accepted/2`` vs ``content_types_provided/2``).

Here's a log that demonstrates what I am seeing. After this are reports from ab that detail the very nice throughput of the GET requests.

It's worth noting that the POST (and PUT) requests do not error in any other way, it's only this timeout, and it's been consistent across every way I've attempted to approach the problem.

Please let me know if you need any other information or spot what I am doing wrong here.

#### console.log
```
2015-01-27 23:21:29.718 [info] <0.10214.0> 201 POST /paste
2015-01-27 23:21:44.722 [error] emulator Error in process <0.10214.0> on node 'privatepaste@gmr-home' with exit value: {{badmatch,{error,timeout}},[{cowboy_req,body_recv,3,[{file,"src/cowboy_req.erl"},{line,508}]},{cowboy_req,body_loop,5,[{file,"src/cowboy_req.erl"},{line,491}]},{cowboy_protocol,next_request,3,[{file,"src/cowboy_protocol.er... 

2015-01-27 23:21:44.722 [error] <0.152.0> Ranch listener privpaste_cowboy_listener had connection process started with cowboy_protocol:start_link/4 at <0.10214.0> exit with reason: {{badmatch,{error,timeout}},[{cowboy_req,body_recv,3,[{file,"src/cowboy_req.erl"},{line,508}]},{cowboy_req,body_loop,5,[{file,"src/cowboy_req.erl"},{line,491}]},{cowboy_protocol,next_request,3,[{file,"src/cowboy_protocol.erl"},{line,498}]}]}

2015-01-27 23:21:44.724 [info] <0.10218.0> 200 GET /714f22b4
```

#### Example of privpaste_paste:get_html/2 velocity
```
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /714f22b4
Document Length:        10787 bytes

Concurrency Level:      100
Time taken for tests:   2.795 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      109210000 bytes
HTML transferred:       107870000 bytes
Requests per second:    3577.18 [#/sec] (mean)
Time per request:       27.955 [ms] (mean)
Time per request:       0.280 [ms] (mean, across all concurrent requests)
Transfer rate:          38150.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   7.2      0     508
Processing:     4   27  49.0     22     528
Waiting:        4   27  48.8     22     528
Total:          6   28  49.4     23     529

Percentage of the requests served within a certain time (ms)
  50%     23
  66%     25
  75%     27
  80%     28
  90%     31
  95%     34
  98%     37
  99%    506
 100%    529 (longest request)
```

#### Example of privpaste_paste:get_json/2 velocity
```
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /714f22b4
Document Length:        6120 bytes

Concurrency Level:      100
Time taken for tests:   1.782 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      62600000 bytes
HTML transferred:       61200000 bytes
Requests per second:    5610.70 [#/sec] (mean)
Time per request:       17.823 [ms] (mean)
Time per request:       0.178 [ms] (mean, across all concurrent requests)
Transfer rate:          34299.76 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    8  21.9      6     355
Processing:     6   10  26.9      8     356
Waiting:        6   10  26.9      8     356
Total:          9   18  34.7     14     367

Percentage of the requests served within a certain time (ms)
  50%     14
  66%     14
  75%     14
  80%     14
  90%     15
  95%     15
  98%     20
  99%     57
 100%    367 (longest request)
```

**Comment by essen** [comment]
You dismiss the returned Req here: https://github.com/gmr/privatepaste/blob/master/src/privpaste_handler_paste.erl#L136

So Cowboy doesn't know you already read the body and will try to read it again before it can process the next request.

**Comment by gmr** [comment]
Ah, I didn't realize that was modifying the request, sorry for the bother!
