### ISSUE TITLE
websocket_terminate not being called

### ISSUE THREAD

**Issue by andyc** [ninenines/cowboy#787]
I have written a vanilla web_socket handler, mostly copy and paste from examples directory. I have added the following lines to the websocket example (and some io:format to see what's being called):

-export([websocket_terminate/3]).

websocket_terminate(Reason, Req, State) ->
    io:format("websocket_terminate Reason ~p Req ~p State ~p~n", [Reason, Req, State]),
    ok.

Note:
 * I have also added a timeout of 10s to the init function.
 * I am invoking this via a release created by erlang.mk/relx in console mode.

I was expecting the following:
 * If I kill the web browser window, that the websocket connection would be terminated and the websocket_terminate would be called.
 * If I didn't kill the web browser window and specified a timeout (as i have done) that eventually websocket_terminate would be called in the process of cowboy killing the ws_handler process.
 * In terms of API design, most other similar implementations of ws and SockJS would typically provide an onClose as part of the behaviour. terminate is more generalised, but I think the obvious use-case is to know when (for whatever reason) the ws is about to disappear. Having said that, if terminate worked, that should be sufficient.

What I observed: websocket_terminate is never called.

ws_handler.erl:

-module(ws_handler).

-export([init/2]).
-export([websocket_handle/3]).
-export([websocket_info/3]).
-export([websocket_terminate/3]).

init(Req, Opts) ->
    io:format("Init Req ~p Opts ~p~n", [Req, Opts]),
    erlang:start_timer(1000, self(), <<"Hello!">>),
    %Pid = self(),                                                                                                                         %kv_server:put(<<"connections">>, Pid, Pid),                                                                                       
    {cowboy_websocket, Req, Opts, 10000}.

websocket_handle({text, Msg}, Req, State) ->
    io:format("websocket_handle Msg ~p~n", [Msg]),
    {reply, {text, << "That's what she said! ", Msg/binary >>}, Req, State};

websocket_handle(Data, Req, State) ->
    io:format("websocket_handle Data ~p~n", [Data]),
    {ok, Req, State}.

websocket_info({server_event, Msg}, Req, State) ->
    io:format("websocket_info server_event Msg ~p~n", [Msg]),
    {reply, {text, Msg}, Req, State};
websocket_info({timeout, _Ref, Msg}, Req, State) ->
    io:format("websocket_info timeout Msg ~p~n", [Msg]),
    {reply, {text, Msg}, Req, State};
websocket_info(Info, Req, State) ->
    io:format("websocket_info Info ~p~n", [Info]),
    {ok, Req, State}.

websocket_terminate(Reason, Req, State) ->
    io:format("websocket_terminate Reason ~p Req ~p State ~p~n", [Reason, Req, State]),
    ok.

Cheers,
Andrew

**Comment by essen** [comment]
You are using Cowboy master, which does not have a websocket_terminate/3 anymore. Rename it to terminate/3 and it should work.

**Comment by andyc** [comment]
Thanks this works now.
