### ISSUE TITLE
Can't Compile Broken on at least on OS X 10.10.2

### ISSUE THREAD

**Issue by edescourtis** [ninenines/cowboy#788]
<pre>
Erics-MacBook-Pro:ewstunnel eric$ ./rebar get-deps compile
==> goldrush (get-deps)
==> lager (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> rel (get-deps)
==> ewstunnel (get-deps)
==> goldrush (compile)
==> lager (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
Compiling /Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl failed:
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:58: can't find include lib "cowlib/include/cow_parse.hrl"
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:270: undefined macro 'IS_WS/1'
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:432: undefined macro 'LOWER/4'
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:258: function parse_hd_name/8 undefined
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:405: function parse_host/3 undefined
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:275: Warning: function parse_hd_name_ws/8 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:282: Warning: function wait_hd_before_value/8 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:295: Warning: function parse_hd_before_value/8 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:314: Warning: function wait_hd_value/9 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:329: Warning: function wait_hd_value_nl/9 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:343: Warning: function parse_hd_value/9 is unused
/Users/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:361: Warning: function clean_value_ws_end/2 is unused
ERROR: compile failed while processing /Users/eric/dev/ewstunnel/deps/cowboy: rebar_abort
</pre>

**Comment by essen** [comment]
Sounds like you updated Cowboy without updating Cowlib.

**Comment by edescourtis** [comment]
I did a rm -rf deps then ./rebar get-deps compile

**Comment by edescourtis** [comment]
Tested again just now on ubuntu 14.04.
<pre>
eric@trading:~/dev/ewstunnel$ ./rebar get-deps compile
WARN:  Expected /home/eric/dev/ewstunnel/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowboy to be an app dir (containing ebin/*.app), but no .app found.
==> rel (get-deps)
==> ewstunnel (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowboy to be an app dir (containing ebin/*.app), but no .app found.
Pulling lager from {git,"git://github.com/basho/lager.git",{branch,master}}
Cloning into 'lager'...
Pulling cowboy from {git,"git://github.com/extend/cowboy.git",{branch,master}}
Cloning into 'cowboy'...
WARN:  Expected /home/eric/dev/ewstunnel/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
==> lager (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.6"}}
Cloning into 'goldrush'...
==> goldrush (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/ranch to be an app dir (containing ebin/*.app), but no .app found.
==> cowboy (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/ranch to be an app dir (containing ebin/*.app), but no .app found.
Pulling cowlib from {git,"git://github.com/ninenines/cowlib.git","1.0.0"}
Cloning into 'cowlib'...
Pulling ranch from {git,"git://github.com/ninenines/ranch.git","1.0.0"}
Cloning into 'ranch'...
==> cowlib (get-deps)
==> ranch (get-deps)
==> goldrush (compile)
Compiled src/gr_manager_sup.erl
Compiled src/gr_counter.erl
Compiled src/glc_lib.erl
Compiled src/gr_context.erl
Compiled src/gr_param_sup.erl
Compiled src/gr_app.erl
Compiled src/gr_counter_sup.erl
Compiled src/gr_param.erl
Compiled src/glc_ops.erl
Compiled src/gr_manager.erl
Compiled src/gre.erl
Compiled src/gr_sup.erl
Compiled src/glc.erl
Compiled src/glc_code.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_msg.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/lager_config.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_format.erl
Compiled src/lager_app.erl
Compiled src/lager_sup.erl
Compiled src/lager_trunc_io.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_console_backend.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager_common_test_backend.erl
Compiled src/lager.erl
Compiled src/lager_file_backend.erl
Compiled src/lager_crash_log.erl
==> cowlib (compile)
Compiled src/cow_date.erl
Compiled src/cow_http.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_cookie.erl
Compiled src/cow_multipart.erl
Compiled src/cow_http_te.erl
Compiled src/cow_qs.erl
Compiled src/cow_spdy.erl
Compiled src/cow_mimetypes.erl
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_app.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch.erl
Compiled src/ranch_server.erl
==> cowboy (compile)
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_loop.erl
Compiling /home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl failed:
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:58: can't find include lib "cowlib/include/cow_parse.hrl"
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:270: undefined macro 'IS_WS/1'
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:432: undefined macro 'LOWER/4'
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:258: function parse_hd_name/8 undefined
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:405: function parse_host/3 undefined
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:275: Warning: function parse_hd_name_ws/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:282: Warning: function wait_hd_before_value/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:295: Warning: function parse_hd_before_value/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:314: Warning: function wait_hd_value/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:329: Warning: function wait_hd_value_nl/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:343: Warning: function parse_hd_value/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:361: Warning: function clean_value_ws_end/2 is unused
ERROR: compile failed while processing /home/eric/dev/ewstunnel/deps/cowboy: rebar_abort
eric@trading:~/dev/ewstunnel$ date
Wed Feb  4 09:32:24 EST 2015
eric@trading:~/dev/ewstunnel$
</pre>

**Comment by essen** [comment]
Oh right I forgot to update the rebar.config file to use cowlib master. Please send a patch or wait a few days for the new tag, this is only temporary.

**Comment by edescourtis** [comment]
I tried to just change the rebar.config to use cowlib master but it still wasn't working for some reason. I'll just wait for now. I will anchor myself to a previously working commit for the next few days.

**Comment by essen** [comment]
Even after rm -rf deps again?

**Comment by edescourtis** [comment]
Apparently.
<pre>
eric@eric:~/dev/ewstunnel$ rm -rf deps
eric@eric:~/dev/ewstunnel$ git tag
1.0.0
1.0.1
1.0.2
1.0.3
eric@eric:~/dev/ewstunnel$ ./rebar get-deps compile
WARN:  Expected /home/eric/dev/ewstunnel/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowboy to be an app dir (containing ebin/*.app), but no .app found.
==> rel (get-deps)
==> ewstunnel (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/lager to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowboy to be an app dir (containing ebin/*.app), but no .app found.
Pulling lager from {git,"git://github.com/basho/lager.git",{branch,master}}
Cloning into 'lager'...
Pulling cowboy from {git,"git://github.com/extend/cowboy.git",{branch,master}}
Cloning into 'cowboy'...
WARN:  Expected /home/eric/dev/ewstunnel/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
==> lager (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.6"}}
Cloning into 'goldrush'...
==> goldrush (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/ranch to be an app dir (containing ebin/*.app), but no .app found.
==> cowboy (get-deps)
WARN:  Expected /home/eric/dev/ewstunnel/deps/cowlib to be an app dir (containing ebin/*.app), but no .app found.
WARN:  Expected /home/eric/dev/ewstunnel/deps/ranch to be an app dir (containing ebin/*.app), but no .app found.
Pulling cowlib from {git,"git://github.com/ninenines/cowlib.git","1.0.0"}
Cloning into 'cowlib'...
Pulling ranch from {git,"git://github.com/ninenines/ranch.git","1.0.0"}
Cloning into 'ranch'...
==> cowlib (get-deps)
==> ranch (get-deps)
==> goldrush (compile)
Compiled src/gr_counter_sup.erl
Compiled src/gr_manager.erl
Compiled src/glc.erl
Compiled src/gr_manager_sup.erl
Compiled src/gr_sup.erl
Compiled src/gr_context.erl
Compiled src/gr_param_sup.erl
Compiled src/gr_counter.erl
Compiled src/glc_ops.erl
Compiled src/gr_app.erl
Compiled src/glc_lib.erl
Compiled src/gre.erl
Compiled src/gr_param.erl
Compiled src/glc_code.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_msg.erl
Compiled src/lager_sup.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_console_backend.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_config.erl
Compiled src/lager_common_test_backend.erl
Compiled src/lager_app.erl
Compiled src/lager.erl
Compiled src/lager_format.erl
Compiled src/lager_crash_log.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_trunc_io.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager_file_backend.erl
==> cowlib (compile)
Compiled src/cow_cookie.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_http_te.erl
Compiled src/cow_date.erl
Compiled src/cow_spdy.erl
Compiled src/cow_qs.erl
Compiled src/cow_http.erl
Compiled src/cow_multipart.erl
Compiled src/cow_mimetypes.erl
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_app.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_tcp.erl
==> cowboy (compile)
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_constraints.erl
Compiled src/cowboy_loop.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy.erl
Compiling /home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl failed:
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:58: can't find include lib "cowlib/include/cow_parse.hrl"
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:270: undefined macro 'IS_WS/1'
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:432: undefined macro 'LOWER/4'
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:258: function parse_hd_name/8 undefined
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:405: function parse_host/3 undefined
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:275: Warning: function parse_hd_name_ws/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:282: Warning: function wait_hd_before_value/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:295: Warning: function parse_hd_before_value/8 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:314: Warning: function wait_hd_value/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:329: Warning: function wait_hd_value_nl/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:343: Warning: function parse_hd_value/9 is unused
/home/eric/dev/ewstunnel/deps/cowboy/src/cowboy_protocol.erl:361: Warning: function clean_value_ws_end/2 is unused
ERROR: compile failed while processing /home/eric/dev/ewstunnel/deps/cowboy: rebar_abort
eric@eric:~/dev/ewstunnel$ date
Wed Feb  4 13:39:08 EST 2015
</pre>

**Comment by edescourtis** [comment]
Let make the change again and see.

**Comment by edescourtis** [comment]
Works

**Comment by essen** [comment]
Cowboy should point to Cowlib 1.1.0 for both Makefile and rebar.config now. Closing, thanks!
