### ISSUE TITLE
Need a more informative websocket example

### ISSUE THREAD

**Issue by ijt** [ninenines/cowboy#791]
I was hoping to see something like a chat server in there. I tried to understand the code well enough to write one myself, but I have to admit defeat.

**Comment by edescourtis** [comment]
I was able to figure it out. What exactly are you having problems with?

**Comment by ijt** [comment]
I have no idea how to broadcast the message coming in from one client to
all the others.

The example doesn't show how to do this. If you look at other libraries
that implement websockets, such as gorilla, they show how to do it.


On Tue, Feb 10, 2015 at 11:37 AM, Eric des Courtis <notifications@github.com

**Comment by edescourtis** [comment]
Each Websocket has a process from what I understand. So you would have to register the processes somewhere (ets, gen_server etc....) in init and notify them by sending them a message (received by websocket_info).

**Comment by edescourtis** [comment]
Does that answer your question?

**Comment by essen** [comment]
Heh this is an example of the Websocket interface, not a web chat. That said, if you know enough Erlang to use Cowboy, you should be able to write a chat based on the example very easily. And if you know gproc, then it should be just a matter of adding 2 lines to the example. :-)

**Comment by ijt** [comment]
Maybe, but I think it would help more to just see a functioning demo of
this.

**Comment by ijt** [comment]
How do I get the process for a websocket? The ws_handler:init function
seems to tell cowboy to make one, but by that time the control is out of my
hands.

Looking in the cowboy websocket code, my searches for "proc" and "pid"
turned up nothing.

If it's so easy, why don't you do it?

**Comment by essen** [comment]
It's the same as with every other types of handlers: 1 process per connection. So `self()` is your pid. It's pure Erlang there, nothing to do with Cowboy, except that you'll receive messages in `websocket_info`, but that should be covered in the guide.

**Comment by pdincau** [comment]
@ijt you can take a look at this https://github.com/mattreduce/minasan

**Comment by edgurgel** [comment]
> If it's so easy, why don't you do it?

That's the right approach :+1: . Perfect way to talk with developers on an open source project.

BTW, you can sponsor the development: http://ninenines.eu/support/

**Comment by essen** [comment]
Ah ah no offense taken. It's a conscious decision that I understand can be frustrating to language newcomers. Making it a real chat would not help at all because it'd still feel like black magic. Minasan that you linked above is exactly that. Same as the Websocket example, plus a few gproc calls. You need to understand processes before it can make sense.

That said, the lack of Cowboy documentation for beginners will be covered by the book, which can go into much greater details to explain how everything works, both from the Erlang point of view and Cowboy's, including client side stuff.

**Comment by edescourtis** [comment]
@ijt Perhaps it might be a good idea to start by reading this book http://learnyousomeerlang.com/content .

**Comment by pdincau** [comment]
@essen I gave the example as a reference an nothing more. I do agree that even the example is pointless without a basic erlang knowledge (and in this case gproc, cowboy knowledge). 

Great to know you are still thinking about writing a book :+1:

**Comment by essen** [comment]
Yep it's a good example, a few steps more than what I show at tutorials/training (I don't really do the client side part there).

Yep started writing the book and had to take a break because of life, will resume later this month. Hope to start publishing it when the chapters covering the first application are done (around 10 of them).

**Comment by ijt** [comment]
Thanks pdincau, very helpful.

**Comment by ijt** [comment]
Loïc Hoguin, having looked at minasan, I agree that it still seems like
black magic, though at least now I have a better idea of how to do it.

There's a gproc:send call where the message is broadcast to all the
websocket processes. The thing I don't see anywhere is a corresponding
receive call. How does that work?

**Comment by essen** [comment]
As I and others pointed out above, and something the Cowboy docs cover in more details, messages received arrive in `websocket_info` (for this particular point, here: http://ninenines.eu/docs/en/cowboy/1.0/guide/ws_handlers/#handling_erlang_messages). This is similar to what `gen_server` and others do in OTP.

I really recommend learning more Erlang before trying Cowboy if this sounds confusing. This is something that is very trivial once you have learnt the basics. My goal with the book is to lower the barrier of entry but until then nobody should try using Cowboy until they get comfortable with Erlang first, there's simply no resources available to learn them side by side.

**Comment by ijt** [comment]
It makes perfect sense now. Thanks for explaining!

**Comment by essen** [comment]
Closing then, thanks everyone for the help.
