### ISSUE TITLE
rebar compile error of latest master.

### ISSUE THREAD

**Issue by ubill** [ninenines/cowboy#793]
I tried rebar get-deps compile on the latest master 89c47d3d , it fails and I get these error traces:

rebar get-deps compile

==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
Compiling src/cowboy_protocol.erl failed:
src/cowboy_protocol.erl:58: can't find include lib "cowlib/include/cow_parse.hrl"
src/cowboy_protocol.erl:270: undefined macro 'IS_WS/1'
src/cowboy_protocol.erl:432: undefined macro 'LOWER/4'
src/cowboy_protocol.erl:258: function parse_hd_name/8 undefined
src/cowboy_protocol.erl:405: function parse_host/3 undefined
src/cowboy_protocol.erl:275: Warning: function parse_hd_name_ws/8 is unused
src/cowboy_protocol.erl:282: Warning: function wait_hd_before_value/8 is unused
src/cowboy_protocol.erl:295: Warning: function parse_hd_before_value/8 is unused
src/cowboy_protocol.erl:314: Warning: function wait_hd_value/9 is unused
src/cowboy_protocol.erl:329: Warning: function wait_hd_value_nl/9 is unused
src/cowboy_protocol.erl:343: Warning: function parse_hd_value/9 is unused
src/cowboy_protocol.erl:361: Warning: function clean_value_ws_end/2 is unused
ERROR: compile failed while processing /mnt/hgfs/aaaa/erl/ERLDEPS/cowboy: rebar_abort

I reverted back to the most recent tag 5ff3fdd9 (2.0.0-pre.1) and it can compile fine.
Not sure if this is the proper place to notify you of this error.

Other information:
Erlang installed from: esl-erlang_17.4-2~debian~wheezy_amd64.deb
OS: Debian 7.8

**Comment by edgurgel** [comment]
This is probably your solution: https://github.com/ninenines/cowboy/pull/789

**Comment by ubill** [comment]
Thanks edgurgel for your helpful effort. The root cause had been identified in https://github.com/ninenines/cowboy/issues/786#issuecomment-74418907 and I got it working for me so far so good since then; I am verifying it further before closing that ticket.

Will close this now, as I am not facing anymore this compile error, only some warnings.
