### ISSUE TITLE
Cowboy 1.0.1 Large file download preventing new connections?

### ISSUE THREAD

**Issue by choptastic** [ninenines/cowboy#794]
Hey,

It's been brought to my attention that there might be an issue with cowboy and large files.  In my case, downloading a large file (using cowboy_static) seems to *sometimes* prevent new connection requests (I've seen it prevent simple requests).

Using the "static_world" example in cowboy, I added a large (~400mb file) to test.

I've made a video of the behavior and posted it up here, to demonstrate.

https://www.youtube.com/watch?v=pXr8yl1kayA

As far as things I've noticed related to this:

1) Preventing connection to the large file (file.bin in my example)
2) Preventing connection requests to the index.html file
3) While the download is going, calling `ls()` in the erlang Shell sometimes locks the shell until the download completes or is cancelled.
4) error_logger sometimes stops printing messages until the download completes (really bizarre).

Numbers 3) and 4), I've only noticed when a websocket connection was also open, so I'm uncertain if that's related, but the overall behavior seems erratic and inconsistent.

Any thoughts as to what I need to change to prevent this behavior?

Erlang R16B on Ubuntu.

Thanks for any suggestions!

**Comment by essen** [comment]
IIRC it's a bug in the VM in older Erlang versions and it can be avoided by using +A 0.

**Comment by choptastic** [comment]
Thanks a bunch Loic!

So very odd, I'll give it a spin today and see how it goes.

Cheers,

-Jesse

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by choptastic** [comment]
Thanks. Initial testing seems to confirm that +A 0 fixes it.

I'll go ahead and close this and re-open if it returns. But I think we're good here!
