### ISSUE TITLE
Check why tcpkali Websocket doesn't work

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#796]
tcpikali (https://github.com/machinezone/tcpkali) has issues with Cowboy when running the following command:

``` bash
$ tcpkali --first-message "N2O," --verbose 3 --ws localhost:8877/ws/static/app/open.htm
```

Apparently it sends the handshake and the first frame in the same packet, and Cowboy replies with something and then doesn't receive the Websocket frame.

It's not unexpected that it does not work as the RFC says:

```
   Once the client's opening handshake has been sent, the client MUST
   wait for a response from the server before sending any further data.
```

But I would like to investigate what Cowboy does exactly when this happens. Perhaps it can still be allowed regardless of what the RFC says.

**Comment by vlm** [comment]
(Fixed in tcpkali.)

**Comment by essen** [comment]
Thanks for the heads up. Still it looks like Cowboy discards some received data and that's not good so I'll have a look later on anyway.

**Comment by 5HT** [comment]
It works:

```
$ tcpkali -T1s --verbose 3 \
     --first-message "N2O," --ws 127.0.0.1:8000/ws/

Destination: [127.0.0.1]:8000
Data(161): ➧HTTP/1.1 101 Switching Protocols\r\n
  connection: Upgrade\r\n
  Access-Control-Allow-Origin: *\r\n
  upgrade: websocket\r\n
  sec-websocket-accept: HSmrc0sMlYUkAGmm5OPpG2HaGWk=\r\n
  \r\n⬅︎
Ramped up to 1 connections.
Data(414): ➧\201~\001\232{"eval":"{ var x = qi('send'); 
x && x.addEventListener('click',function (event){{ if 
(validateSources(['message'])) ws.send(enc(tuple(atom(
'pickle'),bin('send'),bin('g2gCaAVkAAJldmQABWluZGV4ZAA
EY2hhdGsABHNlbmRkAAVldmVudGgDYgAABZFiAAVgSmIABt6n'),
[tuple(atom('message'),querySource('message')),tuple(
tuple(utf8_toByteArray('send'), bin('detail')), event.
detail)])));else console.log('Validation Error'); }});
};"}
Total data sent:     166 bytes (166 bytes)
Total data received: 575 bytes (575 bytes)
Bandwidth per channel: 0.006 Mbps, 0.7 kBps
Aggregate bandwidth: 0.005↓, 0.001↑ Mbps
Test duration: 1.00634 s.
```

**Comment by vlm** [comment]
@essen yes, discarding data is something uncomfortable about that RFC recommendation. Though the recommendation is only concerned about the client behavior (e.g., tcpkali), but not the server. The server is not obliged to honor this rule (by discarding data which is received post-upgrade),

**Comment by essen** [comment]
Yes. It's not expected behavior so I will look into it. I was surprised it did not work before. Looks like the existing buffer is just ignored when starting a Websocket connection, which causes no problems if the RFC is followed (as it is empty) but causes weird problems if not. I'll fix it when I finish my current task.

**Comment by essen** [comment]
Done. Cowboy will process the extra data, if any, even if the protocol does not allow it. Push soon. Thanks!
