### ISSUE TITLE
Issue with uploading big files

### ISSUE THREAD

**Issue by aoeking** [ninenines/cowboy#798]
Hi,

I am trying to upload a big file with the cowboy server. But I am getting a bad match error when doing so. Still I haven't gone through the cowboy code to check whether its a actually issue with cowboy or my code. I am glad if someone can help me on this.

=ERROR REPORT==== 2-Mar-2015::02:01:50 ===
Error in process <0.276.0> on node 'chat@127.0.0.1' with exit value: {[{reason,{badmatch,{more,<<8063826 bytes>>,{http_req,{sslsocket,{gen_tcp,#Port<0.2235>,tls_connection},<0.275.0>},ranch_ssl,keepalive,<0.276.0>,<<4 bytes>>,'HTTP/1.1',{{127,0,0,1},64014},<<9 bytes>>,undefined,8443,<<19 bytes>>,[<<7 bytes>>,<<5 bytes>>],<<0 bytes>>,undefined,[],[{<<4 bytes>>,<<14 bytes>>},{<<10 bytes>>,<<10 bytes>>},{<<14 bytes>>,<<8 bytes>>},{<<6 bytes>>,<<3 bytes>>},{<<6 bytes>>,<<22 bytes>>},{<<16 bytes>>,<<14 bytes>>},{<<10 bytes>>,<<120 bytes>>},{<<12 bytes>>,<<68 bytes>>},{<<7 bytes>>,<<27 bytes>>},{<<15 bytes>>,<<13 bytes>>},{<<15 bytes>>,<<14 bytes>>},{<<6 bytes>>,<<43 bytes>>}],[{<<14 bytes>>,10664380},{<<17 bytes>>,[<<8 bytes>>]},{<<6 bytes>>,undefined},{<<12 bytes>>,{... 

Thanks,
Nuwan

**Comment by essen** [comment]
There should be another report from Ranch with a stacktrace, can you paste it here (truncated if needed; the stacktrace is at the end). Thanks!

**Comment by aoeking** [comment]
The system is working for small size file uploads. But only fails when the files are too big.

                                                                                                                                               {http_req,{sslsocket,{gen_tcp,#Port<0.2235>,tls_connection},<0.275.0>},ranch_ssl,keepalive,<0.276.0>,<<"POST">>,'HTTP/1.1',{{127,0,0,1},64014},<<"localhost">>,undefined,8443,<<"/rest/account/share">>,[<<"account">>,<<"share">>],<<>>,undefined,[],[{<<"host">>,<<"localhost:8443">>},{<<"connection">>,<<"keep-alive">>},{<<"content-length">>,<<"10664380">>},{<<"accept">>,<<"*/*">>},{<<"origin">>,<<"https://localhost:8443">>},{<<"x-requested-with">>,<<"XMLHttpRequest">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36">>},{<<"content-type">>,<<"multipart/form-data; boundary=----WebKitFormBoundaryrcaQiI5QBEBE9FqQ">>},{<<"referer">>,<<"https://localhost:8443/test">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"cookie">>,<<"SESSION_ID=05103fe7302ab311073701e03fe07c21">>}],[{<<"content-length">>,10664380},{<<"transfer-encoding">>,[<<"identity">>]},{<<"expect">>,undefined},{<<"content-type">>,{<<"multipart">>,<<"form-data">>,[{<<"boundary">>,<<"----WebKitFormBoundaryrcaQiI5QBEBE9FqQ">>}]}},{<<"connection">>,[<<"keep-alive">>]}],undefined,[],{stream,2600380,#Fun<cow_http_te.stream_identity.2>,{8064000,10664380},#Fun<cowboy_http.ce_identity.1>},<<>>,{<<"----WebKitFormBoundaryrcaQiI5QBEBE9FqQ">>,<<>>},false,waiting,[],<<>>,undefined}}}},
                                                                                                                       {mfa,{test_rest_handler,handle,2}},
                                                                                                                       {stacktrace,[{test_rest_handler,process,4,[{file,"src/test_rest_handler.erl"},{line,409}]},{cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,111}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,435}]}]},
                                                                                                                       {req,[{socket,{sslsocket,{gen_tcp,#Port<0.2235>,tls_connection},<0.275.0>}},{transport,ranch_ssl},{connection,keepalive},{pid,<0.276.0>},{method,<<"POST">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},64014}},{host,<<"localhost">>},{host_info,undefined},{port,8443},{path,<<"/rest/account/share">>},{path_info,[<<"account">>,<<"share">>]},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:8443">>},{<<"connection">>,<<"keep-alive">>},{<<"content-length">>,<<"10664380">>},{<<"accept">>,<<"*/*">>},{<<"origin">>,<<"https://localhost:8443">>},{<<"x-requested-with">>,<<"XMLHttpRequest">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36">>},{<<"content-type">>,<<"multipart/form-data; boundary=----WebKitFormBoundaryrcaQiI5QBEBE9FqQ">>},{<<"referer">>,<<"https://localhost:8443/test">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>},{<<"cookie">>,<<"SESSION_ID=05103fe7302ab311073701e03fe07c21">>}]},{p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},
                                                                                                                       {state,{state}}],
                                                                                                                      [{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,435}]}]}

**Comment by essen** [comment]
It fails here:

```
{test_rest_handler,process,4,[{file,"src/test_rest_handler.erl"},{line,409}]}
```

Are you sure you handle all the return cases from the body function call? In particular if it can't get the full file in one go it will return a 'more' tuple to allow you to stream the file, in which case you handle the data and call body again until you get an 'ok' tuple.

**Comment by aoeking** [comment]
I tried that but it failed, may be my implementation is not correct . Do you have a sample code that I can try?

**Comment by essen** [comment]
http://ninenines.eu/docs/en/cowboy/HEAD/guide/req_body/#streaming_the_body ?

**Comment by aoeking** [comment]
hi @essen ,

thanks for the tip, it did work.
