### ISSUE TITLE
deps/cowlib/src/cow_ws.erl:48: syntax error before: '{'

### ISSUE THREAD

**Issue by barcoyou** [ninenines/cowboy#800]
When I compile my application with cowboy (master branch) as deps, I got following errors:

/root/proj/website/deps/cowlib/src/cow_ws.erl:48: syntax error before: '{'
/root/proj/website/deps/cowlib/src/cow_ws.erl:133: syntax error before: '{'
/root/proj/website/deps/cowlib/src/cow_ws.erl:156: syntax error before: '{'
/root/proj/website/deps/cowlib/src/cow_ws.erl:246: syntax error before: '{'
/root/proj/website/deps/cowlib/src/cow_ws.erl:444: syntax error before: '{'
/root/proj/website/deps/cowlib/src/cow_ws.erl:17: function negotiate_permessage_deflate/3 undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:18: function negotiate_x_webkit_deflate_frame/3 undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:20: function parse_header/3 undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:21: function parse_payload/9 undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:23: function frame/2 undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:40: type map() undefined
/root/proj/website/deps/cowlib/src/cow_ws.erl:152: spec for undefined function cow_ws:parse_header/3
/root/proj/website/deps/cowlib/src/cow_ws.erl:241: spec for undefined function cow_ws:parse_payload/9
/root/proj/website/deps/cowlib/src/cow_ws.erl:421: spec for undefined function cow_ws:frame/2
/root/proj/website/deps/cowlib/src/cow_ws.erl:71: function parse_permessage_deflate_params/6 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:100: function parse_max_window_bits/1 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:111: function init_permessage_deflate/3 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:216: function parse_header/7 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:224: function opcode_to_frame_type/1 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:231: function frag_state/4 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:288: function split_payload/2 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:299: function validate_close_code/1 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:310: function unmask/3 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:319: function do_unmask/3 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:338: function inflate_frame/5 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:350: function validate_payload/7 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:377: function validate_utf8/2 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:460: function payload_length/1 is unused
/root/proj/website/deps/cowlib/src/cow_ws.erl:467: function deflate_frame/3 is unused
ERROR: compile failed while processing /root/proj/website/deps/cowlib: rebar_abort

**Comment by essen** [comment]
Cowboy master requires Erlang 17+.

**Comment by barcoyou** [comment]
I see.

**Comment by barcoyou** [comment]
after I update the erlang to 17, I got the following error:
deps/cowboy/src/cowboy_loop.erl:25: behaviour cowboy_sub_protocol undefined

**Comment by essen** [comment]
Should be compiled first if using erlang.mk. How do you compile?

**Comment by barcoyou** [comment]
I user rebar compile

**Comment by essen** [comment]
Then it's a warning, not an error. You can safely ignore it.

**Comment by barcoyou** [comment]
no, can not ignore

==> ranch (compile)
Compiled src/ranch_protocol.erl
Compiled src/ranch_transport.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_sup.erl
Compiled src/ranch.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_server.erl
Compiled src/ranch_app.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_acceptors_sup.erl
==> cowboy (compile)
/root/proj/website/deps/cowboy/src/cowboy_loop.erl:25: behaviour cowboy_sub_protocol undefined
ERROR: compile failed while processing /root/proj/website/deps/cowboy: rebar_abort
make: *** [compile] Error 1

**Comment by essen** [comment]
Have you tried updating your rebar version? Rebar should be able to detect the order in which files need to be compiled IIRC.

**Comment by barcoyou** [comment]
this is the latest rebar I cloned from github on master.

**Comment by essen** [comment]
Open a ticket there. This used to work in the past, then got broken, then fixed, and apparently now broken again?

**Comment by barcoyou** [comment]
You mean open a ticket for rebar?

**Comment by essen** [comment]
Yes.

**Comment by tuscland** [comment]
@barcoyou Are you using the Erlang distribution from ErlangSolutions?
