### ISSUE TITLE
Listen on socket instead of port?

### ISSUE THREAD

**Issue by shankardevy** [ninenines/cowboy#803]
I have an elixir app running on prod and it currently listens on port 8000 and I have an nginx running on port 80. The elixir app is available both on domainname.com and domainname.com:8000 if someone directly connects to the cowboy port. 

Since, I intend to run many webapps on the same server, I need nginx to use vhosts + others. Is it possible to use have cowboy listen to a socket so that it's not directly accessible over direct urls? If so, how would I go about configuring it?

Thanks

**Comment by essen** [comment]
If by socket you mean unix domain socket, then it's not possible directly in Erlang today, and the most informative place about this is this ticket: https://github.com/erlang/otp/pull/612 -- it also has some workarounds.

If you do manage to open one from Erlang, then you can pass it to Cowboy using the 'socket' transport option.

**Comment by acammack** [comment]
You can also have your application listen only to localhost by passing `{ip, {127,0,0,1}}` or `{ip, {0,0,0,0,0,0,0,1}}` as part of the transport options (third argument of `cowboy:start_http`).

**Comment by shankardevy** [comment]
thanks @essen, yes I mean unix domain socket.

thakns @acammack. This should at least solve my immediate need of not having my app available to public on cowboy port used by nginx.

**Comment by essen** [comment]
Closing, cheers!

**Comment by emilsoman** [comment]
@essen 

> If you do manage to open one from Erlang, then you can pass it to Cowboy using the 'socket' transport option.

Can you please explain how to do that or point me to any docs regarding this ?

**Comment by essen** [comment]
See the Ranch manual.

**Comment by vyachkonovalov** [comment]
From https://groups.google.com/forum/#!topic/phoenix-talk/dV94pYLvdx8
```elixir
config :hello_phoenix, HelloPhoenix.Endpoint,
  http: [port: 0, ip: {:local, "/tmp/phoenix"}]
```
works in Phoenix 1.2.x, but not in 1.3.0-rc

**Comment by casp-simberg** [comment]
What's the status on this with the latest Phoenix version?

**Comment by cjbottaro** [comment]
I read https://github.com/erlang/otp/pull/612 and couldn't really tell what the outcome was.

Is this possible yet?

**Comment by essen** [comment]
Yes they've added support for unix sockets a while back. I haven't tried it personally.

**Comment by bullno1** [comment]
@cjbottaro It works by simply passing `{local, Path}` as address. Haven't tried on cowboy per se but it works on Ranch which cowboy is based on.
