### ISSUE TITLE
Does websocket frame rate have a limit?

### ISSUE THREAD

**Issue by sitstone** [ninenines/cowboy#811]
I am trying to stream video frames through cowboy websocket, and find that the number of frames  browser received are as fewer as serveral frames per seconds. 

I send a frame as a message to websocket_info callback.  I send 20 fames per second(wall clock), but the browser receive <5 frames per second(wall clock). 

Is this a problem of  cowboy websocket configuration, or I should try another approach?

**Comment by essen** [comment]
Cowboy sends them immediately.

**Comment by essen** [comment]
Hope that helped, closing, thanks!
