### ISSUE TITLE
resource_exists fails on GET on rest handler

### ISSUE THREAD

**Issue by mkuznetsov** [ninenines/cowboy#813]
I take example from rest_pastebin and adapt it. I have 3 parameters. If POST work ok! But it should be GET, and I get fail with {true, Req, index} as result. If I instead of true as first element I return anything I get 404 and correct body.   

resource_exists(Req, _State) ->
  Provider=cowboy_req:binding(provider,Req),
  Search = cowboy_req:binding(search,Req),
  Solution = cowboy_req:binding(solution,Req),

  case {Provider,Search,Solution} of
    {undefined,undefined,undefined} ->
      {true, Req, index};
    {<<"aviasales">>,_,_} when is_atom(Search),is_atom(Solution)->
      {false, Req, index};
    {<<"test_provider">>,_,_} when is_binary(Search),is_binary(Solution)->
      {Status,Rsp}=case check_resource of
                     #{<<"fail">> := _} = Fail ->
                       {false,Fail};
                     Rsp0->
                       {true, Rsp0}
                   end,
      Rsp2=jsx:encode(Rsp),
      lager:debug("Link RSP on exist ~p", [Rsp2]),
      {Status, cowboy_req:set_resp_body(Rsp2, Req), index}; % I tried different values for last element, they don't effect
    {_,_,_} ->
      {false, Req, index}
  end.

content_types_provided(Req, State) ->
  {[
    {{<<"application">>, <<"json">>, []}, process}
  ], Req, State}.

content_types_accepted(Req, State) ->
  {[{{<<"application">>, <<"json">>, []}, process}],
    Req, State}.

allowed_methods(Req, State) ->
  {[<<"GET">>, <<"POST">>], Req, State}.

Ranch listener bf_gds had connection process started with cowboy_protocol:start_link/4 at <0.1503.0> exit with reason: {badarg,[{erlang,iolist_size,[true],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,752}]},{cowboy_rest,respond,3,[{file,"src/cowboy_rest.erl"},{line,973}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,849}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,462}]}]}

**Comment by essen** [comment]
The issue is in the 'process' function. Could you paste it?

**Comment by mkuznetsov** [comment]
Nothing criminal here, for testing i delete real calls and put dummy results. Still work ok with POST, and nothing with GET. I comment resource_exists (by default return true). Same error. 

process(Req, State) ->
  Provider=cowboy_req:binding(provider,Req),
  Search = cowboy_req:binding(search,Req),ok
  Solution = cowboy_req:binding(solution,Req),

  {Output,ReqOut}= case {Provider,Search,Solution} of
                     {undefined, undefined, undefined} ->
                       {ok, Json, Req1} = cowboy_req:body(Req),
                       Input=jsx:decode(Json, [return_maps]),
                       lager:debug("Input ~p", [Input]),
                       {<<"{\"good_result_cnt\":0}">>,Req1};

                     {<<"aviasales">>,_,_}->
                       
                       {<<"{\"good_result_cnt\":1,\"url\":[\"ok\"]}">>,Req};

                     _->
                       {<<"{\"fail\":\"not_implemented\",\"message\":\"no  implementation for this provider\"}">>,Req}
                   end,

  {true,cowboy_req:set_resp_body( Output, ReqOut), State}.

**Comment by essen** [comment]
OK that's your problem there.

You use the process function for both "accepted" and "provided" cases. For "accepted" that's fine, but "provided" is supposed to do something entirely different (provide the resource). The particular crash you get is because this function ultimately returns true, which is not a valid response body.

**Comment by mkuznetsov** [comment]
Thank you a lot. 
"accepted" handler for POST need return {true, cowboy_req:set_resp_body( Output, ReqOut), State}
"provided" handler for GET need return (Output, ReqOut, State)

ok, next "newbie" question: 
History: We have search results from third party company. On POST I get list of items. to get one item I use GET with item code. Provider count clicks and return "one time" url. List result can expire or item can be deleted, If I use item check on resource_exist(...) and return true, i still can get fail from provider and want return 404. 

Can I make change in "provided" function to make it return 404, if resource_exists return true?

Same problem with "accepted" in case of error in processing can I put http code other then 200 without throwing runtime exception?

**Comment by mkuznetsov** [comment]
I mean can I manipulate http code on provided and accepted functions without throwing exceptions?

**Comment by essen** [comment]
You can always return 'halt' and use reply directly, but make sure that there isn't a normal way to do it first. Check the guide it should be there.

**Comment by mkuznetsov** [comment]
In guide I found cowboy_req:reply(Status, Headers, Body, Req). it used on typical http handler, but on rest different story.

If I use it end of accepted function should be it something like this:
ReqOut= cowboy_req:reply(ErrorStatus, [], Body, Req),
{halt, ReqOut, State}.

Am I right?

**Comment by mkuznetsov** [comment]
if so how it should be with provided function? first element is resource body.

**Comment by essen** [comment]
You can give halt to most functions including this one.

**Comment by mkuznetsov** [comment]
Thanks, I will try it later today.
