### ISSUE TITLE
default behaviour if last_modified is undefined

### ISSUE THREAD

**Issue by kittee** [ninenines/cowboy#814]
Wouldn't it be more expected to call method instead of responding 304 not_modified when last_modified is undefined?

**Comment by essen** [comment]
Is your comment relating to If-Unmodified-Since? Looks like this one could be incorrect. If-Modified-Since looks fine.

**Comment by kittee** [comment]
Yes, it is situation, when you did not specified last_modified function in callback module and you get 304 on any If-Modified-Since request. So I wonder, if it's intended behavior, requiring  no_call explicitly set in callback module to ignore If-Modified-Since.

**Comment by essen** [comment]
Can you paste the headers of a request that fails?

**Comment by kittee** [comment]
> Host: tuna.local
> If-None-Match: "552bb786-7ced9"
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8,ru;q=0.6
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Cache-Control: max-age=0
> Cookie: blahblah
> Connection: keep-alive
> If-Modified-Since: Mon, 6 Apr 2015 12:33:10 GMT

there is If-None-Match, so it cowboy_rest checks if_none_match, it is false so then it checks if_modified_since_exists -> if_modified_since_now -> if_modified_since, last_modified is undefined so `LastModified > IfModifiedSince` is false, and it responds with not_modified.

**Comment by essen** [comment]
I think that at some point during development the `IfModifiedSince` value was an integer, in which case it would have worked. That's no longer the case though. We need additional clauses in `cowboy_rest` to handle `undefined`.

Thanks for the report. Feel free to submit a PR as I am fairly busy with another project at the moment.

**Comment by kittee** [comment]
Okay, I will submit a PR asap!

**Comment by christopheradams** [comment]
This reads like the very same issue that is addressed in PR #1030. If that's the case, this can be closed when that is merged.

**Comment by essen** [comment]
Should be fixed in https://github.com/ninenines/cowboy/commit/59c32506c076c5f99e8b404bfed69a1239372a07

If there's still a problem, please reopen.

Thanks!
