### ISSUE TITLE
A bit confuse to cowboy manual about cowboy_req:parse_header

### ISSUE THREAD

**Issue by keroro520** [ninenines/cowboy#815]
In manual [cowboy_req:parse_header](http://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_req/index.html#parse_header), the spec is

    parse_header(Name, Req) ->
    parse_header(Name, Req, Default) -> {ok, ParsedValue, Req2} | {undefined, Value, Req2} | {error, badarg}

but in [example rest_basic_auth](https://github.com/ninenines/cowboy/blob/master/examples/rest_basic_auth/src/toppage_handler.erl#L16) the result is 

    {<<"basic">>, ... }

Although the correct format I got is

     {basic, ...}

**Comment by essen** [comment]
The manual you link is 1.0 and the version you use is master.
