### ISSUE TITLE
Semantics: rename Opts to InitialState

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#817]
This should make the use of init/2 easier for everyone. Also doesn't have to be the actual state BUT if the user uses maps then it's a pretty good name.

**Comment by essen** [comment]
We should also make InitialState optional, defaulting to either `undefined` or `#{}`, probably the latter. Most handlers don't actually need an initial state.

**Comment by essen** [comment]
Believe that's done.

**Comment by leoliu** [comment]
Should `handler_opts` also be renamed to `handler_state`? Just curious.

**Comment by essen** [comment]
Probably. It's a little late for that though so let's deprecate it later and remove handler_opts in 3.0.
