### ISSUE TITLE
REST: Make it possible to set body's easily for any request type

### ISSUE THREAD

**Issue by ahf** [ninenines/cowboy#819]
It would be useful if it was easy, from within the REST handlers, to set the body of a response (according to the media_type as well), such that if a client asks for `application/json` a callback will be called for serving the client `application/json`.

**Comment by essen** [comment]
I am not sure what this ticket is about anymore... :-)

**Comment by essen** [comment]
Closing until I know more. Please reopen or comment when you can! Thanks.
