### ISSUE TITLE
cowboy_clock badarg looking up rfc1123 in ets table

### ISSUE THREAD

**Issue by pdtwonotes** [ninenines/cowboy#820]
Cowboy 1.0.1 running on an armv7h processor, gets this error when the first browser request comes in.  The cowboy_clock module is trying to fetch the rfc1123 value from the ets table.  Since the value is placed there during init, I am not sure how this could happen.

Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.180.0> exit with reason: {badarg,[{**ets,lookup_element,[cowboy_clock,rfc1123,2],[]**},{cowboy_clock,rfc1123,0,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_clock.erl"},{line,54}]},{cowboy_req,reply_no_compress,8,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,933}]},{cowboy_req,reply,4,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,886}]},{cowboy_req,maybe_reply,2,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,996}]},{cowboy_rest,upgrade,4,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_rest.erl"},{line,70}]},{cowboy_protocol,execute,4,[{file,"/home/pd/Develop/benzaiten/bz/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]}

**Comment by essen** [comment]
Is the Cowboy application started?

**Comment by pdtwonotes** [comment]
The top Supervisor has called cowboy:start_http, is that what you mean?  Or a more general application:start(cowboy)?  I will try adding 'cowboy' to the must-be-started-first list.

**Comment by essen** [comment]
Depending on how you do things either add cowboy to that list or use application:start yes.

**Comment by pdtwonotes** [comment]
Ok, explicitly starting cowlib and cowboy seems to have fixed that.  And there have been other changes I was not aware of.  I have modified my dependency to "1.0.x" instead of "master" so that things do not catch me unawares in the future.

**Comment by mokevnin** [comment]
@essen hi, i've got the same error. Cowboy version is 1.0.3.

```
=ERROR REPORT==== 7-Oct-2015::23:18:04 ===
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.11188.2> exit with reason: {badarg,[{ets,lookup_element,[cowboy_clo
ck,rfc1123,2],[]},{cowboy_clock,rfc1123,0,[{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_clock.erl"},{line,54}]},{cowboy_req,reply_no_co
mpress,8,[{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_req.erl"},{line,933}]},{cowboy_req,reply,4,[{file,"/usr/src/app/app/battle/_buil
d/default/lib/cowboy/src/cowboy_req.erl"},{line,886}]},{cowboy_req,maybe_reply,2,[{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_req.erl"
},{line,996}]},{cowboy_handler,handler_init,4,[{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,88}]},{cowboy_protocol,
execute,4,[{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]}

=ERROR REPORT==== 7-Oct-2015::23:18:04 ===
Error in process <0.11191.2> on node 'battle@127.0.0.1' with exit value:
{badarg,[{ets,lookup_element,[cowboy_clock,rfc1123,2],[]},
         {cowboy_clock,rfc1123,0,
                       [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_clock.erl"},
                        {line,54}]},
         {cowboy_req,reply_no_compress,8,
                     [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_req.erl"},
                      {line,933}]},
         {cowboy_req,reply,4,
                     [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_req.erl"},
                      {line,886}]},
         {cowboy_req,maybe_reply,2,
                     [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_req.erl"},
                      {line,996}]},
         {cowboy_handler,handler_init,4,
                         [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_handler.erl"},
                          {line,88}]},
         {cowboy_protocol,execute,4,
                          [{file,"/usr/src/app/app/battle/_build/default/lib/cowboy/src/cowboy_protocol.erl"},
                           {line,442}]}]}
```

**Comment by essen** [comment]
Same question as above? This is not a bug.

**Comment by mokevnin** [comment]
ops, i see the question, my issue is different. it happens in random time during working.

**Comment by essen** [comment]
Then open a new ticket and add more information, if this error happens it's because the cowboy_clock has crashed, so there should be an error when that happens and I'll need it to understand the problem.

**Comment by mokevnin** [comment]
ok, thanks
