### ISSUE TITLE
Merging Response Headers Shouldn't Be Case Sensitive

### ISSUE THREAD

**Issue by cpitman** [ninenines/cowboy#824]
`merge_headers` attempts to merge two sets of headers by only adding entries with new keys, but when it checks for a key the check is case sensitive. Since headers shouldn't be case-sensitive, this seems like a bug.

I'm playing around with proxying requests, so, this is what happened when I sent a request to a server that used upper case header keys:

```
connection: keep-alive
server: Cowboy
date: Fri, 15 May 2015 20:11:24 GMT
content-length: 240
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 240
Content-Type: application/json
Date: Fri, 15 May 2015 20:11:24 GMT
Server: nginx
```

Notice specifically `server`, `content-length`, and `data`.

An easy workaround is to ensure all headers are lower case to match the casing used by cowboy.

**Comment by essen** [comment]
Cowboy expects you to send lowercase headers by convention. It's one of the first thing mentioned in the guide.

**Comment by cpitman** [comment]
Is merging the only reason for the restriction? If yes, then wouldn't changing it to a case-insensitive merge remove the need to document an odd behavior?

Documenting a surprising way of doing things doesn't make it less surprising. Especially when other frameworks (I'm actually using Plug) are built on top of it, it becomes less likely that users will read the guide for every piece of the stack to discover things like this.

**Comment by essen** [comment]
I can't be blamed for the framework not doing what you want and/or not being documented properly.

It's not the only reason headers are lowercase. New HTTP protocols (SPDY, HTTP/2) require you to use lowercase header names. So we would need to convert them. In both case (merge and HTTP/2) the decision was taken to avoid wasting time and memory doing unnecessary things. Also note that the header names must be a binary.

The Gun HTTP client does the same, so there is no conversion needed when going from Gun to Cowboy and vice versa. Other HTTP clients may require you to do more work.

Cowboy is pretty explicit in what it does and that it is very lazy and try to do as little as possible. It's frameworks' job to make your life easier, if that's what you fancy.

**Comment by cpitman** [comment]
Ok, we're obviously on different pages. Sorry for wasting your time.

**Comment by essen** [comment]
No worries, feedback is always useful.
