### ISSUE TITLE
I get the undefined function when starting observer

### ISSUE THREAD

**Issue by nnacin** [ninenines/cowboy#826]
observer:start().
** exception error: undefined function wx_object:start/3
     in function  observer_wx:start/0 (observer_wx.erl, line 67)

I found this but I didn't know where to include the observer.. And I already have runtime tools included.

Thanks for your help!

**Comment by essen** [comment]
You need to include wx also.

**Comment by nnacin** [comment]
I am new to Erlang and Cowboy, so I am not sure where wx needs to be included. Here is my reltool.config file:
{sys, [
       {lib_dirs, ["../apps", "../deps"]},
       {erts, [{mod_cond, derived}, {app_file, strip}]},
       {app_file, strip},
       {rel, "chat", "1",
        [
         kernel,
         stdlib,
         sasl,
         runtime_tools,
         crypto,
         mimetypes,
         ranch,
         cowboy,
         chat
        ]},
       {rel, "start_clean", "",
        [
         kernel,
         stdlib
        ]},
       {boot_rel, "chat"},
       {profile, embedded},
       {incl_cond, exclude},
       {excl_archive_filters, [".*"]}, %% Do not archive built libs
       {excl_sys_filters, ["^bin/.*", "^erts.*/bin/(dialyzer|typer)",
                           "^erts.*/(doc|info|include|lib|man|src)"]},
       {excl_app_filters, ["\.gitignore"]},
       {app, sasl,   [{incl_cond, include}]},
       {app, stdlib, [{incl_cond, include}]},
       {app, kernel, [{incl_cond, include}]},
       {app, gs, [{incl_cond, include}]},
       {app, runtime_tools, [{incl_cond, include}]},
       {app, observer, [{incl_cond, include}, {mod_cond, all}]},
       {app, crypto, [{incl_cond, include}]},
       {app, mimetypes, [{incl_cond, include}]},
       {app, ranch, [{incl_cond, include}]},
       {app, cowboy, [{incl_cond, include}]},
       {app, chat, [{incl_cond, include}]}
      ]}.

{target_dir, "chat"}.

{overlay, [
           {mkdir, "log/sasl"},
           {copy, "files/erl", "\{\{erts_vsn\}\}/bin/erl"},
           {copy, "files/nodetool", "\{\{erts_vsn\}\}/bin/nodetool"},
           {copy, "files/chat", "bin/chat"},
           {copy, "files/chat.cmd", "bin/chat.cmd"},
           {copy, "files/start_erl.cmd", "bin/start_erl.cmd"},
           {copy, "files/install_upgrade.escript", "bin/install_upgrade.escript"},
           {copy, "files/sys.config", "releases/\{\{rel_vsn\}\}/sys.config"},
           {copy, "files/vm.args", "releases/\{\{rel_vsn\}\}/vm.args"}
          ]}.

**Comment by essen** [comment]
Honestly not sure either, I don't use reltool. Check out relx it's much much simpler.

**Comment by ferd** [comment]
Add `{app, wx, [{incl_cond, include}]}` to the list of apps (below `{app, chat, [{incl_cond, include}]}`). You might also be able to remove `{app, gs, [{incl_cond, include}]},` which was the older graphical toolkit.

**Comment by essen** [comment]
Closing then, thanks for the help!
