### ISSUE TITLE
official documentation lies about `cookie_opts` type

### ISSUE THREAD

**Issue by ztmr** [ninenines/cowboy#829]
Documentation ([cowboy_req.ezdoc:38](https://github.com/ninenines/cowboy/blob/master/doc/src/manual/cowboy_req.ezdoc#L38)):

``` Erlang
: cookie_opts() = [{max_age, non_neg_integer()}
    | {domain, binary()} | {path, binary()}
    | {secure, boolean()} | {http_only, boolean()}]
```

Code ([cow_cookie.erl:20](https://github.com/ninenines/cowlib/blob/5ddecbc121/src/cow_cookie.erl#L20)):

``` Erlang
-type cookie_option() :: {max_age, non_neg_integer()}
    | {domain, binary()} | {path, binary()}
    | {secure, boolean()} | {http_only, boolean()}.
-type cookie_opts() :: [cookie_option()].
-export_type([cookie_opts/0]).
```

And ([cow_cookie.erl:173](https://github.com/ninenines/cowlib/blob/5ddecbc121/src/cow_cookie.erl#L173)):

``` Erlang
    SecureBin = case lists:keyfind(secure, 1, Opts) of
        false -> <<>>;
        {_, true} -> <<"; Secure">>
    end,
    HttpOnlyBin = case lists:keyfind(http_only, 1, Opts) of
        false -> <<>>;
        {_, true} -> <<"; HttpOnly">>
    end,
```

So please change types and documentation so that there is `true` instead of `boolean()` or allow the cookie options setter to accept a real boolean, no matter whether it is `true` or `false`.

I would rather see the original boolean thing so that we can write something like this:

``` Erlang
[
    {flag1, true == (application:get_env (myapp, myflag1, false))},
    {flag2, true == (application:get_env (myapp, myflag2, true))},
    ...
]
```

...instead of chain of ugly conditional list unions.

PS: sorry, I am not sure if this issue belongs to `cowlib` or to `cowboy` project -- depends on what part (documentation or code) is to be fixed ;-)

**Comment by essen** [comment]
Sounds like it's a cow_cookie bug, good catch. Should match on {_, true} to use the stuff and anything else _ uses <<>>. Please send a PR.

**Comment by essen** [comment]
Fixed in cowlib, just need to update Cowboy now.

**Comment by essen** [comment]
Should be good for a long time.
