### ISSUE TITLE
Type opts() is undefined in module cowboy_http2, due to this an error is thrown when compile cowboy.

### ISSUE THREAD

**Issue by cabol** [ninenines/cowboy#831]
Error when compile cowboy (caused by latests commit):
>> src/cowboy_http2.erl:80: type opts() undefined

Due to type opts() is undefined:
https://github.com/ninenines/cowboy/blob/master/src/cowboy_http2.erl#L80

Thanks in advance for your help!

**Comment by essen** [comment]
Thanks for the info, will fix that quickly...

**Comment by essen** [comment]
Done, thanks!
