### ISSUE TITLE
QUIC support?

### ISSUE THREAD

**Issue by lavrin** [ninenines/cowboy#834]
Is there any plan to add [QUIC](https://www.chromium.org/quic) support to Cowboy? Would it make sense (probably would require sidestepping ranch as it's UDP based?)? Is it in the roadmap?

**Comment by essen** [comment]
There is no plans until it looks like there will be users or someone wants to sponsor the work.

At this point though, it doesn't look like it would be a very good idea to start implementing as they are working heavily on the spec and it's not even been submitted to IETF yet. Basically everything can change at any time.

We can start implementing when it looks closer to becoming something real and not just a Google-only protocol.

**Comment by lavrin** [comment]
Thanks for a prompt response! I'll close the issue for now.

**Comment by jhg-tgu** [comment]
Hi! Exists changes in the status of QUIC? The features looks interesting, but I don't know the status as standar or if Cowboy is waiting it will be more mature, etc. Or if finally QUIC only was abandoned.

**Comment by essen** [comment]
QUIC is slowly being defined and will eventually become a standard. We're still quite a way to go from getting there I believe. See https://quicwg.github.io/

I would be surprised if it was ready before 2019 personally.

**Comment by g-andrade** [comment]
In case it might be useful to someone, I've [worked on it](https://github.com/g-andrade/quack) for a while but eventually gave up due to the sheer instability and impact of changes on every release.

**Comment by peerst** [comment]
RFC 9000

**Comment by essen** [comment]
See https://github.com/emqx/quic for what is probably the most mature library for this. I have no plans to do QUIC but will probably use this library to finish up the HTTP/3 support.
