### ISSUE TITLE
Failed to do make or make docs

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#835]
hello,

I'm a beginner in cowboy web server, I just started to learn, and as a beginner, I started to follow the README. But unfortunately I realized a fault. The "make" and "make docs" reports some error when creatink symlink. Please check below logs, and let me know if I did something wrong.

Here is the log about what I did
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private> mkdir cowboy
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private> cd cowboy
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy> git clone https://github.com/ninenines/cowboy.git
	Cloning into 'cowboy'...
	remote: Counting objects: 7368, done.
	remote: Compressing objects: 100% (14/14), done.
	remote: Total 7368 (delta 3), reused 0 (delta 0), pack-reused 7354
	Receiving objects: 100% (7368/7368), 5.57 MiB | 1.33 MiB/s, done.
	Resolving deltas: 100% (4346/4346), done.
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy> ls
	cowboy
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy> cd cowboy/
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> ls
	all.sh        CHANGELOG.md     erlang.mk  Makefile      ROADMAP.md
	AUTHORS       CONTRIBUTING.md  examples   README.md     src
	build.config  doc              LICENSE    rebar.config  test
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> make
	 DEP    cowlib
	ln: failed to create symbolic link `./erlang.mk': Read-only file system
	make: *** [/mnt/ethrbh/private/cowboy/cowboy/deps/cowlib] Error 1
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> ls -la
	total 131
	drwxrwxrwx 1 root root  4096 Jun 16 15:09 .
	drwxrwxrwx 1 root root     0 Jun 16 15:08 ..
	-rwxrwxrwx 1 root root   354 Jun 16 15:08 all.sh
	-rwxrwxrwx 1 root root  1166 Jun 16 15:08 AUTHORS
	-rwxrwxrwx 1 root root   597 Jun 16 15:08 build.config
	-rwxrwxrwx 1 root root 30831 Jun 16 15:08 CHANGELOG.md
	-rwxrwxrwx 1 root root  5498 Jun 16 15:08 CONTRIBUTING.md
	drwxrwxrwx 1 root root     0 Jun 16 15:09 deps
	drwxrwxrwx 1 root root     0 Jun 16 15:08 doc
	-rwxrwxrwx 1 root root 58278 Jun 16 15:08 erlang.mk
	drwxrwxrwx 1 root root  4096 Jun 16 15:08 examples
	drwxrwxrwx 1 root root  4096 Jun 16 15:08 .git
	-rwxrwxrwx 1 root root   102 Jun 16 15:08 .gitignore
	-rwxrwxrwx 1 root root   757 Jun 16 15:08 LICENSE
	-rwxrwxrwx 1 root root  2628 Jun 16 15:08 Makefile
	-rwxrwxrwx 1 root root  1431 Jun 16 15:08 README.md
	-rwxrwxrwx 1 root root   158 Jun 16 15:08 rebar.config
	-rwxrwxrwx 1 root root  4123 Jun 16 15:08 ROADMAP.md
	drwxrwxrwx 1 root root  8192 Jun 16 15:08 src
	drwxrwxrwx 1 root root  4096 Jun 16 15:08 test
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> make docs
	 GEN    distclean-asciidoc
	 GEN    clean-docs
	 DEP    ezdoc
	ln: failed to create symbolic link `./erlang.mk': Read-only file system
	make: *** [/mnt/ethrbh/private/cowboy/cowboy/deps/ezdoc] Error 1
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> 

thanks for your help,
/Robi

**Comment by essen** [comment]
Not sure why it tells you that you are on a read only filesystem. What OS is that? Maybe someone who uses Virtualbox can pinch in?

**Comment by ethrbh** [comment]
hello,

I am using pure Ubuntu inside Virtualbox. What is interested is, that I can clone and make other project like Erlang/ALE and make it work. That project uses erlang.mk system too, since I added into that.

Anyway here is the OS version I use
-----------------------------------------------------------------
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> uname -a
Linux ethrbh-VirtualBox 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 15:31:16 UTC 2013 i686 i686 i386 GNU/Linux
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/cowboy/cowboy(master)> 


thanks for your help,
/Robi

**Comment by essen** [comment]
Any chance the repository you work in is a Virtualbox shared directory?

If not, I don't really know. I can try but no sooner than in a few days.

**Comment by ethrbh** [comment]
hello,
Yes, I am working in a shared dir, and it was not a problem till now. Anyway, I could clone and do the make in my home dir. Later on I try find why cowboy does not work in the shared dir.

I guess, you can close the ticket.

thanks for your help,
/Robi

**Comment by essen** [comment]
Right so there's a few very long standing bug in Virtualbox that makes file operations sometimes fail for no good reason. Nothing I can do about it, sorry. :-)

Yours specifically is probably this one: https://www.virtualbox.org/ticket/10085

Closing then!

**Comment by ethrbh** [comment]
hello,

No problem at all. I can leave with this. The good, that I can start toe learn cowboy.

thanks for your help again,
/Robi
