### ISSUE TITLE
Still failed to get it working

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#836]
Hello,

After the discussion in ISSUE (https://github.com/ninenines/cowboy/issues/835), I moved my working directory from a shared to a local dir of the Ubuntu running within Virtualbox. I could clone and do 'make all' the project, but I could not maker docs, and make hello_world example also failed for same reason.

I know, I am a beginner, thus I can imagine that I did something wrong, and I would like to get come help from you.

Please check the below log for detailed info.

OS type
-----------------------------------------------------------
ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> uname -a
Linux ethrbh-VirtualBox 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 15:31:16 UTC 2013 i686 i686 i386 GNU/Linux
ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> 

Clone cowboy
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/Downloads> git clone https://github.com/ninenines/cowboy.git
	Cloning into 'cowboy'...
	remote: Counting objects: 7368, done.
	remote: Compressing objects: 100% (14/14), done.
	remote: Total 7368 (delta 3), reused 0 (delta 0), pack-reused 7354
	Receiving objects: 100% (7368/7368), 5.57 MiB | 366 KiB/s, done.
	Resolving deltas: 100% (4346/4346), done.
	ethrbh@ethrbh-VirtualBox:~/Downloads> cd cowboy/
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> ls -la
	total 168
	drwxr-xr-x  7 ethrbh ethrbh  4096 Jun 16 21:11 .
	drwxr-xr-x  3 ethrbh ethrbh  4096 Jun 16 21:10 ..
	-rwxrwxr-x  1 ethrbh ethrbh   354 Jun 16 21:11 all.sh
	-rw-rw-r--  1 ethrbh ethrbh  1166 Jun 16 21:11 AUTHORS
	-rw-rw-r--  1 ethrbh ethrbh   597 Jun 16 21:11 build.config
	-rw-rw-r--  1 ethrbh ethrbh 30831 Jun 16 21:11 CHANGELOG.md
	-rw-rw-r--  1 ethrbh ethrbh  5498 Jun 16 21:11 CONTRIBUTING.md
	drwxrwxr-x  3 ethrbh ethrbh  4096 Jun 16 21:11 doc
	-rw-rw-r--  1 ethrbh ethrbh 58278 Jun 16 21:11 erlang.mk
	drwxrwxr-x 20 ethrbh ethrbh  4096 Jun 16 21:11 examples
	drwxrwxr-x  8 ethrbh ethrbh  4096 Jun 16 21:11 .git
	-rw-rw-r--  1 ethrbh ethrbh   102 Jun 16 21:11 .gitignore
	-rw-rw-r--  1 ethrbh ethrbh   757 Jun 16 21:11 LICENSE
	-rw-rw-r--  1 ethrbh ethrbh  2628 Jun 16 21:11 Makefile
	-rw-rw-r--  1 ethrbh ethrbh  1431 Jun 16 21:11 README.md
	-rw-rw-r--  1 ethrbh ethrbh   158 Jun 16 21:11 rebar.config
	-rw-rw-r--  1 ethrbh ethrbh  4123 Jun 16 21:11 ROADMAP.md
	drwxrwxr-x  2 ethrbh ethrbh  4096 Jun 16 21:11 src
	drwxrwxr-x  5 ethrbh ethrbh  4096 Jun 16 21:11 test
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> less README.md 
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> make help
	erlang.mk (version 1.2.0-564-g178e214-dirty) is distributed under the terms of the ISC License.
	Copyright (c) 2013-2014 Loïc Hoguin <essen@ninenines.eu>

	Usage: [V=1] make [-jNUM] [target]

	Core targets:
	  all           Run deps, app and rel targets in that order
	  deps          Fetch dependencies (if needed) and compile them
	  app           Compile the project
	  rel           Build a release for this project, if applicable
	  docs          Build the documentation for this project
	  install-docs  Install the man pages for this project
	  tests         Run the tests for this project
	  check         Compile and run all tests and analysis for this project
	  clean         Delete temporary and output files from most targets
	  distclean     Delete all temporary and output files
	  help          Display this help and exit

	The target clean only removes files that are commonly removed.
	Dependencies and releases are left untouched.

	Setting V=1 when calling make enables verbose mode.
	Parallel execution is supported through the -j make flag.

	Package-related targets:
	  pkg-list              List all known packages
	  pkg-search q=STRING   Search for STRING in the package index

	Bootstrap targets:
	  bootstrap          Generate a skeleton of an OTP application
	  bootstrap-lib      Generate a skeleton of an OTP library
	  bootstrap-rel      Generate the files needed to build a release
	  new t=TPL n=NAME   Generate a module NAME based on the template TPL
	  list-templates     List available templates

	Continuous Integration targets:
	  ci          Run 'make tests' on all configured Erlang versions.

	The CI_OTP variable must be defined with the Erlang versions
	that must be tested. For example: CI_OTP = OTP-17.3.4 OTP-17.5.3

	Common_test targets:
	  ct          Run all the common_test suites for this project

	All your common_test suites have their associated targets.
	A suite named http_SUITE can be ran using the ct-http target.

	Dialyzer targets:
	  plt         Build a PLT file for this project
	  dialyze     Analyze the project using Dialyzer

	Elvis targets:
	  elvis       Run Elvis using the local elvis.config or download the default otherwise

	Escript targets:
	  escript     Build an executable escript archive

	EUnit targets:
	  eunit       Run all the EUnit tests for this project

	Shell targets:
	  shell       Run an erlang shell with SHELL_OPTS or reasonable default

	Xref targets:
	  xref        Run Xrefr using REF_CONFIG as config file if defined

	Cover targets:
	  cover-report  Generate a HTML coverage report from previously collected
					cover data.
	  all.coverdata Merge {eunit,ct}.coverdata into one coverdata file.

	If COVER=1 is set, coverage data is generated by the targets eunit and ct. The
	target tests additionally generates a HTML coverage report from the combined
	coverdata files from each of these testing tools. HTML reports can be disabled
	by setting COVER_REPORT_DIR to empty.

Do make all
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> make all
	 DEP    cowlib
	--2015-06-16 21:14:09--  https://raw.githubusercontent.com/ninenines/erlang.mk/master/packages.v2.tsv
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 61658 (60K) [text/plain]
	Saving to: `/home/ethrbh/Downloads/cowboy/.erlang.mk.packages.v2'

	100%[======================================>] 61,658       279K/s   in 0.2s    

	2015-06-16 21:14:11 (279 KB/s) - `/home/ethrbh/Downloads/cowboy/.erlang.mk.packages.v2' saved [61658/61658]

	 DEP    ranch
	make[1]: Entering directory `/home/ethrbh/Downloads/cowboy/deps/cowlib'
	 ERLC   cow_http_hd.erl cow_http_te.erl cow_qs.erl cow_date.erl cow_ws.erl cow_multipart.erl cow_hpack.erl cow_spdy.erl cow_http2.erl cow_cookie.erl cow_mimetypes.erl cow_http.erl
	 APP    cowlib.app.src
	make[1]: Leaving directory `/home/ethrbh/Downloads/cowboy/deps/cowlib'
	make[1]: Entering directory `/home/ethrbh/Downloads/cowboy/deps/ranch'
	 ERLC   ranch_transport.erl ranch.erl ranch_acceptors_sup.erl ranch_listener_sup.erl ranch_ssl.erl ranch_tcp.erl ranch_acceptor.erl ranch_app.erl ranch_server.erl ranch_conns_sup.erl ranch_protocol.erl ranch_sup.erl
	 APP    ranch.app.src
	make[1]: Leaving directory `/home/ethrbh/Downloads/cowboy/deps/ranch'
	 ERLC   cowboy_bstr.erl cowboy_req.erl cowboy_sub_protocol.erl cowboy_rest.erl cowboy_tls.erl cowboy_constraints.erl cowboy_app.erl cowboy_clock.erl cowboy_router.erl cowboy_sup.erl cowboy_websocket.erl cowboy.erl cowboy_static.erl cowboy_protocol.erl cowboy_http2.erl cowboy_spdy.erl cowboy_stream.erl cowboy_handler.erl cowboy_middleware.erl cowboy_loop.erl
	 APP    cowboy.app.src
ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> ls
all.sh        CHANGELOG.md     doc        examples  README.md     src
AUTHORS       CONTRIBUTING.md  ebin       LICENSE   rebar.config  test
build.config  deps             erlang.mk  Makefile  ROADMAP.md
ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> ls deps/
cowlib  ranch

Try make docs
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> make docs
	 GEN    distclean-asciidoc
	 GEN    clean-docs
	 DEP    ezdoc
	make -C /home/ethrbh/Downloads/cowboy/deps/ezdoc
	make[1]: Entering directory `/home/ethrbh/Downloads/cowboy/deps/ezdoc'
	Makefile:6: *** target file `docs' has both : and :: entries.  Stop.
	make[1]: Leaving directory `/home/ethrbh/Downloads/cowboy/deps/ezdoc'
	make: *** [build-doc-deps] Error 2
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> V=1 make docs
	rm -rf doc/html/ doc/guide.pdf doc/man3/ doc/man7/
	rm -rf doc/man3 doc/man7 doc/markdown
	make -C /home/ethrbh/Downloads/cowboy/deps/ezdoc
	make[1]: Entering directory `/home/ethrbh/Downloads/cowboy/deps/ezdoc'
	Makefile:6: *** target file `docs' has both : and :: entries.  Stop.
	make[1]: Leaving directory `/home/ethrbh/Downloads/cowboy/deps/ezdoc'
	make: *** [build-doc-deps] Error 2
	
Try make hello_world example
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> 
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy(master)> cd examples/hello_world/
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> make
	 DEP    cowboy
	make[1]: Entering directory `/home/ethrbh/Downloads/cowboy/examples/hello_world/deps/cowboy'
	Makefile:22: erlang.mk: No such file or directory
	make[1]: *** No rule to make target `erlang.mk'.  Stop.
	make[1]: Leaving directory `/home/ethrbh/Downloads/cowboy/examples/hello_world/deps/cowboy'
	make: *** [deps] Error 2
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> less Makefile 
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> ls ../../
	all.sh        CHANGELOG.md     doc        examples  README.md     src
	AUTHORS       CONTRIBUTING.md  ebin       LICENSE   rebar.config  test
	build.config  deps             erlang.mk  Makefile  ROADMAP.md
	ethrbh@ethrbh-VirtualBox:~/Downloads/cowboy/examples/hello_world(master)> 

	
thanks for your help,
/Robi

**Comment by essen** [comment]
Well you seem to be trying master, it's in the middle of heavy changes and is not supposed to work (unless if you know how to fix the random small issues that pop up).

I suggest following http://ninenines.eu/docs/en/cowboy/1.0/guide/getting_started/ to get started. It will use the stable version.

**Comment by ethrbh** [comment]
hello Essen,

Thanks for your suggestion. I could cowboy make it work and hello_world example runs fine, once I checked out version 1.0.x.

Now I can continue to learn.

I think you can close this ticket.

thanks again,
/Robi

**Comment by essen** [comment]
Enjoy!
