### ISSUE TITLE
cowboy email list

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#838]
hello Essen,

Sorry to make a new issue, but I think this is the faster way to ask you, about mailing list of Cowboy. According to the http://lists.ninenines.eu/listinfo there is only one list available, but that is for the "having trouble with mailing list", but I am interesting about a mailing list, to where I can put my questions. Just because I have a question about my first Cowboy project, and I don't know what did I wrong, but I really would like to understand what went wrong on my site.

thanks a lot,
/Robi

**Comment by essen** [comment]
The Extend mailing list doesn't appear there for you?

**Comment by ethrbh** [comment]
hello Essen,

Ohhh no, I was blind. Of course I can see that.

Close this ticket please.

thanks for your help.
/Robi
