### ISSUE TITLE
apache benchmark (ab) using keepalive is not working

### ISSUE THREAD

**Issue by silviucpp** [ninenines/cowboy#839]
I'm using the last code from master.

The app is very simple (based on hello world rest example)

```erlang
-module(toppage_handler).

-export([init/2, start/0]).
-export([content_types_provided/2]).
-export([hello_to_html/2]).

init(Req, Opts) ->
    {cowboy_rest, Req, Opts}.

content_types_provided(Req, State) ->
    {[
        {<<"text/html">>, hello_to_html}
    ], Req, State}.

hello_to_html(Req, State) ->
    {<<"Hello world">>, Req, State}.

start()->

    ok = application:start(crypto),
    ok = application:start(ranch),
    ok = application:start(cowlib),
    ok = application:start(cowboy),

    Dispatch = cowboy_router:compile(
        [
            {'_', [{"/", toppage_handler, []}]}
        ]),

    {ok, _} = cowboy:start_http(http, 100, [{port, 8080}], [{env, [{dispatch, Dispatch}]}]).
```

I'm trying to benchmark using:

ab -n 100000 -c 1500 -k  http://172.17.4.107:8080/

If -k is present in the arguments nothing happened. Without this one is working fine. I tested on a other webservers the command and is working properly.

Any idea what I'm doing wrong?

Silviu

**Comment by essen** [comment]
No idea. :-)

You might want to configure max_keepalive to infinity, but it won't fix a "nothing happened".

**Comment by silviucpp** [comment]
The above example is working for somebody ?

**Comment by essen** [comment]
I will try when I get back.

**Comment by binarin** [comment]
Looks like cowboy doesn't add "Connection: Keep-Alive" to its response, but still holds connection open. Which is against HTTP/1.0 spec if I understand it correctly. For example, 'ab' in this case waits before cowboy closes connection after 5000ms of inactivity, before it considers request finished (even though it has received all bytes mentioned in content-length).

Which I think is exactly the reason for "nothing happened" of original poster - with every request taking 5s, ab prints progress very slowly.

**Comment by essen** [comment]
Nicely spotted, the code apparently doesn't send connection if it's HTTP/1.0. I guess that branching can be removed.

**Comment by essen** [comment]
Want to send a patch?

**Comment by essen** [comment]
Should be fixed in master. Will backport to 1.0 this afternoon. Thanks!
