### ISSUE TITLE
Missing "content_types_accepted" -> "415 unsupported media type" in flowchart

### ISSUE THREAD

**Issue by derek121** [ninenines/cowboy#840]
The REST flowchart [in the 1.0 docs](http://ninenines.eu/docs/en/cowboy/1.0/guide/rest_flowcharts/) includes the condition of _known_content_type_ moving to _415 unsupported media type_ for a value of _false_. That _known_content_type_ validation is missing [in the diagram for HEAD](http://ninenines.eu/docs/en/cowboy/HEAD/guide/rest_flowcharts/).

Perhaps related, `cowboy_rest:known_content_type/2` [from 1.0.x](https://github.com/ninenines/cowboy/blob/e5170737d229a5b7bb6159d24ac10062fe8d6789/src/cowboy_rest.erl#L170) has been removed [from master](https://github.com/ninenines/cowboy/blob/341f991d58fde702f68fa9d0076ad6dc2f942917/src/cowboy_rest.erl#L159). The check against the types returned from the `content_types_accepted/2` callback _does_ still get done in master, resulting in the 415 going back to the client as expected, but that case just doesn't appear in the flowchart.

Not a major issue, of course, just something I noticed while looking into why I was getting a 415.

**Comment by essen** [comment]
Yes actually known_content_types is separate from the content_types_accepted step. I wasn't sure why it was there, it's after all doing exactly the same thing, so I removed it.

If content_types_accepted returning 415 is missing from the documentation, then this needs to be addressed, thanks.

**Comment by essen** [comment]
I've done it in my local copy to be pushed soon. The corrected diagram will be part of the 2.7 documentation. Thanks!
