### ISSUE TITLE
 undefined macro 'INLINE_LOWERCASE/9'

### ISSUE THREAD

**Issue by weyenrooney** [ninenines/cowboy#842]
I try to compile cowboy with idea and rebar in windows 7 os,but I got Error:(272, -1) erlc: undefined macro 'INLINE_LOWERCASE/9'
Error:(433, -1) erlc: undefined macro 'INLINE_LOWERCASE/4',how can I find them in cowboy

**Comment by essen** [comment]
It's in an include file from cowlib.

**Comment by olgeni** [comment]
Cowlib 1.3.0 does not seem to have it at a first glance (?)

**Comment by essen** [comment]
It doesn't, Cowlib version is currently deeply tied to the Cowboy version referencing it, so don't pay too much attention to the version number yet. Use the right one for Cowboy and things will match.

Cowlib will be a proper project and will follow semver and have docs etc from version 2 onward.

**Comment by essen** [comment]
Closing, but please reopen if this is still an issue. I can help.

**Comment by l1f3l10n** [comment]
Same error when I try to use Gun with Cowboy 1.0.4.
Gun has a dependency on Cowlib 1.3.0. and with that Cowboy 1.0.4 doesn't compile. 

Help please.

**Comment by essen** [comment]
Should work with Gun commit b85c1f726ca49ac0e3abdcf717317cb95b06207d. No plans to make more recent Gun and Cowboy 1.0 compatible, compatibility will be available between Cowboy 2.0 and Gun 1.0 instead.

**Comment by l1f3l10n** [comment]
That was fast. Thanks.
