### ISSUE TITLE
 {function_clause,[{lists,zip

### ISSUE THREAD

**Issue by HelloKevinTian** [ninenines/cowboy#846]
I got the error whenever I send a http request to my cowboy_server ..

=ERROR REPORT==== 8-Jul-2015::11:06:02 ===
Ranch listener my_http_listener had connection process started with cowboy_protocol:start_link/4 at <0.161.0> exit with reason: {function_clause,[{lists,zip,[[transport,connection,pid,method,version,peer,host,host_info,port,path,path_info,qs,qs_vals,bindings,headers,p_headers,cookies,meta,body_state,buffer,multipart,resp_compress,resp_state,resp_headers,resp_body,onresponse],[]],[{file,"lists.erl"},{line,385}]},{lists,zip,2,[{file,"lists.erl"},{line,385}]},{cowboy_handler,handler_terminate,4,[{file,"src/cowboy_handler.erl"},{line,291}]},{cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,118}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}

**Comment by essen** [comment]
Can you show the handler code?

**Comment by HelloKevinTian** [comment]
// This is my test handler.I got the error when I sent a get request with http://127.0.0.1:8080/status
// Thx.

-module(status_handler).
-behaviour(cowboy_http_handler).

-export([init/3]).
-export([handle/2]).
-export([terminate/3]).

-record(state, {
}).

init(_, Req, _Opts) ->
	Req2 = cowboy_req:reply(200,
	 [{<<"content-type">>, <<"text/json">>}],
	 <<"status:ok">>,
	 Req),
	{ok, Req2, #state{}}.

handle(Req, State=#state{}) ->
	{ok, Req2} = cowboy_req:reply(200, Req),
	{ok, Req2, State}.

terminate(_Reason, _Req, _State) ->
	ok.

**Comment by essen** [comment]
OK this happens because in init you have Req2 = instead of {ok, Req2} =

**Comment by HelloKevinTian** [comment]
Perfect! I should have strictly followed the manual.

Thank you so much.

**Comment by essen** [comment]
Closing, enjoy!
