### ISSUE TITLE
Routing: optional bindings are filled in reverse order

### ISSUE THREAD

**Issue by pvalsecc** [ninenines/cowboy#847]
If I have a PathMatch like that:

``` erlang
"/foo/[:kind]/[:id]"
```

And an URL like that:

```
/foo/bar
```

The bindings are filled like that:

``` erlang
kind => undefined
id => <<"bar">>
```

It would be more natural to have:

``` erlang
kind => <<"bar">>
id => undefined
```

**Comment by essen** [comment]
Oops. :-)

**Comment by pvalsecc** [comment]
There is an easy work around, though. It works if the PathMatch is defined like that:
```erlang
"/foo/[:kind/[:id]]"
```

**Comment by essen** [comment]
Sounds like an easy patch, want to do it?

**Comment by pvalsecc** [comment]
That was my initial idea, but I failed to run the current tests (`make tests`). So I didn't feel like modifying code that I don't know without having tests to check that I don't break anything.

Can you point me to some info on how to run the tests without having tons of timeout errors? For example:
```
=== Reason: no match of right hand side value {error,timeout}
  in function  http_SUITE:'-echo_body/1-lc$^0/1-0-'/2 (test/http_SUITE.erl, line 309)
  in call from http_SUITE:echo_body/1 (test/http_SUITE.erl, line 305)
  in call from test_server:ts_tc/3 (test_server.erl, line 1408)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 984)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 926)
```

**Comment by essen** [comment]
Open a PR with the code (even incomplete) and CI will run. Some tests currently fail, I'll be able to confirm which are your doing.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by essen** [comment]
Yeah it's much harder to fix than I thought. I think I will document the behavior as being undefined and recommend using your workaround instead, if there are no other ways to distinguish between them (worth noting that in your example there's one route that's unreachable, which isn't good).

Closing, thanks!
