### ISSUE TITLE
cowboy_protocal:start_link crash

### ISSUE THREAD

**Issue by sugus-seu** [ninenines/cowboy#848]
cowboy_protocal:start_link crash with reason {system_limit,[{erlang,spawn_link...
I guess it reached process limit
When it hanppend, ranch_conns_sup crashed, and all connections linked to the ranch_conns_sup terminate.
I wonder should we catch crash of cowboy_protocal:start_link?

**Comment by essen** [comment]
One thing for sure, you hit an unusual issue. :-) I will get back to you when I get time to investigate, away at the moment.

**Comment by essen** [comment]
We'll need to update Ranch to fix the issue.

**Comment by essen** [comment]
The issue has been fixed in Ranch and will be part of the upcoming Ranch 1.2.

Cowboy master and Cowboy 1.1 will depend on Ranch 1.2 which has this fix.

Almost there. :-)

**Comment by essen** [comment]
This will be fixed in 1.1.0 released hopefully later today. Thanks!
