### ISSUE TITLE
cowboy_static no export function service_available

### ISSUE THREAD

**Issue by weyenrooney** [ninenines/cowboy#849]
when I debug cowboy I can't get correct result,I use Im() to debug it ,I found that cowboy_static no export callback function service_available.
![fy kdq fp2 3usnd3 yac](https://cloud.githubusercontent.com/assets/5090187/8675744/36401914-2a78-11e5-9b79-352a119fa2d9.jpg)
the code line  is 947 in cowboy_rest,like below:
call(Req, State=#state{handler=Handler, handler_state=HandlerState},
		Callback) ->
	case erlang:function_exported(Handler, Callback, 2) of
		true ->
			try
				Handler:Callback(Req, HandlerState)
			catch Class:Reason ->
				error_terminate(Req, State, Class, Reason, Callback)
			end;
		false ->
			no_call
	end.
How can I resolve this?

**Comment by zhongwencool** [comment]
Maybe you should check your cowboy version:（
a lot of change after V2*

**Comment by essen** [comment]
Not sure what your problem is? Can you paste the error? cowboy_static does not have service_available because it doesn't need it.

**Comment by weyenrooney** [comment]
ok,maybe it is because of cowboy version.
The problem is that I try to debug websocket,but in chrome it return 
WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 200
so I  trace into cowboy I found that no callback function service_available and cowboy terminate immediately

**Comment by essen** [comment]
If you get a 200 response, then it's most likely you trying to connect to a handler that does not do Websocket. In your last comment you mention ws://localhost:8080/ which corresponds to / and most likely is the page serving your site rather than the Websocket handler.

If I'm incorrect please reopen. :-)
