### ISSUE TITLE
Add help in docs for HTTPS

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#851]
hello,

I am using Cowboy-1.0.1 version as dependency of my application. I have a problem when I use HTTP and HTTPS at the same time. The problem is, application cannot be stopped, due to "{{case_clause,{error,closed}},[{ranch_acceptor,loop,3,[{file,"src/ranch_acceptor.erl"},{line,28}]}]}" problem. See more logs below.

I would like mention, the problem did not come when I use HTTP only.

I would like to ask you, did I something wrong, or is this an error?

My application can be seen in the github
-----------------------------------------------------------
	https://github.com/ethrbh/websocket_2

The configuration of Cowboy looks like this:
-----------------------------------------------------------
	Dispatch = cowboy_router:compile([
		{'_', [
			   %% This is for basic authentication
			   %%{"/", do_basic_auth, []},
			   
			   %% This is for ordinary websocket handling
			   {"/", cowboy_static, {priv_file, websocket_2, "index.html"}},			
			   {"/websocket_2", ws_handler_2, []},
			   {"/static/[...]", cowboy_static, {priv_dir, websocket_2, "static"}},
				
				%% Must set this line at the end, otherwise Clinet won't connect to the socket for same reason
				%% Here is the ISSUE on Cowboy to solve this: https://github.com/ninenines/cowboy/issues/841
				%% Here is the "Help to use frameset in index.html" emails in mail list.
				{"/[...]", cowboy_static, {priv_dir, websocket_2, ""}}
		]}
	]),

	%% This section is for HTTP
 	{ok, _} = cowboy:start_http(http, 100, [{port, 8080}],
 								[{env, [{dispatch, Dispatch}]}]),
	
	%% This section is for HTTPS
	PrivDir = code:priv_dir(websocket_2),
	{ok, _} = cowboy:start_https(https, 100, [
											  {port, 8443},
											  {cacertfile, PrivDir ++ "/ssl/cowboy-ca.crt"},
											  {certfile, PrivDir ++ "/ssl/server.crt"},
											  {keyfile, PrivDir ++ "/ssl/server.key"}
											 ], 
								 [{env, [{dispatch, Dispatch}]}]),	

Here is how I start/attach the application:
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)> _rel/websocket_2/bin/websocket_2 start
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)> _rel/websocket_2/bin/websocket_2 attach
	Attaching to /tmp/erl_pipes/websocket_2@127.0.0.1/erlang.pipe.1 (^D to exit)

	(websocket_2@127.0.0.1)1> [Quit]
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)> _rel/websocket_2/bin/websocket_2 attach
	Attaching to /tmp/erl_pipes/websocket_2@127.0.0.1/erlang.pipe.1 (^D to exit)

	(websocket_2@127.0.0.1)1> application:which_applications().
	[{websocket_2,"Cowboy websocket example.","1"},
	 {ssl,"Erlang/OTP SSL application","5.3.8"},
	 {cowboy,"Small, fast, modular HTTP server.","1.0.1"},
	 {cowlib,"Support library for manipulating Web protocols.",
			 "1.0.1"},
	 {public_key,"Public key infrastructure","0.22.1"},
	 {runtime_tools,"RUNTIME_TOOLS","1.8.15"},
	 {crypto,"CRYPTO","3.4.2"},
	 {ranch,"Socket acceptor pool for TCP protocols.","1.1.0"},
	 {asn1,"The Erlang ASN1 compiler version 3.0.3","3.0.3"},
	 {stdlib,"ERTS  CXC 138 10","2.3"},
	 {kernel,"ERTS  CXC 138 10","3.1"}]
	(websocket_2@127.0.0.1)2> 
	(websocket_2@127.0.0.1)2> [Quit]
 

Here is how I try stop the application
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)> _rel/websocket_2/bin/websocket_2 stop
	ok
	^C
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)>
	
Above stop did not work, it hangs, and below ERROR messages come in the log file
-----------------------------------------------------------
	ethrbh@ethrbh-VirtualBox:~/projects/github/websocket_2(master)> tail -f _rel/websocket_2/log/erlang.log.1 
	=====
	===== LOGGING STARTED Wed Jul 15 15:35:29 CEST 2015
	=====
	Exec: /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/erts-6.3/bin/erlexec -boot /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/releases/1/websocket_2 -boot_var ERTS_LIB_DIR /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/erts-6.3/../lib -env ERL_LIBS /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/releases/1/lib -config /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/releases/1/sys.config -args_file /home/ethrbh/projects/github/websocket_2/_rel/websocket_2/releases/1/vm.args -- console
	Root: /home/ethrbh/projects/github/websocket_2/_rel/websocket_2
	/home/ethrbh/projects/github/websocket_2/_rel/websocket_2
	Erlang/OTP 17 [erts-6.3] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]

	Eshell V6.3  (abort with ^G)
	(websocket_2@127.0.0.1)1> application:which_applications().
	[{websocket_2,"Cowboy websocket example.","1"},
	 {ssl,"Erlang/OTP SSL application","5.3.8"},
	 {cowboy,"Small, fast, modular HTTP server.","1.0.1"},
	 {cowlib,"Support library for manipulating Web protocols.",
			 "1.0.1"},
	 {public_key,"Public key infrastructure","0.22.1"},
	 {runtime_tools,"RUNTIME_TOOLS","1.8.15"},
	 {crypto,"CRYPTO","3.4.2"},
	 {ranch,"Socket acceptor pool for TCP protocols.","1.1.0"},
	 {asn1,"The Erlang ASN1 compiler version 3.0.3","3.0.3"},
	 {stdlib,"ERTS  CXC 138 10","2.3"},
	 {kernel,"ERTS  CXC 138 10","3.1"}]
	(websocket_2@127.0.0.1)2> 
	(websocket_2@127.0.0.1)2> 
	=ERROR REPORT==== 15-Jul-2015::15:36:17 ===
	Error in process <0.175.0> on node 'websocket_2@127.0.0.1' with exit value: {{case_clause,{error,closed}},[{ranch_acceptor,loop,3,[{file,"src/ranch_acceptor.erl"},{line,28}]}]}

	=ERROR REPORT==== 15-Jul-2015::15:36:17 ===
	Error in process <0.178.0> on node 'websocket_2@127.0.0.1' with exit value: {{case_clause,{error,closed}},[{ranch_acceptor,loop,3,[{file,"src/ranch_acceptor.erl"},{line,28}]}]}

	=ERROR REPORT==== 15-Jul-2015::15:36:17 ===
	Error in process <0.176.0> on node 'websocket_2@127.0.0.1' with exit value: {{case_clause,{error,closed}},[{ranch_acceptor,loop,3,[{file,"src/ranch_acceptor.erl"},{line,28}]}]}

	=ERROR REPORT==== 15-Jul-2015::15:36:17 ===
	Error in process <0.179.0> on node 'websocket_2@127.0.0.1' with exit value: {{case_clause,{error,closed}},[{ranch_acceptor,loop,3,[{file,"src/ranch_acceptor.erl"},{line,28}]}]}

thanks for your help,
/Robi

**Comment by essen** [comment]
Add ssl to the list of applications in Ranch's .app.src file.

**Comment by ethrbh** [comment]
hello,

Thanks, it works. 

I have checked the Cowboy's documentation (http://ninenines.eu/docs/en/cowboy/1.0/guide/), but I did not see anything what may "help" to use HTTPS. So I mean, would it be possible to add a new chapter for HTTPS and probably this "extra" steps can be mentioned as well. What do you think about it?
Or correct me, if I just missed something in the documentation.

Oh, btw, you can close the ticket.

thanks,
/Robi

**Comment by essen** [comment]
Let's leave it open, perhaps change the title to "Add help in docs for HTTPS", and I will not forget when I get to it.

**Comment by ethrbh** [comment]
hello,

Ok. I have changed the title.

thanks for your help.
/Robi

**Comment by essen** [comment]
Heh I actually have another ticket open for that, #804. Closing this one, thanks!
