### ISSUE TITLE
2.0.0-pre.2: cowboy/src/cowboy_http2.erl:80: type opts() undefined

### ISSUE THREAD

**Issue by henrythor** [ninenines/cowboy#852]
Get a build error:

===> Compiling /home/cw/erlfector/_build/default/lib/cowboy/src/cowboy_http2.erl failed
/home/cw/erlfector/_build/default/lib/cowboy/src/cowboy_http2.erl:80: type opts() undefined

**Comment by henrythor** [comment]
deleting the -spec fixes the build error (yes, I'm a rebel)

**Comment by essen** [comment]
I think I fixed that on the commit that immediately follows. Didn't bother tagging. :-)

**Comment by essen** [comment]
Closing, thanks!
