### ISSUE TITLE
HTTP/2.0 not supported

### ISSUE THREAD

**Issue by coolfeature** [ninenines/cowboy#853]
Any plans to add official support for HTTP /2.0?
http://www.ietf.org/blog/2015/02/http2-approved/

**Comment by imsys** [comment]
See https://github.com/ninenines/cowboy/commit/a6f75aa3dcf3de4638d3f454b17bece8ef213bb9

And: http://www.erlang-factory.com/euc2015/loic-hoguin

**Comment by imsys** [comment]
Cowboy 2.0 and HTTP/2.0 are all exiting news :)

**Comment by essen** [comment]
Yep it's being worked on. Probably won't be finalized until the end of the year, but I will put more preview releases over time.

**Comment by edgurgel** [comment]
What about a bountysource to speed up the development? Maybe even the new Salt Bountysource https://salt.bountysource.com/

**Comment by essen** [comment]
I do accept sponsorship, no need to use a third party for this. Sponsors priority currently is first Gun 1.0 and then HTTP/2. New sponsors welcome if HTTP/2 is important to them.

**Comment by coolfeature** [comment]
Great talk! You are an invaluable member of this community! Can you share some information as to how exactly Cowboy is going to handle the HTTP/2.0 traffic? It would be great if you gave a high level overview somewhere as to how exactly the app is going to work from the OTP perspective. Will there be a process running for each connection, how these will be supervised, how will the process registering be handled etc. Information like that could help people who plan to use Cowboy in larger, possibly distributed deployments...

**Comment by essen** [comment]
One process per connection for handling the connection. No change compared to current Cowboy there. However the process doing the connection is also, optionally, a supervisor, in which case it can create a new process for each incoming request and supervise those directly.

For flow control Cowboy will have an "auto" mode or let you handle the flow control yourself if needed.

Nothing changing much after that, Cowboy doesn't register processes, you do.

**Comment by coolfeature** [comment]
Are you planning of adding a mechanism that would offload the main supervisor under massive loads e.g. enlarging the OTP tree and supervising the supervisors?

**Comment by essen** [comment]
That's planned for Ranch 2, there's a ticket in its repo somewhere. Basically making acceptors supervise directly.

**Comment by oubiwann** [comment]
Just wanted to say that this HTTP/2 work is exciting :-) This has caused me to bump up the priority for getting Cowboy support into lmug (the Clojure Ring-like HTTP abstraction framework for LFE).

**Comment by essen** [comment]
Good to hear. While you're there, know that I plan to derive the Cowboy documentation per Erlang VM language (semi-automatically hopefully, should be easy enough for the guide, harder for manual), so I will probably ping you or Robert when I get to it.

**Comment by oubiwann** [comment]
That sounds _fantastic_. Looking forward to helping in whatever way we can.

**Comment by essen** [comment]
Ticket for that is #856.

**Comment by coolfeature** [comment]
Can you give any idea how soon can we expect a http2 test suite? Are you doing the implementation on your own? Would you say it is a matter of weeks, months?

**Comment by oubiwann** [comment]
I think he said towards the end of the year.

**Comment by essen** [comment]
Yes, end of year is the general schedule at the moment. Could be sooner if a sponsor is interested, or if someone is interested to sponsor it. Myself I'm more interested in getting the architecture changes out of the way rather than have the HTTP/2 implementation completed, as they have an impact on a lot more people. Also the end of year target is not for an implementation that has a full test suite as I am more interested in having a full HTTP/1.1 test suite before having one for HTTP/2. Again, if a sponsor is interested, this can change.

**Comment by hwinkel** [comment]
How is going with 2.0 support?

**Comment by schurig** [comment]
Any update on this?

**Comment by essen** [comment]
While incomplete, HTTP/2 is in current master and various clients can connect successfully. Examples and feature tests all run against HTTP/2 as well. Feedback is more than welcome to fix remaining issues. I am close to finishing up 2.0.0-pre.4 and making a larger call for feedback.

**Comment by unbalancedparentheses** [comment]
@essen out of curiosity, if you have some time could you tell us what is missing? I might use master and http/2 for a new project

**Comment by essen** [comment]
Documentation is a big one. A few more breaking changes in cowboy_req another, though I'm getting close to finish that. A few features have been temporarily removed like automatic compression of responses and have not been added back yet. Otherwise, things like HTTP/2 flow control or settings are not implemented, but that shouldn't be a problem for starting a project.

**Comment by nhooyr** [comment]
Any updates?

**Comment by essen** [comment]
This ticket is not productive so I'll be closing it. Please open tickets for specific issues you are having with the HTTP/2 implementation. Patches welcome.

**Comment by nathany** [comment]
@essen Thanks. I was watching this issue to know when HTTP/2 is ready to go.

**Comment by essen** [comment]
Don't know about ready to go, but definitely ready to try and provide feedback.

**Comment by CrowdHailer** [comment]
Is there a branch which has any (even minimal) documentation for what the api will look like. I'm particularly interested in the pre-sending responses before they have been requested

**Comment by essen** [comment]
It's the same API as HTTP/1.1, except for the addition of cowboy_req:push: https://ninenines.eu/docs/en/cowboy/2.0/manual/
