### ISSUE TITLE
Error using examples

### ISSUE THREAD

**Issue by mrakob** [ninenines/cowboy#860]
-module(server_websocket).
-export([start/2, start/0, stop/0, stop/1]).

%% API.
start(_Type, _Args) ->
	Dispatch = cowboy_router:compile([
		{'_', [
			{"/", cowboy_static, {priv_file, websocket, "index.html"}},
			{"/websocket", ws_handler, []},
			{"/static/[...]", cowboy_static, {priv_dir, websocket, "static"}}
		]}
	]),

	{ok, _} = cowboy:start_http(http, 100, [{port, 8080}], [{env, [{dispatch, Dispatch}]}]),

	websocket_sup:start_link().

server_websocket:start().
** exception exit: {noproc,
                       {gen_server,call,
                           [ranch_sup,
                            {start_child,
                                {{ranch_listener_sup,http},
                                 {ranch_listener_sup,start_link,
                                     [http,100,ranch_tcp,
                                      [{port,8080}],
                                      cowboy_protocol,
                                      [{env,[{dispatch,[{'_',[],...}]}]}]]},
                                 permanent,infinity,supervisor,
                                 [ranch_listener_sup]}},
                            infinity]}}
     in function  gen_server:call/3 (gen_server.erl, line 212)
     in call from ranch:start_listener/6 (src/ranch.erl, line 47)
     in call from server_websocket:start/2 (src/server_websocket.erl, line 33)

**Comment by essen** [comment]
Not sure what you're doing exactly.

**Comment by mrakob** [comment]
where problem?

**Comment by essen** [comment]
How do you start this?

**Comment by mrakob** [comment]
-module(server_websocket).
-export([start/2, start/0, stop/0, stop/1]).


start() ->
	start("","").


%% API.
start(_Type, _Args) ->
	Dispatch = cowboy_router:compile([
		{'_', [
			{"/", cowboy_static, {priv_file, websocket, "index.html"}},
			{"/websocket", ws_handler, []},
			{"/static/[...]", cowboy_static, {priv_dir, websocket, "static"}}
		]}
	]),


	websocket_sup:start_link().

stop(_State) ->
	ok.

stop() ->
	stop(normal).

	
	
server_websocket:start().

**Comment by essen** [comment]
That's not going to work like this. This is an OTP application, you either let the release start it, or call either application:start/1 or application:ensure_all_started/1. If you haven't seen OTP applications yet, you might want to leave Cowboy aside for a moment and come back to it later on.

**Comment by essen** [comment]
Hope that helped. Closing, thanks!
