### ISSUE TITLE
Issue with erlang 17B compile: warnings being treated as errors

### ISSUE THREAD

**Issue by aoeking** [ninenines/cowboy#864]
Hi All,

I am getting "compile: warnings being treated as errors" message and stop compilation. This worked till today I clear all the deps and start with a new copy. Appreciate if anyone can give me a help.

++ -flat_namespace -undefined suppress -L /usr/local/lib/erlang/lib/erl_interface-3.7.20/lib -lerl_interface -lei   -shared
 ERLC   jiffy.erl jiffy_utf8.erl
 APP    jiffy.app.src
 ERLC   binstr.erl gen_smtp_application.erl gen_smtp_client.erl gen_smtp_server.erl gen_smtp_server_session.erl mimemail.erl smtp_server_example.erl smtp_util.erl socket.erl
src/smtp_util.erl:65: Warning: crypto:md5_mac/2 is deprecated and will be removed in in a future release; use crypto:hmac/3
 XYRL   smtp_rfc822_parse.yrl
 XYRL   smtp_rfc822_parse.yrl
 APP    gen_smtp.app.src
 ERLC   da_app.erl da_common.erl da_database.erl da_datamanage_fsm.erl da_datamanage_fsm_sup.erl da_manager_svr.erl da_notification_svr.erl da_payment.erl da_presence_svr.erl da_referral_svr.erl da_rest_handler.erl da_sup.erl da_util.erl da_websocket_handler.erl test.erl
compile: warnings being treated as errors
deps/emysql/include/emysql.hrl:37: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
deps/emysql/include/emysql.hrl:38: type gb_tree/0 is deprecated and will be removed in OTP 18.0; use use gb_trees:tree/0 or preferably gb_trees:tree/2
deps/emysql/include/emysql.hrl:39: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
make[1]: *** [ebin/da.app] Error 1
make: *** [all] Error 2

Regards,
Nuwan

**Comment by essen** [comment]
Not a Cowboy issue?

Anyway try running: make erlang-mk; make distclean; make 

If first target fails, update erlang.mk manually.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by aoeking** [comment]
Hi Loïc,

I tried them all and got the same error. Yes sure this may have nothing to do with cowboy but, is there any chance its because of the new update in erlang.mk

Thanks,
Nuwan

**Comment by aoeking** [comment]
I added "ERLC_OPTS = -W0" parameter and added some dependencies to the Makefile and problem got solved. Thanks for the help

**Comment by essen** [comment]
Cool, sorry I couldn't help more, didn't have Internet for almost a week. :-)

Anyway about the "Cowboy issue" comment, it's just that we do have tickets in the erlang.mk repository also. No worries anyway, same people.
