### ISSUE TITLE
Documentation: the type websocket:frame()

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#866]
I have failed to google the definition of the type of a websocket's frame.
And it appears absent on The Guide.

While The Guide (http://ninenines.eu/docs/en/cowboy/HEAD/guide/ws_handlers/) gives very clear intuitive example of frames of several kinds, it says nothing about the "close frame".

What is a "close frame" in erlang's terms?
Is it an atom 'close' or a tuple with the atom 'close' or something else?

**Comment by essen** [comment]
Check here: http://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_websocket/#types

The documentation for HEAD is not complete yet as this part was moved to Cowlib which has no published documentation yet.

**Comment by essen** [comment]
Done in Cowboy for now.
