### ISSUE TITLE
SPDY support in master

### ISSUE THREAD

**Issue by coolfeature** [ninenines/cowboy#867]
I am trying to run a SPDY server using the master branch.
I am using cowboy:start_spdy/4 with Dispatch in env, the function returns {ok,Pid}.
When I do a GET from Chrome 44 the request hangs for a while ending with ERR_EMPTY_RESPONSE.

After some debugging I notice the  ssl:ssl_accept(CSocket, Timeout) in ranch_ssl returns  {error, timeout}. After debugging a bit more I see there is a handshake problem in ssl_connection module of the ssl application in handshake/2 function. 

I am running Erlang 18. Any ideas? Could this be my certificates?

I have run a quick test to see if lucid (https://github.com/tatsuhiro-t/lucid) has the same problem. The server seems to be returning responses in TCP but the moment I turn SSL on it is timing out just like Cowboy does.

**Comment by essen** [comment]
Not sure what the problem is but nothing to do with Cowboy at least. Try on erlang-questions you will have more luck with SSL related issues there. :-)
