### ISSUE TITLE
cowboy multi frame http request handling

### ISSUE THREAD

**Issue by aoeking** [ninenines/cowboy#868]
Hi All,

Recently we made REST calls using android application. When the connection is on LTE the system worked fine and when the connection is slow it appeared that cowboy did not receive the body of the POST  request. Investigations shows us that when the connection is slow android it self sends the http packets by multiple frames.

When it comes to the cowboy it did not process the body part even thought the data received to the ranch_tcp module. But after putting few logs in to "recv(Socket, Length, Timeout)" function in ranch_tcp we got the data but in separate function calls. Please refer the attachment for tcpdump image.

ranch_tcp recv :- {ok,<<"POST /rest/subscribers HTTP/1.1\r\nContent-Type: application/json\r\nContent-Length: 336\r\nHost: xxx.xx.xx.xxx:80\r\nConnection: Keep-Alive\r\n\r\n">>}

ranch_tcp recv :- {ok,<<"{\"email\":\"xxxxxxxxxxxxxxxxx@xxxxxxxxxxxxx.com\",\"password\":\"google pwd\",\"imsi\":\"xxxxxxxxxxxxxxx\",\"imei\":\"xxxxxxxxxxxxxxx\",\"oauth_type\":\"google\",\"nickname\":\"rsfggvg\",\"image_url\":\"aHR0cHM6Ly9saDUuZ29vZ2xldXNlcmNvbnRlbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy\\/c3o9NTA=\",\"mobile\":\"xx@xxxxxxxxx\"}">>}

![test](https://cloud.githubusercontent.com/assets/8343461/9053580/f15059a4-3a76-11e5-8129-f86556bc3b49.png)

Any idea how to solve this.

Thanks & Best Regards,
Nuwan

**Comment by essen** [comment]
I did not fully understand this. There should be no issue with data arriving in separate packets, Cowboy does the reassembly itself. Can you show what the code you've written to handle the body looks like, and also give me what Cowboy version you're using?

**Comment by aoeking** [comment]
I used the following code to catch the body and i am using the master branch for my developments.

{_, Body, _} = cowboy_req:body(Req),

**Comment by essen** [comment]
You have to keep track of the third element of the returned tuples for one, and you may need to call body more than once if it doesn't return 'ok' in the first element of the returned tuple.

**Comment by essen** [comment]
Hope that helped. Closing, thanks!
