### ISSUE TITLE
cowboy websocket wrong behavior on stop in init.

### ISSUE THREAD

**Issue by comtihon** [ninenines/cowboy#871]
In my websocket handler's `Module:init/2` I need to stop handler in some clause.
I use `{stop, Req, undefined};` as in the [documentation](http://ninenines.eu/docs/en/cowboy/HEAD/guide/ws_handlers/).
But instead stopping handler - I got an error `{undef,[{stop,upgrade..`. So, as I can see - instead stopping the process cowboy tries to call `stop:upgrade`, threating stop as a callback Module.

**Comment by essen** [comment]
Yep it looks like the documentation is outdated on this part. The correct behavior is to return ok, I believe, though that might change in the future. Note that you need to send yourself a reply if you want to send something other than 200.

**Comment by comtihon** [comment]
fix in https://github.com/ninenines/cowboy/pull/912
