### ISSUE TITLE
Problem serving Twitter Bootstrap 3 font files

### ISSUE THREAD

**Issue by jhw** [ninenines/cowboy#872]
Hi,

I'm having some trouble getting Cowboy to render Twitter Bootstrap font files.

Instructions for setup are here:

http://stackoverflow.com/questions/19608873/how-to-include-glyphicons-in-bootstrap-3

and recommend you use the following dir structure:

/css      <-- Bootstrap.css here
/fonts    <-- Bootstrap fonts here

I have it slightly differently for legacy reasons: 

/css/lib  	   <-- Bootstrap.css here	    
/css/fonts    	   <-- Bootstrap fonts here

but the way Bootstrap loads font files via relative CSS paths means this should still work (I think):

@font-face {
    font-family: 'Glyphicons Halflings';
    src: url('../fonts/glyphicons-halflings-regular.eot');
    src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg');
}

I have verified all the Bootstrap files (css, fonts, js) exist at their correct locations.

My Cowboy handling code is as follows:

%% http://ninenines.eu/docs/en/cowboy/1.0/guide/static_handlers/

{"/css/[...]", cowboy_static, {priv_dir, ?APP_NAME, "/css"}}

What happens is that core Bootstrap loads fine, *but the fonts and glyphs don't*.

This directory setup works fine with my usual Python webserver. Am I messing up re serving the font files, or is it possible that Cowboy's static serving code is doing something odd here ?

Many thanks.

**Comment by essen** [comment]
But do they load if you access them directly?

**Comment by jhw** [comment]
Yeah actually I can. Good point. Must be something else. Sorry for trouble.
