### ISSUE TITLE
Wrong state when sending yourself message in latest

### ISSUE THREAD

**Issue by henrythor** [ninenines/cowboy#873]
I have a websocket handler that uses erlang:send_after() to send itself a message to timeout if it hasn't received an authentication message from the browser in 30 seconds. Then it ignores messages if the authenticated boolean in my state isn't set.

In 2.0.0-pre.2 this works as expected.

In master the message handler for the timeout seems to get an old State variable somehow. Authentication is successful, messages are getting passed, but when the timeout fires it says we're not authenticated.

Anyone know why this would be happening in the past week?

**Comment by essen** [comment]
Past *week* nothing changed there. Even in the past couple months. Can you try a git bisect?

**Comment by henrythor** [comment]
Very sorry, I removed my build tree and started over from 2.0.0-pre.2. I'll have a look if I can make some replication code against the latest master. If unsuccessful I can let you know and it'll go into the X-Files.

**Comment by henrythor** [comment]
Can't reproduce behaviour

**Comment by essen** [comment]
Cheers.
