### ISSUE TITLE
Master branch compilation failed, illegal use of variable 'Atom' in map

### ISSUE THREAD

**Issue by barcoyou** [ninenines/cowboy#874]
I pull the source from 

deps/cowboy/src/cowboy_req.erl failed:
deps/cowboy/src/cowboy_req.erl:1206: illegal use of variable 'Atom' in map
deps/cowboy/src/cowboy_req.erl:1209: illegal use of variable 'Atom' in map
deps/cowboy/src/cowboy_req.erl:1212: illegal use of variable 'Atom' in map
deps/cowboy/src/cowboy_req.erl:1233: illegal use of variable 'Key' in map
/deps/cowboy/src/cowboy_req.erl:1244: illegal use of variable 'Key' in map

**Comment by essen** [comment]
18+
