### ISSUE TITLE
websocket terminated at init callback, any change for the API?

### ISSUE THREAD

**Issue by barcoyou** [ninenines/cowboy#875]
terminated with reason: {cowboy_handler,[{class,error},{reason,undef},{mfa,{websocket_handler,init,2}},

My code is:

init(Req, _Opt) ->
        {Client,_} = cowboy_req:peer(Req),
    State = #state{client = Client, state = started},
    lager:info("Connection from: ~p", [Client]),
    {cowboy_websocket, Req, State, hibernate}.

**Comment by essen** [comment]
Did you compile with the lager parse transform enabled?

**Comment by barcoyou** [comment]
No

**Comment by barcoyou** [comment]
if
