### ISSUE TITLE
issue on gpg signature download attemps with static dispatch rule

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/cowboy#876]
Hello Loïc,
while using static files dispatch rule, I got a strange error while trying to access a  gpg signature of a file. the dispatch rule work on another file in same directory (i can download it).

Error :
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.210.0> exit with reason: {function_clause,[{cowboy_http,quoted_string,[<<"kIOVU4473">>,#Fun<cowboy_http.19.105814785>],[{file,"src/cowboy_http.erl"},{line,670}]},{cowboy_http,nonempty_list,2,[{file,"src/cowboy_http.erl"},{line,49}]},{cowboy_req,parse_header,4,[{file,"src/cowboy_req.erl"},{line,413}]},{cowboy_rest,if_none_match_exists,2,[{file,"src/cowboy_rest.erl"},{line,576}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]} 

the offenfing  gpg signature file : 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAABAgAGBQJVzkibAAoJEG5LoGhnsrpcoVgH/01UU/8FmzdyaYpJ0CMlQeYV
VhEIyhLefGEVdQ0dqSag1lJBtxhk9E9KaCNak2QYpfDMtRi8eROwESdqsEv4O6m/
GqsGBPJjlQYIglq0mpLw+qUrc+Vkrg0TOWj6z1jEto8/YRR5P8/DBM97vwk+qR3S
laTqM8WdCKQKzhbj1IBIiIql6RYSuT8AW6u4pZibRNZ57vUUZdyG/+TVMMvc+LXS
nj2j8Dkm1V2QVoNGc6TgLxKAevWY7WY4zrVpM28SuEX8E9ERHea63uZR0+x7KEwc
XV3zfzrhYrg3XWdDx+gYIFf5me4k1N3pf+FNzSRfLcLgkxnDLuvdXKJL/ozVtbk=
=X1oR
-----END PGP SIGNATURE-----

Using cowboy  1.0.1  and ranch 1.0.0 from dependencies under simple_bridge project.

**Comment by essen** [comment]
Would be good to know the request headers.

**Comment by crownedgrouse** [comment]
Hum, strange . 
the file debian/dists/unstable/Release.gpg that fails few minutes ago, works now,
but I get error on another file : dists/unstable/main/binary-i386/Packages
while dists/unstable/main/binary-i386/Packages.gz works ...

How can I get the request header ?

**Comment by crownedgrouse** [comment]
note some files have extension , others not. but the issue was first on a .gpg extension, now on a file without extension.  I'm a newbie on cowboy, don't blame if the issue is between the chair and the keyboard...

**Comment by crownedgrouse** [comment]
by typing a wrong trailing /  : debian/dists/unstable/main/binary-i386/Packages/  it  download the file !!! while Packages is a file, not a directory ... the dispatch rules generated by simple_bridge :   [{'_',[],
        [{[<<"debian">>,<<"dists">>,'...'],
          [],cowboy_static,
          {dir,"/var/www//debian/dists/",[{mimetypes,cow_mimetypes,all}]}},
         {[<<"debian">>,<<"pool">>,'...'],
          [],cowboy_static,
          {dir,"/var/www//debian/pool/",[{mimetypes,cow_mimetypes,all}]}},
         {[<<"ubuntu">>,<<"dists">>,'...'],
          [],cowboy_static,
          {dir,"/var/www//ubuntu/dists/",[{mimetypes,cow_mimetypes,all}]}},
         {[<<"ubuntu">>,<<"pool">>,'...'],
          [],cowboy_static,
          {dir,"/var/www//ubuntu/pool/",[{mimetypes,cow_mimetypes,all}]}},
         {'_',[],cowboy_simple_bridge_anchor,[]}]}]

**Comment by essen** [comment]
The error comes from the Etag header I believe. Check what your client sends and what the server response is.

**Comment by crownedgrouse** [comment]
I added a firefox plugin to get http headers sent and received, but I cannot reproduce the problem :(

**Comment by crownedgrouse** [comment]
Anyway it was strange that a wrong / at end of URL allow to download a file. I'm working on a project with deep static directory structure (let says a debian repo ... ) so I will try to give you more info if I get another time the problem. to be continued

**Comment by essen** [comment]
That's a separate issue entirely, feel free to open a ticket for that if you think it's too weird. :-)

**Comment by essen** [comment]
Did you reproduce the crash issue again recently? Should we close?

**Comment by crownedgrouse** [comment]
no, I did not but for the reason you know. I do not use cowboy backend for the moment, until I understand/fix the other issue. You can close. Once cowboy is working properly with simple_bridge I will test again and report issue if there is any.

**Comment by essen** [comment]
Cool thanks.
