### ISSUE TITLE
Dynamic handler on static directory 

### ISSUE THREAD

**Issue by crownedgrouse** [ninenines/cowboy#877]
Hi Loïc , 
Is there a way to redirect request on a static directory to another handler ?
My wish is to create a dynamic index of the content of the static directory. Can do it with inets backend.
Another complication is the deep static directory structure. Would be a nightmare to set it individualy in rules...
Any idea ?

**Comment by essen** [comment]
I am not sure what you are asking exactly, but it sounds like something a normal handler would solve?

**Comment by crownedgrouse** [comment]
Maybe I doing something wrong but when using no static handler,  access to files with extension does not work ?

**Comment by essen** [comment]
Why not? The static handler is a normal handler. A fairly simple one too. You can copy it and customize it to your needs.

**Comment by crownedgrouse** [comment]
OK I will dig.

**Comment by essen** [comment]
Closing for now, following email exchange. Good luck!
