### ISSUE TITLE
websocket badmatch error

### ISSUE THREAD

**Issue by WanliTian** [ninenines/cowboy#883]
ERROR: 15-09-02 10:41:51 [<0.14008.0>@] Ranch listener http had connection process started 
    with cowboy_protocol:start_link/4 at <0.29273.3550> exit with reason: {{badmatch,{error,closed}},
    [{cowboy_req,response,6,[{file,"src/cowboy_req.erl"},{line,1051}]},{cowboy_req,upgrade_reply,3,
    [{file,"src/cowboy_req.erl"},{line,847}]},{cowboy_websocket,websocket_handshake,3,
    [{file,"src/cowboy_websocket.erl"},{line,151}]},{cowboy_protocol,execute,4,
    [{file,"src/cowboy_protocol.erl"},{line,462}]}]}

**Comment by essen** [comment]
What's the problem?

**Comment by WanliTian** [comment]
there are so many `{error, closed}` errors when i used websocket.

**Comment by WanliTian** [comment]
these means the network is not stable?

**Comment by essen** [comment]
The crash happens when the server is trying to send the response to upgrade, because the socket was already closed. Not sure what I can do there?
