### ISSUE TITLE
query string parsing fails with error 500 if a query parameter is empty

### ISSUE THREAD

**Issue by galdor** [ninenines/cowboy#887]
The documentation for cowboy HEAD [indicates](http://ninenines.eu/docs/en/cowboy/HEAD/guide/req/):

> If no default is provided and the value is missing, the query string is deemed invalid and the
> process will crash.

In practice, the handler crashes and the client receives a 500 error. But it really should be a 400 error.

**Comment by essen** [comment]
Agree on both counts, and I confirm it was parsing those properly before. Can you provide a crash log?

**Comment by galdor** [comment]
Sorry, I just modified my message. The problem is not that empty query parameters are not supported. It's that the response is 500 and not 400 (something is wrong with the query, it's not an internal error).

**Comment by essen** [comment]
Alright. Should be an easy patch, check do_maybe_reply in cowboy_req if you want to send a PR. Thanks!

**Comment by essen** [comment]
For future reference: The patch in the closed PR above is good, just incomplete (lacking tests).
