### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#890]
I have found that (handler_module:init) function accepts 3 arguments {{tcp,http}, Req, Opts}
while in the examples it is declared as (handler_module:init/2)

am i using a too old or too new version of cowboy?

**Comment by essen** [comment]
init/2 is cowboy master
init/3 is cowboy 1.0

Examples might be broken on master currently.

**Comment by essen** [comment]
Assuming this was resolved. Enjoy!
