### ISSUE TITLE
cowboy 1.0.1 & cowlib 1.0.1 compatible with Erlang OTP 18?

### ISSUE THREAD

**Issue by sereysethy** [ninenines/cowboy#893]
Hello,

We have an issue of memory leaks in our application after we upgrade to Erlang OTP 18. In our application, we use `cowboy 1.0.1`, `cowlib 1.0.1`, `ranch`, `erlytdl` for diango template. It works just fine with Erlang OTP 17. Until we upgrade to Erlang OTP 18, after a period of time the memory of process `beam.smp` got built up. We need to restart our web server (cowboy application) to avoid any memory shortage problem. I am not sure what is the real cause?

In our application, we use websocket, and also rabbitmq to communicate with our agents. By the way I we also use `erlang.mk version 1.2` to build this our application.

Any suggestions?

Thanks,
Sethy

**Comment by essen** [comment]
Add https://github.com/ferd/recon and check where the memory is used, because i have no clue. I haven't observed something like this myself yet.

**Comment by sereysethy** [comment]
In your knowledge are there any compatibilities issues with Erlang OTP 18 for cowboy 1.0.1?

I never had experience with recon.

**Comment by essen** [comment]
Nope, like I said I have no clue. :-)

**Comment by sereysethy** [comment]
Actually before we had a problem of application start/stop order. Just recently I follow one of your posts https://github.com/ninenines/ranch/issues/90, by adding `ssl` in to `ranch` dependency. But then we face the problem of memory issue.

Now I removed `ssl` from `ranch` dependency. And hope that problem will go away. But still!

Anyway, I will continue to observe it. I just hope you can give me some hints.

**Comment by essen** [comment]
Ah, well if you are using SSL it's well possible that that's where your memory goes, especially since it can cache a lot with its default configuration. If that's indeed where the memory issues come from, look into the SSL application configuration in the OTP docs.

**Comment by sereysethy** [comment]
Yes we use SSL, but I already removed it from the dependency of ranch.

**Comment by essen** [comment]
This won't change anything with regard to memory. :-)

**Comment by sereysethy** [comment]
but before it worked just fine with Erlang 17.

**Comment by essen** [comment]
But the SSL application has changed since Erlang 17. And it's typically from that application that we see odd memory behaviors.

**Comment by sereysethy** [comment]
To be honest, I am not erlang expert. I just tried to fix and debug erlang code written by another person. I am not sure yet where to look at. Since we dont use anything special about SSL, beside we ask user browser to present certificate and pass it on to our agent backend to process it. I look at the code, it seems nothing is unusual.

**Comment by essen** [comment]
You can add recon to your project and try to look into it. This book can help you figure things out: http://www.erlang-in-anger.com/ It's most likely not a problem in your code, just that the properties of the system changed in 18 and you might need to set an option or two.

Unfortunately me guessing can only help you so much. There's no known issues other than SSL not always playing nice (but that's true of all Erlang versions, just with different issues). Some people solve the issue by putting something else in front of Cowboy to handle the SSL connection instead of letting Erlang do it. If that's not possible you can always request my services, shouldn't take more than a few hours to figure out the issue and fix it.

**Comment by sereysethy** [comment]
Thank you very much. I will let you know if your service is required.

**Comment by ferd** [comment]
Erlang version 18.0 as released on the website has a memory leak in the shell. See patched version 18.0.3: http://erlang.org/pipermail/erlang-questions/2015-August/085674.html at https://github.com/erlang/otp/releases/tag/OTP-18.0.3

If you find binary memory is leaking, that might be it.

**Comment by sereysethy** [comment]
Thank @ferd I installed Erlang OTP 18 from Erlang repository on Ubuntu. I do not know is it possible to apply the patch that you mentioned? Plus I have never done it before.

**Comment by bullno1** [comment]
@sereysethy  http://www.erlang.org/doc/installation_guide/INSTALL.html
Alternatively, kerl (https://github.com/yrashk/kerl) and erln8 (http://erln8.github.io/erln8/) can automate the process and help you maintain multiple OTP versions.

**Comment by sereysethy** [comment]
I just run into this thread where people discussed about "R18 Unbounded SSL Session ETS Table Growth" http://blog.gmane.org/gmane.comp.lang.erlang.bugs/month=20150901.

I think this is maybe my problem. They suggest to use `register_unique_session` in SSL.

**Comment by sereysethy** [comment]
http://erlang.2086793.n4.nabble.com/R18-Unbounded-SSL-Session-ETS-Table-Growth-td4713697.html

**Comment by essen** [comment]
Closing this as I believe you found your answers on the ML.

**Comment by sereysethy** [comment]
It works well on Erlang update OTP18.1. Thank you.
