### ISSUE TITLE
cowboy documentation and new .app file generation

### ISSUE THREAD

**Issue by ingwinlu** [ninenines/cowboy#894]
cowboy 1.0.x and master branch both need updates regarding the now no longer generated .app.src file in `doc/src/guide/getting_started.ezdoc`

**Comment by essen** [comment]
Will do when I remove the .app.src from Cowboy, it's planned for 1.1.0 and a future push to master.

**Comment by mxmerz** [comment]
I am currently trying to get cowboy running and would appreciate an update to the documentation.

**Comment by essen** [comment]
State your problem in a new ticket, this ticket is about removing a step from the docs that isn't necessary anymore.

**Comment by essen** [comment]
I will do this one tomorrow.

**Comment by essen** [comment]
Hm master was already done.

**Comment by essen** [comment]
Done. Will update the website soon-ish.
