### ISSUE TITLE
Wyrd file caching behaviour from vagrant

### ISSUE THREAD

**Issue by grahamrhay** [ninenines/cowboy#897]
When running an app in a vagrant box you can sometimes see olde versions of files served, which is deeply confusing.

This is NOT a cowboy specific problem (https://www.virtualbox.org/ticket/9069), but might be worth documenting somewhere.

http://lists.ninenines.eu/archives/extend/2015-September/000550.html

**Comment by bullno1** [comment]
Basically: https://github.com/ninenines/cowboy/issues/812

**Comment by grahamrhay** [comment]
ah, sorry, didn't realise it had been reported already. using NFS always seems to cause me different problems :(

**Comment by essen** [comment]
Closing as duplicate of older ticket.
