### ISSUE TITLE
when i need Initialize middlewares something ,how do I do it?

### ISSUE THREAD

**Issue by wuchuguang** [ninenines/cowboy#905]
I want to implement a middleware module this function need initialize ets:new.
because this middleware:execute has  ets:lookup/2 ets:delete/2, ets:insert/2

**Comment by wuchuguang** [comment]
now i change cowboy.erl,
fix start_https/x start_http/x function 
init_middleware(Middlewares) ->
     Fun = 
     fun(Middleware) ->
               Middleware:module_info(),
               erlang:function_exported(Middleware, init, 1) andalso Middleware:init()
     end,
     lists:foreach(Fun, Middlewares).

can?

**Comment by essen** [comment]
Middlewares are one function, surely you can do your ets:new at the start of the function?

**Comment by wuchuguang** [comment]
my middleware module has session cache ets . so i need load this middleware then init ets

**Comment by essen** [comment]
You can do this when you start your own application though? I don't understand why you think Cowboy should do it for you.

**Comment by wuchuguang** [comment]
middleware, i think this is a like a plugin-in ,so i think the plugin-in initialization

**Comment by wuchuguang** [comment]
ejaaberd gen_mod.erl

**Comment by essen** [comment]
Middlewares are one function, as I mentioned earlier, so there's no initialization going on. They are also specific to a request. They can act as an entry point to other of your own processes, which can do their own initialization, but that's it. Closing, thanks!
