### ISSUE TITLE
I got a lot of error and have no idea how to fix it. Anyone know whats going on?

### ISSUE THREAD

**Issue by cclam0827** [ninenines/cowboy#906]
I got a lot of error and have no idea how to fix it. Anyone know whats going on?

```
[error] emulator Error in process <0.22048.1679> on node 'node@example.com' with exit value: {{case_clause,52},[{cowboy_protocol,parse_hd_name_ws,8,[{file,"src/cowboy_protocol.erl"},{line,276}]}]}

[error] <0.481.0> Ranch listener http_listener had connection process started with cowboy_protocol:start_link/4 at <0.19915.1667> exit with reason: {{case_clause,52},[{cowboy_protocol,parse_hd_name_ws,8,[{file,"src/cowboy_protocol.erl"},{line,276}]}]}
```

**Comment by essen** [comment]
Apparently a client is sending you a header name, followed by whitespace, followed by the character "4". Cowboy expects a ":" between header name and value, not "4".

That, or you have discarded the Req object at some point while reading the body and you just got Cowboy confused when a second request comes in on the same connection (though unlikely considering where it fails).

**Comment by essen** [comment]
Closing because inactive. Cheers!
