### ISSUE TITLE
Ability to access the client SSL Certificate

### ISSUE THREAD

**Issue by Licenser** [ninenines/cowboy#908]
I did find any way to access the clients SSL certificate when used for client authentication. From your article on ranch it seems that access to the socket is needed and adding a function like this to cowboy_req:

```erlang
cert(#http_req{socket = Socket}) ->
    ssl:peercert(Socket).
```

might already do the trick?

**Comment by essen** [comment]
cowboy_req:get(socket, Req)

Don't think we need anything special, this covers it. And while currently undocumented/internal, this isn't going anywhere and will be documented in 2.0 with a big warning about using this (and other) functions.

**Comment by Licenser** [comment]
That works wonderful :) :+1: thanks!

**Comment by willemdj** [comment]
It looks like this is no longer supported in version 2.0? Is there another way to get this information?

Thanks,
Willem

**Comment by essen** [comment]
Open a separate ticket, sounds like this was completely forgotten. It's not currently impossible, but it does involve having a custom protocol that then calls cowboy_tls so it's not user friendly enough.
