### ISSUE TITLE
Configure RAM limit for server process

### ISSUE THREAD

**Issue by sthzg** [ninenines/cowboy#910]
I hope it is okay to raise the question in this issue queue. Are there ways to limit the overall RAM used by the server-processes in a way that when the server is under heavy traffic it would try to consume less than the configured amount?

**Comment by essen** [comment]
No, in parts because the VM doesn't allow, in parts because it's very application dependent. Better measure and put limits on number of connections, which *is* possible.

-- 
Loïc Hoguin
http://ninenines.eu

-------- Original Message --------

**Comment by sthzg** [comment]
I see, that's good to know, thanks for your fast reply.
