### ISSUE TITLE
some ideas of the middleware

### ISSUE THREAD

**Issue by wuchuguang** [ninenines/cowboy#913]
cowboy:start_http(ProtoModule, ProtoParams, GlobalEnv, MidlleWares).

ProtoModule:: like cowboy_protocol.erl but need add -callback execute(Req, GlobalEnv) -> xxx.
ProtoParams:: like [{port, int()}]
GlobalEnv::like {env, somethingEnv}
MiddleWares::  support [middleware::module() | {middleware::module(),   middlewarePrivateEnv} ]

MiddleWare.erl
-callback execute(Req, GlobalEnv, PrivateEnv) -> 
   -> not change

-callback init(PrivateEnv) -> ok.

I can use like this.

         cowboy:start_http(cowboy_protocol, [{port, 8080}], [{globalEnv1, xxx}, {errors, [{404, "not_found.html"}]}], [{web_route, xxxxs}, {web_controller, xxxxs}, {web_view, xxxxs}]).

**Comment by wuchuguang** [comment]
Middleware depend on each other ,more bad?

**Comment by wuchuguang** [comment]
WebMvcEnvs =  [{web_route, xxxxs}, {web_controller, xxxxs}, {web_view, xxxxs}],
     cowboy:start_http(cowboy_protocol, [{port, 8080}], [{globalEnv1, xxx}, {errors, [{404, "not_found.html"}]}],[{web_mvc, WebMvcEnvs}]).

middleware not deppend on each other middleware.

**Comment by wuchuguang** [comment]
WebMvcEnvs = [{web_mvc_route, xxxxs}, {web_mvc_controller, xxxxs}, {web_mvc_view, xxxxs}],

**Comment by essen** [comment]
I'm not sure what you're trying to say.

**Comment by wuchuguang** [comment]
I mean: give middleware provide private env_data , env to env as a global.

**Comment by essen** [comment]
What would this private env data be used for? What problem does this solve?

**Comment by essen** [comment]
Closing for now but feel free to reopen with answers. Thanks!
