### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by psychoss** [ninenines/cowboy#914]
```
defmodule ChunkedHelloWorld do
  use Application

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      # Define workers and child supervisors to be supervised
      # worker(ChunkedHelloWorld.Worker, [arg1, arg2, arg3])
      worker(__MODULE__, [], function: :run)
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: ChunkedHelloWorld.Supervisor]
    Supervisor.start_link(children, opts)
  end

  def run do
    routes = [
      {"/", Handler, []}
    ]
    dispatch = :cowboy_router.compile([{:_, routes}])
    opts = [port: 8080]
    env = [dispatch: dispatch]
    {:ok, _pid} = :cowboy.start_http(:http, 100, opts, [env: env])
  end
end
```
```
defmodule Handler do
  def init(_transport, req, []) do
    {:ok, req, :undefined}
  end

  def handle(req, state) do
    {:ok, req} = :cowboy_req.chunked_reply(200, req)
    :ok = :cowboy_req.chunk("Hello\r\n", req)
    :ok = :timer.sleep(1000)
    :ok = :cowboy_req.chunk("World\r\n", req)
    :ok = :timer.sleep(1000)
    :ok = :cowboy_req.chunk("Chunked!\r\n", req)
    {:ok, req, state}
  end

  def terminate(_reason, _req, _state) do
    :ok
  end
end
```

Error:

---

10:35:12.768 [error] Ranch listener :http had connection process started with :cowboy_protocol:start_link/4 at #PID<0.222.0> exit with reason: {:cowboy_handler, [class: :error, reason: :undef, mfa: {Handler, :init, 2}, stacktrace: [{Handler, :init, [{:http_req, #Port<0.2617>, :ranch_tcp, :keepalive, #PID<0.222.0>, "GET", :"HTTP/1.1", {{127, 0, 0, 1}, 34701}, "localhost", :undefined, 8080, "/", :undefined, "", [], [{"host", "localhost:8080"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "zh-CN,zh;q=0.8"}], [], :waiting, "", :undefined, false, :waiting, [], "", :undefined}, []], []}, {:cowboy_handler, :execute, 2, [file: 'src/cowboy_handler.erl', line: 41]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 470]}], req: [socket: #Port<0.2617>, transport: :ranch_tcp, connection: :keepalive, pid: #PID<0.222.0>, method: "GET", version: :"HTTP/1.1", peer: {{127, 0, 0, 1}, 34701}, host: "localhost", host_info: :undefined, port: 8080, path: "/", path_info: :undefined, qs: "", bindings: [], headers: [{"host", "localhost:8080"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "zh-CN,zh;q=0.8"}], meta: [], body_state: :waiting, buffer: "", multipart: :undefined, resp_compress: false, resp_state: :waiting, resp_headers: [], resp_body: "", onresponse: :undefined], opts: []]}
---

after changed the handler
```
defmodule Handler do
  def init(req, opts) do
    {:ok, req} = :cowboy_req.reply(200, [{"content-type", "text/plain"}], "hello world", req)
    {:ok, req, :undefined}
    end

  def terminate(_reason, _req, _state) do
    :ok
  end
end
```
11:28:40.166 [error] Ranch listener :http had connection process started with :cowboy_protocol:start_link/4 at #PID<0.215.0> exit with reason: {:cowboy_handler, [class: :error, reason: {:badmatch, {:http_req, #Port<0.2599>, :ranch_tcp, :keepalive, #PID<0.215.0>, "GET", :"HTTP/1.1", {{127, 0, 0, 1}, 37650}, "localhost", :undefined, 8000, "/", :undefined, "", [], [{"host", "localhost:8000"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "zh-CN,zh;q=0.8"}], [], :waiting, "", :undefined, false, :done, [], "", :undefined}}, mfa: {Handler, :init, 2}, stacktrace: [{Handler, :init, 2, [file: 'lib/handler.ex', line: 5]}, {:cowboy_handler, :execute, 2, [file: 'src/cowboy_handler.erl', line: 41]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 470]}], req: [socket: #Port<0.2599>, transport: :ranch_tcp, connection: :keepalive, pid: #PID<0.215.0>, method: "GET", version: :"HTTP/1.1", peer: {{127, 0, 0, 1}, 37650}, host: "localhost", host_info: :undefined, port: 8000, path: "/", path_info: :undefined, qs: "", bindings: [], headers: [{"host", "localhost:8000"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "zh-CN,zh;q=0.8"}], meta: [], body_state: :waiting, buffer: "", multipart: :undefined, resp_compress: false, resp_state: :waiting, resp_headers: [], resp_body: "", onresponse: :undefined], opts: []]}

**Comment by essen** [comment]
If you are using Cowboy master, the interface has changed, check the documentation for master, not for 1.0.
