### ISSUE TITLE
Error in examples/rest_basic_auth

### ISSUE THREAD

**Issue by OlegUm** [ninenines/cowboy#921]
https://github.com/ninenines/cowboy/blob/master/examples/rest_basic_auth/src/toppage_handler.erl

This code does not work:
```
is_authorized(Req, State) ->
....
		{<<"basic">>, {User = <<"Alladin">>, <<"open sesame">>}} ->
			....
	end.
```

The correct code is as follows:
```
is_authorized(Req, State) ->
	...
		{basic, User = <<"Alladin">>, <<"open_sesame">>} ->
		....
	end.
```

**Comment by essen** [comment]
Thanks, I have this done locally now, so will be fixed in the next push. Closing!
