### ISSUE TITLE
Return 400 error code on constraint failure

### ISSUE THREAD

**Issue by ibizaman** [ninenines/cowboy#923]
Hi,

For now, if I'm not mistaken, cowboy can only return a 500 Server Error when a queries constraint fails (returns `false`).
It would be great if we could customize that error code. For example I would prefer a 400 Bad Request.

Would you be okay for a PR with this? How would you want this to be implemented?

**Comment by essen** [comment]
There's a function in cowboy_req that checks where a crash occured and can change the 500 into anything else if it detects a different kind of failure.

**Comment by ibizaman** [comment]
Would that be the [`do_maybe_reply`](https://github.com/ninenines/cowboy/blob/master/src/cowboy_req.erl#L875) function?
We should add a function clause calling something like a custom user function, but I don't see how to do that cleanly. Could you provide some pointers?

**Comment by essen** [comment]
I'm not saying you should customize it. The crash occurs inside Cowboy itself, and the behavior for those kind of errors is well defined by the RFC, so it should be just a matter of adding a clause similar to the other ones.

**Comment by ibizaman** [comment]
Okay then. Do you agree with the interpretation I make that having a constraint failing is more a 400 Bad Request than a 500 Server Error?
The former is defined as "The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, **invalid request message framing**, or deceptive request routing)."
The latter is a generic error.

**Comment by essen** [comment]
Yes it definitely should be a 400.

**Comment by essen** [comment]
This was fixed a week or two ago.
