### ISSUE TITLE
error when compiling cowboy_req.erl

### ISSUE THREAD

**Issue by ptmoy2** [ninenines/cowboy#926]
I downloaded 'cowboy-master.zip', extracted files, and tried to build using rebar3.  I got the following error (OTP 17.1):

pm@T110:~/ProgramFiles/cowboy-master$ rebar3 compile

===> Verifying dependencies...
===> Fetching cowlib ({git,"https://github.com/ninenines/cowlib",
                                  "master"})
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref}, otherwise updating the dep may not work as expected.
===> Fetching ranch ({git,"https://github.com/ninenines/ranch","1.1.0"})
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref}, otherwise updating the dep may not work as expected.
===> Compiling cowlib
===> Compiling ranch
===> Compiling cowboy
===> Compiling /home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl failed
/home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl:1206: illegal use of variable 'Atom' in map
/home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl:1209: illegal use of variable 'Atom' in map
/home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl:1212: illegal use of variable 'Atom' in map
/home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl:1233: illegal use of variable 'Key' in map
/home/pm/ProgramFiles/cowboy-master/_build/default/lib/cowboy/src/cowboy_req.erl:1244: illegal use of variable 'Key' in map

**Comment by essen** [comment]
You need Erlang 18+.
