### ISSUE TITLE
Cannot make ezdoc from Cowboy

### ISSUE THREAD

**Issue by haspok** [ninenines/cowboy#927]
Executing `make docs` results in the following error:

    make[1]: Entering directory 'deps/ezdoc'
    Makefile:6: *** target file 'docs' has both : and :: entries. Stop.

Manually changing line 6 in `deps/ezdoc/Makefile`

    docs: all

to

    docs:: all

fixes the problem.

**Comment by essen** [comment]
Thanks for the report!

**Comment by essen** [comment]
The documentation has been converted to AsciiDoc, the format I now use across all projects, so I will be closing this. Thanks!
