### ISSUE TITLE
http 415 in REST requests when Content-Type includes charset

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowboy#929]
```
curl -H "content-type: application/x-www-form-urlencoded; charset=UTF-8"  -d param=value -i -X PUT http://domain.com/url
```

when the `; charset=UTF-8` part presents, the REST handler does not understand the real content-type and returns `415 Unsupported Media Type`. It's a quite common extension, my browser sends it in the 'content-type' field.

**Comment by essen** [comment]
There's a notation to accept any parameter, it may or may not be '_', and should be in the documentation. If not using a wildcard, Cowboy matches exactly.

**Comment by brigadier** [comment]
Thank you, it's `'*'`, found in the comments in cowboy_rest.erl. No mention in the documenttion `http://ninenines.eu/docs/en/cowboy/HEAD/guide` though

**Comment by essen** [comment]
Reopening to not forget to document it then.

**Comment by hachreak** [comment]
Hi, I think also the examples should be updated.
Look e.g.: https://github.com/ninenines/cowboy/blob/master/examples/rest_pastebin/src/toppage_handler.erl#L27

Should it be like `'*'` instead of `[]`?
```erlang
   {{<<"text">>, <<"plain">>, '*'}, paste_text},
```

**Comment by essen** [comment]
It could be.

**Comment by essen** [comment]
It's been documented a while ago, and I've improved the mentioned example on my local copy. Thanks!
