### ISSUE TITLE
Cowboy server is attacked

### ISSUE THREAD

**Issue by noerl** [ninenines/cowboy#931]
=ERROR REPORT==== 2-Jan-2016::01:24:05 ===
Error in process <0.867.0> with exit value:
{function_clause,
    [{cowboy_protocol,parse_method,
         [<<>>,
          {state,#Port<0.2244>,ranch_tcp,
              [cowboy_router,cowboy_handler],
              false,
              [{listener,http},
               {dispatch,
                   [{'_',[],
                        [{[],[],cowboy_static,{priv_file,kuai,"index.html"}},
                         {[<<"search">>],[],search,[]},
                         {['...'],[],cowboy_static,{priv_dir,kuai,[]}}]}]}],
              undefined,5,1,100,4096,64,4096,100,5000,-576251932192},
          <<0,0,0,113,106,129,110,48,129,107,161,3,2,1,5,162,3,2,1,10,164,129,
            94,48,92,160,7,3,5,0,80,128,0,16,162,4,27,2,78,77,163,23,48,21,
            160,3,2,1,0,161,14,48,12,27,6,107,114,98,116,103,116,27,2,78,77,
            165,17,24,15,49,57,55,48,48,49,48,49,48,48,48,48,48,48,90,167,6,2,
            4,31,30,185,217,168,23,48,21,2,1,18,2,1,17,2,1,16,2,1,23,2,1,1,2,
            1,3,2,1,2>>],
         [{file,"src/cowboy_protocol.erl"},{line,175}]}]}

i think cowboy need add the code 

parse_method(<< C, Rest/bits >>, State, SoFar) ->
	case C of
		$\r -> error_terminate(400, State);
		$\s -> parse_uri(Rest, State, SoFar);
		_ -> parse_method(Rest, State, << SoFar/binary, C >>)
	end;
parse_method(<<>>, State, _SoFar) ->
	error_terminate(400, State).

**Comment by essen** [comment]
#448
