### ISSUE TITLE
Improve the set_resp_body_fun interface

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#933]
Currently we have side effect functions that either receive the socket or a function to send chunks. It's not very easy to remember or even use.

It would be good if this could be made simpler, using the same method for both kinds, and if possible to have it side effect free. Perhaps we could have a fun that we call repeatedly with a state (a bit like a fold).

**Comment by 0xfei** [comment]
So set_resp_body_fun has been removed?

**Comment by essen** [comment]
Yes, instead you can call `set_resp_body(Body, Req)` with Body either the data or a `sendfile` tuple. If things go well the manual for that function will be up later today. And if you need to stream the response, `stream_reply/stream_body` got you covered.

Closing this as this is not relevant anymore.
