### ISSUE TITLE
Define and properly handle specific throw errors

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#934]
We could define behavior for specific kinds of throws, for example {input_error, ...}, and use those to detect that we need to send a 400, for example. By defining classes of errors like this, applications could throw early and still expect to have the right status code sent to the client.

**Comment by bullno1** [comment]
What do you think about making it generic like elli: `is_allowed(Req) orelse throw({403, [], <<"Permission denied">>})`?

**Comment by essen** [comment]
It's not readable. I wrote an HTTP server and even I don't really know what 403 does off the top of my head.

**Comment by essen** [comment]
Changing my answer a bit to be clearer.

This is not the use case. If you need to handle most status codes properly, you write a resource (cowboy_rest). This ticket is not really about the user code (with exceptions) but about having cowboy_req functions throw on error and Cowboy catching those and sending the right reply without having to look at where the crash occured.

**Comment by essen** [comment]
Has been implemented. It's exits with request_error tuples.
