### ISSUE TITLE
cowboy router error

### ISSUE THREAD

**Issue by Sepuka** [ninenines/cowboy#936]
Bad request examle: GET /version/path/%\u0016\u0016/path
drop cowboy server with stack

```
Ranch listener https had connection process started with cowboy_protocol:start_link/4 at <0.802.0> exit with reason:
{function_clause,[{cow_qs,unhex,[22],[{file,"/home/shlomin/portal/deps/cowlib/src/cow_qs.erl"},line,345}]},
cow_qs,urldecode,2,[{file,"/home/shlomin/portal/deps/cowlib/src/cow_qs.erl"},{line,336}]},
cowboy_router,'-split_path/2-lc$^1/1-1-',1,[{file,"src/cowboy_router.erl"},{line,331}]},
{cowboy_router,'-split_path/2-lc$^1/1-1-',1,[{file,"src/cowboy_router.erl"},{line,331}]},
cowboy_router,split_path,2,[{file,"src/cowboy_router.erl"},{line,331}]},
{cowboy_router,split_path,2,[{file,"src/cowboy_router.erl"},{line,334}]},
{cowboy_router,match_path,4,[{file,"src/cowboy_router.erl"},{line,271}]},
{cowboy_router,execute,2,[{file,"src/cowboy_router.erl"},{line,169}]}]}
```

reason: cowboy could not parse %\u0016\u0016 string
cowboy version 1.0.4

**Comment by essen** [comment]
I had no idea what this was so I went looking. Apparently it's a non-standard percent encoding: https://en.wikipedia.org/wiki/Percent-encoding#Non-standard_implementations

I have no plans to support it.

**Comment by Sepuka** [comment]
yes, but the program should not fail.
I see function_clause error in cow_qs:unhex func
and author protect this code - try catch.
```
	catch
		error:badarg ->
			badrequest
	end.
```
but actualy, throws "error:function_clause",
Why not substitute error:badarg to error:_anyReason?

**Comment by essen** [comment]
Does this result in Cowboy not sending back a response, or sending back an incorrect response?

**Comment by Sepuka** [comment]
my common tests fail, http client got {error,socket_closed_remotely}
i think "badrequest" msg look better than closed socket

**Comment by essen** [comment]
Fair enough, it should send an error back properly.

**Comment by essen** [comment]
Thanks for the report!

**Comment by isaiahdw** [comment]
I'm experiencing this issue as well. Bad url encoding causes Cowboy to crash and just close the connection.

URL: `/part1%20%/part2`

Error:
```[error] Ranch protocol #PID<0.778.0> (:cowboy_protocol) of listener Sre.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :cow_qs.urldecode/2
        (cowlib) src/cow_qs.erl:335: :cow_qs.urldecode("%", "part1 ")
        (cowboy) src/cowboy_router.erl:331: :cowboy_router."-split_path/2-lc$^1/1-1-"/1
        (cowboy) src/cowboy_router.erl:331: :cowboy_router."-split_path/2-lc$^1/1-1-"/1
        (cowboy) src/cowboy_router.erl:331: :cowboy_router.split_path/2
        (cowboy) src/cowboy_router.erl:334: :cowboy_router.split_path/2
        (cowboy) src/cowboy_router.erl:271: :cowboy_router.match_path/4
        (cowboy) src/cowboy_router.erl:169: :cowboy_router.execute/2
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4````

**Comment by essen** [comment]
The good news is that this was fixed a while ago and Cowboy returned a 500. The better news is that it now returns a 400. Thanks!
