### ISSUE TITLE
REST: order of is_authorized and resource_exists callbacks

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowboy#937]
AT the moment `is_authorized` is called at the beginning of the request, before the `resource_exists` callback. But sometimes authorization is made on object by object basis, so the authorization should be performed after resource_exists check. Maybe add another callback for this use case?

**Comment by essen** [comment]
Hm you do have all the info from the request so I'm not sure why you can't check this in is_authorized and keep things in the state from that point onward?

**Comment by brigadier** [comment]
SUre it is possible to get the object in is_authorised. I'm thinking more about convenience of callbacks code and callbacks names.

**Comment by essen** [comment]
I think adding more callbacks with similar purpose would be too confusing. I don't see a problem with fetching things in one function over another. That's why you have the State variable.
