### ISSUE TITLE
explanation for http 400 code

### ISSUE THREAD

**Issue by maxlapshin** [ninenines/cowboy#939]
I've got issue with one client:  his browser is requesting the same content from cowboy server (in our flussonic) and sometimes it gets response 400.

I've looked into cowboy code: https://github.com/ninenines/cowboy/blob/master/src/cowboy_protocol.erl#L520

error_terminate responds with empty body without giving any explanation.

Maybe it would be good to tag all error_terminate calls with some response for debugging? Will you accept such pull request?

**Comment by essen** [comment]
You can set a body with the onresponse hook.

**Comment by maxlapshin** [comment]
cowboy_protocol is raising 400 error code, not me.  I need to identify what is the problem and why 5% of requests are failing with code 400.  So I need to get more info from cowboy_protocol calls to error_terminate

**Comment by maxlapshin** [comment]
I've made inplace modification for this place in cowboy_protocol, now it looks like:

	error_terminate(400, <<"too long header size\n">>, State);

and it is possible to find out what is happening.

**Comment by essen** [comment]
I suppose this could be improved in 2.0.

**Comment by maxlapshin** [comment]
so you don't want to patch this in 1.x?

**Comment by essen** [comment]
I've improved both the detail of errors and how much you have access to error events in Cowboy 2.0. Nothing should stop you from processing them as you wish now.

I have no plans for further 1.x releases.
