### ISSUE TITLE
cowboy_req:reply bug?

### ISSUE THREAD

**Issue by jonasrichard** [ninenines/cowboy#940]
When a request in the state of done `cowboy_req:reply(204, Req)` results in a function_clause.
Shouldn't it work for `done` requests, too? I blamed the file and in an earlier comment the guards have been added because of not supporting chunked something. But it filters out done (maybe stream, too but I don't know what it is good for).

https://github.com/ninenines/cowboy/blob/dbb636034f20736e16eb9d6c809217c9525b6cbd/src/cowboy_req.erl#L687

**Comment by essen** [comment]
`done` means the reply has already been sent. You can't send two replies to one request in HTTP.

**Comment by jonasrichard** [comment]
The problem was that I am inside a rest handler. And that is why it said that response already sent.
