### ISSUE TITLE
cowboy_static won't serve file with + in the path

### ISSUE THREAD

**Issue by jeromede** [ninenines/cowboy#942]
Steps to reproduce:
Use the static_world example, add a+/index.html in priv/ and then try to get http://localhost:8080/a+/index.html 
-> 404

**Comment by jeromede** [comment]
I think it's the way the URL is parsed in cowlib and maybe '+' is considered as special. Although it seems it shouldn't in a fragment, according to https://www.ietf.org/rfc/rfc3986.txt
I'll check cowlib.

**Comment by essen** [comment]
It's possible that the wrong urldecode function is used. One urldecode function has + become space, one doesn't. I don't remember offhand which is which.

**Comment by jeromede** [comment]
Looks like both cow_qs:urldecode and cow_qs:parse_qs_name change $+ to space. I think it should be done for a query part fragment only, not for a path segment.

**Comment by essen** [comment]
I believe you are correct.

**Comment by essen** [comment]
This has been fixed a couple days ago and it's now tested. Thanks!
