### ISSUE TITLE
Valid HTTP header crashing process

### ISSUE THREAD

**Issue by semmons99** [ninenines/cowboy#943]
We're receiving the following connection header

`Connection: keep-alive Te`

Cowboy is seeing this and crashing, saying it's invalid. According the http/1.1 spec, any arguments after the first are meant for proxies to read and delete those headers when forwarding. If there's no proxy between the two servers, then everything after the first argument should be ignored. Unfortunately this isn't the case.

Sadly, I come from the Ruby/Elixir world and don't quite know where to start. I'd gladly contribute a patch with guidance though.

**Comment by essen** [comment]
Hm that's not a valid Connection header.

```
   The Connection header field's value has the following grammar:

     Connection        = 1#connection-option
     connection-option = token
```

The `1#` part means a list of at least one element. Elements of a list are always separated by a comma and optional whitespace. I don't see a comma here.

**Comment by semmons99** [comment]
Ah, so is that the real issue? I know their client software is written in Go and appends " Te" to every Connection header it sends. Is there documentation I can take to that project showing that it should be ", Te"?

**Comment by essen** [comment]
https://tools.ietf.org/html/rfc7230#section-6.1

**Comment by semmons99** [comment]
Thank you!
