### ISSUE TITLE
zlib problems or? [websockets MsgQ bottlenecking]

### ISSUE THREAD

**Issue by vans163** [ninenines/cowboy#944]
I have a strange issue where I am flooding a websocket client with json msgs (the flooding is not out of the ordinary, just under 1mbps), and the cowboy session genserver cannot process them intime, there is a scheduler on the machine at 100%, so safe to assume that zlib cannot keep up.  Here is a snippet from observer:

```
cowboy_protocol:init4  14009   100mb  {'MsgQ',  697586}  zlib:collect/1
... Wait some time
cowboy_protocol:init4  180581   153mb  {'MsgQ',  824811}  zlib:arg_flush/1
... Wait some time
cowboy_protocol:init4  12007   160mb  {'MsgQ',  1039961}  cowboy_websocket:handler_loop/4
```

It seems to spend most time displaying it is in zlib related functions.

Reading about zlib led me to http://joearms.github.io/2013/03/28/solving-the-wrong-problem.html which says that it was rewritten in pure erlang.  Being a happy camper I assume they tested it and made sure the rewrite was faster than original?

**Comment by essen** [comment]
The one with Erlang/OTP is still in C AFAIK.

Just to be clear, you are testing Websocket with compression enabled against master? Because if you don't enable it it shouldn't call zlib.

**Comment by vans163** [comment]
Yes compression enabled of course.  Is there a way to disable compression on cowboy so as to check?

Also if it was all in C I dont think it can call zlib:?/? functions it would just be a handful of functions, googling the function names like arg_flush leads me to pure erlang implementation.  I could get to the bottom of this with some concrete profiler captures, I just want a confirmation if this is indeed an issue before going ahead.

**Comment by essen** [comment]
There is a module in Erlang that calls a port driver, and the code for zlib is still https://github.com/erlang/otp/tree/maint/erts/emulator/zlib in maint at least.

It seems I did not put an option to disable it yet, although we definitely need one before Cowboy 2.0 is released.

I'm wondering what Erlang version you use though? I don't recall seeing this problem with zlib, although the autobahntestsuite compression tests are pretty slow. If it still runs badly like this I could be interested in using a different zlib implementation. Did Concurix open source theirs?

**Comment by vans163** [comment]
Im making a test case now, its the latest release R18,2.  

Concurix. It does not seem so, their website landing is blank page.

**Comment by vans163** [comment]
I cant seem to make a test case for it locally.. I would have to analyze it off a running deployment.  The connect processes all the msgs intime (a gen_server feeding the connected client with msgs).

**Comment by vans163** [comment]
This is a complex problem to solve, for example we want to use rle strategy for png's or other image data. We want to use huffman_only if our data is completely random text or very short.  Also WindowBits of 15 vs -15 could have a positive effect for cpu time at the expend of 2 extra bytes per msg.

I think a possible way to solve this is to do (best_speed):
in cowboy as default (dont touch cowlib), and then allow the user to pass a level, and strategy. 
Opts = #{level => best_speed, mem_level => 8, strategy => default},

**Comment by essen** [comment]
Yes it's missing all the options. :-)

**Comment by vans163** [comment]
Overall this zlib that the websocket consortium added is half assed.  You don't want to be deflating every 10-20byte msg you send, as the nature of websocket framing disallows any buffering to take place. Compression in this case should have be handled by the implementation of the end user.  A good fix for them to implement is to add a bitflag to the msg if it is deflated, per msg.  Not auto-on for every single one.

Let me see if I can create a pull. Would cowlib need to be touched at all? (I am not too familiar with cowboy internals)

**Comment by essen** [comment]
There is a bitflag, it's the Cowboy implementation that is half-assed. The current implementation was meant to not break the interface (yet), something which we can do for 2.0. I believe I had your same concerns posted somewhere, probably a ticket. I'm not sure what the interface should be in the end though (we definitely need an "auto compress" mode and one without compression, but something in-between would be nice.

I don't believe Cowlib needs to be changed at all, just cowboy_websocket.

**Comment by vans163** [comment]
Websockets, because they just expose to you   
```
(javascript browser side)
websocket.send(Data);  
it should be 
websocket.send(Data, Options);
Options = [deflate, '...']

```

**Comment by essen** [comment]
Ah you meant on Javascript's side. Yes, that part is pretty bad.

**Comment by vans163** [comment]
So all websocket browser implementations read a bitflag and inflate based on that?  So cowboy would be able to control if to send the msg deflated or not, on a msg per msg basis?

**Comment by essen** [comment]
https://tools.ietf.org/html/rfc7692 is the one you want. It's implemented as an RSV flag from the frame.

**Comment by essen** [comment]
```
PMCEs
   use the RSV1 bit of the WebSocket frame header to indicate whether a
   message is compressed or not so that an endpoint can choose not to
   compress messages with incompressible contents.
```

**Comment by vans163** [comment]
Yes perfect.  Okay opened pull request, I will slowly chip away at it.
https://github.com/ninenines/cowboy/pull/945

**Comment by vans163** [comment]
Okay thats about it, the zlib works fine at -15. That means sliding window is disabled, yet it still seems zlib itself does some kind of sliding window style features.  

I have no idea why but setting it to 15 causes the browser to crash, there must be something extra appended/removed from the payload if it has sliding window.

**Comment by essen** [comment]
Closing since it's now possible to configure all the options. Thanks!
