### ISSUE TITLE
Secure connection or not

### ISSUE THREAD

**Issue by AstRonin** [ninenines/cowboy#950]
Now I have no way for understanding which connection I'm using, `http` or `https`. 
I suggest add next method into `cowboy_req` or something like that:

```erlang
secure(Req) ->
	Bool = case Req#http_req.transport:name() of
		ssl -> true;
		_ -> false
	end,
	{Bool, Req}.
```

**Comment by essen** [comment]
There will be a function for getting the scheme part of the URI (http or https).

**Comment by essen** [comment]
The scheme function has been added to master. Thanks!
