### ISSUE TITLE
case sensitive headers

### ISSUE THREAD

**Issue by nesQuick** [ninenines/cowboy#951]
I can produce a request like:

```
👌  helloplug curl -vvvv localhost:4000/
* Connected to localhost (127.0.0.1) port 4000 (#0)
> GET / HTTP/1.1
> Host: localhost:4000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: Cowboy
< date: Thu, 18 Feb 2016 10:23:54 GMT
< content-length: 13
< cache-control: max-age=0, private, must-revalidate
< Server: Plug
<
* Connection #0 to host localhost left intact
Hello, world!%
```

But the [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2) states that headers are case-insensitive

>   Each header field consists of a case-insensitive field name [...]

I think the second header should overwrite the first in order, in order to mimic the behaviour as I would have passed a `server` header. On the other hand, it would be allowed to have the same header multiple times. but that should also be reflected in the first case.

cheers

**Comment by essen** [comment]
By convention the Cowboy functions expect and return lowercase header names. The documentation reflects that.
