### ISSUE TITLE
When does error 414 occur?

### ISSUE THREAD

**Issue by ibizaman** [ninenines/cowboy#952]
Sorry in advance, my question is quite vague.
And it is quite vague because I cannot reproduce it correctly and found no place in cowboy code about it.

I have, sometimes, cowboy returning a 414 error. When that happens, I can simply resend the same query and it works. I don't expect one to solve this but could someone provide pointers as to where I can look in the code?

Thank you :)

**Comment by essen** [comment]
https://github.com/ninenines/cowboy/blob/master/src/cowboy_protocol.erl#L156 I guess?

Increase the max_request_line_length option, it defaults to 4096 (that's included method, whitespace and HTTP version).

**Comment by ibizaman** [comment]
Thank you, should have closed this earlier, sorry.
