### ISSUE TITLE
Crash when replying after commencing reading body but not completing

### ISSUE THREAD

**Issue by strange** [ninenines/cowboy#955]
Leaving a "reply" after an unfinished (i.e. stop reading after `badlength` or `more`) call to `body/2` or `body_qs/1` results in a crash:

```
Req3 = cowboy_req:reply(400, Req2),                                 
{ok, Req3, State}
```

Results in:

```
16:55:13.134 [error] Error in process <0.356.0> with exit value:
{{badmatch,{error,closed}},[{cowboy_req,body_recv,3,[{file,"src/cowboy_req.erl"},{line,464}]},{cowboy_req,body_loop,5,[{file,"src/cowboy_req.erl"},{line,447}]},{cowboy_protocol,next_request,3,[{file,"src/cowboy_protocol.erl"},{line,504}]}]}
16:55:13.134 [error] Ranch listener http terminated with reason: no match of right hand value {error,closed} in cowboy_req:body_recv/3 line 464
```

N.B. That the crash happens _after_ the reply has been successfully received by the client (i.e. this problem is not affecting the client to my knowledge).

Removing the call to `reply/2` results in an empty response and no crash.

**Comment by essen** [comment]
Closing this because this all has changed in 2.0 and shouldn't be an issue anymore. Thanks!
