### ISSUE TITLE
Cowboy as your first Erlang app

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#956]
Could be good to write a piece of documentation that explains Cowboy from the point of view of the beginner Erlang developer.

**Comment by Kyche** [comment]
I could do this with Elixir if that would be helpful.

**Comment by essen** [comment]
Feel free to experiment and report back the results, this won't be on my todo list for a while. :-)

**Comment by essen** [comment]
I would welcome such documentation but let's be honest, I'll never get around to it myself. Closing, thanks!
