### ISSUE TITLE
content_types_provided with no GET

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#957]
We want to accept a media-type, but we don't want to define a callback if we are not going to call it. I currently recommend putting undefined. Maybe '' would be a better value. Maybe there can be another, cleaner solution.

**Comment by bullno1** [comment]
Some suggestion:

1. Just return a shorter tuple?
2. `fun cowboy_rest:unexpected/2` which halts into 500?

**Comment by essen** [comment]
Documented this in resource_design.asciidoc. Closing, thanks!
