### ISSUE TITLE
Is ssl_hello_world_app.erl valid?I can't even compile

### ISSUE THREAD

**Issue by suexcxine** [ninenines/cowboy#958]
I got the following error message:
> src/ssl_hello_world_app.erl:25: syntax error before: ','

line 25 is:
```
#{env, [{dispatch, Dispatch}]}
```
is this a valid map?

**Comment by essen** [comment]
It's not. Master is undergoing large changes and the examples and docs are probably incorrect.

**Comment by essen** [comment]
It has been fixed a while ago. Some other examples are still broken though. Closing, thanks!
