### ISSUE TITLE
Compress didn't override external content-length

### ISSUE THREAD

**Issue by AstRonin** [ninenines/cowboy#959]
I added header `<<"content-length">>` to response by function `set_resp_header` in my code. But Cowboy didn't override length after compressing response body.

**Comment by essen** [comment]
What version?

**Comment by AstRonin** [comment]
1.0.1

**Comment by essen** [comment]
Is that with the `{compress, true}` option? Cowboy does set a content-length there, but if you specify one yourself then Cowboy will use yours (what you set overrides the defaults).

Note that there should be no need to set content-length yourself as Cowboy sets it for you when needed.
