### ISSUE TITLE
websocket permessage-deflate support in v1

### ISSUE THREAD

**Issue by martinpritchard** [ninenines/cowboy#960]
As I understand it, there is support for websocket ```permessage-deflate``` in cowboy V2.

Could it be easily added to V1? I have a requirement to support this, but I'm not in a position to upgrade to V2.

**Comment by essen** [comment]
It shouldn't be too difficult.

**Comment by martinpritchard** [comment]
OK, I'll take a look.  

As an aside, when is V2 due to come out of 'preview' and become an official release suitable for production use?

**Comment by essen** [comment]
Officially not for a long time. But it should get close in the second part of the year.

**Comment by martinpritchard** [comment]
Back to permessage-deflate: Do you have any pointers on the best way to go about this change?  I've had a quick look around the src, it seems that some of permessage-deflate support is contained within cowlib, so an upgrade to a newer version of cowlib may be required?  Is this likely to cause any issues with other areas of cowboy?

**Comment by essen** [comment]
Upgrading cowlib would cause issues. Upgrading just cow_ws and parts of cow_http_hd is unlikely to.

**Comment by martinpritchard** [comment]
Myself and a colleague are in the final stages of completing this, and we're planning on submitting a PR. Is that something you would be interested in? We've had some memory management issues to overcome, hence the delay.

**Comment by essen** [comment]
I'm always interested in a PR. :-)

**Comment by jonathanprouse** [comment]
This is the colleague mentioned above. We're ready to submit a PR, although we've made changes to cowlib along with cowboy.
Will a PR need to be made for both separately? If you could advise on how best to move forward that would be great, thanks.

**Comment by essen** [comment]
I'm wondering what changes were needed in Cowlib? Do you have a link to the commit/branch?

**Comment by jonathanprouse** [comment]
The change was mainly to back-port cow_ws.erl into 1.0.x, as such there was no need to touch any other files.
However cow_ws.erl has had a change in deflate_frame/3 to stop a memory issue caused by zlib along with modification to set takeover and max_window_bit extensions.

Link is here:
https://github.com/bet365/cowlib/tree/1.0.2.ws_permessage_deflate.1

**Comment by essen** [comment]
OK then I suppose we can go this way:

* Make a Cowlib PR with the small changes against master (where I can easily test things out)
* When merged, backport the cow_ws module into Cowlib's 1.0.x
* Tag Cowlib 1.0.3 (not semver but Cowlib has not been following it properly and won't before 2.0)
* Make the Cowboy PR against 1.1.x (it's basically 1.0.x + some Cowlib/Ranch versions updated for now)

When (or whether) there'll be a 1.1.0 version of Cowboy is still undecided. I spend all my time on master currently. But I suppose this is functionality enough to increment the version.

How does that sound?

**Comment by jonathanprouse** [comment]
Yeah, that sounds good, thanks. I'll get started with the Cowlib PR.

**Comment by bryanhuntesl** [comment]
Did anything ever happen with this? Is there permessage-deflate support in V1/V2 ?

**Comment by essen** [comment]
2.0 has it, 1.0 has an open PR but there's no more 1.x releases planned.

**Comment by bryanhuntesl** [comment]
Thanks for quick response @essen

**Comment by martinpritchard** [comment]
@essen is the associated memory issue also fixed in 2.0?

**Comment by essen** [comment]
Not sure. Can you double check?
