### ISSUE TITLE
Logging requests and crashes in app using Cowboy/Elixir/Phoenix

### ISSUE THREAD

**Issue by hubertlepicki** [ninenines/cowboy#962]
I have stumbled upon some cowboy crashes, which are due to default configuration, when developing Elixir/Phoenix app. All sorted out but I wanted to add logging of those crashes to Phoenix/Plug itself so that next developers won't waste 4 hours of their lives debugging the same issue.

So example is 400 Bad Request when cookies set are too large, or similar error when query string is too long etc etc. Currently, Phoenix won't log anything to the console since the errors happen in Cowboy itself, and never even reach Phoenix/Plug.

Issue I opened originally on plug: https://github.com/elixir-lang/plug/issues/365

Is providing `onresponse` handler the best way of catching and logging those error responses? I'm interested in both error status code and a message so I can display it or log in the log file.

**Comment by essen** [comment]
I don't know about best. I think it's the only way.

**Comment by hubertlepicki** [comment]
Ok cool and thanks for response @essen
