### ISSUE TITLE
The static handler sets the wrong content-type for 404 responses, tripping Chrome

### ISSUE THREAD

**Issue by jonathanperret** [ninenines/cowboy#963]
When generating a 404 response, the `cowboy_static` handler defaults to the `application/octet-stream` content-type (with an empty body). This (`application/octet-stream` for an error page) causes Google Chrome (49.0.2623.87) to display an obscure `ERR_INVALID_RESPONSE` message instead of a "not found" message as Firefox does (Safari obligingly downloads a 0-byte file). Making the problem even harder to diagnose, the offending request is suppressed from Chrome's Web Inspector view, making it very difficult to see the original (and benign) 404 code, and causing the poor programmer to go around in circles chasing an elusive error for a few hours (true story).

Comments on a related issue in Chrome's bug tracker suggest this is intentional (https://bugs.chromium.org/p/chromium/issues/detail?id=434392):

> We refuse to download an error response to a local file, and can't do anything else with that mime type, so we return an error.

This is reproducible with this basic configuration of the `cowboy_static` handler:

``` erlang
-module(hello_cowboy_app).
-behaviour(application).

-export([start/2]).
-export([stop/1]).

start(_Type, _Args) ->
    Dispatch = cowboy_router:compile([
        {'_', [{"/[...]", cowboy_static, {priv_dir, hello_cowboy, "static"}}]}
    ]),
    {ok, _} = cowboy:start_http(my_http_listener, 100, [{port, 8080}],
        [{env, [{dispatch, Dispatch}]}]
    ),
    hello_cowboy_sup:start_link().

stop(_State) ->
    ok.
```

And an existing but otherwise empty `priv/hello_cowboy/static` directory. And of course, requesting `http://localhost:8080/some-non-existing-path` in Chrome.

May I suggest refraining from adding a Content-Type header when no file is being returned?

**Comment by essen** [comment]
I can reproduce.

**Comment by essen** [comment]
I have no easy fix. I will fix this as part of adding a test suite for RFC7231. Might be a while.

A workaround is to use cowboy_req:delete_resp_header in the resource_exists function, when the method is HEAD or GET and the resource does not exist.

**Comment by jonathanperret** [comment]
Noted, thanks for confirming.

**Comment by essen** [comment]
This has been fixed on my local copy and will be pushed later today. Thanks!
