### ISSUE TITLE
REST: Add Authorization to Vary header field when appropriate

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#964]
When the resource defines `is_authorized/2` we do not typically want to allow caching to be shared between users with different authorization header values. Therefore it may make sense to add "Authorization" to the "Vary" header by default.

**Comment by christopheradams** [comment]
I'm not sure this is necessary. [rfc7234 section 3](https://tools.ietf.org/html/rfc7234#section-3) says in part:

```
   A cache MUST NOT store a response to any request, unless:

   o  the Authorization header field (see Section 4.2 of [RFC7235]) does
      not appear in the request, if the cache is shared, unless the
      response explicitly allows it (see Section 3.2), and
```

It looks like the only way to possibly cache a response to an Authorization header is to use one of "public", "s-maxage", or "must-revalidate" for Cache-Control headers.

So `Vary: Authorization` wouldn't hurt, but it also seems like it isn't needed by default.

**Comment by essen** [comment]
Yes you are of course correct. I saw this a few weeks after initially opening this ticket. There are other mentions about Authorization not being necessary in Vary in that RFC. I will close this. Thanks!

**Comment by christopheradams** [comment]
Great. I realized that section 7.1.4 is actually explicit on this point:

> there is no need to send the Authorization field name in Vary because reuse across users is constrained by the field definition
