### ISSUE TITLE
REST examples do not work

### ISSUE THREAD

**Issue by aberman** [ninenines/cowboy#966]
It looks like the REST examples are using old code.  It would be nice to at least have one working example for new users (like me).  I was able to get the hello world rest example to work by changing to the new init callback:

init({tcp, http}, Req, Opts) ->
    {upgrade, protocol, cowboy_rest}.

**Comment by essen** [comment]
All the examples work in the latest stable release, 1.0. Master is undergoing large changes and examples will only get fixed after that.

**Comment by aberman** [comment]
Yeah, sorry, I closed it after realizing I was in the Master branch.  Thanks, Loïc.
