### ISSUE TITLE
rest_init does not support halt

### ISSUE THREAD

**Issue by aberman** [ninenines/cowboy#968]
I was wondering why rest_init doesn't implement the standard {halt, Req, State} form to be able to throw HTTP codes.  In rest_init, I'd like to be able to extract the path variable, validate its format, and then put it in the State.  For example, let's say my id is a uuid and the URL is http://foo.com/myResource/:myId.  Now, if the URL comes in as /myResource/de305d54-75b4-431b-adb2-eb6b9e546014 we're all good, but what if someone tries to hack the URL and puts in /myResource/foo.  Foo will be stored as myId but it is invalid since it is not a UUID.  Since I know this at the rest_init step, why should I have the server continue down the flowchart?  I want to halt the request and send a 404 immediately and not have the server process any further.  Thoughts?

**Comment by essen** [comment]
Two comments:

* If you have a path like /myResource/:myId with :myId expecting a UUID, you should put a constraint on :myId to check that you receive a UUID; when you don't the path will not match and you will get a 404 even earlier.
* rest_init/2 is gone in Cowboy 2.0, merged with init/2 which can end the request there so this is not an issue.

Thanks!

**Comment by aberman** [comment]
I'll use constraints, that is exactly what I want.  Thanks!
