### ISSUE TITLE
small formatting mistake in docs

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#969]
in http://ninenines.eu/docs/en/cowboy/2.0/guide/req/

where it says

     Read more about constraints

constraints is formatted as a exponent or something similar, I think you wanted to make it a link?

**Comment by essen** [comment]
lol

Well that's an oversight from converting to asciidoc I guess. Should be an xref link.

**Comment by essen** [comment]
That one is also fixed, thanks!
