### ISSUE TITLE
bad markup for content_types_provided default value in docs

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowboy#970]
http://ninenines.eu/docs/en/cowboy/2.0/guide/rest_handlers/

scroll to the bottom table, it contains `$$[, I guess that's markup that went wrong.

**Comment by essen** [comment]
Thanks. That one's related to https://github.com/ninenines/ninenines.github.io/issues/9

**Comment by essen** [comment]
That one's fixed, thanks!
