### ISSUE TITLE
http terminated with reason: no function clause matching 

### ISSUE THREAD

**Issue by maruks** [ninenines/cowboy#971]
I sometimes get errors like this one:

[error] Error in process <0.484.0> with exit value:
{function_clause,[{cowboy_protocol,parse_method,[<<>>,{state,#Port<0.5164>,ranch_tcp,[cowboy_router,cowboy_handler],false,[{listener,http},{dispatch,[{'_',[],[{[],[],cowboy_static,{priv_file,zole_ws,"index.html"}},{[<<"websocket">>],[],zole_ws_handler,[]},{[<<"static">>,'...'],[],cowboy_static,{priv_dir,zole_ws,"static"}}]}]}],undefined,undefined,5,1,100,4096,64,4096,100,5000,1460008899771},<<139,0,0,0,68,172,8,194,140,156,49,158,12,48,36,241,108,150,10,52,27,166,157,204,196,7,120,195,116,105,103,92,8,94,224,200,244,139,241,73,136,102,52,198,160,48,188,179,133,77,14,8,255,4,254,73,62,141,78,205,89,210,234,210,138,201,9,120,31,177,4,194,34,175,245,202,172,24,158,176,248,168,12,57,88,232,219,88,40,117,72,209,131,79,177,133,10,238,117,169,250,54,243,41,157,55,75,197,186,100,99,160,237,107,138,81,236,154,103,146,11,117,7,33,12,173,12,103,222,209,121,247,222,164,158,73,201,208,243,63,21,87,238>>],[{file,"/home/maris/Projects/erl-zole-ws/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,168}]}]}
07:01:34.775 [error] Ranch listener http terminated with reason: no function clause matching cowboy_protocol:parse_method(<<>>, {state,#Port<0.5164>,ranch_tcp,[cowboy_router,cowboy_handler],false,[{listener,http},{dispatch,[...]}],...}, <<139,0,0,0,68,172,8,194,140,156,49,158,12,48,36,241,108,150,10,52,27,166,157,204,196,7,120,195,...>>) line 168

**Comment by essen** [comment]
There'll be proper handling in Cowboy 2, there's another ticket for this. Thanks!
