### ISSUE TITLE
Set vary: accept-encoding when compression is enabled

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#974]
Looks like it's not currently set in Cowboy 1.0.

**Comment by nhooyr** [comment]
Is there anything holding this up?

**Comment by essen** [comment]
Please do not ask for updates on tickets like this. It's not only rude, but also a waste of time. If you need something done quicker, you can either send a patch including the change, tests and documentation, or buy my services so I focus on your particular needs instead of my own.

**Comment by nhooyr** [comment]
I'm sorry, I didn't mean to be rude, it's just that it sounds like a trivial fix. I don't know erlang/elixir, I was just checking out your framework and wondered if there was some deeper issue preventing this from being fixed.

**Comment by essen** [comment]
Most of the tickets are trivial, both in effort and in importance (this one can easily be fixed by the user, for example). I am focusing on the more important tasks at the moment (the last few breaking changes before 2.0).

**Comment by essen** [comment]
Done. Thanks!
