### ISSUE TITLE
Previously working Cowboy-based application not running anymore (undef bad_return)

### ISSUE THREAD

**Issue by dervism** [ninenines/cowboy#975]
Hi!

My previously working application does not start anymore and the crash dump / error messages doesnt make any sense to me. Could you please help me understand what exactly is the issue? The code: https://github.com/dervism/erlang_raspberrypi_temperature_sensor

After builing with Erlang.mk and running "./_rel/webserver/bin/webserver console":

application: webserver
    exited: {bad_return,
             {{webserver_app,start,[normal,[]]},
              {'EXIT',
               {undef,
                [{cowboy,start_http,
                  [http,100,
                   [{port,8080}],
                   [{env,
                     [{dispatch,[{'_',[],[{[],[],toppage_handler,[]}]}]}]}]],
                  []},
                 {webserver_app,start,2,
                  [{file,"src/webserver_app.erl"},{line,25}]},
                 {application_master,start_it_old,4,
                  [{file,"application_master.erl"},{line,273}]}]}}}}
    type: permanent
Eshell V7.1  (abort with ^G)
(webserver@127.0.0.1)1> {"Kernel pid terminated",application_controller,"{application_start_failure,webserver,{bad_return,{{webserver_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy,start_http,[http,100,[{port,8080}],[{env,[{dispatch,[{'_',[],[{[],[],toppage_handler,[]}]}]}]}]],[]},{webserver_app,start,2,[{file,\"src/webserver_app.erl\"},{line,25}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}

**Comment by essen** [comment]
Don't use master or if you do, stay at the tag 2.0.0-pre.3. The current set of breaking changes has not been documented yet.

**Comment by dervism** [comment]
Yep, that fixed it! Thanks!
