### ISSUE TITLE
Crash in cowboy_rest when accept header is missing?

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#977]
Not sure if it really happened but I had a crash after removing the accept header in a request today. Investigate later.

**Comment by essen** [comment]
Might also be a problem when the client has "*/*" and the server has content-types only with parameters.

**Comment by villasv** [comment]
Not sure if related, but I'm experiencing a [unavoidable 406](http://stackoverflow.com/questions/41968752/cowboy-content-types-provided-with-json-giving-406) if I try to override the `content_types_provided`.

Although it works with the default, so that is a clue that is my mistake instead of a bug.

**Comment by essen** [comment]
I don't know Elixir, sorry.

**Comment by villasv** [comment]
No problem. The mystery is not in the code, really. I'm receiving 406 even though my request has no headers, which is impossible according to the flowcharts in the docs (since those checks are going to be skipped). With a little debugging, I've seen that in this case the accept header is set as "*/*", which may be triggering those checks inevitably.

**Comment by essen** [comment]
You need the accept header regardless of what you define. A lack of accept header means that you accept nothing. `accept: */*` means that you accept everything.

**Comment by OvermindDL1** [comment]
>I don't know Elixir, sorry.

@essen It is the same as erlang, just a different syntax, straight conversion though of this Elixir:
```elixir
defmodule App do
    use Application

    def start(_type, _args) do
        dispatch = :cowboy_router.compile([{:_, [
            {"/thing", IndexHandler, []},
        ]}])
        {:ok, _} = :cowboy.start_clear(
            :http, 100, [{:port, 8080}],
            %{:env => %{:dispatch => dispatch}}
        )
    end
end

defmodule IndexHandler do
    def init(req, state) do
        {:cowboy_rest, req, state}
    end

...

    def content_types_provided(req, state) do
        {[{{"application", "json", '*'}, &to_json/2}], req, state}
    end
    def to_json(req, state) do
        {"{json: here}", req, state}
    end
end
```
To this Erlang (please excuse any mis-types, the above Elixir becomes two modules in Erlang):
```erlang
-module('App').

-behaviour(application).

-export(start/2).

start(_type, _args) ->
  Dispatch = cowboy_router:compile([{'_', [
    {<<"/thing">>, 'IndexHandler', []}
  ]}]),
  {ok, _} = cowboy:start_clear(
    http, 100, [{port, 8080}],
    #{env => #{dispatch => Dispatch}}
    )
```
```erlang
-module('IndexHandler').

-export(init/2, content_types_provided/2, to_json/2).

init(Req, State) ->
  {cowboy_rest, Req, State}.

% ...

content_types_provided(Req, State) ->
  {[{{<"application">, <"json">, "*"}, fun to_json/2}], Req, State}.

to_json(Req, State) ->
  {<"{json: here}">, Req, State}.
```

/me is a helper to convert Elixir -> Erlang  ^.^

**Comment by essen** [comment]
You can't return a fun there, only a function name.

**Comment by OvermindDL1** [comment]
> You can't return a fun there, only a function name.

That might indeed be his bug then.  :-)

**Comment by villasv** [comment]
Hoh, well. That is certainly going to bite later, but it can't be the cause since the 406 is returned before that argument can be relevant.

**Comment by essen** [comment]
You'll have to show what requests you do if you want more help.

**Comment by villasv** [comment]
I think I solved it changing `{[{{"application", "json", '*'}` to `{[{{"application", "json", []}`. I didn't fully understand the role of the Param in the third element and followed the default value, so I just copied the '*' from the documented default.

Then after changing that `fun` to an atom makes a smooth 200 OK. So as I suspected, not a bug. :~) thanks for the Accept explanation anyway.

**Comment by essen** [comment]
Closing because original ticket was vague and it got hijacked into something else. Thanks!
