### ISSUE TITLE
Better URL function

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#978]
Rather than have two functions returning either the full URL or the URL without path/qs, we should have one function with one argument. The argument would allow us to get just what we want:

* `full` gives a URL like `scheme://host[:port]/path/to/resource?query=string`
* `no_qs` gives a URL like `scheme://host[:port]/path/to/resource`
* `no_path` gives a URL like `scheme://host[:port]`

More options can be added later on if needed but these are the big threes. The second one is currently heavily lacking from the current interface.

**Comment by essen** [comment]
On top of that it would be cool if we could build a url with some parts updated. For example the real hostname may be different from what the request said (if there's a proxy in front).

**Comment by bullno1** [comment]
That sounds like too much work in one function though. How about just: `url_parts` that returns parts in a tuple and `url_from` that builds url from parts?

**Comment by essen** [comment]
Talking about cowboy_req:url here, that probably wasn't clear enough. It builds a URL from the host/part/scheme of the request. I'm just saying we need to better control output (first comment) and input (second comment). Both have different use cases.

**Comment by essen** [comment]
I'm leaning toward this:

```
full                    uri(Req)
protocol relative       uri(Req, #{scheme => undefined})
no query string         uri(Req, #{qs => undefined})
no path                 uri(Req, #{path => undefined, qs => undefined})
added fragment          uri(Req, #{fragment => "custom"})
changed port            uri(Req, #{port => 443})
```

"protocol relative" means the URI has no scheme, it starts with //host...; this is useful to have the browser/client reuse the protocol (http or https).

For removing the query string or path, <<>> or "" should also work.

**Comment by essen** [comment]
Done in https://github.com/ninenines/cowboy/commit/19468d0503f80a4a2ef4d40abe1b91bdb3516988

Thanks for feedback!
