### ISSUE TITLE
Failed to make cowboy

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#979]
hello

I cloned the cowboy project at master branch, but unfortunately "make" fails. Does it possible that I don't use the latest Erlang/OTP version? I am using v17.5. Please details log below.

ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy(master)> make
 DEP    cowlib
 DEP    ranch
make[1]: Entering directory `/mnt/ethrbh/private/projects/github/cowboy/deps/cowlib'
../../erlang.mk:4035: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
 DEPEND cowlib.d
../../erlang.mk:4035: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_ws.erl
 APP    cowlib.app.src
make[1]: Leaving directory `/mnt/ethrbh/private/projects/github/cowboy/deps/cowlib'
make[1]: Entering directory `/mnt/ethrbh/private/projects/github/cowboy/deps/ranch'
 DEPEND ranch.d
 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
 APP    ranch.app.src
make[1]: Leaving directory `/mnt/ethrbh/private/projects/github/cowboy/deps/ranch'
 DEPEND cowboy.d
 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clear.erl cowboy_clock.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_static.erl cowboy_stream.erl cowboy_stream_h.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
src/cowboy_http.erl:495: illegal use of variable 'Name' in map
src/cowboy_http.erl:496: illegal use of variable 'Name' in map
make[1]: *** [ebin/cowboy.app] Error 1
make: *** [app] Error 2
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy(master)> which erl
/home/ethrbh/tools//erlang_otp_17_5/lib/erlang/bin//erl
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy(master)> 
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy(master)> 
ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy(master)> erlErlang/OTP 17 [erts-6.4] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1> erlang:system_info(version).
"6.4"
2> 

thanks for your help,
/Robi

**Comment by essen** [comment]
Need 18+.

**Comment by bouazizihsan** [comment]
Hello,
I am trying to configure my server.When I type:
Make release
Here is my error at cow_http2.erl:
...
===> Compiling _build / default / lib / cowlib / src / cow_http2.erl failed
_build / default / lib / cowlib / src / cow_http2.erl: 183: syntax error before: '{'
_build / default / lib / cowlib / src / cow_http2.erl: 307: syntax error before: '{'
_build / default / lib / cowlib / src / cow_http2.erl: 314: syntax error before: '{'
_build / default / lib / cowlib / src / cow_http3.erl: 365: syntax error before: '{'
_build / default / lib / cowlib / src / cow_http2.erl: 369: syntax error before: '{'

_build / default / lib / cowlib / src / cow_http2.erl: 18: function parse / 1 undefined
_build / default / lib / cowlib / src / cow_http2.erl: 20: function parse_settings_payload / 1 undefined
_build / default / lib / cowlib / src / cow_http2.erl: 27: function settings / 1 undefined
_build / default / lib / cowlib / src / cow_http2.erl: 28: function settings_payload / 1 undefined
_build / default / lib / cowlib / src / cow_http2.erl: 40: type map () undefined
_build / default / lib / cowlib / src / cow_http2.erl: 80: function parse / 1 undefined

_build / default / lib / cowlib / src / cow_http2.erl: 280: Warning: function parse_fin / 1 is unused
_build / default / lib / cowlib / src / cow_http2.erl: 283: Warning: function parse_head_fin / 1 is unused
_build / default / lib / cowlib / src / cow_http2.erl: 286: Warning: function parse_exclusive / 1 is unused
_build / default / lib / cowlib / src / cow_http2.erl: 289: warning: function parse_error_code / 1 is unused

Make: *** [release] Error 1

How i can fix it
Thank you

**Comment by essen** [comment]
You also need Erlang/OTP 18+.

**Comment by bouazizihsan** [comment]
How i change the version.I am working on ubuntu 14.For the update i have already done

**Comment by ethrbh** [comment]
hello bouazizihsan,

The best way to get newer version of Erlang/OTP, to download the latest Erlang/OTP from http://www.erlang.org/downloads, and install it into your Ubuntu. This is what I am doing time-to-time, when new version comes out.

br,
/Robi

**Comment by bouazizihsan** [comment]
I tried it with apt-get install erlang but the version raste the same
Erlang R16B03
For the link the downloaded versions are for windows and not for ubuntu

**Comment by ethrbh** [comment]
hello,

The apt-get gives you the latest version what is in its repo. What I tried suggest, try download the Erlang/OTP source, and do the ordinary installation.

br,
/Robi

**Comment by ethrbh** [comment]
hello,

If you are interested, this is how I do it. Hope it helps for you.

- Install Erlang/OTP
	- Install required packages for Erlang/OTP
			sudo apt-get install fop libncurses5-dev unixodbc-dev g++ libssl-dev xsltproc
			
			or one-by-one
			
			sudo apt-get install fop 
			sudo apt-get install libncurses5-dev
			sudo apt-get install openjdk-7-jdk
			sudo apt-get install unixodbc-dev
			sudo apt-get install g++
			sudo apt-get install libssl-dev
			sudo apt-get install xsltproc
		
		# for wxwidgets used in erlang
			sudo apt-get install libwxbase2.8
			sudo apt-get install libwxgtk2.8-dev
			sudo apt-get install libqt4-opengl-dev
			sudo apt-get install libgtk2.0-dev
	
	- On Ubuntu
		- export ERLANG_VER=19.2
		- download Erlang/OTP source
		- mkdir -p /home/ethrbh/tools/
		- cd /home/ethrbh/tools/
		- WARNING: Mount /mnt/ethrbh/ if it does not done yet.
			WEB: http://www.giannistsakiris.com/2008/04/09/virtualbox-access-windows-host-shared-folders-from-ubuntu-guest/
			mkdir /mnt/ethrbh/
			sudo mount -t vboxsf ethrbh /mnt/ethrbh
		- cp /mnt/ethrbh/private/Erlang-OTP/otp_src_${ERLANG_VER}.tar.gz .
		- gunzip otp_src_${ERLANG_VER}.tar.gz
		- tar xf otp_src_${ERLANG_VER}.tar
		- cd otp_src_${ERLANG_VER}
		- ./configure --prefix=/mnt/ethrbh/private/vbox_tools/installed/erlang_otp_${ERLANG_VER}
		- make -j 2
		- make install
		- rm -rf otp_src_${ERLANG_VER}

br,
/Robi

**Comment by bouazizihsan** [comment]
Thank you all,
In case of installing the new version how to remove the old one?

**Comment by ethrbh** [comment]
hello,

You can do it like this: sudo apt-get remove packagename

But I would guess, google can be your friend :-)

br,
/Robi

**Comment by bouazizihsan** [comment]
Yes of course
thank you
