### ISSUE TITLE
Erlang crash when start upload example

### ISSUE THREAD

**Issue by ethrbh** [ninenines/cowboy#980]
hello,

I have refreshed my system with Erlang/OTP-18.3. Later I re-started to compile cowboy from the master branch. The compilation was done. At next I started to try the examples/upload example app. Its compilation was also done, but erlang has chraseh when I started the app. The crash says the cowboy:start_http function does not exists. And yes, this is not there. I doublechecked by opening the cowboy/src/cowboy.erl module, and I do not see this function. I also have an oldest version cowboy, where this function was there. Thus I guess, there were a major changes surround this area, but the examples are not updated.

Plese have a look at the log about crash below, and please let me know what did I wrong.

Also please correct/confirm me regarding the cowboy:start_http function.

	The Erlang version what I use
	------------------------------
		Eshell V7.3  (abort with ^G)
		(upload_example@127.0.0.1)1> erlang:system_info(version).
		"7.3"
		(upload_example@127.0.0.1)2> 

	The crash when starting app:
	------------------------------
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy/examples/upload(master)> ls
	Makefile  priv  README.asciidoc  relx.config  src
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy/examples/upload(master)> make
	 DEP    cowboy
	make[1]: Entering directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/cowboy'
	 DEP    cowlib
	 DEP    ranch
	make[2]: Entering directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/cowlib'
	../../../../erlang.mk:4035: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
	 DEPEND cowlib.d
	../../../../erlang.mk:4035: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
	 ERLC   cow_cookie.erl cow_date.erl cow_hpack.erl cow_http.erl cow_http2.erl cow_http_hd.erl cow_http_te.erl cow_mimetypes.erl cow_multipart.erl cow_qs.erl cow_spdy.erl cow_ws.erl
	 APP    cowlib.app.src
	make[2]: Leaving directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/cowlib'
	make[2]: Entering directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/ranch'
	 DEPEND ranch.d
	 ERLC   ranch.erl ranch_acceptor.erl ranch_acceptors_sup.erl ranch_app.erl ranch_conns_sup.erl ranch_listener_sup.erl ranch_protocol.erl ranch_server.erl ranch_ssl.erl ranch_sup.erl ranch_tcp.erl ranch_transport.erl
	 APP    ranch.app.src
	make[2]: Leaving directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/ranch'
	 DEPEND cowboy.d
	 ERLC   cowboy.erl cowboy_app.erl cowboy_bstr.erl cowboy_clear.erl cowboy_clock.erl cowboy_constraints.erl cowboy_handler.erl cowboy_http.erl cowboy_http2.erl cowboy_loop.erl cowboy_middleware.erl cowboy_req.erl cowboy_rest.erl cowboy_router.erl cowboy_static.erl cowboy_stream.erl cowboy_stream_h.erl cowboy_sub_protocol.erl cowboy_sup.erl cowboy_tls.erl cowboy_websocket.erl
	 APP    cowboy.app.src
	 GEN    rebar.config
	make[1]: Leaving directory `/mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps/cowboy'
	 DEPEND upload.d
	 ERLC   upload_app.erl upload_handler.erl upload_sup.erl
	 APP    upload
	 GEN    /mnt/ethrbh/private/projects/github/cowboy/examples/upload/relx
	===> Starting relx build process ...
	===> Resolving OTP Applications from directories:
			  /mnt/ethrbh/private/projects/github/cowboy/examples/upload/ebin
			  /mnt/ethrbh/private/projects/github/cowboy/examples/upload/deps
			  /home/ethrbh/tools/erlang_otp_18.3/lib/erlang/lib
			  /mnt/ethrbh/private/projects/github/cowboy/examples/upload/apps
	===> Resolved upload_example-1
	===> Including Erts from /home/ethrbh/tools/erlang_otp_18.3/lib/erlang
	===> release successfully created!
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy/examples/upload(master)> ./_rel/upload_example/bin/upload_example console
	Exec: /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example/erts-7.3/bin/erlexec -boot /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example/releases/1/upload_example -boot_var ERTS_LIB_DIR /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example/erts-7.3/../lib -config /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example/releases/1/sys.config -args_file /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example/releases/1/vm.args -- console
	Root: /mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example
	/mnt/ethrbh/private/projects/github/cowboy/examples/upload/_rel/upload_example
	Erlang/OTP 18 [erts-7.3] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

	=INFO REPORT==== 26-Apr-2016::10:29:34 ===
		application: upload
		exited: {bad_return,
				 {{upload_app,start,[normal,[]]},
				  {'EXIT',
				   {undef,
					[{cowboy,start_http,
					  [http,100,
					   [{port,8080}],
					   [{env,
						 [{dispatch,
						   [{'_',[],
							 [{[],[],cowboy_static,
							   {priv_file,upload,"index.html"}},
							  {[<<"upload">>],[],upload_handler,[]},
							  {[<<"files">>,'...'],
							   [],cowboy_static,
							   {priv_dir,upload,"files"}}]}]}]}]],
					  []},
					 {upload_app,start,2,[{file,"src/upload_app.erl"},{line,20}]},
					 {application_master,start_it_old,4,
					  [{file,"application_master.erl"},{line,273}]}]}}}}
		type: permanent
	Eshell V7.3  (abort with ^G)
	(upload_example@127.0.0.1)1> {"Kernel pid terminated",application_controller,"{application_start_failure,upload,{bad_return,{{upload_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy,start_http,[http,100,[{port,8080}],[{env,[{dispatch,[{'_',[],[{[],[],cowboy_static,{priv_file,upload,\"index.html\"}},{[<<\"upload\">>],[],upload_handler,[]},{[<<\"files\">>,'...'],[],cowboy_static,{priv_dir,upload,\"files\"}}]}]}]}]],[]},{upload_app,start,2,[{file,\"src/upload_app.erl\"},{line,20}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}

	Crash dump is being written to: erl_crash.dump...done
	Kernel pid terminated (application_controller) ({application_start_failure,upload,{bad_return,{{upload_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy,start_http,[http,100,[{port,8080}],[{env,[{dispa
	ethrbh@ethrbh-VirtualBox:/mnt/ethrbh/private/projects/github/cowboy/examples/upload(master)> 

	
Thanks for your help,
/Robi

**Comment by essen** [comment]
The examples and documentation for master are not up to date. They will be updated next. You may want to use 1.0 if you can't get started with just the code.

**Comment by ethrbh** [comment]
hello Essen,

Thanks for the update. I will start use 1.0 instead.

br,
/Robi

**Comment by essen** [comment]
The example has been converted and a test has been added. Thanks!
