### ISSUE TITLE
cowboy_req:socket/1

### ISSUE THREAD

**Issue by fgc** [ninenines/cowboy#982]
I need ssl client certificate data in my handlers to perform authorization. 
I'm using ssl:peercert/1 as suggested in the ranch guide, but I can't get the request socket with the existing cowboy_req API.
For now I'm just grabbing the socket from the Req object myself, but I wonder if this usage would justify adding cowboy_req:socket/1 .

**Comment by essen** [comment]
There's a cowboy_req:get/2 function that you can use.

**Comment by fgc** [comment]
Thanks! Saw it in the module and didn't think to check if it was exported.
