### ISSUE TITLE
On master, improve sendfile support

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#984]
Right now we can sendfile only a specific part of a file. With Range support, we will want to be able to sendfile more than once per response to be able to handle something like `0-100,200-`.

**Comment by nhooyr** [comment]
When would a client ever really need that though? And with http/2, multi range requests are basically obsolete.

**Comment by essen** [comment]
Why would they be obsolete? The number of streams is limited. You can't expect to open as many as the ranges you want.

Anyway the feature is not just about sendfile ranges of one file, it's also about being able to sendfile many files in one response (for example for multipart, or for building a tar.gz archive on the fly, or others).

**Comment by nhooyr** [comment]
How would building a .tar.gz archive on the fly require sendfile?

**Comment by essen** [comment]
You seem to be confusing sendfile the syscall with sendfile the stream handler command. This ticket is about the latter (which may or may not result in a sendfile syscall later on).

**Comment by nhooyr** [comment]
I am, thanks for clearing it up.

**Comment by essen** [comment]
Currently working on this.

The difficulty for doing this is compression. I've figured out that an uncompressed block can be used so I'll do that for the time being when a sendfile command is received. We can look into improving that later on (perhaps behind an option, so that the sendfile syscall can still be used when compression is enabled).

Useful resources:

* https://tools.ietf.org/html/rfc1951#section-3.2.4
* http://calmarius.net/?lang=en&page=programming%2Fzlib_deflate_quick_reference for easy to read format details
* https://www.zlib.net/manual.html for sync flush explanation

**Comment by essen** [comment]
Hm a question remains though, do we want a sendfile command or do we want the data command to include any type of response body (`iodata() | {sendfile ...}`). Leaning toward the latter now that I started doing the former.

**Comment by essen** [comment]
Well I couldn't do anything other than read the file in memory and compressing it. I could send an uncompressed block via sendfile, but then the CRC/length at the end of the Zstream are wrong, so that sucks.

Done in my local copy, push in a few!
