### ISSUE TITLE
Responding to request with "big" body makes connection reach timeout.

### ISSUE THREAD

**Issue by ibizaman** [ninenines/cowboy#985]
I have an application listening to incoming requests and responding to those. Classic.
The weird thing though is that a timeout is reached when a body of about more than 2kb is sent to the app and the app tries to respond. The call to `cowboy_req.reply` just stalls.

The app looks like this (please excuse the dialect, it's Elixir, not Erlang):
```elixir
:cowboy.start_http(:http, 100, [{:port, port}],
  [
    {:env, [{:dispatch, :cowboy_router.compile(routes)}]},
    {:middlewares, [Cowboy.Middleware.Mrouter, :cowboy_router, :cowboy_handler]}
  ]
)

# Then somewhere I call:
:cowboy_req.reply(code, [
        {"content-type", "application/json"}
    ], json_object, request)
```
I'm doing nothing fancy. I have also a lot of other routes and have no problem apart this one.
So like I said, that last call stales until reaching a timeout, then I get these error messages:
```
08:00:06.632 [error] Ranch listener :http had connection process started with
:cowboy_protocol:start_link/4 at #PID<0.388.0> exit with reason:
{{:badmatch, {:error, :closed}}, [
    {:cowboy_req, :body_recv, 3, [file: 'src/cowboy_req.erl', line: 464]},
    {:cowboy_req, :body_loop, 5, [file: 'src/cowboy_req.erl', line: 447]},
    {:cowboy_protocol, :next_request, 3, [file: 'src/cowboy_protocol.erl', line: 504]}
]}
     
     
     08:00:06.636 [error] Process #PID<0.388.0> raised an exception
     ** (MatchError) no match of right hand side value: {:error, :closed}
         (cowboy) src/cowboy_req.erl:464: :cowboy_req.body_recv/3
         (cowboy) src/cowboy_req.erl:447: :cowboy_req.body_loop/5
         (cowboy) src/cowboy_protocol.erl:504: :cowboy_protocol.next_request/3
```

I also can parse the body I receive, I get also the correct amount of bytes from the body. Everything goes well on "my" side of the application.

Would anyone have a pointer on what could happen or what I could try? I hope there's enough info in this ticket but if not I'll happily add missing pieces. I just don't know at all what to look for.

**Comment by essen** [comment]
Somewhere you discard the Req that is returned, probably after reading the body.

**Comment by ibizaman** [comment]
Wow, you were spot on. It's stupid because I've seen that remark everywhere in the docs...

This is what I did, ripped off of my own code: (again, Elixir)
```elixir
#In the request handler:
queries = :cowboy_req.match_qs(queries_spec, request)
{:ok, body, _} = :cowboy_req.body(request)
{:ok, success_reply(request), nil}
```
But should have done:
```elixir
queries = :cowboy_req.match_qs(queries_spec, request)
{:ok, body, request} = :cowboy_req.body(request)
{:ok, success_reply(request), nil}
```

Thank. You. I searched for so long...

**Comment by hbelhaj** [comment]
thank you  for raising this issue
