### ISSUE TITLE
Headers with capital letters result in an endless loop on HTTP/2

### ISSUE THREAD

**Issue by djustinek** [ninenines/cowboy#986]
When calling cowboy_req:reply/4 if a header that has a capital letter is present it enters an endless loop when using HTTP/2.

Steps to reproduce on `ssl_hello_world` example.

In `toppage_handler.erl` change: 
```
<<"content-type">> => <<"text/plain">>
```

to

```
<<"Content-Type">> => <<"text/plain">>
```

`make run`

Make a HTTP/2 request to https://localhost:8443/ and it will enter an endless loop.

**Comment by essen** [comment]
Fun, thanks.

**Comment by essen** [comment]
I cannot reproduce with the nghttp client. What client did you use?

Note that with nghttp I get this error:

```
[  0.062] [INVALID; error=Invalid HTTP header field was received] recv HEADERS frame <length=55, flags=0x04, stream_id=13>
```

It's normal all things considered.

Cowboy is wrong to send the header with an uppercase BUT Cowboy also expects you to provide a lowercase header (regardless of protocol). I don't rule out a debug mode where Cowboy would check such inputs more thoroughly but we don't have that yet (request for such a feature should be a separate ticket).

The infinite loop on the other hand doesn't seem to be inside Cowboy.

**Comment by essen** [comment]
Closing for now. Thanks!
