### ISSUE TITLE
Serving static files over HTTP/2 results in an error

### ISSUE THREAD

**Issue by djustinek** [ninenines/cowboy#987]
Serving a static file results in an error when trying to connect through HTTP/2.

Example for a png image:

```
19:30:34.323 <0.3345.4> Undefined:Undefined@Undefined [error] CRASH REPORT Process <0.3345.4> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size([<<"image">>,<<"/">>,<<"png">>,<<>>]) in cow_hpack:table_insert/2 line 1253
```

```
19:30:34.324 <0.513.0> Undefined:Undefined@Undefined [error] Ranch listener https_api had connection process started with cowboy_tls:start_link/4 at <0.3345.4> exit with reason: badarg
```

HTTP/1.1 works as expected.

Dispatch rule example:

```
Rules = {'_',
      [{"/test/[...]", cowboy_static, {dir, StaticDir, [{mimetypes, cow_mimetypes, all}]}}]
}
```

Listener startup:

```
...
Dispatch = cowboy_router:compile(Rules), 
{ok, _} = cowboy:start_tls(https_api, 128, HttpsOpts, #{ env => #{ dispatch => Dispatch }})
```

**Comment by essen** [comment]
D'oh. Thanks. I have to look why the test suite didn't detect it.

**Comment by djustinek** [comment]
You're welcome ;-)

I'll keep digging. :-)

**Comment by essen** [comment]
Well the test suite simply didn't cover this. I'll fix it in Cowlib but Cowboy won't cover this case in its test suite for a while.

**Comment by essen** [comment]
Fixed! Thanks.

**Comment by essen** [comment]
So this error has been fixed, but it's not the only one. Cowboy will have a static handler test suite pushed sometimes next week, also testing HTTP/2.

**Comment by essen** [comment]
FYI all errors are now fixed and static files have a new and huge test suite.
