### ISSUE TITLE
Incorrect URLs at ninenines website

### ISSUE THREAD

**Issue by t0il3ts0ap** [ninenines/cowboy#988]
All the front page links at http://ninenines.eu/ for cowboy are for 1.0

I started following the guide to finally figure out that there are drastic changes in code I have ( 2.0.0 pre3 ) and front page documentation which is 1.0

Like in http://ninenines.eu/docs/en/cowboy/1.0/guide/  itself, It uses behavior cowboy_http_handler which is not there in new version.

I think if the default links point to new guide ( 2.0 ), It would be better for people who are going to start with cowboy.

**Comment by essen** [comment]
2.0 is not ready for general consumption. New people really should use 1.0 right now.
