### ISSUE TITLE
Question: How to send an array or an object within a multipart request?

### ISSUE THREAD

**Issue by elado** [ninenines/cowboy#990]
I'm building a multipart request (with JS) that should contain parts that are arrays/objects. What's the proper way to do that? Coming from other frameworks, the common ways are putting `Content-Type` on the part or to append `[]` to the parameter name, such as 

```
members[]=first&members[]=second&members[]=third
```

I've tried all kinds of variations:

- Defining a `Content-Type` for the JSON part:

```
------WebKitFormBoundary77vzryAH8e35s3o5
Content-Disposition: form-data; name="name"

blah
------WebKitFormBoundary77vzryAH8e35s3o5
Content-Disposition: form-data; name="members"; filename="blob"
Content-Type: application/json

["bdf8f0f6-2a6c-477b-beb2-7f15484b2311","e81e6afd-7fba-459e-997e-7616f39c61e2","ec6ea38b-8362-49ae-8d8b-dd62e561ca40"]
------WebKitFormBoundary77vzryAH8e35s3o5
```

- Multiple `members[]` field:

```
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="name"

test12
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members[]"

bdf8f0f6-2a6c-477b-beb2-7f15484b2311
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members[]"

e81e6afd-7fba-459e-997e-7616f39c61e2
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members[]"

ec6ea38b-8362-49ae-8d8b-dd62e561ca40
------WebKitFormBoundarySSIN5tWdPGbcPm3y--
```

Also tried with `members[0], members[1], members[2]`.

- Multiple `members`:

```
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="name"

test12
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members"

bdf8f0f6-2a6c-477b-beb2-7f15484b2311
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members"

e81e6afd-7fba-459e-997e-7616f39c61e2
------WebKitFormBoundarySSIN5tWdPGbcPm3y
Content-Disposition: form-data; name="members"

ec6ea38b-8362-49ae-8d8b-dd62e561ca40
------WebKitFormBoundarySSIN5tWdPGbcPm3y--
```

All failed to automatically parse. Is there a standard way for cowboy, or should it be parsed manually?

**Comment by essen** [comment]
Can you show the code you used to read these? Pretty sure they'd all be working.

Note that Cowboy only parses the multipart standard and does not do weird things with the []. As far as Cowboy is concerned, parts are parts. There's no function such as "process all parts" either, there's two functions: read the next part headers and read the next part body. From there you should be able to get any behavior you want.
