### ISSUE TITLE
`cowboy_http_handler undefined` while following the getting started tutorial

### ISSUE THREAD

**Issue by currycoder** [ninenines/cowboy#994]
The tutorial step to create an http handler uses a template offered by erlang.mk: `make new t=cowboy_http n=hello_handler`

However the cowboy http handler template generated by erlang.mk is outdated:
https://github.com/ninenines/erlang.mk/blob/1fee577a15f5dbcc391b8f555458dad68f24afde/plugins/bootstrap.mk#L180
It uses a behaviour `cowboy_http_handler` which no longer exists.

Additionally, the tutorial could do with a little more info in the Prerequisites section, e.g: 
- Check that you have erlang 18 : `run this`
- Check that your version of erlang.mk is current: `run this`
- Check that your version of cowboy is current: `run this`

**Comment by essen** [comment]
Yes, it looks like I put Cowboy's commit to master but I did not make sure it works. The templates in Erlang.mk are fine, they're for Cowboy 1.0. Cowboy itself will come with templates for 2.0, not Erlang.mk. That part hasn't been started yet.

The chapter right before has info about Erlang 18. There should be no need to worry about the version of Erlang.mk or Cowboy if you are following the tutorial though.

**Comment by bakki** [comment]
I am just learning Erlang/Cowboy and the error in the tutorial is confusing. I am getting:
 ERLC   hello_erlang_app.erl hello_handler.erl
compile: warnings being treated as errors
src/hello_handler.erl:2: behaviour cowboy_http_handler undefined
make[1]: *** [erlang.mk:5054: ebin/hello_erlang.app] Error 1
make: *** [erlang.mk:4857: app] Error 2
I understand that the template generated by erlang.mk is outdated. I got the latest version of everything (Erlang R19) but I am still getting the error. Also the tutorial refers to init/2 but the template has init/3. What would a corrected version of the tutorial look like?

**Comment by essen** [comment]
If you are new to Erlang, and want to use Cowboy master, clone Cowboy and copy examples/hello_world as your starting point. You'll need to download the erlang.mk file and tweak the Makefile, but it'll work just fine after that.

**Comment by essen** [comment]
This shouldn't be an issue anymore with the current version. Cowboy master comes with its own set of templates, and the 2.0 getting started has been updated to reflect this. Closing, thanks!
