### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by eugene-panferov** [ninenines/cowboy#996]
i am using cowboy "by the book" which implies erlang.mk and relx.
the release launches epmd as: "epmd -deamon" (listening to all interfaces).
how can i pass arguments to epmd? (giving it the list of interfaces to listen on)

**Comment by essen** [comment]
You can set environment variables: http://erlang.org/doc/man/epmd.html#environment_variables

You can also start it on its own before/independently from the release.
